#+title: Vaje iz Fizikalnih merjenj, 10. teden v letu
#+subtitle: 2026/03/03
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Uvod v združevanje odvisnih meritev

Prejšnji teden smo na vajah povedali, da za dve meritvi \( z_1, z_2 \) s pripadajočima variancama \( \sigma_1, \sigma_2 \), ki sta med seboj odvisni \( \sigma_{12} \ne 0 \), velja enačba za optimalno oceno

\[ \hat{x}_{(12)} = z_1 + \frac{\sigma_1 ^2 - \sigma_{12}}{\sigma_1 ^2 + \sigma_2 ^2 - 2 \sigma_{12}} \left( z_2 - z_1 \right).
\]

Optimalni oceni pripada tudi svoja varianca, ki je določena z oceno

\[ \hat{\sigma}_{(12)} ^2 = \left( 1 - \rho_{12} ^2 \right) \left( \frac{1}{\sigma_1 ^2} + \frac{1}{\sigma_2 ^2} - \frac{2 \rho_{12}}{\sigma_1 \sigma_2} \right) ^{-1},
\]

kjer je \( \rho_{12} \) korelacijski faktor.

Predpostavimo sedaj, da imamo še tretjo meritev \( x_3 \) in pripadajočo varianco \( \sigma_3 \). Kako bi sedaj združili vse tri meritve skupaj?

To storimo tako, da združimo optimalno oceno \( \hat{x}_{(12)} \) ter \( x_3 \). Njuno korelacijo potem izračunamo po definiciji

\[ \sigma_{x_{(12)}, 3} = \left\langle \left( \hat{x}_{(12)} - x \right) \left( z_3 - x \right) \right\rangle.
\]

Naše naloge bodo vse vsebovale samo po dve meritvi.
** Varianca povprečja odvisnih meritev

Imejmo vzorec \( \left\{ z_i \right\}_N \), ki ima Gaussovo porazdelitev. Vse meritve naj majo isto povprečje \( \left\langle z_i \right\rangle = \mu \), vendar ima lahko vsaka meritev svojo varianco

\[ \left\langle \left( z_i - \mu \right) ^2 \right\rangle = \sigma_i ^2.
\]

Hkrati so lahko med seboj posamezne meritve tudi korelirane

\[ \left\langle \left( z_i - \mu \right) \left( z_j - \mu \right) \right\rangle = \sigma_{ij}\ne 0.
\]

Povprečje meritev je po definiciji

\begin{equation}
\label{eq:2}
 \bar{z} = \frac{1}{N} \sum\limits_{i = 1}^N z_i,
\end{equation}

pričakovana vrednost povprečja pa je

\[ \left\langle \bar{z} \right\rangle  = \frac{1}{N} \sum\limits_{i = 1}^N \left\langle z_i \right\rangle = \frac{1}{N} \sum\limits_{i = 1}^N \frac{1}{N} N \mu = \mu.
\]

Varianco povprečja

\[ \sigma_M ^2 = \left\langle \left( \bar{z} - \mu \right) ^2 \right\rangle,
\]

 kjer indeks \( M \) označuje ang. /mean/ želimo izraziti s poznanimi variancami \( \sigma_i ^2 \) in kovariancami \( \sigma_{ij} \).

 Za začetek v varianci povprečja upoštevamo definicijo povprečja

 \begin{align*}
   \sigma_M ^2 &= \left\langle \left( \frac{1}{N} \sum\limits_{i = 1}^N z_i - \mu \right) ^2  \right\rangle\\
&= \frac{1}{N ^2} \left\langle \left( \sum\limits_{i = 1}^N z_i - N \mu \right) ^2 \right\rangle = \frac{1}{N ^2} \left\langle \left( \sum\limits_{i = 1}^N \left[ z_i - \mu \right] \right) ^2 \right\rangle
 \end{align*}

 V drugi vrstici smo iz oklepaja izpostavili \( \frac{1}{N} \) ter oba člena v vsoti zapisali s pomočjo vsote. V vsoti prepoznamo razliko kvadratov, kar pomeni, da lahko razstavimo na dva dela

 \[ \sigma_M ^2 = \frac{1}{N ^2} \left\langle \sum\limits_{i = 1}^N \left( z_i - \mu \right) \sum\limits_{j = 1}^N \left( z_j - \mu \right)  \right\rangle.
 \]

 Na izraz sedaj apliciramo pričakovano vrednost in prepoznamo izraza za varianco in kovarianco

 \begin{align*}
   \sigma_M ^2 &= \frac{1}{N ^2} \left( \left\langle \sum\limits_{i = 1}^N \left( z_i - \mu \right) ^2 \right\rangle + \left\langle \sum\limits_{i, j = 1, \ i \ne j}^N \left( z_i - \mu \right) \left( z_j - \mu \right) \right\rangle \\
&= \frac{1}{N ^2} \sum\limits_{i, j = 1}^N \sigma_{ij}
 \end{align*}

 Varianca posamezne meritve je tako zajeta znotraj vsote, saj \( \sigma_{ii} = \sigma_i ^2 \).

 Zapišemo lahko tudi drugače

 \begin{align*}
  \sigma_m ^2 &= \frac{1}{N ^2} \left( \sum\limits_{i = 1}^N \sigma_i ^2 + \sum\limits_{i, j = 1, \ i \ne j}^N \sigma_{ij} \right) \\
&= \frac{1}{N ^2} \left( \sum\limits_{i = 1}^N \sigma_i ^2 + 2 \sum\limits_{i > j = 2}^N \sigma_{ij} \right),
 \end{align*}

 saj je kovarianca simetrična \( \sigma_{ij} = \sigma_{ji} \).

 V primeru neodvisnih izmerkov je kovarianca \( \sigma_{ij} = 0 \) za vsak \( i, j \), in dobimo

 \begin{equation}
 \label{eq:1}
 \sigma_M ^2 = \frac{1}{N ^2} \sum\limits_{i = 1}^N \sigma_i ^2.
 \end{equation}

 Če so variance enake, npr. če merimo z istim inštrumentom, \( \sigma_i = \sigma \) za vsak \( i \), potem je varianca povprečja odvisnih meritev

 \[ \sigma_M ^2 = \frac{N}{N ^2} \sigma ^2 = \frac{1}{N} \sigma ^2
 \]

 Povprečna vrednost je v obeh zgornji primerih porazdeljen po normalni porazdelitvi

 \[ \bar{z} \sim \mathcal{N} \left( \mu, \frac{\sigma ^2}{N} \right).
 \]
* Naloga: meritev višina
#+begin_problem
Imamo dve neodvisni meritvi višine. Prva meritev je \( h_1 = 2139 \mathrm{m} \) z varianco \( \sigma_1 = 12 \mathrm{m} \), druga meritev pa je \( h_2 = 2130 \mathrm{m} \) z varianco \( \sigma_2 = 6 \mathrm{m} \). Izračunaj povprečje ter optimalno združevanje. 
#+end_problem

Meritvi sta neodvisni, torej bo \( \sigma_{12} = 0 \) in \( \rho_{12} = 0 \). Povprečje bomo izračunali po enačbi \ref{eq:2}, ki smo jo izpeljali v teoretičnem delu. Varianco povprečja pa bomo izračunali po enačbi \ref{eq:1}. 

Torej

\[ \mathbf{h} = \frac{1}{2} \left( h_1 + h_2 \right) = 2134.5 \mathrm{m}.
\]

Kvadrat variance povprečja je

\[ \sigma_M = \frac{1}{N ^2} \sum\limits_{i = 1}^2 \sigma_i ^2 = \frac{1}{4} \left( \sigma_1 ^2 + \sigma_2 ^2 \right) = 45 \mathrm{m} ^2.
\]

Varianca je potem \( \sigma_M = 6.7 \mathrm{m} \). Opazimo, da je napaka večja kot najmanjša napaka od meritev, kar nam pove, da v danem primeru povprečje ni optimalno združevanje. 

Oglejmo si še optimalno združevanje. Poslužili se bomo dveh enačb, ki sta bili izpeljani na prejšnjih vajah in sicer enačba za optimalno oceno je

\[ \hat{x} =  z_1 + \frac{\sigma_1 ^2 - \sigma_{12}}{\sigma_1 ^2 + \sigma_2 ^2 - 2 \sigma_{12}} \left( z_2 - z_1 \right),
\]

varianca optimalne ocene pa je

\[ \hat{\sigma} ^2 = \frac{\sigma_1 ^2 \sigma_2 ^2 - \sigma_{12} ^2}{\sigma_1 ^2 + \sigma_2 ^2 - 2 \sigma_{12}}.
\]

Upoštevamo, da za naš primer \( \sigma_{12} = 0 \) in optimalna ocena je tako

\[ \hat{h} = h_1 + \frac{\sigma_1 ^2}{\sigma_1 ^2 + \sigma_2 ^2} \left( h_2 - h_1 \right) = h_1 + K \left( h_2 - h_1 \right),
\]

kjer smo s \( K = \frac{\sigma_1 ^2}{\sigma_1 ^2 + \sigma_2 ^2} \) označili ojačevalni faktor. Meritev z manjšo napako dobi večjo utež pri optimalnem združevanju. 

Vrednost optimalne ocene je tako \( \hat{h} = 2131.8 \mathrm{m} \). Izračunajmo še optimalno varianco, ki jo prav tako lahko zapišemo z ojačevalnim faktorjem \( K \)

\[ \hat{\sigma} ^2 = K \sigma_2 ^2 = \sigma_2 ^2 - \frac{\sigma_2 ^2}{\sigma_1 ^2 + \sigma_2 ^2}.
\]

Člen \( \frac{\sigma_2 ^2}{\sigma_1 ^2 + \sigma_2 ^2} \) je večji od \( 0 \), kar pomeni, da bo izostril/zmanjšal varianco. Posledično bo varianca optimalne ocene manjša od obeh meritev. Vstavimo podatke v enačbo in dobimo

\[ \hat{\sigma} ^2 = K \sigma_2 ^2 = \frac{144}{180} \cdot 36 \mathrm{m} ^2 = 28.8 m ^2.
\]

Varianca je tako \( \hat{\sigma} = 5.4 \), kar je res manj od najmanjše variance posamezne meritve.
* Optimalno združevanje neodvisnih meritev

Za neodvisne meritve velja \( \sigma_{12} = 0 \) in \( \rho_{12} = 0 \). Če imamo dve neodvisni meritvi, bo njuna optimalna ocena

\[ \hat{x} = z_1 + \frac{\sigma_1 ^2}{\sigma_1 ^2 + \sigma_2 ^2} \left( z_2 - z_1 \right) 
\]

ter varianca

\[ \hat{\sigma} ^2 = \frac{\sigma_1 ^2 \sigma_2 ^2}{\sigma_1 ^2 + \sigma_2 ^2} = \left( \sigma_1 ^{-2} + \sigma_2 ^{-2} \right)^{-1}.
\]

V primeru več kot dveh neodvisnih rešitev, zapišemo rekurzivno obliko. To lahko naredimo zaradi neodvisnosti meritevi n bodo njihove kovariance ničelne. Po \( n \) združenih meritvah imamo tako oceno \( \hat{x}_n \) z varianco \( \sigma_n ^2 \). Dodamo še eno meritev \( z_{n + 1} \) z varianco \( \sigma_{n + 1} ^2 \), ki ju združimo z že obstoječo oceno. Enačbi sta tako

\[ \hat{x}_{n + 1} = \hat{x}_n + \frac{\sigma_n ^2 }{\hat{\sigma}_n ^2 + \sigma_{n + 1} ^2} \left( z_{n + 1} - \hat{x}_n \right) \quad \text{ in } \quad \hat{\sigma}_{n + 1} ^{-2} = \hat{\sigma}_n^{-2} + \sigma_{n + 1}^{-2} \implies \hat{\sigma}_{n + 1} ^2 = \frac{\hat{\sigma}_n ^2 \sigma_{n + 1} ^2}{\hat{\sigma}_n ^2 + \sigma_{n + 1} ^2}.
\]

Danemu setu enačb pravimo /Kalmanov filter za združevanje neodvisnih meritev konstante/ in se uporablja za sprotno združevanje meritev.

[vstavi grafiko filtra?]

Za \( n = 0 \) je optimalna ocena

\[ \hat{x} = \hat{x}_0 + \frac{\hat{\sigma}_0 ^2}{\hat{\sigma}_0 ^2 + \sigma_1 ^2} \left( z_1 - \hat{x}_2 \right) \quad \text{ in } \quad \hat{\sigma}_1 ^{-2} = \hat{\sigma}_0^{-2} + \sigma_0 ^{-2}.
\]

\( \hat{x}_0 \) je izostrena ocena brez opravljenih meritev in zaseda poljubno vrednost, saj je pred meritvijo ne poznamo. Hkrati mora še vedno imeti Gaussovo porazdelitev, vendar bo varianca \( \hat{\sigma}_0 = \infty \), saj lahko izostrena ocena zaseda katerokoli vrednost.

Posledično je

\[ \hat{x} = \hat{x}_0. 
\]

Za \( n = 1 \) je izostrena ocena

\[ \hat{x}_1 = z_1 \quad \text{ in } \sigma_1 ^2 = \sigma_1 ^2.
\]

Kalmanov filter *ni primeren*, če imamo podatke že vnaprej tabelirane, ker moramo po nepotrebnem izračunavati vmesne rezultate. Namesto tega takrat uporabimo uteženo povprečevanje. Slednje je bolj računsko ugodno, ker ne računamo vseh vmesnih rezultatov.

Enačbi za uteženo povprečje sta

 \[ \hat{x}_n = \frac{\sum\limits_{i = 1}^n \frac{z_i}{\sigma_i ^2}}{\sum\limits_{i = 1}^n \frac{1}{\sigma_i ^2}} \quad \text{ in } \quad \hat{\sigma}_n ^2 = \frac{1}{\sum\limits_{i = 1}^n \frac{1}{\sigma_i ^2}}
 \]

 oziroma

 \[ \frac{\hat{x}_n ^2}{\hat{\sigma}_n ^2} = \sum\limits_{i = 1}^n \frac{z_i}{\sigma_i ^2}.
 \]

 Zgornje enačbe predstavljajo enak postopek, kakor če bi šli rekurzivno čez vse meritve s Kalmanovim filtrom.
* Naloga: meritev hitrosti (zvoka) 
#+begin_problem
Imamo set treh meritev s pripadajočimi variancami

\begin{align*}
  c_1 &= 342 \frac{\mathrm{m}}{\mathrm{s}} \quad \sigma_1 = 2 \frac{\mathrm{m}}{s} \\
  c_2 &= 343 \frac{\mathrm{m}}{\mathrm{s}} \quad \sigma_2 = 4 \frac{\mathrm{m}}{s} \\
  c_1 &= 346 \frac{\mathrm{m}}{\mathrm{s}} \quad \sigma_3 = 6 \frac{\mathrm{m}}{s} \\
\end{align*}

Zanima nas optimalna ocena \( \hat{c} \) ter njena varianca \( \hat{\sigma} ^2 \). Izračunaj preko uteženega povprečja, za domačo nalogo pa lahko ponoviš postopek še s Kalmanovih filtrom.
#+end_problem

Varianca bo po enači iz teoretičnega uvoda

\begin{align*}
  \hat{\sigma} ^2 &= \left( \frac{1}{2 ^2} + \frac{1}{4 ^2} + \frac{1}{6 ^2} \right)^{-1} \\
&= \frac{144}{49} \left( \frac{\mathrm{m}}{\mathrm{s}} \right) ^2 \sim 2.9 \left( \frac{\mathrm{m}}{\mathrm{s}} \right) ^2
\end{align*}

Napaka optimalne ocene je torej \( \hat{\sigma} = 1.7 \frac{\mathrm{m}}{\mathrm{s}} \).

Optimalna ocena pa bo potem

\[ \hat{c} = 2.9 \left( \frac{342}{4} + \frac{343}{16} + \frac{346}{36} \right) \frac{\mathrm{m}}{\mathrm{s}} = 342.5 \frac{\mathrm{m}}{s}. 
\]

V primeru povprečenja bi dobili

\[ \bar{c} = 343.7 \frac{\mathrm{m}}{\mathrm{s}} \quad \text{ in } \quad  \sigma_M = 2.5 \frac{\mathrm{m}}{\mathrm{s}}.
\]
* Naloga: Uteženo povprečje in Kalmanov filter
#+begin_problem
Pokaži, da je uteženo povprečje

\[  \hat{x}_n = \frac{\sum\limits_{i = 1}^n \frac{z_i}{\sigma_i ^2}}{\sum\limits_{i = 1}^n \frac{1}{\sigma_i ^2}} \quad \text{ in } \quad \hat{\sigma}_n ^2 = \frac{1}{\sum\limits_{i = 1}^n \frac{1}{\sigma_i ^2}} 
\]

ekvivalentno Kalmanovem filtru

\[  \hat{x} = z_1 + \frac{\sigma_1 ^2}{\sigma_1 ^2 + \sigma_2 ^2} \left( z_2 - z_1 \right)  \quad \text{ in } \quad  \hat{\sigma} ^2 = \frac{\sigma_1 ^2 \sigma_2 ^2}{\sigma_1 ^2 + \sigma_2 ^2} = \left( \sigma_1 ^{-2} + \sigma_2 ^{-2} \right)^{-1}.
\]
#+end_problem

Za \( n \)-to meritev v Kalmanovem filtru bo veljala enakost

\[ \hat{\sigma}_n ^{-2} = \sum\limits_{i = 1}^n \sigma_i ^{-2}.
\]

Za \( n + 1 \) meritev potem velja

\[ \hat{\sigma}_{n + 1}^{-2} = \sum\limits_{i = 1}^{n + 1} \sigma_i ^{-2} = \sum\limits_{i = 1}^n \sigma_i^{-2} + \sigma_{n + 1} ^{-2}.
\]

To lahko zapišemo tudi z \( n \)-to meritvijo kot

\begin{equation}
\label{eq:3}
 \hat{\sigma}_{n + 1}^{-2} = \hat{\sigma}_n ^{-2} + \sigma_{n + 1}^{-2}.
\end{equation}

Razmerje ocen in variance za \( n \)-to meritev je

\[ \frac{\hat{x}_n}{\hat{\sigma}_n ^2} = \sum\limits_{i = 1}^n \frac{z_i}{\sigma_i ^2}.
\]

Za \( n + 1 \) meritev pa je

\[ \frac{\hat{x}_{n + 1}}{\sigma_{n +1} ^2} = \sum\limits_{i = 1}^{n + 1} \frac{z_i}{\sigma_i ^2} = \sum\limits_{i = 1}^n \frac{z_i}{\sigma_i ^2} + \frac{z_{n + 1}}{\sigma_{n + 1} ^2}.
\]

Ponovno lahko to zapišemo z \( n \)-to meritvijo

\[ \frac{\hat{x}_{n + 1}}{\sigma_{n + 1} ^2} = \frac{\hat{x}_n}{\hat{\sigma}_n ^2} + \frac{z_{n + 1}}{\sigma_{n + 1} ^2}.
\]

Enačbo lahko sedaj pomnožimo z \( \hat{\sigma}_{n + 1} \), iz česar sledi

\[ \hat{x}_{n + 1} = \frac{\hat{\sigma}_{n + 1} ^2}{\hat{\sigma}_n ^2} \hat{x}_n + \frac{\hat{\sigma}_{n + 1} ^2}{\sigma_{n + 1} ^2} z_{n + 1} 
\]


Upoštevajoč \ref{eq:3} veljata identiteti

\[ \frac{\hat{\sigma}_{n + 1} ^2}{\hat{\sigma}_n ^2} = \frac{\sigma_{n + 1} ^2}{\hat{\sigma}_n ^2 + \sigma_{n + 1} ^2} \quad \text{ in } \quad \frac{\hat{\sigma}_{n + 1} ^2}{\sigma_{n + 1} ^2} = \frac{\hat{\sigma}_n ^2}{\hat{\sigma}_n ^2 + \sigma_{n + 1} ^2} 
\]

kar zgornji izraz pretvori v

\[ \hat{x}_{n + 1} =  \frac{\sigma_{n + 1} ^2}{\hat{\sigma}_n ^2 + \sigma_{n + 1} ^2} \hat{x}_n + \frac{\hat{\sigma}_n ^2}{\hat{\sigma}_n ^2 + \sigma_{n + 1} ^2} z_{n + 1}.
\]

Ponovno upoštevamo izraz \ref{eq:3}, vendar tokrat izrazimo \( \sigma_{n + 1} ^2 \) in dobimo ven ravno Kalmanov filter

\[ \hat{x}_{n + 1} = \hat{x}_n - \frac{\hat{\sigma}_n ^2}{\hat{\sigma}_n ^2 + \sigma_{n + 1} ^2} \hat{x}_n + \frac{\hat{\sigma}_n ^2}{\hat{\sigma}_n ^2 + \sigma_{n + 1} ^2} z_{n + 1} = \hat{x}_n + \frac{\hat{\sigma}_n ^2}{\hat{\sigma}_n ^2 + \sigma_{n + 1} ^2} \left( z_{n + 1} - \hat{x}_n \right).
\]

