#+title: 2. vaje iz Kvantne mehanike
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* 2. sklop nalog
** Vezana stanja v delta potencial, alternativno

Imamo potencialno jamo oblike

\[ V \left( x \right) = - \lambda \delta(x)
\]

Schrödingergjeva enačba je oblike

\begin{equation}
\label{eq:1}
 H \Psi(x) = E \Psi(x)
\end{equation}

kjer je

\[ H = \frac{p ^2}{2m} + V(x) = - \frac{\hbar ^2}{2m} \frac{\mathrm{d} ^2 }{\mathrm{d}x ^2} - \lambda \delta(x)
\]

Potencial je sod, saj velja \( V(x) = V \left( - x \right) \).

[glej graf na tablici]

Označimo levo polravnino z \( x < 0 \) z \( i \), desno polravnino pa z \( ii \).

Ločimo dva primera

- soda valovna funkcija, kjer velja \( \Psi(x) = \Psi(-x) \).

  \begin{align*}
    \Psi_{ii} &= A e^{- \kappa x} \\
        \Psi_i &= A e^{\kappa x }
  \end{align*}

- liha valovna funkcija \( \Psi(x) = - \Psi(- x) \), kjer pa je

  \begin{align*}
    \Psi_{ii} (x) &= A e^{-\kappa x} \\
        \Psi_i (x) &= - A e^{\kappa x}
  \end{align*}

Želimo najti robni pogoj okoli \( x = 0 \). Integriramo Schrödingerjevo enačbo \ref{eq:1} v mejah \( [-\epsilon, \epsilon] \) in dobimo

\[ - \left. \frac{\hbar ^2}{2m} \frac{\mathrm{d} }{\mathrm{d} x} \Psi(x) \right|_{0_-}^{0_+} - \Psi(0) \lambda = E \int\limits_{0_-}^{0^+} \Psi(x) \, \mathrm{d} x
\]

kjer sta \( 0_- \) levi in \( 0_+ \) desni odvod. Desna stran je ekvivalentna \( 0 \), kar bomo kasneje tudi preverili.

Razliki levega in desnega odvoda sta za \( - \Psi(0) \lambda \cdot \frac{2m}{\hbar ^2} \) narazen - torej nista zvezna

\begin{equation}
\label{eq:2}
 \Psi'(0_+) - \Psi' (0_-) = - \Psi(0) \lambda \cdot \frac{2m}{\hbar ^2} = - \Psi(0) 2 \kappa_0
\end{equation}

Razliki levega in desnega odvoda sta podobni Heavisodovi funkciji \( H(x) \), katere odvod je \( \delta(x) \).

\ref{eq:2} predstavlja prvi pogoj, ki ga mora naša enačba zadovoljiti, medtem ko drugi pogoj pa je to, da je \( \Psi \) zvezna, torej \( \Psi(0_-) = \Psi(0_+) \).

Liha valovna funckija temu ne zadošča, torej obravnavamo samo sodo funkcijo. Uporabimo nastavek sode funkcije in ju odvajamo

\begin{align*}
  \Psi'(0_+) &= - A \kappa e^{- \kappa 0_+} = - A \kappa \\
\Psi'(0_-) &= A \kappa e^{\kappa 0_-} = A \kappa
\end{align*}

Upoštevajoč pogoj \ref{eq:2} dobimo

\begin{align*}
  A \kappa + A \kappa &= A 2 \kappa_0 \\
2 \kappa &= 2 \kappa_0
\end{align*}

iz česar dobimo

\[ \Psi(x) = A e^{- \left| x \right| \kappa_0}
\]
** Sipanje

Imamo delec z energijo \( E \), ki potuje skozi tri različna območja. Območji \( V_1 \) in \( V_2 \) sta večji in konstantni, medtem kot območje \( V_3 \) je postavljena med ostala potenciala in ima spremenljiv, poljuben potencial. Predpostavimo \( E > V_1, V_2 \) zaradi česar je delec prost v teh območjih.

Nastavka valovnih funkcij za območji s konstantnimi potenciali sta

\begin{equation}
\label{eq:4}
 \Psi_1 (x) = A_1 e^{\mathrm{i} k x} + B_2 e^{- \mathrm{i} k_1 x} \quad \Psi_2 (x) = B_1 e^{\mathrm{i} k_2 x} + A_2 e^{ -\mathrm{i} k_2 x }
\end{equation}


kjer sta

\[ k_1 = \sqrt{ \frac{2m \left( E - V_1 \right)}{\hbar ^2}} \quad k_2 = \sqrt{\frac{2m \left( E - V_2 \right)}{\hbar ^2}}
\]

Dogovor je, da členi s koeficienti \( A_i \) potujejo proti potencialu \( V_3 \), medtek ko členi s koeficienti \( B_i \) potujejo stran od tega potenciala.

Kot omenjeno na predavanjih, verjetnostni tok je definiran

\begin{equation}
\label{eq:3}
 j(x) = \frac{\hbar}{2m \mathrm{i}} \left[ \Psi^{\ast } (x) \Psi '(x) - \Psi(x) \Psi '^{\ast}  \right] = \frac{\hbar}{m} \mathrm{Im} \left\{ \Psi^{\ast} \Psi'(x) \right\}
\end{equation}

Vstavimo nastavka \ref{eq:4} v verjetnostni tok \ref{eq:3}

\[ j_1 \left( x \right) = \frac{\hbar}{m} \mathrm{Im} \left\{ \left| A_1 \right| ^2 k_1 \mathrm{i} - \left| B_2 \right| ^2 k_2 \mathrm{i} \underbrace{- A_1^{\ast} B_2 k_1 \mathrm{i} e^{-2i k_1 x}}_{z} \underbrace{+ A_1 B_1 ^{\ast} k_1 \mathrm{i} e^{2\mathrm{i} k_1 x}}_{z^{\ast}}  \right\}
\]

Velja iz Mat4, da je \( z + z^{\ast} \in \mathbb{R} \), kar pomeni, da zadnje dva člena ne prideta v upoštev za imaginarna del produkta.

\[ j_1 (x) = \frac{\hbar k_1}{m} \left( \left| A_1 \right| ^2 + \left| B_1 \right| ^2\right), \quad j_2 (x) = \frac{\hbar k_2}{m} \left( \left| B_2 \right| ^2 - \left| A_2 \right| ^2\right)
\]

Definiramo hitrosti \( v_1 \) in \( v_2 \) s koeficienti iz verjetnostnih tokov

\[ v_1 = \frac{\hbar k_1}{m},  \quad v_2 = \frac{\hbar k_2}{m}
\]

in predefiniramo nastavke \ref{eq:4}, saj valovni funkciji oscilirata in ne moreta biti normalizirani.

\begin{equation}
\label{eq:5}
\Psi_1 (x) = A_1 \frac{e^{\mathrm{i} k_1 x}}{\sqrt{v_1}} +  B_1 \frac{e^{- k_1 x}}{\sqrt{v_1}}, \quad
\Psi_2 (x) = B_2 \frac{e^{\mathrm{i} k_2 x}}{\sqrt{v_2}} +  A_2 \frac{e^{- k_2 x}}{\sqrt{v_2}}
\end{equation}

s pripadajočima verjetnostima tokovoma

\[ j_1 (x) = \left| A_1 \right| ^2 - \left| B_1 \right| ^2, \quda j_2 (x) = \left| B_2 \right| ^2 - \left| A_2 \right| ^2
\]

Za področje s potencialom \( V_3 \) potrebujemo bolj splošen nastavek, ker ne poznamo lastnosti potenciala \( V_3 (x) \). Ker imamo opravka z diferencialno enačbo drugega reda, vemo, da bo splošna oblika rešitve linearna kombinacija dveh neodvisnih funkcij

\[ \Psi_3 (x) = C \phi(x) + D \chi(x)
\]

Ker je valovna funkcijo zvezna in zvezno odvedljiva, moramo zadostiti pogojem

\begin{align*}
  \Psi_1 (a) &= \Psi_3 (a) \\
\Psi_1 '(a) &= \Psi_3 '(a) \\
  \Psi_2 (b) &= \Psi_3 (b) \\
\Psi_2 '(b) &= \Psi_3 '(b) \\
\end{align*}

Imamo konstante \( A_1, B_1, A_2, B_2, C \) in \( D \). Če poznamo \( A_1 \) in \( A_2 \) bomo rešitev imeli enolično določeno.

Preko dveh od štirih pogojev dobimo elimirano konstante \( C, D \), preko ostalih dveh pa izrazimo kosntanti \( B_1 \) in \( B_2 \) v odvisnosti od \( A_1 \) in \( A_2 \).


\begin{equation}
\label{eq:6}
 \begin{pmatrix} B_{1} \\ B_{2} \end{pmatrix} = \begin{pmatrix}
                                                  r & t' \\
                                                  t & r'
                                                   \end{pmatrix} \begin{pmatrix} A_{1} \\ A_{2} \end{pmatrix}
\end{equation}

kjer je \( 2 \times 2 \) matrika sipalna matrika \( S \) (ang. /scattering matrix/).

Velja

\begin{align*}
  \begin{pmatrix} r \\ t \end{pmatrix} &= \begin{pmatrix}
                                         r & t' \\
                                         t & r'
                                          \end{pmatrix} \begin{pmatrix} 1 \\ 0 \end{pmatrix} \\
\begin{pmatrix} t' \\ r' \end{pmatrix} &= \begin{pmatrix}
                                          r & t' \\
                                          t & r'
                                           \end{pmatrix} \begin{pmatrix} 0 \\ 1 \end{pmatrix}
\end{align*}

Definiramo refleksivnost \( R = \left| r \right| ^2 \), ki nam pove koliko delcev se odbije od potenciala, medtem ko tranzitivnost \( T = \left| t \right| ^2 \) pove koliko delcev gre skozi potenciala.

Velja identiteta

\[ 1 = \left| r \right|  ^2 + \left| t \right| ^2
\]

in verjetnostna tokova potem zapišemo s parametroma \( r, t \)

\[ j_1 (x) = 1 - \left| r \right|  ^2,  \quad j_2 (x) = \left| t \right| ^2
\]

Ker smo v nerelativistični kvantni mehaniki, je predpostavka, da se število delcev ohranja, kar nam poda dva dodatna toka

\begin{align*}
  j_{in} &= \left| A_1 \right| ^2 + \left| A_2 \right| ^2 && \text{proti sipalcu} \\
j_{out} &= \left| B_1 \right| ^2 + \left| B_2 \right| ^2 && \text{od sipalca}
\end{align*}

 \( A_2 \) in \( B_1 \) sta v verjetnostnih tokov drugačno predznačena, vendar nas zanima vsota.

Vsoti \( j_{in} \) in \( j_{out} \) zapišemo v vektorskem zapisu

\begin{align*}
  \left| A_1 \right| ^2 + \left| A_2 \right| ^2 &= \left(A_1 ^{\ast} \, A_2^{\ast} \right) = A^{\dagger} A \\
  \left| B_1 \right| ^2 + \left| B_2 \right| ^2 &= \left(B_1 ^{\ast} \, B_2^{\ast} \right) = B^{\dagger} B \\
\end{align*}

Zaradi ohranitve tokov velja \( j_{in} = j_{out} \) oziroma \( A^{\dagger}A = B^{\dagger}B \). Preko enačbe \ref{eq:6} dobimo enakost

\begin{align*}
  A^{\dagger} A &= \left( SA \right)^{\dagger} SA \\
&= A^{\dagger} S^{\dagger} S A
\end{align*}

Iz tega dobimo, da velja \( S^{\dagger} S = I \) oziroma matematično, matrika \( S \) je unitarna za vsako matriko \( A \).

Predpostavimo, da je Hamiltonian \( H \in \mathbb{R} \) in konjugirana Schrödingerjeva enačba

\[ H \Psi(x) = E \Psi(x)
\]

bo tudi sipalno stanje. Torej, konjugiramo sedaj \ref{eq:5}, da dobimo

\begin{equation}
\label{eq:7}
\Psi_1^{\ast} (x) = A_1 ^{\ast} \frac{e^{- \mathrm{i} k_1 x}}{\sqrt{v_{1}}} + B_1 ^{\ast} \frac{e^{\mathrm{i} k_1 x}}{ \sqrt{v_{1}}}, \quad
\Psi_2^{\ast} (x) = B_1 ^{\ast} \frac{e^{- \mathrm{i} k_2 x}}{\sqrt{v_{2}}} + A_1 ^{\ast} \frac{e^{\mathrm{i} k_2 x}}{ \sqrt{v_{2}}}
\end{equation}

Vlogi koeficientov sta se zamenjali, in naša enačba za sipanje postane

\begin{align*}
  \begin{bmatrix} A_{1}^{\ast} \\ A_2^{\ast} \end{bmatrix} &= S \begin{bmatrix} B_{1}^{\ast} \\ B_{2}^{\ast} \end{bmatrix} \\
A^{\ast} &= S B^{\ast} \\
S^{\dagger} &= S^{\dagger} S B^{\ast} \\
S^{\dagger} A^{\ast} &= B^{\ast} && \left/ ^{\ast} \right. \\
S^T A &= B
\end{align*}

Torej, ob predpostavki, da je Hamiltonian realen, in ob vedenju, da za vsako matriko velja \ref{eq:6}, je iz zgornje izpeljave razvidno, da velja

\[ S^T = S
\]

in je sipalna matrika simetrična in sta prosta parametra samo \( t \) in \( t' \). Hamiltonian (npr. pri magnetizmu) ni nujno realen.

Za sod potencial \( V(x) = V(-x) \) in Schrödingerjevo enačbo

\[ H \Psi(x) = E \Psi(x)
\]

nas zanima soda valovna funkcija

\[ H \Psi(-x) = E \Psi(-x )
\]

Iz sodega potenciala dobimo enakost \( k_1 = k_2 \equiv k \) in \( v_1 = v_2  \equiv v \). Valovni funkciji \ref{eq:5} bosta tako pri \( \Psi(-x) \) enaki

\[ \Psi_1 = B_2 \frac{e^{- \mathrm{k} x}}{\sqrt{v}} + A_2 \frac{e^{\mathrm{i} k x}}{\sqrt{v}} \quad  \Psi_2 = A_1 \frac{e^{- \mathrm{k} x}}{\sqr\sqrt{v}}} + B_1 \frac{e^{\mathrm{i} k x}}{\sqr\sqrt{v}}}
\]

Zgornje lahko zapišemo v matrični obliki kot

\begin{equation}
\label{eq:8}
 \begin{pmatrix} B_{2} \\ B_{1} \end{pmatrix} = S \begin{pmatrix} A_{2} \\ A_{1} \end{pmatrix} = S \begin{pmatrix}
                                                                                                     0 & 1 \\
                                                                                                     1 & 0
                                                                                                      \end{pmatrix}  \begin{pmatrix} A_{1} \\ A_{2} \end{pmatrix}
\end{equation}


kjer smo uvedli Diracovo matriko \( \sigma_x \), ki je enaka

\[ \sigma_x = \begin{pmatrix}
              0 & 1 \\
              1 & 0
               \end{pmatrix}
\]

Stanje s koeficienti \( B \) lahko tudi zapišemo kot \( \sigma_x B (-x) = B \). Velja, da je \( \sigma_x ^2 = I \). Enačbo \ref{eq:8} pomnožimo s \( \sigma_x \) in upoštevamo identiteto, da dobimo

\[ S = \sigma_x S \sigma_x
\]

Velja,da je \( \sigma_x S \sigma_x = \begin{pmatrix} r' & t \\ t' & r \end{pmatrix} \), kar pomeni, da je matrika \( S \) enaka

\[ S = \begin{pmatrix}
       r & t \\
       t & r
        \end{pmatrix}
\]
