#+title: 4. vaje iz Kvantne mehanike
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}

* Princip nedoločenosti - nadaljevanje

Rešujemo diferencialno enačbo

\[ \left( - \mathrm{i} \hbar \frac{\mathrm{d} }{\mathrm{d} x} - \left\langle p \right\rangle \right) \psi(x) = \mathrm{i} \mu \left( x - \left\langle x \right\rangle \right) \psi(x)
\]

Splošna rešitev te diferencialne enačbe je

\[ \psi(x) = A \exp \left\{ \frac{\mathrm{i}}{\hbar} \left[ \left\langle p \right\rangle  - \mathrm{i} \mu \left\langle x \right\rangle\right]x + \mathrm{i} \mu \frac{x ^2}{2} \right\},
\]

kjer je \( A \) amplituda. Eksponent lahko dopolnimo do popolnega kvadrata in rešitev postane

\[ \psi(x) = A \exp \left\{ - \frac{\mu}{2 \hbar} \left( x - \left\langle x \right\rangle \right)^2 + \frac{\mathrm{i}}{\hbar} \left\langle p \right\rangle x \right\} = \tilde{A} \exp \left\{ - \frac{\mu}{2 \hbar} \left( x - \left\langle x \right\rangle \right) ^2 \right\} e^{\mathrm{i} \frac{\left\langle p \right\rangle x}{\hbar}}
\]

Vrednost \( \exp \left\{ \left\langle x \right\rangle ^2 \frac{\mu}{2 \hbar} \right\} \) je konstantna in smo jo zato skrili v \( \tilde{A} \).


Valovna funkcija mora biti normirana

\[ \int\limits_{- \infty}^{\infty} \left| \psi(x) \right| ^2 \, \mathrm{d} x = 1,
\]

kjer je v našem primeru

\[ \rho(x) = \left| \psi(x) \right| = \left| \tilde{A} \right|^2 \cdot e^{- \frac{\mu}{\hbar} \left( x - \left\langle x \right\rangle \right) ^2} = \frac{1}{\sqrt{2\pi}\sigma} e^{- \frac{\left( x - \left\langle x \right\rangle \right) ^2}{2 \sigma ^2}}, \ \sigma > 0
\]

Poslužili smo se znanja iz verjetnosti v fiziki, saj smo prepoznali v verjetnostni gostoti Gaussovo krivuljo. Rešitev naše diferencialne enačbe je 3 parametrična krivulja

\[ \psi(x) = \frac{1}{\left( 2 \pi \sigma ^2 \right)^{\frac{1}{4}}} \exp \left\{ - \frac{\left( x - \left\langle x \right\rangle \right) ^2}{4 \sigma ^2}  \right\} e^{\mathrm{i} \frac{\left\langle p \right\rangle x}{\hbar}},
\]

ki jim pravimo Gaussov valovni paket. Parametri so \( \sigma, \left\langle x \right\rangle \) in \( \left\langle p \right\rangle \). Člen \( e^{\mathrm{i} \frac{\left\langle p \right\rangle x}{\hbar}} \) je ravni val z valovno dolžino

[narišemo graf Im psi(x), Re psi(x) ter rho(x)]

\[ \frac{\left\langle p \right\rangle}{\hbar} \lambda = 2 \pi  \implies \ \lambda = \frac{h}{p}
\]

Tej valovni dolžini pravimo de Brogliejeva valovna dolžina.
* Pričakovane vrednosti in nedoločenosti v odvisnosti od časa

Zanimata nas pričakovana vrednost položaja \( \left\langle x \right\rangle \) in gibalne količine \( \left\langle p \right\rangle \) v odvisnosti od časa. Odvisnost od časa je izražena

\[ \left\langle i, t \right\rangle  = \int\limits_{}^{} \psi^{\ast} (i, t) i \psi(i, t) \, \mathrm{d} i, \quad i = x, p
\]

Nedoločenost v odvisnosti od časa je

\[ \delta i (t) = \sqrt{\left\langle x ^2, t \right\rangle - \left\langle x, t \right\rangle ^2}, \quad i = x, p
\]

Vrednosti ob času to \( \left\langle x, 0 \right\rangle = \left\langle  x \right\rangle\) za položaj, \( \left\langle p, 0 \right\rangle = \left\langle p \right\rangle\). Začetna vrednost nedoločenosti položaja je določena preko našega znanja Verjetnosti v fiziki \( \delta x(0) = \sigma \). Zaradi pogoja minimalizirane nedoločenosti

\[ \delta x \delta p = \frac{\hbar}{2}
\]

pa je začetna vrednost nedoločenosti gibalne količine \( \delta p (0) = \frac{\hbar}{2 \sigma} \)
** Teorija časovnega razvoja
*** Valovna funkcija

Časovni razvoj valovne funkcije dobimo tako, da rešimo stacionarno Schrödingerjevo enačbo

\[ H \left| \psi_n \right\rangle  = E_n \left| \psi_n \right\rangle
\]

Začetno stanje \( \psi(x, 0) \) razvijemo po lastnih baznih funkcijah

\[ \psi(x , 0) = \left| \psi, 0 \right\rangle = \sum\limits_n^{} c_n \psi_n (x) = \sum\limits_n^{} c_n \left| \psi_n \right\rangle,
\]

kjer \( n \)-ti koeficient časovnega razvoja izračunamo preko

\[ c_n = \left\langle \psi, 0 \middle| \psi_n \right\rangle
\]

Časovni razvoj valovne funkcije je dobljen tako, da dodamo časovno odvisen faktor razvoju po lastnih funkcijah

\[ \psi(x, t) = \left| \psi, t \right\rangle = \sum\limits_n^{} c_n \exp \left\{ - \mathrm{i} \frac{E_n}{\hbar} t \right\} \left| \psi_n \right\rangle
\]
*** Časovno odvisen operator

Funkcija operatorja \( A \) je definirana s pomočjo Taylorjevega razvoja te funkcije

\begin{equation}
\label{eq:3}
 F(A) = \sum\limits_n^{} \frac{1}{n!} f^{(n)} (A) A^n
\end{equation}

Povedali smo že v prejšnjem podpoglavju, da je časovni razvoj funkcije enak

\[ \left| \psi, t \right\rangle = \sum\limits_n^{} c_n \exp \left\{- \mathrm{i} \frac{E_n}{\hbar} t \right\} \left| \psi_n \right\rangle
\]

Sedaj bomo dokazali, da dobimo enak rezultat, če na začetno stanje \( \left| \psi, 0 \right\rangle \) delujemo s časovnim operatorjem \( e^{- \mathrm{i} \frac{H t}{\hbar}} \), ki smo ga izpeljali na predavanjih.

#+begin_theorem
Dokazujemo

\[ \left| \psi, t \right\rangle = \sum\limits_n^{} c_n \exp \left\{ - \mathrm{i} \frac{E_n}{\hbar}t  \right\}\left| \psi_n \right\rangle= \exp \left\{ - \mathrm{i} \frac{Ht}{\hbar} \right\} \left| \psi, 0 \right\rangle
\]
#+end_theorem

#+begin_proof
Začetno stanje valovne funkcije, na katerega vplivamo s časovnim operatorjem, razvijemo časovno

\[ e^{- \mathrm{i} \frac{Ht}{\hbar}} \left| \psi, 0 \right\rangle = \sum\limits_n^{} c_n e^{- \mathrm{i} \frac{Ht}{\hbar}} \left| \psi_n \right\rangle.
\]

Eksponent je neodvisen od vsote in ga lahko premaknemo znotraj vsote. Upoštevamo Taylorjev razvoj funkcije z operatorjem \ref{eq:3}. Naša funkcija je eksponentna, torej

\[ e^{- \mathrm{i} \frac{H t}{\hbar}} \left| \psi, 0 \right\rangle = \sum\limits_n^{} c_n \left[ \sum\limits_m^{} \frac{1}{m!} \left( - \mathrm{i} \frac{t}{\hbar} \right) ^m H^m \left| \psi_n \right\rangle \right]
\]

Spomnimo, da so \( \left| \psi_n \right\rangle \) lastna stanja Hamiltoniana preko Schrödingerjeve enačbe. Tako operator pretvorimo v skalar

\[ H^m \left| \psi_n \right\rangle = H^{m - 1} \cdot H \left| \psi_n \right\rangle = H^{m - 1} \cdot E_n \left| \psi_n \right\rangle = \ldots = E_n^m \left| \psi_n \right\rangle
\]

Zgornja vsota po definiciji Taylorjevega razvoja eksponentne funkcije postane

\[ e^{- \mathrm{i} \frac{Ht}{\hbar}} \left| \psi, 0 \right\rangle = \sum\limits_n^{} c_n e^{- \mathrm{i} \frac{E_n t}{\hbar} } \left|\psi_n \right\rangle
\]
#+end_proof
*** Časovno odvisna pričakovana vrednost

Zanima nas pričakovana vrednost operatorja \( A \) ob času \( t \). S spoznanjem prejšnjega podpoglavja zapišemo pričakovano po definiciji

\[ \left\langle A, t \right\rangle = \left\langle \psi, t \middle| A \middle| \psi, t \right\rangle
\]

Ket lahko zapišemo kot

\[ \left| \psi, t \right\rangle = e ^{- \mathrm{i} \frac{Ht}{\hbar}} \left| \psi, 0 \right\rangle,
\]

medtem ko bra zapišemo na podoben način s pomočjo kompleksne konjugacije

\[ \left\langle \psi, t \right| = \left\langle \psi, 0 \right| \left( e^{- \mathrm{i} \frac{Ht}{\hbar}} \right) ^{\dagger} = \left\langle \psi, 0 \right| e^{\mathrm{i} \frac{Ht}{\hbar}}.
\]

Pričakovano vrednost operatorja \( A \) ob času \( t \) tako zapišemo

\[ \left\langle A, t \right\rangle = \left\langle \psi, 0 \middle| A(t) \middle| \psi, 0 \right\rangle,
\]

kjer je \( A(t) = e^{\mathrm{i} \frac{Ht}{\hbar}} A e^{- \mathrm{i} \frac{Ht}{\hbar}}  \).

S podanim začetnim stanjem \( \left| \psi, 0 \right\rangle \) lahko sedaj preko časovnega operatorja izračunamo časovno odvisne pričakovane vrednosti, kar je precej lažje kot iskanje časovnega razvoja valovne funkcije \( \left| \psi, t \right\rangle \). Prvemu načinu iskanja pričakovanih vrednosti pravimo Heisenbergov pristop (slika), slednjemu pa Schrödingerjev pristop (slika).
*** Operator

Zanima nas časovni razvoj operatorja \( A \). Rešujemo diferencialno enačbo

\[ \frac{\mathrm{d} }{\mathrm{d} t} A(t) = e^{\mathrm{i} \frac{H t}{\hbar}} \cdot \frac{\mathrm{i} H}{\hbar} A e^{- \mathrm{i} \frac{Ht}{\hbar}} + e^{\mathrm{i} \frac{Ht}{\hbar}} A e^{- \mathrm{i} \frac{Ht}{\hbar}} \left( - \frac{\mathrm{i} H}{\hbar} \right).
\]

Člena \( e^{- \mathrm{i} \frac{Ht}{\hbar}} \) in \( \left( - \mathrm{i} \frac{H}{\hbar} \right) \) lahko zamenjamo, saj komutirata. To se da tudi preveriti tako, da zapišemo Taylorjev razvoj in preverimo komutacijo z vsakim členom. Komutacija nam omogoči, da izpostavimo eksponent

\[ \frac{\mathrm{d} }{\mathrm{d} t} A(t) = e^{\mathrm{i} \frac{Ht}{\hbar}} \left(\mathrm{i} \frac{H}{\hbar} A - A \mathrm{i} \frac{H}{\hbar} \right) e^{- \mathrm{i} \frac{Ht}{\hbar}} = \frac{\mathrm{i}}{\hbar} \left[ H, A \right] e^{- \mathrm{i} \frac{H t}{\hbar}} = - \frac{\mathrm{i}}{\hbar} \left[ H, A \right](t)
\]

Časovni razvoj operatorja torej dobimo z reševanjem diferencialne enačbe

\begin{equation}
\label{eq:1}
 \frac{\mathrm{d} }{\mathrm{d} t} A(t) = - \frac{\mathrm{i}}{\hbar} \left[ H, A \right](t)
\end{equation}

z začetnim pogojem \( A(0)= A \).

Pri operatorjih omenimo še naslednje identitete:

- \( \left( \alpha A + \beta B \right)(t) = \alpha A(t) + \beta B(t) \) za \( \alpha, \beta \in \mathbb{C} \), saj

  \[ \left( \alpha A + \beta B \right)(t) = e^{\mathrm{i} \frac{Ht}{\hbar}} \left( \alpha A + \beta B \right) e^{- \mathrm{i} \frac{Ht}{\hbar}} = \alpha \left( e^{\mathrm{i} \frac{Ht}{\hbar}} A e^{- \mathrm{i} \frac{Ht}{\hbar}} \right) + \beta \left( e^{\mathrm{i} \frac{Ht}{\hbar}} B e^{- \mathrm{i} \frac{Ht}{\hbar}} \right) = \alpha A(t) + \beta B(t)
  \]

- \( \left( AB \right) (t) = A(t) B(t) \), saj

  \[ \left( AB \right) (t) = e^{\mathrm{i} \frac{Ht}{\hbar}} AB e^{- \mathrm{i} \frac{Ht}{\hbar}} = e^{\mathrm{i} \frac{Ht}{\hbar}} A e^{- \mathrm{i} \frac{Ht}{\hbar}} e^{\mathrm{i} \frac{Ht}{\hbar}} B e^{- \mathrm{i} \frac{Ht}{\hbar}} = A(t) B(t)
  \]

- \( \left( A^{\dagger} \right)(t) = \left( A(t) \right)^{\dagger} \), saj

  \[ \left( A^{\dagger} \right) (t) = e^{\mathrm{i} \frac{Ht}{\hbar}} A^{\dagger} e^{-\mathrm{i} \frac{Ht}{\hbar}} = \left( e^{\mathrm{i} \frac{Ht}{\hbar}} A e^{- \mathrm{i} \frac{Ht}{\hbar}} \right) ^{\dagger} = \left( A(t) \right)^{\dagger}
  \]

** Reševanje naloge

Imamo Hamiltonian \( H = \frac{p ^2}{2m} + V(x) \), kjer je potencial \( V(x) = 0 \). Bazne funkcije prostega delca so zvezne, zato bomo namesto indeksa \( n \), s katerim označujemo diskretni spekter, uporabili indeks \( k \). Valovna funkcija prostega delca je

\[ \psi_k (x) = \frac{e^{\mathrm{i} k x}}{\sqrt{2\pi}} \text{ in } E_k = \frac{\hbar ^2 k ^2}{2m} .
\]

Funkcijo smo normirali s faktorjem \( \frac{1}{\sqrt{2 \pi}} \), saj ob normalizaciji dobimo navadno delta funkcijo. Začetno stanje \( \left| \psi, 0 \right\rangle \) bomo razvili po lastnih stanjih, vendar ker smo v zveznem spektru, bo vsoto nadomestil integral

\[ \psi(x, 0) = \frac{1}{\sqrt{2\pi}} \int\limits_{}^{} c_k e^{\mathrm{i} k x} \, \mathrm{d} k
\]

Posamezen koeficient v razvoju dobimo tako, da v zgornjem integralu prepoznamo Fourierovo transformacijo funkcije \( c(k) \) iz \( k \) v \( x \). \( c(k) \) bo tako inverzna Fourierova transformacija

\[ c(k) = \frac{1}{\sqrt{2 \pi}} \int\limits_{}^{} \psi(x, 0) e^{- \mathrm{i} k x} \, \mathrm{d} x
\]

Časovni razvoj funkcije bi tako bil

\[ \psi(x, t) = \frac{1}{\sqrt{2\pi}}\int\limits_{}^{} c(k) e^{- \frac{E_k t}{\hbar}} e^{\mathrm{i} kx} \, \mathrm{d} k
\]

Imamo operatorje \( x, p, x ^2 \) in \( p ^2 \). Kvadrata operatorjev sta povezana z operatorji preko identitete

\[ x ^2 (t) = \left[ x(t) \right] ^2 \ \text{ in } \ p ^2 (t) = \left[ p(t) \right] ^2
\]

Časovni razvoj operatorja kraja je po enačbi \ref{eq:1} enak

\[ \frac{\mathrm{d} }{\mathrm{d} t}x(t) = \frac{\mathrm{i}}{\hbar} \left[ H, x \right] (t).
\]

Za nadaljevanje reševanja diferencialne enačbe uporabimo identiteto

\[ \left[ AB, C \right] = A \left[ B, C \right] + \left[ A,C \right] B.
\]

S to identiteto potem velja

\[ \left[ H, x \right] = \left[ \frac{p ^2}{2m}, x \right] = \frac{1}{2m} \left[ p ^2, x \right] = \frac{1}{2m} \left( p \left[ p, x \right] + \left[ p, x \right] p \right) = - \frac{\mathrm{i} \hbar p}{m},
\]

saj \( \left[ p, x \right] = - \mathrm{i} \hbar \). Torej dobimo

\begin{equation}
\label{eq:2}
 \frac{\mathrm{d} }{\mathrm{d} t} x(t) = \frac{p(t)}{m}
\end{equation}

Izračunajmo sedaj še \( p(t) \) ponovno preko \ref{eq:1}

\[ \frac{\mathrm{d} }{\mathrm{d} t} p(t) = \frac{\mathrm{i}}{\hbar} \left[ H, p \right] (t) = \frac{\mathrm{i}}{\hbar} \left[ \frac{p ^2}{2m}, p \right](t) = 0
\]

Dobili smo dve sklopljeni enačbi. Gibalna količina je konstantna, saj je njen odvod ničeln. Označimo \( p(t) = p \). Rešimo \ref{eq:2}

\[ \frac{\mathrm{d} x}{\mathrm{d} t}(t) = \frac{p}{m} \implies \ x(t) = \frac{p}{m} t + D
\]

in z upoštevanjem začetnega pogoja \( x(0) = x \) sledi \( x(0) = D = x \), kar pomeni, da je časovni razvoj operatorja kraja

\[ x(t) = \frac{p}{m} t + x.
\]

Pričakovana vrednost položaja je

\[ \left\langle x, t \right\rangle  = \left\langle x(t), 0 \right\rangle = \left\langle \frac{p}{m}t + x, 0 \right\rangle= \frac{t}{m} \left\langle p, 0 \right\rangle + \left\langle x, 0 \right\rangle = \frac{t}{m} \left\langle p \right\rangle + \left\langle x \right\rangle.
\]

To pomeni, da se gostota porazdelitve premika premo enakomerno. Pričakovana vrednost gibalne količine

\[ \left\langle p, t \right\rangle  = \left\langle p(t), 0 \right\rangle = \left\langle p, 0 \right\rangle = \left\langle p \right\rangle
\]

pa se ne spreminja.

Nedoločenost gibalne količine je, ponovno spomnimo,

\[ \delta p (t) = \sqrt{\left\langle p ^2, t \right\rangle - \left\langle p, t \right\rangle ^2}
\]

Kvadrat pričakovane vrednosti

\[ \left\langle p ^2, t \right\rangle  = \left\langle p ^2 (t), 0 \right\rangle = \left\langle \left[ p(t) \right]^2, 0 \right\rangle = \left\langle p ^2, 0 \right\rangle
\]

se tako kot pričakovana vrednost gibalne količine ne spreminja. Ker se ne ena, ne druga količina ne spreminjata, je tudi nedoločenost gibalne količine konstantna

\[ \delta p(t) = \delta p(0) = \frac{\hbar}{2 \sigma}
\]

Analogno postopamo tudi pri nedoločenosti kraja

\[ \delta x ^2 (t) = \left\langle x ^2, t \right\rangle - \left\langle x, t \right\rangle ^2
\]

Pričakovana vrednost kraja je

\[ \left\langle x, t \right\rangle  = \frac{\left\langle p \right\rangle}{m} t + \left\langle x \right\rangle.
\]

Medtem ko pri kvadratu pričakovane vrednosti kraja pa moramo biti pozorna na vrstni red operatorjev

\begin{align*}
  \left\langle x ^2, t \right\rangle = \left\langle \left[ x(t) \right] ^2, 0 \right\rangle &= \left\langle \left[ \frac{p t}{m} + x \right] ^2, 0 \right\rangle  \\
&= \frac{t ^2}{m ^2} \left\langle p ^2, 0 \right\rangle + \frac{t}{m} \left\langle px, 0 \right\rangle+ \frac{t}{m} \left\langle xp, 0 \right\rangle + \left\langle x ^2, 0 \right\rangle
\end{align*}

Nadaljujemo naslednjič.
