#+title: 8. vaje iz Kvantne mehanike
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Harmonski oscilator v dveh dimenzijah

Imamo prvo vzbujeno stanje, ki ima dve degenerirani stanji \( \left| 1, 0 \right\rangle \) in \( \left| 0, 1 \right\rangle \). Želimo najti linearno kombinacijo teh dveh stanj tako, da bosta tudi lastni stanji operatorja \( L_z \).

Spomnimo, da velja

\[ L_z = \frac{e^{\mathrm{i} m \phi}}{\sqrt{2\pi}} = \hbar m \frac{e^{\mathrm{i} m \phi}}{\sqrt{2\pi}}, \ m \in \mathbb{Z},
\]

kjer je \( L_z = -\mathrm{i} \hbar \frac{\partial }{\partial \phi}  \). Vemo, da obstajata identiteti

\[ e^{\mathrm{i} \phi} = \cos \phi + \mathrm{i} \sin \phi \text{ in } e^{- \mathrm{i} \phi}  = \cos \phi - \mathrm{i} \sin \phi,
\]

kar nas navdihne, da zapišemo lastni stanji \( L_z \) za \( m = 1 \) kot

\[ \left| m = 1 \right\rangle = \frac{1}{\sqrt{2}} \left( \left| 1, 0 \right\rangle + \mathrm{i} \left| 0, 1 \right\rangle\right).
\]

Faktor \( \frac{1}{\sqrt{2}} \) poskrbi, da je naše stanje normalizirano. Na podoben način skonstruiramo stanje za \( m = -1 \), kjer potem velja

\[ \left| m = - 1 \right\rangle  = \frac{1}{\sqrt{2}} \left( \left| 1, 0  \right\rangle- \mathrm{i} \left| 0, 1 \right\rangle \right)
\]

** Drugi pristop

Iščemo lastna stanja operatorja \( L_z \), ki so hkrati tudi lastna stanja Hamiltoniana z energijo \( E = 2 \hbar \omega \).

\begin{equation}
\label{eq:1}
\left| \psi \right\rangle = \alpha \left| 10 \right\rangle + \beta \left| 01 \right\rangle
\end{equation}

Dvodimenzionalni Hamiltonian zapisan s kreacijskim in anihilacijskim operatorjem je enak

\[ H = H_x + H_y = \hbar \omega_x \left(  a_x ^{\dagger} a_x + \frac{1}{2} \right) + \hbar \omega_y \left( a_y ^{\dagger} a_y + \frac{1}{2} \right).
\]

Če je harmonski oscilator izotropen \( \omega_x = \omega_y = \omega \), se naš izraz še dodatni poenostavi, hkrati pa so tudi konstante \( x_0, y_0, p_{0x} \) in \( p_{0y} \) enake za posamezen operator.

\[ a_x = \frac{1}{\sqrt{2}} \left( \frac{x}{x_0} + \mathrm{i} \frac{p_x}{p_0} \right) \text{ in } a_y \frac{1}{\sqrt{2}} \left( \frac{y}{x_0} + \mathrm{i} \frac{p_y}{p_0} \right) ,
\]

kjer sta \( x_0 = \sqrt{\frac{\hbar}{m \omega}} \) in \( p_0 = \frac{\hbar}{x_0} \).

Operator vrtilne količine je po definiciji \( L_z = x p_y - y p_x \). Če ga izrazimo z anihilacijskima in kreacijskima operatorjema, to postane

\begin{align*}
  L_z &= \frac{x_0}{\sqrt{2}} \left( a_x + a_x ^{\dagger} \right) \cdot \frac{p_0}{\sqrt{2} \mathrm{i}} \left( a_y - a_y ^{\dagger} \right) - \frac{x_0}{\sqrt{2}} \left( a_y + a_y ^{\dagger} \right) \cdot \frac{p_0}{\sqrt{2} \mathrm{i}} \left( a_x - a_x^{\dagger} \right) \\
&= \frac{x_0 p_0}{2 \mathrm{i}} \left( \left[ a_x + a_x ^{\dagger} \right] \left[ a_y - a_y ^{\dagger} \right] - \left[ a_y + a_y ^{\dagger} \right] \left[ a_x - a_x ^{\dagger} \right] \right)
\end{align*}

Upoštevamo komutacijo \( \left[ a_x, a_y \right] = \left[ a_x ^{\dagger}, a_y ^{\dagger} \right] = \left[ a_x ^{\dagger}, a_y \right] = 0 \) in preostane nam izraz

\[ L_z = - \mathrm{i} \hbar \left( a_x ^{\dagger} a_y - a_x a_y ^{\dagger} \right)
\]

Če je naše stanje lastno stanje \( L_z \), potem lahko zapišemo kot

\[ L_z \left( \alpha \left| 10 \right\rangle + \beta \left| 01 \right\rangle\right) = \gamma \left( \alpha \left| 10 \right\rangle + \beta \left| 01 \right\rangle \right),
\]

kjer bo \( \gamma \) sorazmeren z \( \hbar \omega \). Vplivajmo z izpeljanim \( L_z \) na naše prvo vzbujeno stanje \ref{eq:1}.


\begin{align*}
  L_z \left( \alpha \left| 10 \right\rangle + \beta \left| 01 \right\rangle\right) &= \mathrm{i} \hbar \left( a_x a_y ^{\dagger} - a_x ^{\dagger} a_y \right) \left( a \left| 1 \right\rangle \left| 0 \right\rangle + \beta \left| 0 \right\rangle \left| 1 \right\rangle\right) \\
&= \mathrm{i} \hbar \left[ \alpha a_x \left| 1 \right\rangle + a_y^{\dagger} \left| 0 \right\rangle + \beta a_x \left| 0 \right\rangle a_y^{\dagger} \left| 1 \right\rangle - \alpha a_x^{\dagger} \left| 1 \right\rangle a_y \left| 0 \right\rangle - \beta a_x ^{\dagger} \left| 0 \right\rangle a_y \left| 1 \right\rangle \right]  \\
&= \mathrm{i} \hbar \left[ a \left| 0 \right\rangle \left| 1 \right\rangle - \beta \left| 1 \right\rangle \left| 0 \right\rangle \right] = \gamma \left[ \alpha \left| 10 \right\rangle + \beta \left| 01 \right\rangle\right]
\end{align*}

Dobimo sistem sklopljenih enačb, kjer velja

\begin{align*}
  \left| 10 \right\rangle: \quad - \mathrm{i} \hbar \beta &= \gamma \alpha \\
\left| 01 \right\rangle: \quad - \mathrm{i} \hbar \alpha &= \gamma \beta.
\end{align*}

Sistem lahko zapišemo tudi v matrični obliki kot

\[ \mathrm{i} \hbar \begin{bmatrix}
                    0 & -1 \\
                    1 & 0
                     \end{bmatrix} \begin{bmatrix} \alpha \\ \beta \end{bmatrix} = \gamma \begin{bmatrix} \alpha \\ \beta \end{bmatrix}
\]

Matriko lahko zapišemo tudi z matričnimi elementi \( L_z \)

\[ \begin{bmatrix}
   \left\langle 10 \middle| L_z \middle| 10 \right\rangle & \left\langle 10 \middle| L_z \middle| 01 \right\rangle \\
   \left\langle 01 \middle| L_z \middle| 10 \right\rangle& \left\langle 01 \middle| L_z \middle| 01 \right\rangle
    \end{bmatrix} = \mathrm{i} \hbar \begin{bmatrix}
                                     0 & -1 \\
                                     1 & 0
                                      \end{bmatrix}
\]

Preverimo en člen, ostali so prepuščeni za domačo nalogo

\[ \left\langle 01 \middle| \mathrm{i} \hbar \left( a_x a_y ^{\dagger} - a_x ^{\dagger} a_y \right) \middle| 10 \right\rangle = \mathrm{i} \hbar \left\langle 01 \middle| 01 \right\rangle = \mathrm{i} \hbar
\]

Z reševanjem matričnega sistema se priborimo do lastnih vrednosti, ki nam bodo potem dali lastne vektorje teh stanj, ki bi morali biti enaki tistim iz prejšnjega poglavja. Lastne vrednosti dobimo iz izračuna determinante

\[ \begin{bmatrix}
   -\gamma & - \mathrm{i} \hbar \\
\mathrm{i}\hbar    &  - \gamma
        \end{bmatrix}  = \gamma ^2 - \hbar ^2 \implies \ \gamma = \pm \hbar
\]

Za \( \gamma = \hbar \) dobimo sistem

\[ \begin{bmatrix}
0 & - \mathrm{i}\hbar \\
\mathrm{i} \hbar & 0
    \end{bmatrix} \begin{bmatrix} \alpha \\ \beta \end{bmatrix} = \hbar \begin{bmatrix} \alpha \\ \beta \end{bmatrix},
\]

ki nam poda enakost \( \beta = \mathrm{i} \alpha \) in pripadajoč lastni vektor je \( (1, \mathrm{i}) \). V Diracovem zapisu tako dobimo direktno enak rezultat kot v prejšnjem poglavju

\[ \left| m = 1 \right\rangle = \frac{1}{\sqrt{2}} \left( \left| 10 \right\rangle + \mathrm{i} \left| 01 \right\rangle\right).
\]

Drug lastni vektor je \( (\mathrm{i}, 1) \), kjer pa se stanje v Diracovem zapisu razlikuje v fazi, vendar to ni problem, saj

\[ \left| m = -1 \right\rangle  = \frac{1}{\sqrt{2}} \left( \mathrm{i} \left| 10 \right\rangle  + \left| 01 \right\rangle\right) = \mathrm{i} \frac{1}{\sqrt{2}} \left( \left| 10 \right\rangle - \mathrm{i} \left| 01 \right\rangle\right)
\]
* Vrtilna količina
** Teorija

Operator vrtilne količine je definirana kot

\[ \vec{L} = \vec{r} \times \vec{p}.
\]

Vrtilna količina ima tri komponente \( L_x, L_y \) in \( L_z \), ki med seboj ne komutirajo, saj velja \( \left[ L_{\alpha}, L_{\beta} \right]= \mathrm{i} \hbar \sum\limits_{\alpha \beta \gamma}^{} L_{\gamma}  \). Velikost vrtilne količin je enaka \( L ^2 = \vec{L} ^2 \) in komutira s posameznimi komponentami \( \left[ L ^2, L_{\alpha} \right] = 0 \).

Posledično velja tudi \( \left[ L ^2, L_z \right] = 0 \). Operator \( L ^2 \), ki vpliva na lastno stanje \( \left| lm \right\rangle \), nam da enakost

\[ L ^2 \left| lm \right\rangle  = \hbar ^2 l (l + 1) \left| lm \right\rangle.
\]

Lastno stanje istega stanja operatorja \( L_z \) pa ima lastno vrednost

\[ L_z \left| lm \right\rangle  = \hbar m \left| lm \right\rangle.
\]

Stanja \( \left| lm \right\rangle \) so predstavljena s sferičnimi harmoniki

\[ Y_{lm}  \left( \theta, \phi \right) = P_{lm} \left( \cos \theta \right) e^{\mathrm{i} m \phi},
\]

kjer so \( P_{lm} (\cos \theta) \) Legendrovi polinomi.

Definiramo tudi lestvična operatorja

\[ L_{\pm} = L_x \pm \mathrm{i} L_y,
\]

za katera tudi velja \( L_+ = L_- ^{\dagger} \) in

\[ L_{\pm} \left| lm \right\rangle = \hbar \sqrt{l(l + 1) - m (m \pm 1)} \left| l, m \pm 1 \right\rangle.
\]

Operatorja \( L_x \) in \( L_y \) lahko tudi izrazimo preko lestvičnih operatorjev in velja

\begin{equation}
\label{eq:2}
 L_x = \frac{L_+ + L_-}{2}, \quad L_y = \frac{L_+ - L_-}{2 \mathrm{i}}
\end{equation}

** Naloga

#+begin_problem
Imamo delec z vrtilno količino \( l = 1 \) in magnetnim momentom \( \mu \), ki se nahaja v magnetnem polju \( \vec{B} = B \hat{e}_z \). Magnetni moment \( \vec{\mu} \) in magnetno polje med seboj tvorita kot \( \theta \).
#+end_problem

Hamiltonian delca z magnetnim momentom \( \vec{\mu} \) v zunanjem magnetnem polju \( \vec{B} = B \hat{e}_z \) je

\[ H = - \vec{\mu} \cdot \vec{B} = - \lambda \vec{L} \cdot \vec{B}
\]

#+begin_note
  Če je neko stanje \( \left| \psi \right\rangle \) lastno stanje operatorja \( \vec{L} \cdot \hat{e} \) tako, da velja

  \[ \vec{L} \hat{e} \left| \psi \right\rangle = \hbar \left| \psi \right\rangle,
  \]

  potem pravimo, da vrtilna količina kaže v smeri \( \hat{e} \). Opomba, da je lastna vrednost tega stanja, največja možna lastna vrednost.
#+end_note

Zapišemo začetni pogoj \( \vec{L} \hat{e} \left| \psi, 0 \right\rangle = \hbar \left| \psi, 0 \right\rangle\), kjer \( \hat{e} \) kaže v smer, v katero je na začetku kazal magnetnim moment \( \vec{\mu} \). Predpostavimo lahko, da se je magnetnim moment \( \vec{\mu} \) na začetku nahajal v \( xz \)  ravnini, kar nam olajša zapis smeri \( \hat{e} \) v sferičnih koordinatah v

\[ \hat{e} = \begin{bmatrix} \sin \theta \\ 0 \\ \cos \theta \end{bmatrix}
\]

Tretja komponenta vrtilne količine \( m \) zaseda vrednosti od \( -l \) do \( l \), kar pomeni, da moramo za določitev začetnega stanja najti vrednosti \( \alpha, \beta \) in \( \gamma \) v linearni kombinaciji

\[ \left| \psi, 0 \right\rangle  = \alpha \left| 1,- 1 \right\rangle + \beta \left| 1, 0 \right\rangle + \gamma \left| 1,  1 \right\rangle
\]

Naš sistem je lastno stanje Hamiltoniana

\[ H \left| 1 m \right\rangle  = - \lambda B \hbar m \left| 1m \right\rangle,
\]

kar pomeni, da lahko začetno stanje razvijemo po času

\[ \left| \psi, t \right\rangle = \alpha \exp \left\{ \mathrm{i} \lambda B  (-1) \right\} \left| 1, -1 \right\rangle + \beta \exp \left\{ - \mathrm{i} \lambda B \cdot 0 \right\} \left| 10 \right\rangle + \gamma \exp \left\{ \mathrm{i} \lambda B (+1) \right\} \left| 11 \right\rangle
\]

\( \vec{L} \hat{e} \) lahko po definiciji skalarnega produkta zapišemo kot

\[ \left( \vec{L} \cdot \hat{e} \right) = L_x \sin \theta + L_z \cos \theta.
\]

Na začetno stanje vplivamo s tem operatorjem in dobimo

\begin{equation}
\label{eq:3}
 \left( \vec{L} \cdot \hat{e} \right) \left| \psi, 0 \right\rangle = \left( L_x \sin \theta + L_z \cos \theta \right) \left[ \alpha \left| 1, -1 \right\rangle + \beta \left| 1, 0 \right\rangle + \gamma \left| 1, 1 \right\rangle\right] = \hbar \left( \alpha \left| 1, -1  \right\rangle + \beta \left| 1, 0 \right\rangle + \gamma \left| 1, 1 \right\rangle\right)
\end{equation}


Za olajšanje kasnejših računov, si izračunajmo vmesne vrednosti, ki jih povzročijo operatorji \( L_+, L_- \) in \( L_z \) na stanja \( \left| 1, -1 \right\rangle, \left| 1, 0 \right\rangle\) in \( \left| 1, 1 \right\rangle \).

- Operator \( L_+ \) poda vrednosti

  \begin{align*}
    L_+ \left| 1, - 1 \right\rangle &= \sqrt{2} \hbar \left| 1, 0 \right\rangle \\
        L_+ \left| 1, 0 \right\rangle &= \sqrt{2} \hbar \left| 1, 1 \right\rangle \\
        L_+ \left| 1, 1 \right\rangle &= 0
  \end{align*}

  \( L_+ \) bi pri stanju \( \left| 1, 1 \right\rangle \) ustvaril stanje \( \left| 1, 2 \right\rangle \), ki pa zaradi omejitve \( m \) ni mogoče in to težavo nam reši lastna vrednost stanja, saj je enaka \( 0 \).

- Operator \( L_- \) poda vrednosti

  \begin{align*}
    L_- \left| 1, -1 \right\rangle  &= 0 \\
        L_- \left| 1, 0 \right\rangle &= \sqrt{2} \hbar \left| 1, -1 \right\rangle \\
        L_- \left| 1, 1 \right\rangle &= \sqrt{2} \hbar \left| 1, 0 \right\rangle
  \end{align*}

- Operator \( L_z \) poda vrednosti

  \begin{align*}
    L_z \left| 1, -1 \right\rangle &= - \hbar \left| 1, - 1 \right\rangle \\
        L_z   \left| 1, 0 \right\rangle &= 0 \\
        L_z \left| 1, 1 \right\rangle &= \hbar \left| 1, 1 \right\rangle
  \end{align*}

Z dobljenimi vrednostmi lahko sedaj preko enačbe \ref{eq:2} izrazimo \( L_x \) in \( L_y \)

\begin{align*}
  L_x \left| 1, -1 \right\rangle &= \frac{1}{2} \left( \sqrt{2} \hbar \left| 1, 0 \right\rangle + 0 \right) \\
L_x \left| 1,  0\right\rangle &= \frac{1}{2} \left( \sqrt{2} \hbar \left| 1, 1 \right\rangle + \sqrt{2} \hbar \left| 1, -1 \right\rangle \right)\\
L_x \left| 1, 1 \right\rangle &= \frac{1}{2} \left( 0 + \sqrt{2} \hbar \left| 1, 0 \right\rangle \right)
\end{align*}

Posledično lahko enačbo \ref{eq:3} posodobimo v

\begin{align*}
 \left( L_x \sin \theta + L_z \cos \theta \right) \left( \alpha \left| 1, -1 \right\rangle + \beta \left| 1, 0 \right\rangle + \gamma \left| 1, 1 \right\rangle\right) = &\alpha \sin \theta \frac{\sqrt{2}}{2} \hbar \left| 1, 0 \right\rangle \\
&+ \beta \sin \theta \frac{\sqrt{2}}{2} \hbar \left( \left| 1, 1 \right\rangle + \left| 1, -1 \right\rangle\right) \\
&+ \gamma \sin \theta \frac{\sqrt{2}}{2} \hbar \left| 1, 0 \right\rangle \\
&- \gamma \cos \theta \hbar \left| 1, -1 \right\rangle - \gamma \cos \theta \hbar \left| 1, 1 \right\rangle
\end{align*}

Dobimo sistem treh enačb, vendar ker so vse homogene, pomeni, da imamo rešitev samo do prostega parametra - v našem primeru bo to \( \beta \).

\begin{align*}
  \left\langle 1, - 1 \right|: \quad \alpha \hbar &= \beta \sin \theta \frac{\sqrt{2}}{2} \hbar - \cos \theta \alpha \hbar \\
\left\langle 1, 0 \right|: \quad \beta \hbar &= \alpha \sin \theta \frac{\sqrt{2}}{2} \hbar + \gamma \theta  \frac{\sqrt{2}}{2} \hbar \\
\left\langle 1, 1 \right|: \quad \gamma\hbar &= \beta \sin \theta \frac{\sqrt{2}}{2} \hbar + \gamma \cos \theta \hbar
\end{align*}

Ta sistem nam ne more podati določiti vseh konstant, zato bomo iz prve in tretje enačbe preko polovičnih kotov določili \( \alpha \) in \( \gamma \) kot

\[ \alpha = \frac{\beta \sin \theta \frac{\sqrt{2}}{2}}{1 + \cos \theta} = \frac{\sqrt{2}}{2} \beta \tan \frac{\theta}{2}, \quad \gamma = \frac{\beta \sin \theta \frac{\sqrt{2}}{2}}{1 - \cos \theta} = \frac{\sqrt{2}}{2} \beta \mathrm{ctg} \frac{\theta}{2}
\]

Konstanto \( \beta \) bomo določili preko normalizacije. Osnovno stanje je tako

\[ \left| \psi, 0 \right\rangle = \frac{\sqrt{2}}{2} \beta \tan \frac{\theta}{2} \left| 1, - 1 \right\rangle + \beta \left| 1, 0 \right\rangle + \frac{\sqrt{2}}{2} \beta \mathrm{ctg} \frac{\theta}{2} \left| 1, 1 \right\rangle
\]

In iz normalizacije sledi

\begin{align*}
  \left\langle \psi, 0 \middle| \psi, 0 \right\rangle &= \left| \beta \right| ^2 \left( \left[ \frac{\sqrt{2}}{2} \tan \frac{\theta}{2} \right] ^2 + \left[ \frac{\sqrt{2}}{2} \mathrm{ctg} \frac{\theta}{2} \right] ^2 \right) \\
&= \left| \beta \right| ^2 \left( \frac{\sin ^4 \frac{\theta}{2} + 2 \cos  ^2 \frac{\theta}{2} \sin ^2 \frac{\theta}{2} + \cos ^4 \frac{\theta}{2}}{2 \cos ^2 \frac{\theta}{2} \sin ^2 \frac{\theta}{2}} \right) \\
&= \left| \beta \right| ^2 \frac{1}{2 \cos ^2 \frac{\theta}{2} \sin ^2 \frac{\theta}{2}},
\end{align*}

da je \( \beta = \sqrt{2} \cos \frac{\theta}{2} \sin \frac{\theta}{2} \).

Začetno stanje je torej

\[ \left| \psi, 0 \right\rangle  = \sin ^2 \frac{\theta}{2} \left| 1, - 1 \right\rangle + \sqrt{2} \cos  \frac{\theta}{2} \sin \frac{\theta}{2} \left| 1, 0 \right\rangle + \cos ^2 \frac{\theta}{2} \left| 1, 1 \right\rangle,
\]

katerega časovni razvoj je

\begin{equation}
\label{eq:4}
 \left| \psi, t \right\rangle  = \sin ^2 \frac{\theta}{2} \exp \left\{ - \mathrm{i} \lambda B t \right\} \left| 1, - 1 \right\rangle + \sqrt{2} \cos  \frac{\theta}{2} \sin \frac{\theta}{2} \left| 1, 0 \right\rangle + \cos ^2 \frac{\theta}{2} \exp \left\{ \mathrm{i} \lambda B t \right\} \left| 1, 1 \right\rangle.
\end{equation}


Pričakovana vrednost operatorja \( L_z \) skozi čas je precej enostavna, saj vrne enako stanje pomnoženo z lastno vrednostjo.

\[ L_z \left| lm \right\rangle = \hbar m \left| lm \right\rangle.
\]

Pričakovana vrednost po definiciji je

\begin{align*}
  \left\langle L_z, t \right\rangle &= \left\langle \psi, t \middle| L_z \middle| \psi, t \right\rangle \\
&= \left\langle \psi, t \right| \left( - \hbar \sin ^2 \frac{\theta}{2} \exp \left\{ - \mathrm{i} \lambda B t \right\} \left| 1, -1 \right\rangle + \hbar \cos ^2 \frac{\theta}{2} \exp \left\{ \mathrm{i} \lambda B t \right\} \left| 1,1 \right\rangle \right)
\end{align*}

Vektor \( \left| \psi, t \right\rangle \) moramo kompleksno konjugirati, da ga pretvorimo v bra. Torej

\begin{align*}
\left\langle L_z, t \right\rangle &= \sin ^2 \frac{\theta}{2} \exp \left\{ \mathrm{i} \lambda B t \right\} \left| 1, - 1 \right\rangle \left( - \hbar \sin ^2 \frac{\theta}{2} \exp \left\{ - \mathrm{i} \lambda B t \right\} \left| 1, - 1 \right\rangle \right) \\
&\quad + \cos ^2 \frac{\theta}{2} \exp \left\{ - \mathrm{i} \lambda B t \right\} \left\langle 1, 1 \right| \cdot \hbar \cos ^2 \frac{\theta}{2} \exp \left\{ \mathrm{i} \lambda B t \right\} \left| 1, 1 \right\rangle + 0 \\
&= - \hbar \sin ^4 \frac{\theta}{2} + \hbar \cos ^4 \frac{\theta}{2} + \hbar \left( \cos ^2 \frac{\theta}{2} + \sin ^2 \frac{\theta}{2} \right) \left( \cos ^2 \frac{\theta}{2} - \sin ^2 \frac{\theta}{2} \right) = \hbar \cos \theta
\end{align*}

Preko identitet \ref{eq:2} lahko določimo tudi pričakovani vrednosti \( L_x \) in \( L_y \):

\begin{align*}
  \left\langle L_x, t \right\rangle &= \left\langle \psi, t \middle| \frac{L_+ + L_-}{2}\middle| \psi, t \right\rangle \\
&= \frac{1}{2} \left( \left\langle L_+, t \right\rangle + \left\langle L_-, t \right\rangle \right) \\
\left\langle L_y, t \right\rangle &= \left\langle \psi, t \middle| \frac{L_+ - L_-}{2 \mathrm{i}} \middle| \psi, t \right\rangle \\
&= \frac{1}{2 \mathrm{i}} \left( \left\langle L_+, t \right\rangle - \left\langle L_-, t \right\rangle\right)
\end{align*}

Ker velja \( L_+ ^{\dagger} = L_- \), lahko posledično zapišemo \( \left\langle L_-, t \right\rangle = \left\langle L_+^{\dagger}, t \right\rangle = \left\langle L_+, t \right\rangle ^{\ast}\). Pričakovana vrednost \( L_x \) se tako zapiše

\[ \left\langle L_x, t \right\rangle = \frac{1}{2} \left( \left\langle L_+, t \right\rangle + \left\langle L_+, t \right\rangle ^{\ast}\right) = \mathrm{Re} \left( \left\langle L_+, t \right\rangle \right)
\]

ter \( L_y \) je

\[ \left\langle L_y, t \right\rangle = \mathrm{Im} \left( \left\langle L_+, t \right\rangle \right).
\]

Upoštevamo vrednosti zapisane v alinejah in lahko precej preprosto izračunamo pričakovano vrednost \( \left\langle L_+, t \right\rangle \)

\begin{align*}
  \left\langle L_+, t \right\rangle &= \left\langle \psi, t \right| \left( \sqrt{2} \hbar \sin ^2 \frac{\theta}{2}  \exp \left\{- \mathrm{i} \lambda B t \right\} \left| 1, 0 \right\rangle + 2 \hbar \sin \frac{\theta}{2} \cos \frac{\theta}{2} \left| 1, 1 \right\rangle \right) \\
&= 2 \hbar \sin ^3 \frac{\theta}{2} \cos \frac{\theta}{2} + 2 \hbar \cos ^3 \frac{\theta}{2} \cos \frac{\theta}{2} \exp \left\{ - \mathrm{i} \lambda B t \right\} \\
&= \exp \left\{ - \mathrm{i} \lambda B t \right\} \sin \frac{\theta}{2} \cos \frac{\theta}{2} \left( \sin ^2 \frac{\theta}{2} + \cos ^2 \frac{\theta}{2} \right) 2 \hbar \\
&= \hbar \sin \theta \exp \left\{ - \mathrm{i} \lambda B t \right\} \\
&= \hbar \sin \frac{\theta}{2} \left( \cos (\lambda B t) - \mathrm{i} \sin (\lambda B t) \right)
\end{align*}

Da zaključimo: operator \( L_z \) se tekom časa ne spreminja

\[ \left\langle L_z, t \right\rangle  = \hbar \cos \theta.
\]

Operatorja \( L_x \) in \( L_y \) pa krožita okoli magnetnega polja

\[ \left\langle L_x, t \right\rangle = \hbar \sin \theta \cos (\lambda B t) \quad \text{ in } \left\langle L_y, t \right\rangle = - \hbar \sin \theta \sin (\lambda B t).
\]

Temu kroženju pravimo Larmorjeva precesija, ki pa jo poznamo že iz klasične fizike.

V primeru, da funkcija še ni razvita po lastnih stanjih (npr. na kolokviju), jo moramo najprej razviti, preden lahko ugotavljamo pričakovane vrednosti operatorja.
*** Meritev \( L_z \) ob času \( t \)

Po aksiomih kvantne mehanike je pred meritvijo valovna funkcija v vseh možnih stanjih, ki jih določa enačba \ref{eq:4}. V primeru, da izvedemo meritev ob času \( t = 0 \), bo valovna funkcija kolapsirala in bo za vse čase \( t_+ = 0 + \epsilon \) za \( \epsilon > 0 \) v opaženem stanju.

\begin{array}{|c|c|c|} \hline
\text{rezultat meritve} & \text{verjetnost} & \left| \psi, t_+ \right\rangle \\ \hline
-\hbar & \sin ^4 \frac{\theta}{2} & \left| 1, -1 \right\rangle \\
0 & 2 \sin ^2 \frac{\theta}{2} \cos ^2 \frac{\theta}{2} & \left| 1, 0 \right\rangle \\
\hbar & \cos ^4 \frac{\theta}{2} & \left| 1, 1 \right\rangle \\ \hline
\end{array}
