#+title: 9. vaje iz Kvantne mehanike
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Rashbova sklopitev

#+begin_problem
Obravnavajmo delec v dvodimenzionalni \( x, y \) ravnini s spinom \( S = \frac{1}{2} \) in Hamiltonianom

\[ H = \frac{p ^2}{2m} + \lambda \left( p_x S_y - p_y S_x \right),
\]

kjer sta \( \vec{p} = (p_x, p_y, 0) \) in \( \vec{S} = (S_x, S_y, 0) \) gibalna količina in spin operatorja. \( \lambda \) je konstantna. Iščemo lastne vrednosti in funkcije Hamiltoniana \( H \).
#+end_problem

Matematično je spinska vrtilna količina identitična tirni vrtilni količini. Zanjo veljajo tudi enake relacije, čeprav ima fizikalno drugačen pomen.

Hilbertov prostor \( \mathcal{H} \) je tenzorski prostor Hilbertovega prostora krajevnega dela in spinskega dela

\[ \mathcal{H} = \mathcal{H}_r \otimes \mathcal{H}_s.
\]

Valovna funkcija v Hilbertovem prostoru \( \mathcal{H} \) je

\[ \left| \psi  \right\rangle = \left| \psi_r \right\rangle \otimes \left| \psi_2 \right\rangle
\]

Delec s spinom \( S = \frac{1}{2} \) ima valovno funkcijo, ki je linearna kombinacija obeh stanj

\[ \left| \psi_2 \right\rangle = \alpha \left| \frac{1}{2}, \frac{1}{2} \right\rangle + \beta \left| \frac{1}{2}, - \frac{1}{2} \right\rangle,
\]

kjer prvo kvantno število označuje velikost spina \( s= \frac{1}{2} \), druga številka pa projekcijo spina \( m_s \in \left\{ - \frac{1}{2}, \frac{1}{2} \right\} \).

Operator spina \( S ^2 \) deluje na stanje \( \left| s, m_s \right\rangle \)

\begin{equation}
\label{eq:1}
 S ^2 \left| s, m_s \right\rangle = \hbar ^2 s( s + 1 ) \left| s, m_s \right\rangle.
\end{equation}

Učinek operatorja \( S ^2 \) na bazno stanje bo torej po \ref{eq:1}

\[ S ^2 \left| \frac{1}{2}, \frac{1}{2} \right\rangle = \frac{3}{4} \hbar ^2 \left| \frac{1}{2}, \frac{1}{2} \right\rangle, \quad S ^2 \left| \frac{1}{2}, - \frac{1}{2} \right\rangle = \frac{3}{4} \hbar ^2 \left| \frac{1}{2}, - \frac{1}{2} \right\rangle
\]

Operator \( S_z \) pa ima na stanje \( \left| s, m_s \right\rangle \) naslednji učinek

\[ S_z \left| s, m_s \right\rangle = \hbar m \left| s, m_s \right\rangle
\]

\( S_z \) na bazno stanje bo torej povzročilo

\[ S_z \left| \frac{1}{2}, \frac{1}{2} \right\rangle = \frac{\hbar}{2} \left| \frac{1}{2}, \frac{1}{2} \right\rangle, \quad S_z \left| \frac{1}{2}, - \frac{1}{2} \right\rangle = - \left| \frac{1}{2}, - \frac{1}{2} \right\rangle
\]

Za stanja v spinskem prostoru ponavadi uporabimo drugo notacijo. Stanje s spinom navzgor \( \left| \frac{1}{2}, \frac{1}{2} \right\rangle \) označimo z \( \left| \uparrow \right\rangle \), stanje s spinom navzdol pa označimo \( \left| \downarrow \right\rangle \).

Krajevni Hilbertov prostor je neskončno-dimenzionalen, medtem ko spinski del pa je dvodimenzionalen, saj je osnovno stanje predstavljeno z linearno kombinacijo dveh vektorjev.
** Lestvični operatorji spina

Podobno kot pri tirni vrtilni količini lahko definiramo lestvična operatorja, ki nam zvišujeta ali znižujeta dano stanje \( m_s \)

\[ S_{\pm} \left| s, m_s \right\rangle = \hbar \sqrt{s (s+ 1) - m_{s} (m_{s} \pm 1)} \left| s, m_s \pm 1 \right\rangle
\]

Definirana sta kot

\begin{align}
  S_+ &= S_x + \mathrm{i} S_y \label{eq:spinU} \\
S_- &= S_x - \mathrm{i} S_y \label{eq:spinD}
\end{align}

S seštevanjem in odštevanjem enačb lahko izrazimo operatorja \( S_x \) in \( S_y \)

\begin{align}
S_x &= \frac{S_+ + S_-}{2} \label{eq:spinX} \\
S_y &= \frac{S_+ - S_-}{2 \mathrm{i}} \label{eq:spinY}
\end{align}

#+begin_my_example
Kot primer si poglejmo, kako lestvični operatorji vplivajo na stanje s spinom navzgor \( \left| \uparrow \right\rangle \) in navzdol \( \left| \downarrow \right\rangle \).

Operator \( S_+ \) ima na stanji sledeč učinek

\[ S_+ \left| \uparrow \right\rangle = 0 \text{ in } S_+ \left| \downarrow \right\rangle = \left| \uparrow \right\rangle \hbar \sqrt{ \frac{1}{2} \cdot \frac{3}{2} + \frac{1}{2} \cdot \frac{1}{2}} = \hbar \left| \uparrow \right\rangle
\]

Analogno velja tudi

\[ S_- \left| \uparrow \right\rangle = \left| \downarrow \right\rangle \hbar \sqrt{\frac{3}{4} - \frac{1}{2} \left( - \frac{1}{2} \right)} = \hbar \left| \downarrow \right\rangle \text{ in } S_- \left| \downarrow \right\rangle = 0
\]

Z upoštevanjem definiciji \ref{eq:spinX} dobimo

\[ S_x \left| \uparrow \right\rangle = \frac{\hbar}{2} \left| \downarrow \right\rangle \text{ in } S_x \left| \downarrow \right\rangle = \frac{\hbar}{2} \left| \uparrow \right\rangle,
\]

ter analogno

\[ S_y \left| \uparrow \right\rangle  = - \frac{\hbar}{2 \mathrm{i}} \left| \downarrow \right\rangle \text{ in } S_y \left| \downarrow \right\rangle = \frac{\hbar}{2 \mathrm{i}} \left| \uparrow \right\rangle
\]
#+end_my_example

** Reševanje naloge

Lastne funkcije in stanja bomo dobili preko reševanje Schrödingerjeve enačbe

\[ H \left| \psi \right\rangle = E \left| \psi \right\rangle.
\]

Enačbo bomo reševali z nastavkom

\[ \left| \psi \right\rangle = \left| \psi_{\uparrow} \right\rangle \left| \uparrow \right\rangle + \left| \psi_{\downarrow} \right\rangle \left| \downarrow \right\rangle,
\]

kjer iščemo funkciji \( \left| \psi_{\uparrow} \right\rangle \) in \( \left| \psi_{\downarrow} \right\rangle \).

Upoštevamo definicijo Hamiltoniana in nastavek

\[ \left( \frac{p_x ^2 + p_y ^2}{2m} + \lambda \left( p_x S_y - p_y S_x \right)  \right) \left( \left| \psi_{\uparrow}\right\rangle  \left| \uparrow \right\rangle + \left| \psi_{\downarrow} \right\rangle \left| \downarrow \right\rangle \right) = E \left( \left| \psi_{\uparrow}\right\rangle  \left| \uparrow \right\rangle + \left| \psi_{\downarrow} \right\rangle \left| \downarrow \right\rangle \right)
\]

Operatorja gibalne količine delujeta na \( \left| \psi_{\uparrow} \right\rangle \) in \( \left| \psi_{\downarrow} \right\rangle \), medtem ko operatorja spina delujte na \( \left| \uparrow \right\rangle \) ter \( \left| \downarrow \right\rangle \). Za operatorja gibalne količine ne vemo točnega rezultata, kakšen bo učinek.

Našo enačbo pomnožimo in razpišemo

\begin{align*}
   E \left( \left| \psi_{\uparrow}\right\rangle  \left| \uparrow \right\rangle + \left| \psi_{\downarrow} \right\rangle \left| \downarrow \right\rangle \right) = & \frac{1}{2m} \left[ \left| \uparrow \right\rangle \left( p_x ^2 \left| \psi_{\uparrow} \right\rangle + p_y ^2 \left| \psi_{\uparrow} \right\rangle \right) + \left| \downarrow \right\rangle \left( p_x ^2 \left| \psi_{\downarrow} \right\rangle + p_y ^2 \left| \psi_{\downarrow} \right\rangle \right) \right] \\
& + \lambda \left[ p_x \left| \psi_{\uparrow} \right\rangle \cdot \left( - \frac{\hbar}{2 \mathrm{i}} \right)\left| \downarrow \right\rangle + p_x \left| \psi_x \right\rangle \frac{\hbar}{2 \mathrm{i}} \left| \uparrow \right\rangle - p_y \left| \psi_{\uparrow} \right\rangle \frac{\hbar}{2} \left| \downarrow \right\rangle - p_y \left| \psi_{\downarrow} \right\rangle \cdot \frac{\hbar}{2} \left| \uparrow \right\rangle \right]
\end{align*}

Dobljeno pomnožimo z \( \left\langle \uparrow \right| \)

\[ \frac{1}{2m} \left( p_x ^2 \left| \psi_{\uparrow} \right\rangle + p_y ^2 \left| \psi_{\uparrow} \right\rangle \right) + \lambda \left( p_x \left| \psi_{\downarrow}\right\rangle  \cdot \frac{\hbar}{2 \mathrm{i}} - p_y \left| \psi_{\downarrow} \right\rangle \frac{\hbar}{2} \right) = E \cdot \left| \psi_{\uparrow} \right\rangle.
\]

Analogno pomnožimo tudi z \( \left\langle \psi_{\downarrow} \right| \)

\[ \frac{1}{2m} \left( p_x ^2 \left| \psi_{\downarrow} \right\rangle + p_y ^2 \left| \psi_{\downarrow} \right\rangle \right) + \lambda \left( p_x \left| \psi_{\uparrow}\right\rangle  \cdot\left( -  \frac{\hbar}{2 \mathrm{i}}\right) - p_y \left| \psi_{\uparrow} \right\rangle \frac{\hbar}{2} \right) = E \cdot \left| \psi_{\downarrow} \right\rangle.
\]

Dobili smo sistem diferencialnih enačb, ki jih lahko z upoštevanjem definicijo operatorjev zapišemo

\begin{align*}
 -\frac{\hbar ^2}{2m} \nabla ^2 \psi_{\uparrow} \left( \vec{r} \right) + \lambda \left( - \frac{\mathrm{i} \hbar \partial_x \psi_{\downarrow} \hbar}{2 \mathrm{i} } + \mathrm{i} \hbar \partial_y \psi_{\downarrow} \cdot \frac{\hbar}{2} \right) &= E \psi_{\uparrow} \left( \vec{r} \right) \\
 -\frac{\hbar ^2}{2m} \nabla ^2 \psi_{\downarrow} \left( \vec{r} \right) + \lambda \left( \frac{\mathrm{i} \hbar \partial_x \psi_{\uparrow} \hbar}{2 \mathrm{i} } + \mathrm{i} \hbar \partial_y \psi_{\uparrow} \cdot \frac{\hbar}{2} \right) &= E \psi_{\downarrow} \left( \vec{r} \right).
\end{align*}

Ne bomo reševali tega sistema, ampak bomo ubrali lažjo pot, ki vključuje simetrije.

Za začetek bomo dokazali, da velja

\[ \left[ H, \vec{p} \right] = 0.
\]

Za dokaz moramo dokazati, da hamiltonian \( H \) komutira z vsako komponento \( \vec{p} \).

\[ \left[ H, p_x \right] = \left[ \frac{p_x ^2 + p_y ^2}{2m} + \lambda \left( p_x S_y - p_y S_x  \right), p_x \right]
\]

Operatorja \( p_x ^2 \) in \( p_x \) komutirata in prav tako \( p_y ^2 \) in \( p_x \). Poglejmo si še člen Rashbove sklopitve \( \left( p_x S_y - p_y S_x \right) \). \( p_x \) in \( p_y \) komutirata s \( p_x \). Spinska operatorja \( S_{x, y} \) delujeta na Hilbertov prostor \( \mathcal{H}_s \), medtem ko \( p_x \) deluje na Hilbertov prostor \( \mathcal{H}_p \).

Vsak operator iz enega Hilbertovega prostora komutira z vsakim operatorjem iz drugega Hilbertovega prostora. Sledi

\[ \left[ H, p_x \right] = \left[ H, p_y \right] = 0
\]

Za dva operatorja, ki komutirata, lahko najdemo lastne funkcije, ki so hkrati lastne funkcije obeh operatorjev. Z drugimi besedamo, lastne funkcije gibalne količine so prav tako lastne funkcije Hamiltoniana. Velja tudi obratno, vendar je lastne funkcije \( \vec{p} \) lažje najti.
