#+title: Vaje iz Mehanike kontinuov, 10. teden v letu
#+subtitle: 2026/03/04
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Enoosna deformacija palice

#+begin_problem
Na palico delujemo s silo \( F \) v smeri \( z \) na osnovno ploskev \( S \). Zanima nas, kako se spremeni površina po aplikaciji sile.
#+end_problem

Spremembo površine bomo izračunali po enačbi, izpeljani na predavanjih,

\[ \frac{\Delta V}{V} = \mathrm{tr} \left( \mathsf{u} \right).
\]

Priboriti se moramo torej do posameznih elementov deformacijskega tenzorja.

Delovanje sile bomo opisali z

\[ p_{zk} n_k = - \frac{F}{S}.
\]

Sila deluje vzporedno z normalo osnovne ploskve, kar pomeni, da bo normala \( \mathbf{n} = (0, 0, 1) \). Zapišemo tenzor

\[ \begin{pmatrix}
   p_{xx} & p_{xy} & p_{xz} \\
   p_{yx} & p_{yy} & p_{yz} \\
   p_{zx} & p_{zy} & p_{zz}
   \end{pmatrix} \begin{pmatrix} 0 \\ 0 \\ 1 \end{pmatrix} = \begin{pmatrix} p_{xz} \\ p_{yz} \\ p_{zz} \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \\ - \frac{F}{S} \end{pmatrix}.
\]

Če si kot primer pogledamo še na stranico palice, ki ima normalo \( \mathbf{n} = (1, 0, 0) \).

\[ \begin{pmatrix}
   p_{xx} & p_{xy} & p_{xz} \\
   p_{yx} & p_{yy} & p_{yz} \\
   p_{zx} & p_{zy} & p_{zz}
   \end{pmatrix} \begin{pmatrix} 1 \\ 0 \\ 0 \end{pmatrix} = \begin{pmatrix} p_{xx} \\ p_{yx} \\ p_{zx} \end{pmatrix} = 0
\]

Robni pogoj bo torej

\[ p_{zz} = - \frac{F}{S},
\]

napetostni tenzor v matrični formi pa bo

\[ p_{ij} = \begin{bmatrix}
            0 & 0 & 0 \\
            0 & 0 & 0 \\
            0 & 0 & -\frac{F}{S}
            \end{bmatrix}
\]


Nimamo sil, ki delujejo na celoten volumen, iz česar sledi \( f_z = 0 \). Cauchyjeva enačba je

\[ \frac{\partial p_{zk}}{\partial x_{k}} = 0.
\]

Deformacijski tenzor ustreza enačbi iz uvoda \eqref{eq:1}

\[ u_{ij} = \frac{1}{2 \mu} p_{ij} - \frac{\lambda}{2 \mu \left( 2 \mu + 3 \lambda \right)} p_{ll} \delta_{ij}.
\]

Ker so vsi nediagonalni členi napetostnega tenzorja ničelni (\( p_{ij, i \ne j} = 0 \)), bo isto veljalo tudi za deformacijski tenzor \( u_{ij, i \ne j} = 0 \).

\( p_{kk} \) predstavlja sled tenzorja in je enaka

\[ p_{kk} = p_{xx } + p_{yy} + p_{zz} = - \frac{F}{S}.
\]

Torej so diagonalne komponente deformacijskega tenzorja

\begin{align}\label{ali:1}
  u_{xx } &= \frac{\lambda}{2 \mu \left( 2\mu + 3 \lambda \right)} \frac{F}{S}\\
  u_{yy } &= \frac{\lambda}{2 \mu \left( 2\mu + 3 \lambda \right)} \frac{F}{S} \\ \label{ali:3}
  u_{zz } &= - \frac{F}{2 \mu S} + \frac{\lambda}{2 \mu \left( 2\mu + 3 \lambda \right)} \frac{F}{S} = - \frac{F}{S} \left( \frac{\mu + \lambda}{\mu \left( 2 \mu + 3\lambda \right)} \right).
\end{align}

Sprememba volumna je torej

\[ \frac{\Delta V}{V} = \mathrm{tr} \left( u \right) = \frac{2F}{S} \frac{\lambda}{2\mu \left( 2 \mu + 3 \lambda \right)} - \frac{F}{S} \frac{\mu + \lambda}{\mu \left( 2 \mu + 3 \lambda \right)} = - \frac{F}{S} \frac{1}{2 \mu + 3 \lambda}.
\]

Iz klasične fizike vemo, da za Youngov modul velja

\[ \frac{F}{S} = E \frac{\Delta l}{l} = E u_{zz}.
\]

kjer vemo iz predavanj, da velja \( \frac{\Delta l}{l} = u_{zz} \). Iz \ref{ali:3} lahko odčitamo Youngov modul.

\[ \frac{F}{S} = - \left( \frac{\mu \left( 2 \mu + 3\lambda \right)}{\mu + \lambda} \right) u_{zz}.
\]

Poissonovo število pa je po definiciji

\[ \sigma = - \frac{u_{xx }}{u_{zz}} = \frac{\lambda}{2(\mu + \lambda)},
\]

kjer smo uporabili enačbi \ref{ali:1} in \ref{ali:3}.

* Potopljena kocka
#+begin_problem
Potopimo kocko v vodo in nanjo deluje tlak \( p \). Zanima nas sprememba prostornine.
#+end_problem

Na vse stranice kocke deluje tlak \( p \). Kot primer si pogledamo

\[ p_{ij} \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix} = \begin{bmatrix} p_{xx} \\ p_{yx} \\ p_{zx} \end{bmatrix} = \begin{bmatrix} - p \\ 0 \\ 0 \end{bmatrix}.
\]

Upoštevali smo, da tlak kaže v nasprotni smeri normale na površino. Torej bo napetostni tenzor

\[ p_{ij} = - p \delta_{ij}.
\]

Za kocko velja Navierova enačba

\[ \frac{\partial p_{ij}}{\partial x_{j}} = 0.
\]

Vsi diagonalni elementi napetostnega tenzorja  so si medseboj enaki je

\[ u_{xx } = - \frac{1}{2 \mu}p + \frac{3 \lambda p}{2 \mu \left( 2 \mu + 3 \lambda \right)} = \frac{- p}{2 \mu + 3\lambda} .
\]

Sprememba volumna je torej
* Teoretičen uvod/recap

Hookov zakon \( F = k \Delta x \) je opisan s pomočjo deformacijskega tenzorja

\[ u_{ij} = \frac{1}{2} \left( \frac{\partial u_{i}}{\partial x_{j}} + \frac{\partial u_{j}}{\partial x_{i}}  \right),
\]

ki igra vlogo razteznega koeficienta, ter napetostnega tenzorja \( p_{ij} \), ki igra vlogo sile. Definiran je kot

\[ f_i = \frac{\partial }{\partial x_{j}}  p_{ij}.
\]

Drugi Newtonov zakon v zveznem mediju je Cauchyjeva enačba

\[ \rho \ddot{u}_i = f_i + \frac{\partial p_{ik}}{\partial x_{k}},
\]

kjer so \( f_i \) zunanje sile, ki delujejo po gostoti površine (gravitacija, električno polje). V primeru ravnovesja velja

\[ f_i \frac{\partial p_{ik}}{\partial x_{k}} = 0.
\]

Zvezni medij ima robne pogoje

\[ p_{ik}  n_k = \tilde{F}_i,
\]

kjer je \( \tilde{F}_i \) opisuje sile na meji medija.

Hookov zakon lahko zapišemo z Laméjevimi koeficienti ali pa z Youngovim modulom in Poissonovim številom

\[ p_{ij} = 2 \mu u_{ij} + \lambda u_{ll} \delta_{ij} = \frac{E}{1 + \sigma} \left( u_{ij} + \frac{\sigma}{1 - 2 \sigma} u_{kk} \delta_{ij} \right).
\]

Deformacijski tenzor pa izrazimo iz Hookovega zakona

\begin{equation}
\label{eq:1}
 u_{ij} = \frac{1}{2 \mu} p_{ij} - \frac{\lambda}{2 \mu \left( 2 \mu + 3 \lambda \right)} p_{ll} \delta_{ij} = \frac{1}{E} \left[ \left( 1 + \sigma \right) p_{ij} - \sigma p_{ll} \delta_{ij} \right] .
\end{equation}

Ko združimo Cauchyjevo enačbo in Hookov zakon, dobimo Navierovo enačbo

\[ \rho \ddot{u}_i = f_i + \mu \nabla ^2 u_i + \left( \mu + \lambda \right) \frac{\partial }{\partial x_{i}} \left( \frac{\partial u_{i}}{\partial x_{k}} \right),
\]

oz. vektorsko

\[ \rho \ddot{\mathbf{u}} = \mathbf{f} + u \nabla ^2 \mathbf{u} + \left( \mu + \lambda \right) \nabla \nabla \mathbf{u}
\]
* Vrteč elastičen cilinder

#+begin_problem
Imamo elastičen cilinder, ki se vrti s frekvenco \( \omega \) okoli osi, ki poteka skozi središča krogov osnovne ploskve. Zanima nas deformacija tega cilindra zaradi vrtenja.
#+end_problem

Deformacija je samo v radialni smeri \( \mathbf{u} = u_r (r) \hat{e}_r \) in je vse v osno simetrično.

Navierova enačba v vektorski obliki za ravnovesno stanje je

\[ \mathbf{f} + \mu \nabla ^2 \mathbf{u} + \left( \mu + \lambda \right) \nabla \nabla \mathbf{u} = 0.
\]

Zapišemo jo z Youngovim modulom in Poissonovim številom

\[ \mathbf{f} + \frac{E}{2(1 + \sigma)} \left( \nabla ^2 \mathbf{u} + \frac{1}{1 - 2\sigma} \nabla \nabla \cdot \mathbf{u} \right) = 0.
\]

Iz mafije (allegedly) vemo, da je gradient divergence enak

\[ \nabla \nabla = \nabla ^2 + \nabla \times \nabla \times.
\]

V Navierovi enačbi nadomestimo Laplaceov operator z zgornjo identiteto in lahko zapišemo

\[ \mathbf{f} + \left( 1 + \frac{1}{1 - 2\sigma} \right) \frac{E}{2(1 + \sigma)} \nabla \nabla \cdot \mathbf{u} - \frac{E}{2(1 + \sigma)} \nabla \times \nabla \times \mathbf{u} = 0
\]

Spomnimo se rotorja v cilindričnih koordinatah, ki je

\[ \nabla \times \mathbf{u} = \left( \frac{1}{r} \frac{\partial u_{r}}{\partial \phi} - \frac{\partial u_{\phi}}{\partial z}  \right) \hat{e}_r + \left( \frac{\partial u_{r}}{\partial z}  - \frac{\partial u_{z}}{\partial r}  \right) \hat{e}_{\phi} + \left( \frac{1}{r} \frac{\partial (r u_{\phi})}{\partial r} - \frac{1}{r} \frac{\partial u_{r}}{\partial \phi}  \right)\hat{e}_z.
\]

Ker je \( u_r = u_r (r) \ne u_r (\phi, z) \) in \( u_{\phi} = u_z = 0 \), bo zgornji rotor ničeln.

Preostane nam enačba

\[ \mathbf{f} + \left( 1 + \frac{1}{1 - 2\sigma} \right) \frac{E}{2 (1 + \sigma)} \nabla \nabla \cdot \mathbf{u} = 0.
\]

Sistemsko silo, ki je posledica vrtenja, predstavimo kot \( \mathbf{f} = \omega ^2 r \rho \hat{e}_r \).

Spomnimo se še, da je divergenca vektorja

\[ \nabla \cdot \mathbf{u} = \frac{1}{r} \left( \frac{\partial (u_{r} r)}{\partial r}  \right) + \frac{1}{r} \frac{\partial u_{\phi}}{\partial \phi}  + \frac{\partial u_{z}}{\partial z}.
\]

Nadalje lahko preoblikujemo enačbo v

\[ \rho \omega ^2 r \hat{e}_r + \frac{1 - \sigma}{1 - 2\sigma} \frac{E}{1 + \sigma} \nabla \left( \frac{1}{r} \frac{\partial (r u_{r})}{\partial r}  \right) = 0.
\]

Gradient je samo \( \frac{\partial }{\partial r}  \) in enačba je

\begin{align*}
0 &= \rho \omega ^2 r \hat{e}_r + \frac{1 - \sigma}{1 - 2 \sigma} \frac{E}{1 + \sigma} \frac{\partial }{\partial r}  \left( \frac{1}{r} \frac{\partial (r u_{r})}{\partial r}  \right) \hat{e}_r \\
-\alpha r &= \frac{\partial }{\partial r} \left( \frac{1}{r} \frac{\partial (r u_{r})}{\partial r}  \right).
\end{align*}

Po prvem integriranju nam ostane

\[ \frac{1}{r} \frac{\partial (r u_{r})}{\partial r}  = -\alpha \frac{r ^2}{2} + A,
\]

vrednost drugega integriranja pa je

\[ r u_r = - \alpha \frac{r ^4}{8} + A \frac{r ^2}{2} + B \implies \ u_r = - \alpha \frac{r ^3}{8} + A \frac{r}{2} + \cancel{\frac{B}{r}}.
\]

Konstanta \( B = 0 \), saj bi drugače rešitev divergirala v izhodišču, kar pa ne. Določiti moramo še konstanto, ki jo bomo določili preko robnega pogoja

\[ p_{rr} n_r = 0,
\]

kar pomeni, da je površina neobremenjena.

Napetostni tenzor je po definiciji

\[ p_{rr} = \frac{E}{1 + \sigma} \left[ u_{rr} + \frac{\sigma}{1 - 2 \sigma} \left( \nabla \cdot \mathbf{u} \right) \delta_{ij} \right].
\]

Deformacijski tenzor je preko dobljene rešitve in definicije

\[ u_{rr} = \frac{\partial u_{r}}{\partial r} = \frac{3 \alpha}{8} r ^2 + \frac{A}{2}.
\]

Divergenca tenzorja je prav tako po prej izpeljani rešitvi

\begin{align*}
  \nabla \cdot \mathbf{u} &= \frac{1}{r} \left( \frac{\partial (r u_{r})}{\partial r}  \right) \\
&= \frac{1}{r} \left[ - \alpha \frac{4 r ^3}{8} + A r \right] = - \alpha \frac{r ^2}{2} + A
\end{align*}

Napetostni tenzor je potem

\[p_{rr} &= \frac{E}{1 + \sigma} \left[ - \frac{3 \alpha}{8} r ^2 + \frac{A}{2} + \frac{\sigma}{1 - 2\sigma} \left( - \alpha \frac{r ^2}{2} + A \right) \right],
\]

kjer velja

\[ \left. p_{rr} \right|_{r = R} = 0.
\]

Dobimo enačbo

\begin{align*}
0 &= -\frac{3 \alpha}{8} R ^2 + \frac{A}{2} + \frac{\sigma}{1 - 2 \sigma} \left( - \alpha \frac{R ^2}{2} + A \right) \\
&= A \left[ \frac{1}{2} + \frac{\sigma}{1 - 2 \sigma} \right] - R ^2 \alpha \left[ \frac{3}{8} + \frac{\sigma}{1 - 2\sigma} \frac{1}{2} \right].
\end{align*}

Enačbo rešimo in dobimo, da je vrednost koeficienta

\[ A = \frac{3 - 2 \sigma}{4} R ^2 \alpha.
\]

Želimo si še pogledati, kaj dejansko pomeni, da je deformacija zgolj v radialni smeri. Zato bomo izračunali še

\[ p_{zz} = \frac{E}{1 + \sigma} \left[ u_{zz} + \frac{\sigma}{1 - 2\sigma} \left( \nabla \cdot \mathbf{u} \right) \right] .
\]

\( u_{zz} = 0 \), saj je \( u_z = 0 \). Preostane nam torej zgolj

\[ p_{zz} = \frac{E}{1 + \sigma} \frac{\sigma}{1 - 2\sigma} \left[ - \alpha \frac{r ^2}{2} + A \right] = \frac{E \sigma}{(1 + \sigma) (1 - 2\sigma)} \left[ - \frac{\alpha r ^2}{2} + \frac{3 - 2 \sigma}{4} R ^2 \alpha \right].
\]

\( p_{zz} \) je torej različen od nič, in če ne bi bil omejen z osnovnima ploskvama, bi se deformiral tudi v \( z \) smeri. Teoretično je naš pogoj napačen.

Na podoben način pridemo tudi do

\[ p_{\phi \phi} = \frac{E}{(1 + \sigma)} \left[ - \alpha \frac{r ^2}{8} + \frac{3 - 2 \sigma}{8} R ^2 \alpha + \frac{\sigma}{1 - 2 \sigma} \left( - \frac{\alpha r ^2}{2} + \frac{3 - 2\sigma}{4} R ^2 \alpha \right) \right].
\]
