#+title: Vaje iz Mehanike kontinuov, 11. teden v letu
#+subtitle: 2026/03/11
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Jeklena cev s plaščem
#+begin_problem
Jeklena cev s polmerom \( R_1 = 2.5 \mathrm{cm} \) je obdana s \( 5 \)-centimetrskim plaščem (\( R_2 = 7.5 \mathrm{cm} \)) izolacije iz umetne mase. Plašč želimo zasukati okrog cevi: najprej ga primemo, t.j. v radialni smeri enakomerno stisnemo s tlakom \( p_0 = 10^6 \mathrm{Pa} \), nato pa počasi zasučemo. Izračunaj, za kolikšen kot je treba zavrteti zunanji del plašča, da izolacija zdrsne okrog cevi. Vzdolž simetrijske osi ni deformacije. Youngov modul umetne mase je \( E = 10^7 \mathrm{Pa} \), Poissonovo število \( \sigma = 0.4 \), koeficient lepenja med jeklom in umetno maso pa \( k = 0.8 \). Deformacija cevi je zanemarljiva.
#+end_problem
Vir: Naloge iz elastomehanike, D. Svenšek, str. 39

Silo, ki nasprotuje vrtenju izolacijskega sloja, označimo s \( \mathbf{F}_l \). Vektor premika \( \mathbf{u} \) bo imel dve komponenti

\[ \mathbf{u}(r) =  u_r (r) \hat{e}_r + u_{\phi} (r) \hat{e}_{\phi}.
\]

Navierova enačba za dan primer je

\[ \rho \ddot{\mathbf{u}} = 0 = \frac{E}{2 (1 + \sigma)} \left( \nabla ^2 \mathbf{u} + \frac{1}{1 - 2\sigma} \nabla \nabla \cdot \mathbf{u} \right).
\]

Upoštevamo identiteto

\[ \nabla ^2 \mathbf{u} = \nabla \nabla \cdot \mathbf{u} - \nabla \times \left( \nabla \times \mathbf{u} \right).
\]

V cilindričnih koordinatah so gradient, divergenca in rotor

\begin{align*}
\nabla f &= \frac{\partial }{\partial r}  \hat{e}_r + \frac{1}{r} \frac{\partial f}{\partial \phi} \hat{e}_{\phi} + \frac{\partial f}{\partial z} \hat{e}_z \\
 \nabla \cdot \mathbf{u} &= \frac{1}{r} \left( \frac{\partial (u_{r} r)}{\partial r}  \right) + \frac{1}{r} \frac{\partial u_{\phi}}{\partial \phi}  + \frac{\partial u_{z}}{\partial z} \\
   \nabla \times \mathbf{u} &= \left( \frac{1}{r} \frac{\partial u_{r}}{\partial \phi} - \frac{\partial u_{\phi}}{\partial z}  \right) \hat{e}_r + \left( \frac{\partial u_{r}}{\partial z}  - \frac{\partial u_{z}}{\partial r}  \right) \hat{e}_{\phi} + \left( \frac{1}{r} \frac{\partial (r u_{\phi})}{\partial r} - \frac{1}{r} \frac{\partial u_{r}}{\partial \phi}  \right)\hat{e}_z
\end{align*}

Zaradi odvisnosti vektorja premika so členi, ki se ohranijo pri divergenci

\[ \nabla \cdot \mathbf{u} = \frac{1}{r} \left( \frac{\partial (r u_{r})}{\partial r}  \right).
\]

Pri gradientu divergence vektorja premika bo se ohrani samo

\begin{equation}
\label{eq:1}
 \nabla \left( \nabla \cdot \mathbf{u} \right) = \frac{\partial }{\partial r} \left( \frac{1}{r} \frac{\partial (r u_{r})}{\partial r}  \right) \hat{e}_r.
\end{equation}

Edini člen,ki bo preživel pri rotorju, pa bo

\[ \nabla \times \mathbf{u} = \frac{1}{r} \frac{\partial (r u_{r})}{\partial r} \hat{e}_z.
\]

Nadalje

\begin{equation}
\label{eq:2}
 \nabla \times \left( \nabla \times \mathbf{u} \right) = - \frac{\partial }{\partial r}  \left( \frac{1}{r} \frac{\partial \left( r u_{r}\right)}{\partial r}  \right)\hat{e}_{\phi}.
\end{equation}

V Navierovi enačbi sta člena \ref{eq:1} in \ref{eq:2} neodvisna med seboj, kar pomeni, da bo njuna vsota enaka nič, samo ko bosta oba člena posebej ničelna. Člena sta podobna po sestavi, torej bo splošen nedoločen integral

\begin{align*}
  \frac{1}{r} \frac{\partial (r u_{r})}{\partial r} &= A \\
ru _r &= \frac{A r ^2}{2} + B
\end{align*}

Posamezni komponenti sta torej

\[ u_r = \frac{A r}{2} + \frac{B}{r} \quad \text{ in } \quad u_{\phi} = \frac{C r}{2} + \frac{D}{r}.
\]

Za določitev koeficientov moramo določiti robne pogoje. Prvi robni pogoj je pri polmeru \( r = R_1 \)

\begin{equation}
\label{eq:3}
u_r (R_1) = u_{\phi} (R_1) = 0.
\end{equation}

Tlak, ki deluje na plašč ima radialno smer, torej bo normalni vektor v cilindričnih koordinatah \( \mathbf{n} = (n_r, n_{\phi}, n_z) = (1, 0, 0) \). Splošna enačba robnega pogoja je

\[ p_{ij} n_j = \tilde{F}_i.
\]

Za naš dotični primer je drugi robni pogoj

\begin{equation}
\label{eq:4}
\left. p_{rr} \right|_{r = R_2} = - p_0.
\end{equation}

Do tega smo prišli preko

\[ \begin{pmatrix}
   p_{rr} & p_{\phi r} & p_{z r} \\
   p_{r \phi} & p_{\phi \phi} & p_{\phi z} \\
   p_{z r} & p_{z \phi} & p_{zz}
   \end{pmatrix} \begin{pmatrix} 1 \\ 0 \\ 0 \end{pmatrix} = \begin{pmatrix} p_{rr} \\ p_{r\phi} \\ p_{r z} \end{pmatrix} = \begin{pmatrix} - p_{0} \\ 0 \\ 0 \end{pmatrix},
\]

kjer smo upoštevali v zadnjem enačaju, da je to ravno površinska gostota sila, ki deluje na kot posledica stiskanja.

Zadnji robni pogoj pa je, ko plašč zdrsne - to bo takrat, ko tangentni člen ne bo več ničeln pri \( r = R_1 \).

\begin{equation}
\label{eq:5}
k p_{rr} = - p_{r \phi}.
\end{equation}

Do tega pridemo preko

\[ p_{ij} n_j = \begin{pmatrix} p_{rr} \\ p_{r\phi} \\ p_{rz} \end{pmatrix} = \begin{pmatrix} - \frac{F_l}{A} \\ - k \frac{F_l}{A}  \\ 0 \end{pmatrix}.
\]

Robni pogoj \eqref{eq:3} nam da enačbo oblike

\[ \frac{A R_1}{2} + \frac{B}{R_1} = 0,
\]

iz česar dobimo vrednosti

\[ u_r: \ B = - \frac{A R_1 ^2}{2} \quad \text{ in } \quad u_{\phi}: \ D = \frac{C R_1 ^2}{2}.
\]

Za drugi robni pogoj \ref{eq:3} moramo upoštevati definicijo napetostnega tenzorja

\[ p_{ij} = \frac{E}{1 + \sigma} \left( u_{ij} + \frac{\sigma}{1 - 2 \sigma} \nabla \cdot \mathbf{u} \delta_{ij} \right).
\]

Za \( p_{rr} \) komponento potrebujemo \( u_r \), da lahko izračunamo \( u_{rr} \) in \( \nabla \cdot u = \frac{1}{r} \frac{\partial (r u_{r})}{\partial r}  \), ki sta

\[ \frac{\partial u_{r}}{\partial r} = \frac{A}{2} - \frac{B}{r ^2} \quad \text{ in } \quad \nabla \cdot \mathbf{u} = A.
\]

\begin{align*}
  p_{rr} &= \frac{E}{1 + \sigma} \left[ A \left( \frac{\sigma}{1 - 2 \sigma} + \frac{1}{2} \right) - \frac{B }{r ^2} \right] \\
&= \frac{E}{1 + \sigma} \left[ \frac{1}{2 (1 - 2 \sigma)} A - \frac{B}{r ^2} \right] \\
&= \frac{E}{1 - \sigma} A \left[ \frac{1}{2 (1 - 2 \sigma)} + \frac{1}{2} \frac{R_1 ^2}{r ^2} \right],
\end{align*}

kjer smo v zadnji vrstici upoštevali rezultat robnega pogoja \ref{eq:3}. Robni pogoj \( p_{rr} (R_2) = - p_0 \) nam poda potem vrednost konstante \( A \)

\[ A = \frac{1 + \sigma}{E} \frac{- p_0}{\frac{1}{2 (1 - 2 \sigma)}} + \frac{1}{2} \frac{R_1 ^2}{R_2 ^2} = -0.0548.
\]

Upoštevamo še robni pogoj \ref{eq:5}

\[ p_{r \phi} = \frac{E}{1 + \sigma} \left[ \frac{\partial u_{\phi}}{\partial r} - \frac{u_{\phi}}{r} \right] = - \frac{E}{(1 + \sigma)} \frac{D}{r ^2}.
\]

Vrednost robnega pogoja je \( - p_{r\phi} (R_1) = k p_{rr} (R_2) \), iz česar dobimo

\begin{align*}
\frac{E}{(1 + \sigma) R_1 ^2} &= k \frac{E}{(1 + \sigma)} A \left[ \frac{1}{2 (1 - 2 \sigma)} + \frac{1}{2} \right] \\
D &= \frac{1}{2 } k A R_1 ^2 \left[ \frac{1}{1 - 2\sigma} + 1 \right] = -8.22 \cdot 10^{-6} m ^2
\end{align*}

Preostala konstanta je

\[ C = - \frac{2 D}{R_1 ^2} = 2.63 \cdot 10^{-2}.
\]
* Elastična krogla
#+begin_problem
Iščemo frekvence radialnega lastnega nihanja elastične krogle s polmerom \( R \).
#+end_problem

Quick cheat sheet vektorskih operatorjev v sferičnih koordinatah

\begin{align*}
  \nabla f &= \frac{\partial f}{\partial r} \hat{e}_r + \frac{1}{r} \frac{\partial f}{\partial \theta}  \hat{e}_{\theta} + \frac{1}{r \sin \theta} \frac{\partial f}{\partial \phi} \hat{e}_{\phi} \\
\nabla \cdot \mathbf{u} &= \frac{1}{r ^2} \frac{\partial \left( r ^2 u_r \right)}{\partial r} + \frac{1}{r \sin \theta} \left( \frac{\partial \left( \sin \theta u_{\phi} \right) }{\partial \theta} + \frac{\partial u_{\phi}}{\partial \phi}  \right) \\
\nabla \times \mathbf{u} &= \frac{1}{r \sin \theta} \left( \frac{\partial (\sin \theta U_{r})}{\partial \theta} - \frac{\partial u_{\theta}}{\partial \phi}  \right) \hat{e}_r \\
& \quad + \frac{1}{r} \left( \frac{1}{\sin \theta} \frac{\partial u_{r}}{\partial \phi} - \frac{\partial \left( r u_{\phi}\right) }{\partial r}  \right) \hat{e}_{\theta} \\
& \qquad + \frac{1}{r} \left( \frac{\partial }{\partial r} \left( r u_{\theta} \right) - \frac{\partial u_{r}}{\partial \theta}  \right) \hat{e}_{\phi}.
\end{align*}

Funkcija bo odvisna zgolj od radialnega dela \( \mathbf{u} = u_r (r) \hat{e}_r \).

Laplaceov člen v Navierovi enačbi ponovno razpišemo na gradient divergence vektorja \( \mathbf{u} \) in rotor rotorja, ki pa bo tokrat ničeln.

Ostane nam

\[ \rho \ddot{\mathbf{u}} = \frac{E}{2 (1 + \sigma)} \nabla (\nabla \cdot \mathbf{u}) \left[ 1 + \frac{1}{1 - 2 \sigma} \right] = \frac{E (2 - 2 \sigma)}{2 (1 + \sigma) (1 - 2 \sigma)} \nabla \left( \nabla \cdot \mathbf{u} \right)
\]

Vemo, da niha, torej bo časovna odvisna vektorja \( \mathbf{u} = \mathbf{u}_0 e^{\mathrm{i} \omega t} \). Navierova enačba je tako

\[ - \rho \omega ^2 \mathbf{u}_0 = \frac{E (1 - \sigma) \nabla \left( \nabla \cdot \mathbf{u}_0 \right)}{(1 + \sigma) ( 1 - 2\sigma )}.
\]

Uvedemo konstanto

\[ k ^2 = - \frac{\rho ( 1 + \sigma ) (1 - 2 \sigma)}{E (1 - \sigma)},
\]

in imamo enačbo

\[ \nabla \left( \nabla \cdot \mathbf{u}_0 \right) + k ^2 \mathbf{u}_0 = 0.
\]

Razpišemo divergenco in gradient

\[ u_0 k ^2 \hat{e}_r + \frac{\partial }{\partial r}  \left[ \frac{1}{r ^2} \left( \frac{\partial (r ^2 u_0)}{\partial r}  \right) \right] \hat{e}_r = 0
\]

ter odvajamo

\[ k ^2 u_0 + \frac{2}{r} \frac{\partial u_{0}}{\partial r}  - \frac{2 u_0}{r ^2} + \frac{\partial ^2 u_{0}}{\partial r ^2} = 0.
\]

Enačbo delimo s \( k ^2 \) in enačba dobi obliko sferične Besslove diferencialne enačbe za spremenlijvko \( x = kr \)

\[ \frac{1}{k ^2} \frac{\partial ^2 u_{0}}{\partial r ^2}  + \frac{2}{k ^2 r} \frac{\partial u_{0}}{\partial r}  + \left( - \frac{2}{k ^2 r ^2} + 1 \right) u_0 = 0
\]

#+begin_note
  Sferična Besslova diferencialna enačba je oblike

  \[ \frac{\partial ^2 }{\partial x ^2} z_l (x) + \frac{2}{x} \frac{\partial }{\partial x} z(x) + \left( 1 - \frac{l (l + 1)}{x ^2} \right) z_l (x) = 0
  \]

  in rešita jo \( j_l (x) \) in \( n_l (x) \).
#+end_note

Z uvedbo spremenljivke \( x \) enačba postane

\[ \frac{\partial ^2 }{\partial x ^2}   + \frac{2}{x} \frac{\partial u_{0}}{\partial x} + \left( - \frac{2}{x ^2} + 1 \right) u_0 = 0,
\]

iz česar lahko določimo, da je \( l(l + 1) = 2 \) in posledično \( l = 1 \). Nastavek rešitve bo potem \( u_0 (x) = A J_0 (x) \).

Robni pogoj je, da je površina prosta

\[ \left. p_{rr} \right|_{r = R} = 0.
\]

Za napetostni tenzor

\[ p_{ij} = \frac{E}{1 + \sigma} \left( u_{ij} + \frac{\sigma}{1 - 2 \sigma} \nabla \cdot \mathbf{u} \, \delta_{ij} \right),
\]

je element \( p_{rr} \) enak

\begin{align*}
  p_{rr} &= \frac{E}{1 + \sigma} \left( u_{rr} + \frac{\sigma}{1 - 2 \sigma} \left( \nabla \cdot \mathbf{u} \right) \right) \\
&= \frac{E}{1 + \sigma} \left( \frac{\partial u_{r}}{\partial r}  + \frac{\sigma}{1 - 2\sigma} \left( \nabla \cdot \mathbf{u} \right) \right) \\
&= \frac{E}{1 + \sigma} \left( \frac{\partial u_{r}}{\partial r}  + \frac{\sigma}{1 - 2 \sigma} \frac{1}{r ^2} \frac{\partial \left( r ^2 u_r \right)}{\partial r}  \right).
\end{align*}

Upoštevajoč nastavek zapišemo

\[ p_{rr} = \frac{E A}{1 + \sigma} \left( \frac{\partial J_{1}(x)}{\partial r} + \frac{\sigma}{1 - 2 \sigma} \frac{1}{r ^2} \frac{\partial \left( r ^2 J_1 (x) \right) }{\partial r}   \right)
\]

ter spremenljivko \( x = kr  \)

\[ p_{rr} = \frac{E Ak}{1 + \sigma} \left( \frac{\partial j_1 (x)}{\partial x} + \frac{\sigma}{(1 - 2 \sigma)  x ^2} \frac{\partial \left( x ^2 J_1 (x) \right) }{\partial x} \right)
\]

#+begin_note
  Iz Kuščer-Kodreta razberemo identitete, s katerimi se sprehajamo čez Besslove funkcije

  \[ - x^{-l} z_{l + 1} = \left( x^{-l} z_l \right) ' \quad \text{ in } \quad x^{l + 1} z_{l - 1} = \left( x^{l + 1} z_l \right)',
  \]

  kjer je \( j_0 (x) = \frac{\sin x}{x} \).
#+end_note

Za \( l = 1 \) velja

\[ \frac{\partial \left( x ^2 j_1 (x) \right) }{\partial x} = x ^2 j_0 (x).
\]

Določimo lahko, da je za \( l = 0 \)

\[ - j_1 (x) = \frac{\partial j_{0}(x)}{\partial x} \implies \ j_1 = - \frac{\cos x}{x} + \frac{\sin x}{x ^2}.
\]

Odvod je torej

\[ \frac{\partial j_{1}(x)}{\partial x}  = \frac{\sin x}{x} + \frac{\cos x}{x ^2} + \frac{\cos x}{x ^2} - \frac{2 \sin x}{ x ^3}.
\]

Za robni pogoj pri \( x = k R \) torej dobimo

\[ p_{rr} = 0 = \left[ \frac{\sin (k R)}{kR} - \frac{2 \sin (kR)}{\left( k R \right) ^3} + \frac{2 \cos (k R)}{\left( kR \right) ^2} + \frac{\sigma}{1 - 2 \sigma} \frac{\sin (kR)}{kR} \right].
\]

Rešitev delimo s \( \frac{kR}{\cos (kR)} \) in izpostavimo \( \tan  \) funkcije, da dobimo transcedentno enačbo

\[ \tan (kR) = \frac{k R}{1 - \frac{1 - \sigma}{2 (1 - 2 \sigma)} \left( k R \right) ^2}
\]
