#+title: 2. vaje iz Elektromagnetnega polja
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Nadaljevanje: električno polje nabite ravne plošče z režo

#+begin_solution
Električno polje v odvisnosti od \( z \) je enako

\[ E(z) = \frac{\sigma}{\pi \epsilon_0} \left( \frac{\pi}{2} - \mathrm{arctg} \frac{a}{2z} \right)
\]

Če je \( z \gg a \), je \( \mathrm{arctg} \) blizu \( 0 \) in ga lahko zanemarimo. Električno polje tako postane ekvivalentno neskončni ravni plošči

\[ E(z) = \frac{\sigma}{2 \epsilon_0}
\]

Če je \( z \ll a \), pa uporabimo Taylorjev razvoj za \( \mathrm{arctg} x \) za \(  x \ll 1 \), ki je ekvivalenten

\[ \mathrm{arctg} x = \frac{\pi}{2} - x + \ldots
\]

Električno polje ob upoštevanju razvoja postane

\begin{align*}
  E(z) &= \frac{\sigma}{\pi \epsilon_0} \left( \frac{\pi}{2} - \frac{\pi}{2} + \frac{2z}{a} \right) \\
&= \frac{2\sigma z}{\pi \epsilon_0 a} \\
&= \frac{2\sigma}{\pi \epsilon_0 a} z
\end{align*}

Vidimo, da se električno polje povečuje skoraj linearno.
#+end_solution
* Teorija

Imamo diferencialno obliko Gaussovega zakona (na predavanjih smo ga označevali s \( \phi \)):

\begin{equation}
\label{eq:1}
 \vec{\nabla} \cdot \vec{E} \left( \vec{r} \right) = \frac{\rho \left( \vec{r} \right)}{\epsilon_0}
\end{equation}

Prav tako velja naslednja zveza med električnim poljem \( \vec{E} \) in potencialom \( U \)

\[ \vec{E} \left( \vec{r} \right) = -  \vec{\nabla} U \left( \vec{r} \right)
\]

V Gaussov zakon \ref{eq:1} vstavimo zvezo med \( \vec{E} \) in poljem \( U \), da dobimo Poissonovo enačbo

\[ \nabla ^2 U \left( \vec{r} \right) = - \frac{\rho \left( \vec{r} \right)}{\epsilon_0}
\]

#+begin_my_example
Obravnavajmo točkast električen naboj. Gostoto zapišemo kot

\[ \rho \left( \dot{r} \right) = e \delta \left( \vec{r} - 0 \right)
\]

kjer je \( \delta \) funkcija z enotami \( \frac{1}{m } \). Vstavimo gostoto v Poissonovo enačbo

\[ \nabla ^2 U \left( \vec{r} \right) = - \frac{e}{\epsilon_0} \delta \left( \vec{r} \right)
\]

Poissonovo enačbo bomo rešili preko Fourierove transformacije.
#+end_my_example

Potencial \( U \left( \vec{r} \right)  \) zapišemo s Fourierovo transformacijo kot

\[ U \left( \vec{r} \right) = \iiint\limits_{}^{} U \left( \vec{k} \right) e^{\mathrm{i} \vec{k} \vec{r}} \,\mathrm{d} ^3 \vec{k}
\]

\( U \left( \vec{k} \right) \) je amplituda (uteži) ravnih valov z valovnim vektorjem \( \vec{k} \). Na Fourierovo transformacijo lahko fizikalno gledamo kakor razvoj po bazi ravnih valov in nato iskanje amplitud.

Za izračun \( U \left( \vec{k} \right) \) skalarno množimo z drugo bazno funkcijo \( e^{- \mathrm{i} \vec{k} \, ' \vec{r}} \)

\[ \iiint\limits_{}^{} U \left( \vec{r} \right) e^{- \mathrm{i} \vec{k} \vec{r}} \,\mathrm{d} ^3 \vec{k} \, ' = \iiint\limits_{}^{} \iiint\limits_{}^{} U \left( \vec{k} \right) e^{\mathrm{i} \left( \vec{k} - \vec{k} \, ' \right) \cdot \vec{r}} \,\mathrm{d} ^3 \vec{k} \,\mathrm{d } ^3 \vec{r}
\]

Desni integral po \( \vec{r} \) je \( \delta \) funkcija, saj se ortogonalno ravni valovi izničijo povsod razen v točki izvora, kjer konstruktivno interferirajo. Enačba se tako poenostavi v

\[ \iiint\limits_{}^{} U \left( \vec{r} \right) e^{- \mathrm{i}\vec{k} \vec{r}} \,\mathrm{d } ^3 \vec{r} = \left( 2 \pi \right) ^3 \iiint\limits_{}^{} U \left( \vec{k} \right) \delta \left( \vec{k} - \vec{k} \, ' \right) \,\mathrm{d } ^3 \vec{k} = \left( 2\pi \right) ^3 U \left( \vec{k} \, ' \right)
\]

Na tak način lahko zapišemo izraz za amplitude \( U \left( \vec{k} \right) \) kot

\[ U \left( \vec{k} \right) = \frac{1}{\left( 2 \pi \right) ^3} \iiint\limits_{}^{} U \left( \vec{r}\right)  e^{- \mathrm{i} \vec{k} \vec{r}} \,\mathrm{d} ^3 \vec{r}
\]

Gradient ima na Fourierovo transformacijo

\[ \vec{\nabla} U \left( \vec{r} \right) = \iiint\limits_{}^{} U \left( \vec{k} \right) \mathrm{i} \vec{k} e^{\mathrm{i} \vec{k} \vec{r}} \,\mathrm{d} ^3 \vec{k}
\]

saj vpliva samo na \( \vec{r} \). Na analogen način dobimo, da se Laplacian \( \nabla ^2  \) v Fourierovem prostoru poenostavi \( - k ^2 \).


* Poissonova enačba za točkasti naboj

#+begin_problem
Reši Poissonovo enačbo za potencial električnega polja točkastega naboja \( e \),

\[ \nabla ^2 U \left( \vec{r} \right) = - \frac{e}{\epsilon_0} \delta \left( \vec{r} \right)
\]

s pomočjo Fourierove transformacije.
#+end_problem

#+begin_solution
Kakor smo izpeljali v teoriji, postopamo naprej z

\[ \nabla ^2 U \left( \vec{r} \right) = - \frac{e}{\epsilon_0} \delta ^3 \left( \vec{r} \right)
\]

Preidemo v Fourierov prostor in naša enačba se poenostavi v

\[ k ^2 U \left( \vec{k} \right) = + \frac{e}{\epsilon_0} \frac{1}{\left( 2 \pi \right) ^3}
\]

Upoštevali smo, da se \( \delta \) pretvori v \( \left( 2 \pi \right) \). Sedaj lahko izrazimo

\begin{equation}
\label{eq:2}
U \left( \vec{k} \right) = \frac{e}{\left( 2\pi \right) ^3} \frac{1}{k ^2}
\end{equation}

Z drugo Fourierovo transformacijo enačbe \ref{eq:2} bomo dobili rešitev za \( U \left( \vec{r} \right) \).

\[ U \left( \vec{r} \right) = \int\limits_{}^{} U \left( \vec{k} \right) e^{\mathrm{i} \vec{k} \vec{r}} \, \mathrm{d} ^3 k = \frac{e}{\left( 2 \pi \right) ^3 \epsilon_0} \int\limits_{}^{} \frac{e^{\mathrm{i} \vec{k} \vec{r}}}{k ^2} \, \mathrm{d} ^3 k
\]

Za reševanje integrala, definiramo kot \( \theta \) med \( \vec{r} \) in \( \vec{k} \) in preidemo v sferične koordinate.

\[ U \left( \vec{r} \right) = \frac{e}{\left( 2 \pi \right) ^3} \int\limits_0^{2\pi} \, \mathrm{d} \phi \int\limits_{-1}^1 \, \mathrm{d} \left( \cos \theta \right) \int\limits_0^{\infty} k ^2 \frac{e^{\mathrm{i} k r \cos \theta }}{k ^2} \, \mathrm{d} k
\]

Integral po \( \phi \) je enostavna, medtem ko integral po \( \cos \theta \) poda razliko eksponentov, ki je enaka \( 2 \mathrm{i} \). Ostane nam

\[ U \left( \vec{r} \right) = \frac{2 e}{\left( 2\pi \right) ^2 \epsilon_0 r} \int\limits_0^{\infty} \frac{1}{k \mathbf{r}} \sin \left( kr \right) \, \mathrm{d} k \mathbf{r}
\]

Razširili smo z odebeljenima \( \vec{r} \), uvedemo novo spremenljivko \( u = kr \) in rešitev tega integrala je tako enaka

\[ U \left( \vec{r} \right) = \frac{2 e}{\left( 2 \pi \right) ^2 \epsilon_0 r} \int\limits_0^{\infty} \frac{\sin u}{u} \, \mathrm{d} u = \frac{e}{4 \pi \epsilon_0 r}
\]

kjer je integral enak \( \frac{\pi}{2} \).

Na koncu vstavimo rezultat še v Poissonovo enačbo in rezultat je

\[ \nabla ^2 \frac{e}{4 \pi \epsilon_0 r} = - \frac{e}{\epsilon_0} \delta \left( \vec{r} \right)
\]

kar nam na koncu poda

\[ \nabla ^2 \frac{1}{r} = - 4 \pi \delta \left( \vec{r} \right)
\]
#+end_solution

Za točkasti naboj z gostoto \( \rho \left( \vec{r} \right) = e \delta \left( \vec{r} - 0 \right) \) lahko preko Poissonove enačbe izpeljemo potencial, ki je enak

\[ U \left( \vec{r} \right) = \frac{e}{4 \pi \epsilon_0 \left| \vec{r} - 0 \right|}
\]
* Teorija: električno polje poljubne porazdelitve naboja

Poljubno porazdelitev sestavimo iz točkasih nabojev z razširitvijo po bazi \( \delta \) funkcije

\[ \rho \left( \vec{r}  \right)= \int\limits_{}^{} \rho \left( \vec{r}\, ' \right) \delta \left( \vec{r} - \vec{r} \, ' \right) \, \mathrm{d} ^3 \vec{r} \,'
\]

Rešitev za potencial \( U \left( \vec{r} \right) \) Poissonove enačbe je

\[ U \left( \vec{r} \right) = \int\limits_{}^{} \frac{ \rho \left( \vec{r} \, ' \right) \, \mathrm{d} ^3 \vec{r} \, '}{ 4 \pi \epsilon_0 \left| \vec{r} - \vec{r}\, ' \right|}
\]

Pripadajoče električno polje \( \vec{E} \left( \vec{r} \right) \) je

\[ \vec{E} \left( \vec{r} \right) =- \vec{\nabla} U \left( \vec{r} \right) = \frac{1}{4 \pi \epsilon_0} \int\limits_{}^{} \frac{\rho \left( \vec{r} \, ' \right)}{\left| \vec{r} - \vec{r} \, ' \right|} \frac{\vec{r} - \vec{r} \, '}{\left| \vec{r} - \vec{r} \, ' \right|}
\]
* Električno polje vodikovega atoma

#+begin_problem
Potencial električnega polja vodikovega atoma v osnovnem stanju ima obliko

\[ U \left( r \right) = \frac{e}{4 \pi \epsilon_0} \frac{e^{- \alpha r}}{r} \left( 1 + \frac{\alpha r}{2} \right)
\]

kjer je \( r \) oddaljenost od jedra atoma z nabojem \( e \) in \( \alpha^{-1} = \frac{a_B}{2} \), pri čemer je \( a_B \) Bohrov radij. Določi prostorsko gostoto naboja, ki vodi do takšnega potenciala. Kvalitativno interpretiraj dobljeni rezultat.
#+end_problem

Za sferno simetrijo velja naslednja zveza:

\[ \nabla ^2 = \frac{1}{r ^2} \frac{\partial }{\partial r}  \left( r ^2 \frac{\partial }{\partial r}  \right)
\]

ko je primer sferno simetričen.

#+begin_solution
Uporabimo Poissonovo enačbo, ki povezuje potencial \( U \) z gostoto naboja \( \rho \left( \dot{r} \right) \) preko enačbe

\[ \nabla ^2 U = - \frac{\rho \left( \vec{r} \right)}{\epsilon_0}
\]

Izračunamo Laplace potenciala upoštevajoč zgornjo zvezo in dobimo

\begin{align*}
  \nabla ^2 U &= \nabla ^2 \left( \frac{e}{4 \pi \epsilon_0} \frac{e^{- \alpha r}}{r} \left( 1 + \frac{\alpha r}{2} \right) \right) \\
&= \frac{e}{4 \pi \epsilon_0} \frac{1}{r ^2} \frac{\partial }{\partial r}  \left( r ^2 \left( \frac{- \alpha e^{- \alpha r} r - e^{- \alpha r}}{r ^2} \right) - \frac{\alpha ^2}{2} e^{-\alpha r} \right) \\
&= \frac{e}{4 \pi \epsilon_0} \frac{1}{r ^2} \frac{\partial }{\partial r}  \left( - \alpha e^{- \alpha r}r - e^{- \alpha r} - \frac{\alpha ^2}{2} r ^2 e^{- \alpha r} \right) \\
&= - \frac{e}{4 \pi \epsilon_0 r ^2} \frac{\partial }{\partial r}  \left( e^{- \alpha r} \left[ 1 + \alpha r + \frac{\alpha ^2 r ^2}{2} \right] \right) \\
&= - \frac{e}{4 \pi \epsilon_0 r ^2} \left[ - \alpha e^{- \alpha r} \left( 1 + \alpha r + \frac{\alpha ^2 r ^2}{2} \right) + e ^{- \alpha r} \left( \alpha + \alpha ^2 r \right) \right] \\
&= \frac{e}{4 \pi \epsilon_0 r ^2} \left( e^{- \alpha r} \cdot \frac{\alpha ^3 r ^2}{2} \right) \\
&= \frac{e e^{- \alpha r} \alpha ^3}{8 \pi \epsilon_0}
\end{align*}

Gostota naboja je upoštevajoč zgornji rezultat enaka

\[ \rho \left( \vec{r} \right) = - \frac{e \alpha ^3}{8 \pi} e^{- \alpha r}
\]

Gostota naboja je negativna, saj smo upoštevali samo elektrone. V nasěm primeru smo zanemarili naboj protona v gostoti, saj se nahaja v izhodišču našega koordinatnega sistema in predstavlja singularnost gostote električnega naboja

\[ \rho_+ \left( \vec{r} \right) = e \delta \left( \vec{r} \right)
\]

Pri računanju Laplace smo ignorirali singularnost.

Celotna gostota je vsota elektrona in protona

\[ \rho \left( \vec{r} \right) = e \delta \left( \vec{r} \right) - \frac{e \alpha ^3}{8 \pi} e^{- \alpha r}
\]
#+end_solution
* Ploščni kondenzator s prečnim trakom
#+begin_problem
Med dve veliki ravni prevodni plošči, ki se nahajata v medsebojni razdalji \( a \), vstavimo dolg raven prevodni trak širine \( a \), tako da je pravokoten na plošči in se plošč ravno še ne dotika. Plošči ozemljimo, na trak pa priključimo napetost \( U_0 \).

a) Izračunaj potencial električnega polja povsod znotraj takšnega kondenzatorja. Lahko se osredotočiš na desno polovico kondenzatorja in rešitev za levo polovico dobiš s pomočjo simetrije.
b) Poenostavi dobljeni izraz za velik oddaljenosti od traku.
c) Izračunaj jakost električnega polja v simetrijski ravnini kondenzatorja, vzporedni z njegvima ploščama. Dobljeno vrsto seštej.

[glej sliko v navodilih]
#+end_problem

#+begin_solution
Reševali bomo problem v kartizičnih koordinatah. Os \( x \) bo vzporedna s stranicama kondenzatorja. Os \( y \) je vzporedno s prevodnim trakom in os \( z \) gre v globino.

Znotraj kondenzatorja je potencial neodvisen od \( z \), saj je v tej smeri translacijsko invarianten.

Prostor med ploščama je prazen, in Laplaceova enačba nam poda

\[ \nabla ^2 U (x, y) = 0
\]

kjer je Laplace v kartezičnih koordinatah enak

\[ \nabla ^2 = \frac{\partial ^2 }{\partial x ^2} + \frac{\partial ^2 }{\partial y ^2}
\]

Imamo še robne pogoje:

\begin{align}
  u (x, 0) &= 0 && \text{spodaj} \\
u(x, a) &= 0 && \text{zgoraj} \\
u(0, y) &= U_0 && \text{trak} \\
U(\infty, y) &\ne \infty \text{desno}
\end{align}
#+end_solution
