#+title: 12. vaje iz Elektromagnetnega polja
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Točkast dipol v krogelni lupini dielektrika

#+begin_problem
V razsežni homogeni snovi z dielektrično konstanto \( \epsilon \) je krogelna votlina polmera \( a \). V njeno središče postavimo točkast električni dipol z električnim dipolnim momentom \( p_e \).

a) Izračunaj potencial električnega polja povsod po prostoru kot funkcijo krogelnih koordinat \( r \) in \( \theta \). Na podlagi dobljenega izraz pokaži, da ima električno polje zunaj krogelne votline obliko polja električnega dipola z električnim dipolnim momentom

   \[ p_e ' = \frac{3 p_e}{(2 \epsilon + 1)}.
   \]

   Polarni kot \( \theta \) je merjen od smeri dipola.

b) Izračunaj površinsko gostoto vezanega naboja na površini krogelne votline kot funkcijo polarnega kota \( \theta \). Izhajaš lahko iz pod a) podanega izraza za \( p_e' \).

c) Preveri, da je prostorninska gostota vezanega naboja povsod v snovi enaka nič.
#+end_problem

Zadnjič smo rešili Poissonovo enačbo v sferični koordinatah in dobili, da je potencial električnega dipola

\[ U (r, \theta) = \begin{cases}
                   \frac{p_e}{4 \pi \epsilon_0} \frac{\cos \theta}{r ^2} + A_1 r \cos \theta &; r < a \\
                   B_1 \frac{1}{r ^2} \cos \theta &; r > a
                   \end{cases}
\]

Zahtevamo zveznost za \( U \), saj brez nje imamo na določenih točkah neskončno električno polje.

\begin{equation}
\label{eq:1}
U_{not} (a, \theta) = U_{zun} (a, \theta).
\end{equation}

Drugi robni pogoj dobimo iz rotorja električnega polja \( \nabla \times \vec{E} = 0 \). Po ploskovnem integralu preseka lahko preko Stokesovega izreka pretvorimo na integral po zaključeni zanki.

\begin{align*}
  \nabla \times \vec{E} &= 0 && \left/ \int\limits_{}^{} \mathrm{d} \vec{S} \right. \\
\oint\limits_{}^{} \vec{E} \cdot \mathrm{d} \vec{l} &= 0.
\end{align*}

Iz tega sledi \( E_{zun}^{\parallel} = E_{not}^{\parallel} \). Do enakega rezultata smo prišli pri prejšnji nalog. Zaradi definicij potenciala in cikličnih odvodov funkcij, dobimo pogoj

\[ \frac{\partial U_{zun}}{\partial \theta}  = \frac{\partial U_{not}}{\partial \theta},
\]

kar pa je ekvivalentno pogoju zveznosti..

Lahko pa uporabimo pogoj

\[ \nabla \cdot \vec{D} = 0,
\]

ki velja povsod razen v središču. Po integraciji, ki je ekvivalentna b) delu dobimo

\[ D_{zun}^{\perp} - D_{not}^{\perp} = 0 \implies \epsilon E_{zun}^{\perp } = E_{not} ^{\perp },
\]

Z električnim potencialom zapišemo pogoj kot
\begin{equation}
\label{eq:2}
\left. \epsilon \left( - \frac{\partial U_{zun}}{\partial r}   \right)\right|_a = - \left. \frac{\partial U}{\partial r} \right|_a
\end{equation}

kar pa je sedaj naš delujoč drugi pogoj.

Iz robnega pogoja \ref{eq:1} dobimo enakost

\begin{equation}
\label{eq:3}
 \frac{p_e}{4 \pi \epsilon_0} = B_1 - A_1 a ^3.
\end{equation}

Iz robnega pogoja \ref{eq:2} pa dobimo

\begin{align*}
  \epsilon \left( + 2 B_1 \frac{\cos \theta}{a ^3} \right) &= \frac{p_e}{4 \pi \epsilon_0} \frac{2 \cos \theta}{a ^3} - A_1 \cos \theta \\
2 \epsilon B_1 &= \frac{p_e}{4 \pi \epsilon_0} \cdot 2 - A_1 a ^3
\end{align*}

Upoštevamo \ref{eq:3}, katerega izraz nadomestimo v zgornji enačbi, da dobimo enakost

\[ 2 \epsilon B_1 = \frac{p_e}{2 \pi \epsilon_0 } + \frac{p_e}{4 \pi \epsilon_0} - B_1,
\]

in izrazimo koeficient

\[ B = \frac{3 p_e}{4 \pi \epsilon_0} \frac{1}{2 \epsilon + 1} .
\]

Drugi koeficient je

\[ A = - \frac{p_e}{4 \pi \epsilon_0 a ^3} \frac{2 (\epsilon - 1)}{2 \epsilon + 1} .
\]

Električni potencial dipola je tako

\[ U (r, \theta) = \begin{cases}
                   \frac{p_e}{4 \pi \epsilon_0} \frac{\cos \theta}{r ^2} - \frac{p_e}{4 \pi \epsilon_0 a ^2} \frac{2 (\epsilon - 1)}{2 \epsilon  + 1} r \cos \theta &; r < a \\
                   \frac{3p_e}{4 \pi \epsilon_0} \frac{1}{2 \epsilon + 1} \frac{\cos \theta}{r ^2} &; r > a
                   \end{cases}
\]

Preverimo, če je rezultat validen. Ob predpostavki, da je \( \epsilon = 1 \), bi morali dobiti potencial električnega dipola.

Popravek znotraj sfere za \( \epsilon = 1 \) je

\[ U_2 =\left. - \frac{p_e}{4 \pi \epsilon_0 a ^2} \frac{2 (\epsilon - 1)}{2 \epsilon  + 1} r \cos \theta \right|_{\epsilon = 1} = 0.
\]

Zunaj sfere pa je

\[  \frac{3p_e}{4 \pi \epsilon_0} \frac{1}{2 \epsilon + 1} \frac{\cos \theta}{r ^2} = \frac{p_e}{4 \pi \epsilon_0} \frac{\cos \theta}{r ^2}.
\]

Oba rezultata za \( \epsilon = 1 \) se ujemata z dipolom.

\( U_2 \) je homogeno polje, ki izvira iz vezanih nabojev na površini.

Če definiramo \( p_e' = \frac{3 p_e}{2\epsilon + 1} \), potem ima polje zunaj krogle točno dipolno obliko.
** Točka b)

Postopamo preko divergence polja, saj velja

\[ \nabla \cdot \vec{E} = \rho_v,
\]

kjer so \( \rho_v \) vezani naboji. Po volumnskem integralu kvadra, ki tesno objema rob sfere, dobimo enakost

\[ E_{zun}^{\perp } - E_{not}^{\perp } = \frac{\sigma_v}{\epsilon_0}
\]

Drugače povedano, velja

\[ \sigma_v = \epsilon_0 \left( E_{zun}^{\perp } - E_{not}^{\perp } \right) = \left( -\left. \frac{\partial U_{zun}}{\partial r} \right|_{r = a} + \left. \frac{\partial U_{r}}{\partial r} \right|_{ r = a}  \right) .
\]

Upoštevamo potencial izpeljan v prejšnji podnalogi

\begin{align*}
  \sigma_v &= \epsilon_0 \left( - \frac{p_e}{4 \pi \epsilon_0} \frac{2 \cos \theta}{a ^3} - \frac{p_e}{4 \pi \epsilon_0 a ^3} \frac{2 (\epsilon - 1)}{2 \epsilon + 1} \cos \theta + \frac{3}{2} \frac{6p_e}{4 \pi \epsilon_0} \frac{1}{2\epsilon + 1} \frac{\cos \theta}{a ^3} \right) \\
&= \frac{p_e}{4 \pi} \frac{\cos \theta}{a ^3} \left( -2 - \frac{2(\epsilon - 1)}{2 \epsilon + 1} + \frac{6}{(2 \epsilon+ 1)} \right) \\
&= \frac{p_e}{4 \pi} \frac{\cos \theta}{a ^3} \left( \frac{-2(2 \epsilon + 1) - 2(\epsilon - 1) + 6}{(2 \epsilon + 1)} \right) \\
&= \frac{p_e}{4 \pi} \frac{\cos \theta}{a ^3}\left( \frac{-6 \epsilon + 6}{(2\epsilon + 1)} \right) \\
&= \frac{-3 p_e}{2 \pi} \frac{\cos \theta}{a ^3} \left( \frac{\epsilon - 1}{2 \epsilon + 1} \right)
\end{align*}

Če je \( \epsilon = 1 \), ni dielektrika in vezanih nabojev.

Preko gostote električnega naboja \( \vec{D} = \epsilon_0 \vec{E}+ \vec{P} = \epsilon \epsilon_0 \vec{E} \) dobimo polarizacijo

\[ \vec{P} = \epsilon_0 (\epsilon - 1) \vec{E}.
\]

Gostoto vezanih nabojev dobimo preko

\[ \rho_v = - \nabla \cdot \vec{P} = - \epsilon_0 (\epsilon - 1) \nabla \cdot \vec{E} = 0
\]
* Elektromagnetno valovanje v hladni plazmi

#+begin_problem
Pri obravnavi potovanja elektromagnetnih valov po hladni plazmi lahko predpostavimo, da sestavni ioni zaradi velike mase skoraj mirujejo, sestavni elektroni pa so skoraj povsem prosti, tako da se hitro odzivajo na zunanja polja. Ker je plazma hladna, lahko termično gibanje elektronov zanemarimo.

a) S pomočjo enačbe gibanja za proste elektrone mase \( m \) in naboja \( -e \) pokaži, da frekvenčno odvisnost dielektričnosti plazme zapišemo kot

   \[ \epsilon (\omega) = 1 - \frac{\omega_p ^2}{\omega ^2} ,
   \]

   kjer je \( \omega_p = \sqrt{\frac{ne ^2}{m\epsilon_0}} \) plazemska frekvenca in \( n \) številksa gostota elektronov v plazmi.

b) S pomočjo rezultata pod a) pokaži, da je disperzijska relacija elektromagnetnih valov, ki se lahko širijo po plazmi

   \[ \omega (k) = \sqrt{\omega_p ^2 + c_0 ^2 k ^2},
   \]

   kjer je \( c_0 \) hitrost elektromagnetnega valovanja v vakuumu. Kako se rezultat poenostavi v limitnih primerih velikih in majhnih frekvenc?

c) Izračunaj krajevno odvisnost jakosti električnega polja ravnega elektromagnetnega vala s frekvenco znotraj frekvenčne reže, se pravi pri \( \omega < \omega_p \).

d) S pomočjo rezultata pod b) izračunaj in skiciraj frekvenčno odvisnost fazne in grupne hitrosti elektromagnetnih valov v plazmi. Primerjaj obe hitrosti s hitrostjo svetlobe v vakuumu.
#+end_problem

Plazma je plin nabitih delcev. S pridevnikom hladno želimo povzročiti, da ni termičnega gibanja. Imamo velika pozitivna nabita jedra, ki v Bohrnovi aproksimaciji mirujejo, medtem ko manjši elektroni se gibljejo. Elektromagnetno polje bomo predstavili z ravnim valom

\[ \vec{E} = \vec{E}_0 e^{\mathrm{i} (k  z - \omega t)}
\]

Po novih smernicah (?) se ne reče več dielektrična kostantna \( \epsilon \), ampak relativna dielektričnost.

Gibalna enačba elektrona z maso \( m \) in nabojem \( -e \) jedra

\[  m \ddot{r} = - e \vec{E} \implies \ddot{r} = - \frac{e}{m} \vec{E}_0 e^{\mathrm{i} (kz - \omega t)}.
\]

kjer \( \vec{r} \) odmik od mirovne lege. Za rešitev enačbe uporabimo nastavek \( \vec{r} = \vec{r}_0 e^{\mathrm{i} (kz - \omega t)} \). Nastavek vstavimo v gibalno enačbo

\[ - \vec{r} _0 \omega ^2 e^{\mathrm{i} (kz -- \omega t)} = - \frac{e}{m} \vec{E}_0 e^{\mathrm{i} (kz - \omega t)},
\]

iz česar dobimo amplitudo nihanja okrog mirovne lege

\[ \vec{r}_0 = \frac{e}{m \omega ^2} \vec{E}_0.
\]

Oscilacije mimo mirovne lege ustvari polarizacijo z amplitudo \( \vec{p}_e = - \vec{r} e  \). Nadomestimo amplitudo nihanja s prej izračunanim

\[ \vec{p}_e = - \frac{e ^2}{m \omega ^2} \vec{E}_0 e^{\mathrm{i} (kz - \omega t)}
\]

Časovno neodvisna amplituda je

\[ \vec{p}_{e0} = - \frac{e ^2}{m \omega ^2} \vec{E}_0 .
\]

Izračunamo še polarizacijo \( \vec{P} \), ki jo povezuje gostota elektronov \( n \) in dipolni moment

\[ \vec{P} = n \vec{p}_e
\]

Enačimo

\[ \vec{P}_0 = - \frac{n e ^2}{m \omega ^2} \vec{E}_0 = \epsilon_0 (\epsilon - 1) \vec{E}_0 \implies \ \epsilon  = -\frac{n e ^2}{m \omega ^2 \epsilon_0} + 1.
\]

Definiramo plazemsko frekvenco \( \omega_p \) kot

\[ \omega_p = \sqrt{\frac{n e ^2}{m \epsilon_0}},
\]

in res smo prišli do relativne dielektričnosti v odvisnosti od frekvence valovanja

\begin{equation}
\label{eq:5}
 \epsilon \left( \omega \right) = 1 - \left( \frac{\omega_p}{\omega} \right) ^2
\end{equation}
** Izpeljava valovne enačbe

Izhajamo iz Maxwellovih zakonov

\begin{align*}
  \nabla \cdot \vec{E} = 0 & \quad \nabla \times \vec{E} = - \mu_0 \frac{\partial \vec{H}}{\partial t}  \\
\nabla \cdot \vec{H} = 0 & \quad \nabla \times \vec{H} = \epsilon_0 \epsilon \frac{\partial \vec{E}}{\partial t}
\end{align*}

Z rotorjem vplivamo na drugo enačbo \( \nabla \times \vec{E} \)

\begin{align*}
  \nabla \times \left( \nabla \times \vec{E} \right) &= - \mu_0 \frac{\partial }{\partial t} \nabla \times \vec{H} \\
\nabla \left( \nabla \cdot \vec{E} \right) - \nabla ^2 \vec{E} &= - \mu_0 \epsilon_0 \epsilon \frac{\partial }{\partial t}  \frac{\partial \vec{E}}{\partial t}
\end{align*}

Iz prve Maxwellove enačbe se nam enačba poenostavi v

\begin{equation}
\label{eq:4}
 \nabla ^2 \vec{E} - \mu_0 \epsilon_0 \epsilon \frac{\partial ^2 \vec{E}}{\partial t ^2} = 0,
\end{equation}

kar pa je valovna enačba, kjer velja \( \frac{1}{c ^2} = \mu_0 \epsilon_0 \epsilon \).
** Naloga

V valovno enačbo \ref{eq:4} vstavimo naše časovno odvisno polje \( \vec{E} = \vec{E}_0 e^{\mathrm{i} \omega t} \).

Dobimo

\[ - k ^2 \vec{E} - \frac{1}{c ^2}\left( - \omega ^2 \right) \vec{E} = 0 \implies \ \vec{E} \left( - k ^2 + \frac{\omega ^2}{c ^2} \right) = 0
\]

Zgornja enakost velja samo, če \( \omega = ck \).

Za prazen prostor je \( c = c_0 \), kar pomeni, da imamo linearno zvezo \( \omega = c_0 k \).

V nepraznem prostoru pa ponovno izhajamo iz zgornje zveze

\[ \mu_0 \epsilon_0 \epsilon  \omega ^2 - k ^2  = 0  \implies \ \omega ^2 = k ^2 \frac{c_0 ^2}{\epsilon}.
\]

Izraz za relativno dielektričnost \ref{eq:5} vstavimo v zgornjo enačbo

\[ \omega ^2 \left( 1 - \frac{\omega_p ^2}{\omega ^2} \right) = k ^2 c_0 ^2
\]

Nazadnje lahko izrazimo frekvenco v odvisnosti od valovnega vektorja in pridobili smo disperzijsko relacijo

\[ \omega (k) = \sqrt{k ^2 c_0 ^2 + \omega_p ^2}
\]

Poglejmo si še limitne primer. Za velike \( k \) velja \( kc_0 \gg \omega_p \) velja \( \omega = kc_0 \).

Za majhne \( k \) razvijemo

\begin{align*}
  \omega (k) &= \omega_p \sqrt{1 + \left( \frac{c_0}{\omega_p} k \right) ^2} \\
&= \omega_p \left( 1 + \frac{1}{2} \left( \frac{c_0}{\omega_p}k  \right)^2 \right) \\
&= \omega_p + \frac{1}{2} \frac{c_0 ^2}{\omega_p} k ^2.
\end{align*}
** Točka d)

Fazna hitrost je definirana kot \( v_F = \frac{\omega}{k} \), medtem ko grupna hitrosti, ki lahko nosi informacije pa je \( v_g = \frac{\partial \omega}{\partial k}  \).

Za zgornje izračunane rezultate je fazna hitrost

\[ v_F = \sqrt{c_{0} ^2 - \left( \frac{\omega_p}{k} \right) ^2}.
\]

Slednji rezultat je sicer večji od \( c_0 \), vendar ker z njo ne moremo prenašati informacije, vse štima - whatever that means.

Grupna hitrost je odvod

\[ v_G = \frac{c_0}{\sqrt{1 + \left( \frac{\omega_p}{c_0 k} \right) ^2}}.
\]

Produkt hitrosti je

\[ v_F \cdot v_G = c_0 ^2
\]
