#+title: 13. vaje iz Elektromagnetnega polja
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Valovni vodnik iz dveh vzporednih plošč
#+begin_problem
Veliki vzporedni prevodni plošči v medsebojni razdalji \( a \) uporabimo kot valovni vodnik.

a) Če smer širjenja valovanja označimo z \( z \), pokaži, da lahko komponente \( E_x, E_y, H_x \) in \( H_y \) jakosti električnega in magnetnega polja vse izrazimo s komponentama \( E_z \) in \( H_z \). Za popolno poznavanje elektromagnetnega polja v valovnem vodniku torej zadostuje poiskati krajevni odvisnosti vzdolžnih komponent \( E_z \) in \( H_z \). To velja tudi v splošnem za valovni vodnik s poljubnim presekom.

b) Izračunaj krajevno odvisnost vzdolžne komponente \( E_z \) za transverzalni magnetni (TM) način valovanja, pri katerem je \( H_z = 0 \), in krajevno odvisnost vzdolžne komponente \( H_z \) za transverzalni električni (TE) način valovanja, pri katerem je \( E_z = 0 \). Za oba primera izračunaj tudi disperzijsko relacijo valovanja.

c) Pokaži, da ima v TM načinu impedanca valovnega vodnika, ki jo definiramo kot

   \[ Z = \frac{E_{\perp }}{H_{\parallel}},
   \]

   (kjer je \( E_{\perp } \) komponenta električnega polja pravokotna na plošči, \( H_{\parallel} \) pa komponenta magnetnega polja vzporedna s ploščama), frekvenčno odvisnost

   \[ Z = Z_0  \sqrt{1 - \frac{\omega_0 ^2}{\omega ^2}},
   \]

   kjer je \( Z_0  = \sqrt{\frac{\mu_0}{\epsilon_0}} \) upor vakuuma in \( \omega_0 \) najnižja možna frekvenca valovnja v uporabljenem valovnem načinu. Pokaži, da ima v TE načinu impedavnca valovnega vodnika, ki jo podobno definiramo kot

   \[ Z = \frac{E_{\parallel}}{H_{\perp }},
   \]

   frekvenčno odvisnost

   \[ Z = \frac{Z_0}{\sqrt{1 - \frac{\omega_0 ^2}{\omega ^2}}} .
   \]

d) Pokaži, da je v TM načinu razmerje amplitud prečne in vzdolžne komponente jakosti električnega polja enako \( \frac{k}{\kappa} \), kjer je \( k \) valovni vektor valovanja in \( \kappa \) valovni vektor, ki opisuje prečno krajevno odvisnost polj. Ta rezultat nam omogoča preprosto predstavo širjenja valovanja vzdolž plošč: valovanje izgleda kot periodično odbijanje valovnih front med obema ploščama.

e) Nadgradnja opisanega valovnega vodnika je valovni vodnik s pravokotnim presekom s stranicama \( a \) in \( b \). Izračunaj krajevni odvisnosti komponent \( E_z \) za TM način valovanja in \( H_z \) za TE način valovanj ter disperzijsko relacijo valovanja v obeh primerih.
#+end_problem

V valovnem vodniku je širjenje ravnega elektromagnetnega vala v določeni smeri, ki jo določimo s prevodnimi mejami. Vodniki so prazni, včasih pa so lahko napolnjeni z dielektrikom.

V primeru praznega vodnika se Mawxwellove enačbe glasijo

\begin{align}
  \nabla \cdot \vec{E} &= 0 \label{eq:max1} \\
\nabla \times \vec{E} &= - \mu_0 \frac{\partial \vec{H}}{\partial t} \label{eq:max2}\\
\nabla \cdot \vec{H} &= 0 \label{eq:max3} \\
\nabla \times \vec{H} &= \epsilon_0 \frac{\partial \vec{E}}{\partial t} \label{eq:max4}
\end{align}

Z rotarizacijo enačbe \ref{eq:max1} dobimo valovni enačbi za električni tok in jakost magnetnega polja

\begin{align*}
  \nabla ^2 \vec{E} - \frac{1}{c_0 ^2} \frac{\partial ^2 \vec{E}}{\partial t ^2} &= 0 \\
\nabla ^2 \vec{H} - \frac{1}{c_0 ^2} \frac{\partial ^2 \vec{H}}{\partial t ^2} &= 0
\end{align*}

V ravnem vodniku je smer širjenja v eni smer (v našem primeru v smeri \( z \)). Gostota naboja \( \vec{\rho} \) je pravokotna na smer širjenja neodvisno od koordinatnega sistem (kartezični, cilindrični).

Ravni val v smeri \( z \) zapišemo z

\[ \vec{E} \left( \vec{r}, t \right) = \vec{E} \left( \vec{\rho} \right) \exp \left\{ \mathrm{i} (kx - \omega t) \right\}.
\]

Laplaceov operator v cilindričnih koordinatah je

\[ \nabla ^2 = \frac{\partial ^2 }{\partial z ^2} + \nabla_{\phi} ^2 = - k ^2 + \nabla_{\phi} ^2,
\]

kjer smo upoštevali drugi odvod po \( z \) ravnega vala. Vrednost drugega odvod po času \( t \) ravnega vala je \( - \omega ^2 \). Dobljene vrednosti vstavimo v valovno enačbo za električno polje

\[ \left[ \nabla_{\phi} ^2 + \left( \frac{\omega ^2}{c_0 ^2} - k ^2 \right) \right] \vec{E} \left( \vec{\rho} \right) = \left[ \nabla_{\phi} ^2 + \kappa ^2 \right] \vec{E} = 0.
\]

Uvedli smo \( \kappa ^2 = \frac{\omega ^2}{c_0 ^2} - k ^2 \). Enačbi se reče amplitudna enačba.

Amplitudno enačbo dobimo analogno tudi za magnetno polje

\[ \left( \nabla_{\phi} ^2 + \kappa ^2 \right) \vec{H} = 0.
\]

Vsak vektor \( \vec{E} \) in \( \vec{H} \) imata v našem problem 3 komponente, kar pomeni, da imamo 6 enačb.
** Točka a)

Dokazujemo, da je dovolj izračunati \( E_z \) in \( H_z \), ostale komponente se izrazijo z njima. Za dokaz bomo uporabili enačbe \ref{eq:max2} in \ref{eq:max4}. Rezultata, ki nam bosta prav prišla sta tudi prva odvoda po času \( t \) in koordinati \( z \) ravnega vala.

\[ \frac{\partial }{\partial z}  \vec{E}(\vec{r}, t) = \mathrm{i} k \quad \text{ in } \quad \frac{\partial }{\partial t} = - \mathrm{i} \omega.
\]

Izračunajmo sedaj rotor električnega polja:

\[ \begin{bmatrix} \frac{\partial }{\partial x}   \\ \frac{\partial }{\partial y}  \\ \frac{\partial }{\partial z}  \end{bmatrix} \times \begin{bmatrix} E_{x} \\ E_{y} \\ E_{z} \end{bmatrix} = - \mu_0 \frac{\partial }{\partial t} \begin{bmatrix} H_{x} \\ H_{y} \\ H_{z} \end{bmatrix}.
\]

Dobimo

\[ \begin{bmatrix} \frac{\partial E_{z}}{\partial y}  - \mathrm{i} k E_y \\ \mathrm{i} k E_x - \frac{\partial E_{z}}{\partial x}  \\ \frac{\partial E_{y}}{\partial x} - \frac{\partial E_{x}}{\partial y} \end{bmatrix} = \mathrm{i} \mu_0 \omega \begin{bmatrix} H_{x} \\ H_{y} \\ H_{z} \end{bmatrix}.
\]

Analogno dobimo tudi z magnetnim poljem, vendar različno predznačeno

\[ \begin{bmatrix} \frac{\partial H_{z}}{\partial y}  - \mathrm{i} k H_y \\ \mathrm{i} k H_x - \frac{\partial H_{z}}{\partial x}  \\ \frac{\partial H_{y}}{\partial x} - \frac{\partial H_{x}}{\partial y} \end{bmatrix} = - \mathrm{i} \epsilon_0 \omega \begin{bmatrix} E_{x} \\ E_{y} \\ E_{z} \end{bmatrix}.
\]

Imamo sklopljene enačbe in lahko zapišemo

\[ H_x = \frac{1}{\mathrm{i} \mu_0 \omega} \left( \frac{\partial E}{\partial y}  - \mathrm{i} k E_y \right)
\]

Dano vstavimo v drugo enačbo magnetnega polja

\[ \frac{1}{\mu_0} \frac{k}{\omega} \left( \frac{\partial E_{z}}{\partial y} - \mathrm{i} k E_y \right) - \frac{\partial H_{z}}{\partial x}  = - \mathrm{i} \epsilon_0 \omega E_y
\]

Izpostavimo iz dane enačbe \( E_y \) in dobimo

\[ E_y = \frac{\frac{\partial H_{z}}{\partial x}  - \frac{1}{\mu_0} \frac{k}{\omega} \frac{\partial E_{z}}{\partial y} }{\mathrm{i \epsilon_0 \omega \left( 1 - c_0 ^2 \frac{k ^2}{\omega ^2} \right)}}
\]

Po množenju števca in imenovalca z \( \frac{\omega ^2}{c_0 ^2} \) in nekaj krajšanja dobimo rezultat

\begin{equation}
\label{eq:1}
 E_y = \frac{\mathrm{i}}{k ^2 - \frac{\omega ^2}{c_0 ^2}} \left( \mu \omega_0 \frac{\partial H_{z}}{\partial x} - k \frac{\partial E_{z}}{\partial y}  \right)
\end{equation}

Analogno lahko tudi \( E_x \) izrazimo

\[ E_x = \frac{\mathrm{i}}{k ^2 - \frac{\omega ^2}{c_0 ^2}} \left( - \omega \mu_0 \frac{\partial H_{z}}{\partial y}  - k \frac{\partial E_{z}}{\partial x}  \right).
\]

Enačbi za \( x \) in \( y \) komponento magnetnega polja pa sta

\[ H_x = \frac{\mathrm{i}}{k ^2 - \frac{\omega ^2}{c_0 ^2}} \left( \omega \epsilon_0 \frac{\partial E_{z}}{\partial y} - k \frac{\partial H_{z}}{\partial x}  \right) \quad \text{ in } \quad H_x = \frac{\mathrm{i}}{k ^2 - \frac{\omega ^2}{c_0 ^2}} \left( - \omega \epsilon_0 \frac{\frac{\partial E_{z}}{\partial x} }{\partial y} - k \frac{\frac{\partial H_{z}}{\partial x} }{\partial x}  \right)
\]

Robni pogoji, ki jih potrebujemo sledijo iz enačb \ref{eq:max2} in \ref{eq:max3}. Kot že večkrat se poslužimo kvadrata ali pravokotnika na meji domene, ki jo tesno objemata.

\[ \left. E_{\parallel} \right|_{\partial } = 0 \quad \text{ in } \quad \left. H_{\perp} \right_{\partial } = 0
\]

Za lažje reševanje si izberemo, da je \( E_z \ne 0 \) in \( H_z = 0 \) ali obratno. V prvem primeru je \( H \) pravokoten na smer širjenja in pravimo, da imamo transverzalni magnetni način valovanja (TM). V drugem primeru je električno polje pravokotno na smer širjenja in imamo transverzalni električni način valovanja.

Vedno mora biti vsaj eden izmed \( z \) komponent električnega ali magnetnega polja mora biti različen od nič.
** Točka b)

V navodili naloge piše, da imamo transverzalni magnetni način valovanja, iz česar sledi, da \( E_z \ne 0 \) in ga želimo izračunati.

V dveh enačbah za \( E_{x, y} \) in \( H_{x, y} \) se pojavita kombinacija tega, da imamo \( H_z \), katera vrednost je \( 0 \) in odvod po \( y \) električnega polja \( E_z \), ki je tudi ničeln. Iz enačbe \ref{eq:1} torej sledi \( E_y = 0 \) in analogno \( H_x = 0 \).

Neničelne komponente so \( E_{z, x} \) in \( H_y \).

Rešujemo enačbo

\[ \left( \frac{\partial ^2 }{\partial z ^2} + \kappa ^2 \right) E_z = 0
\]

z robnimi pogoji

\[ \left. E_z \right|_{x = 0} = \left. E_z \right|_{x = a} = 0.
\]

Splošna rešitve amplitudne enačbe je

\[ E_z (x) = A \sin (\kappa x)  + B \cos (\kappa x)
\]

in iz robni pogojev sledi \( B = 0 \) ter

\[ \kappa_n = \frac{n \pi}{a}, \, n = 1,2,3, \ldots.
\]

\( n \ne 0 \), saj bi sicer imeli rešitev - konstanto, vendar ne bi bila ciklična, kar pa mora biti.

Rešitev za en \( n \) je

\[ E_z (x) = E_{z_0} \sin (\kappa_n x),
\]

splošna rešitev pa je linearna kombinacija.

S poznavanjem vrednosti, ki jih lahko \( \kappa \) zasede, ter relacijo od prej dobimo

\[ \kappa ^2 = \left( \frac{n \pi}{a} \right) ^2 = \frac{\omega ^2}{c_0 ^2} - k ^2.
\]

Posledično lahko izrazimo disperzijsko relacijo, kjer pa ima vsaka vrednost \( n \) svojo vejo

\[ \omega = c_0 \sqrt{\left( \frac{n\pi}{a} \right)^2 + k ^2},
\]

ki je podobna tisti iz plazme.

Intervalu \( [0, \frac{c_0 \pi}{a}] \) se reče frekvenčna reža, kar je območje \( \omega \), v katerem širjenje valovanja ni mogoče.

Če si izberemo frekvenco \( \omega \) na npr. intervalu \( \left( 3c_0 \frac{\pi}{a}, 4c_0 \frac{\pi}{a} \right) \), bo naše valovanje sestavljeno iz kombinacije treh različnih valovanj, kar pa ni dobro za našo definiranost polj. Posledično intervalu \( \left[ c_0 \frac{\pi}{a}, 2c_0 \frac{\pi}{a} \right) \) pravimo uporabni pas, saj imamo samo en valovni vektor \( k \) za dano frekvenco \( \omega \).

Širini intervali

\[ \Delta \omega = 2 c_0 \frac{\pi}{a} - c_0 \frac{\pi}{a} = c_0 \frac{\pi}{a}
\]

pravimo pasovna širina.
** Točka c)

Zanima nas impedanca valovnega vodnika, ki je definirana kot

\[ Z = \frac{E_{\perp }}{H_{\parallel}}.
\]

Za naš primer to pomeni

\[ Z = \frac{E_x}{H_y} = \frac{- \omega \mu_0 \frac{\partial H_{z}}{\partial y} - k \frac{\partial E_{z}}{\partial x}  }{- \omega \epsilon_0 \frac{\partial E_{z}}{\partial x} - k \frac{\partial H_{z}}{\partial y} } = \frac{k}{\omega \epsilon_0}
\]

\( k \) lahko nadomestimo z \( \omega \) preko disperzijske relacije

\[ k = \sqrt{\frac{\omega ^2}{c_0 ^2} - \left( \frac{n \pi}{a} \right) ^2}
\]

in dobimo impedančno odvisnost od frekvence

\[ Z (\omega) = \frac{1}{\omega \epsilon_0} \sqrt{\frac{\omega ^2}{c_0 ^2} - \left( \frac{n \pi}{a} \right) ^2} = \frac{1}{c_0 \epsilon_0} \sqrt{1 -  \left( \frac{c_0 n \pi}{a \omega} \right) ^2 } = Z_0 \sqrt{1 - \frac{\omega_n ^2}{\omega ^2} }.
\]

\( Z_0 \) je impedanca vakuuma, ki jo izračunamo preko

\[ Z_0 = \frac{1}{c_0 \epsilon_0} = \sqrt{\epsilon_0 \mu_0 \frac{1}{\epsilon_0 ^2}} = \sqrt{\frac{\mu_0}{\epsilon_0}} = 376  \Omega.
\]

V korenu prepoznamo, da so to vrednosti, ki jih lahko zasedajo naše frekvence valovanja

\[ \omega_n = \frac{c_0 n \pi}{a}.
\]

Za uporabni pas, kjer \( n = 1 \) velja

\[ Z(\omega) = Z_0 \sqrt{1 - \frac{\omega_1 ^2}{\omega ^2}}.
\]
** TE način

V tem primeru velja, da so neničelne vrednosti \( E_y \) in \( H_{z, x} \).

Amplitudna enačba je tako

\[ \left( \frac{\partial ^2 }{\partial x ^2}  + \kappa ^2 \right) H_z (x) = 0
\]

s splošno rešitvijo

\[ H_z (x) = A \sin (\kappa x) + B \cos (\kappa x).
\]

Hkrati imamo tudi robni pogoj

\[ \left. H_{\perp } \right|_{\partial} = 0 \implies H_x (0) = \frac{\partial H_{z}}{\partial x} (0) = H_x (a) = \frac{\partial H_{z}}{\partial x} (a) = 0
\]

Zgornjima odvodoma pravimo /normalni odvod/ in velja za \( \vec{H} \) v primerih vseh valovnih vodnikov. Dobimo enkaost, da je \( A = 0 \)  ter

\[ \sin (\kappa a) = 0 \implies \kappa_n \frac{n \pi}{a}, \, n = 1, 2, 3, \ldots.
\]

Ponovno dobimo enako disperzijsko relacijo \( \omega(k) \). Impedanca je v tem primeru definirana kot

\[ Z = \frac{E_{\parallel}}{H_{\perp }} = \frac{E_y}{H_x} = \frac{Z_0}{\sqrt{1 - \frac{\omega_n ^2}{\omega ^2}}} .
\]

Graf impedance je prezrcaljen čez premico, ki jo ustvari \( Z_0 \).
