#+title: Predavanja iz Fizike trdne snovi, 14. teden v letu
#+subtitle: 2026/04/01
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Polprevodniki

Gostota stanj vrzeli \( n_c \) ima eksponentno odvisnost \( \exp \left\{ - \frac{E_g}{2 k_B T} \right\} \).

Meritev širine energijske reže \( E_{gap} = \epsilon_c - \epsilon_v \), kjer je \( \epsilon_c \) energija valenčnega nivoja in \( \epsilon_v \) energija vrzeli. Če v kristal obsevamo s fotoni, ki imajo ravno energijo \( E_{gap} \), potem lahko elektron izbije v valenčni pas. V takem primeru velja enačba

\[ E_f = E_{gap} = h \nu.
\]

#+begin_my_example
Za \( E_{gap} = 1 \mathrm{eV} \) mora biti valovna dolžina fotona \( \lambda \sim 1240 \mathrm{nm} \), saj

\[ E_{gap} = 1 \mathrm{eV} = \frac{h c}{\lambda} = \frac{1240 \mathrm{eV \, nm} }{\lambda}
\]

Valovni vektor ima potem vrednost

\[ k_F = \frac{2 \pi}{\lambda} \sim 2 \pi \cdot 10^{-3} \mathrm{nm}^{-1}
\]

in recipročni vektor ima vrednost \( K \sim 2 \pi \cdot 10 \mathrm{nm}^{-1} \). Preko enačbe

\[ K = \frac{2 \pi}{a}
\]

dobimo vrednost razdalje elektronske reže \( a \sim 0.1 \mathrm{nm} \).
#+end_my_example

\[
\begin{array} {c|c}
& E_g [ \mathrm{eV}] \\ \hline
\mathrm{Si} & 1.12 \\
\mathrm{Ge} & 0.67 \\
\mathrm{Te} & 0.35 \\
\mathrm{InAs} & 0.350 \\
\mathrm{GaAs} & 1.40 \\
\end{array}
\]

Energijo elektronov ali vrzeli lahko razvijemo okoli minimuma - za elektrone je to valenčni pas, za vrzeli pa vrh spodnjega pasu.

\[ \epsilon_{e /v} (\mathbf{k}) = \epsilon_c (\mathbf{k}_0) \pm  \frac{1}{2}  ^2 \sum\limits_{i, j}^{} \delta_{ki} \left( M^{-1} \right)_{ij} \delta_{kj},
\]

kjer je \( M \) masni tenzor. Slednji je realen in simetričen in ga lahko zapišemo tudi z lastnimi vrednostmi

\[ \epsilon_{c / v} (\mathbf{k}) = \epsilon_{c/ v} \pm \frac{1}{2}\hbar ^2 \left( \frac{k_1 ^2}{m_{ef, c/v}} + \frac{k_2 ^2}{m_{ef, c/v}} + \frac{k_3 ^2}{m_{ef, c/v}}   \right),
\]

kjer je \( m_{ef} \) efektivna masa. Lastne vrednosti \( k_i, i = 1, 2, 3 \) nam povejo oddaljenost od minimuma.

V primeru kubične simetrije je energija potem

\[ \epsilon_{c/v} = \epsilon_{c/ v} \left( \hbar \right) \pm \frac{\hbar ^2 k ^2}{2m_{ef,c/v}}.
\]

Enačba za gostota stanj elektronov v valenčnem pasu se izračuna po enačbi

\[ n_c (T) = \int\limits_{\epsilon_c}^{\infty} g_c (\epsilon) f(\epsilon) \, \mathrm{d} \epsilon.
\]

Meje integrala so tako določene, saj imajo vzbujeni elektroni energijo višjo od pasu pod valenčnim pasom.

Analogen razmislek za vrzeli je

\[ n_v (T) = \int\limits_{- \infty}^{\epsilon_v} g_v (\epsilon) \left( 1- f(\epsilon) \right) \, \mathrm{d} \epsilon.
\]

Ker elektroni in vrzeli živijo okoli ekstrema, lahko za aproksimacijo uporabimo gostoto stanj prostih elektronov

\begin{align*}
  g_c (\epsilon) &= \sqrt{2 \left( \epsilon - \epsilon_c \right) } \frac{m_c ^{\frac{3}{2}}}{\pi ^2 \hbar ^3} \\
g_v (\epsilon) &= \sqrt{2 \left( \epsilon_v - \epsilon \right)} \frac{m_v^{\frac{3}{2}}}{\pi ^2 \hbar ^3}
\end{align*}

Eksponent v Fermi-Diracovi porazdelitvi

\[ f(\epsilon) = \frac{1}{\exp \left\{ \frac{\epsilon - \mu}{k_B T} \right\} + 1},
\]

je lahko hitro večji od \( 1 \). Pri sobni temperaturi ima produkt vrednost \( k_B T= \frac{1}{40} \mathrm{eV} \ll \epsilon - \mu \). Iz tega potem sledi

\[ \epsilon_c - \mu \gg k_B T \quad \text{ in } \quad \mu - \epsilon_v \gg k_B T.
\]

Porazdelitev \( f(\epsilon) \) lahko potem aproksimiramo z eksponentom \( f(\epsilon) \sim e^{- \beta \left( \epsilon - \mu \right)} \), kjer je \( \beta = \frac{1}{k_B T} \).

Integral se poenostavi v

\[ n_c (T) = \int\limits_{\epsilon_c}^{\infty} g_c (\epsilon) e^{- \beta \left( \epsilon - \mu \right)} \, \mathrm{d} \epsilon.
\]

Eksponent lahko razširimo z \( \epsilon_c - \epsilon_c \) in izpostavimo eksponent, ki je neodvisen od energije

\begin{align*}
  n_c (T) &= e^{- \beta \left( \epsilon_c - \mu \right)} \int\limits_{\epsilon_c}^{\infty} \sqrt{2 \left( \epsilon - \epsilon_c \right)} \frac{m_c ^{\frac{3}{2}}}{\pi ^2 \hbar ^3} e^{- \beta \left( \epsilon - \epsilon_c \right)} \, \mathrm{d} \epsilon \\
&= e^{- \beta \left( \epsilon_c - \mu \right)} \frac{\sqrt{2} m_c ^{\frac{3}{2}}}{\pi ^2 \hbar ^3 \beta^{\frac{3}{2}}} \int\limits_0^{\infty} \sqrt{x} e^{-x} \, \mathrm{d} x = N_c (T) e^{- \beta \left( \epsilon_c - \mu \right)}.
\end{align*}

Zadnji integral, ki se pojavi v zgornji enačbi je definicija \( \Gamma \) funkcija za \( s = \frac{1}{2} \).

Število elektronov je podano z enačbo

\[ N_c (T) = \frac{1}{4} \left( \frac{2 m _c k_B T}{\pi \hbar ^2} \right)^{\frac{3}{2}}.
\]

Pri vrzelih pa je porazdelitev

\[ 1 - f(\epsilon) = \frac{1}{\exp \left\{ - \beta \left( \epsilon - \mu \right) + 1 \right\}
\]

in volumnska gostota vrzeli je potem

\[ p_v (T) = P_v (T) e^{- \beta \left( \mu - \epsilon_v \right)},
\]

kjer je

\[ P_v = \frac{1}{4} \left( \frac{2 m_v  k_B T}{\pi \hbar ^2} \right)^{\frac{3}{2}}
\]

Ohranja se naboja in torej velja

\[ n_c (T) = n_p (T) = n_i (T),
\]

kjer indeks \( i \) pomeni čist oz. ang. /intrinsic/.

Kvadrat \( n_i \) lahko zapišemo

\[ n_i ^2 = n_c (T) p_v (T) = N_c (T) P_v (T) \exp \left\{ - \frac{\left( \epsilon_c - \epsilon_v \right)}{k_B T} \right\},
\]

njen koren pa je potem

\[ n_i = n_c = p_v = \sqrt{N_{c} (T) P_{v}(T)} \exp \left\{ - \frac{E_g}{2 k_B T} \right\}.
\]

Sedaj lahko preverimo, če je bil naš približek polovice energijske režen pravilen.

Iz zgornje enačbe velja

\[ N_c (T) e^{- \beta \left( \epsilon_c - \mu \right)} = P_v (T) e^{- \beta \left( \mu - \epsilon_v \right)},
\]

po logaritmiranju pa potem velja

\[ k_B T \ln \frac{N_c}{P_v} - \left( \epsilon_c - \mu \right) = - \left( - \mu - \epsilon_v \right).
\]

Iz enačbe lahko izrazimo kemijski potencial in upoštevamo \( \epsilon_c = \epsilon_v + E_{gap} \).

\begin{align*}
  \mu &= \frac{1}{2} \left( \epsilon_c + \epsilon_v \right) + \frac{1}{2} k_B T \ln \frac{P_v}{N_c} \\
\mu &= \epsilon_v + \frac{E_g}{2} + \frac{3}{4} k_B T \ln \left( \frac{m_v}{m_c} \right).
\end{align*}

If we crunch some numbers, dobimo potrdilo, da je izpolnjeno \( \epsilon - \mu \gg k_B T \).

V primeru dopiranja dobimo različno gostoto elektronov in vrzeli \( n_c \ne p_v \). Razliko gostoto označimo

\begin{equation}
\label{eq:1}
 n_c - p_v = \Delta n.
\end{equation}

Navkljub dopiranju bo še zmeraj veljalo

\[ n_i = N_c e^{- \beta \left( \epsilon_c - \mu_i \right)},
\]

kjer je \( \mu_i \) kemijski potencial čistega polprevodnika. Zaradi enačbe \ref{eq:1} pa bo veljalo, da je kemijski potencial \( \mu \) dopiranega polprevnodika premaknjen glede \( \mu_i \). Gostota elektronov v valenčnem pasu je

\[ n_c = N_c e^{- \beta \left( \epsilon_c - \mu \right)} = n_i e^{- \beta \left( \mu_i - \mu \right)}.
\]

Analogno za valenčni pas lahko zapišemo

\[ p_v = n_i e^{- \beta \left( \mu - \mu_i \right)}.
\]

Poleg enačbe \ref{eq:1} bo še zmeraj veljala

\begin{equation}
\label{eq:2}
n_c p_v = n_i ^2.
\end{equation}

To se zgodi ob predpostavki, da je nečistoč v polprevodniku enostavno tako malo, da se kristalna struktura ne spremeni bistveno - zgolj kemijski potencial.

Iz enačb \ref{eq:1} in \ref{eq:2} dobimo kvadratni enačbo, katere rešitev je

\[ \begin{bmatrix} n_{c} \\ p_{v} \end{bmatrix} = \frac{1}{2}\sqrt{\Delta n ^2 + 4 n_i ^2} \pm \frac{\Delta n}{2}.
\]
