#+title: 1. in 2. predavanje iz Kvantne mehanike
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Uvod

Pri klasični mehaniki nas zanima trajektorija delca \( \vec{r}(t) \). Z Newtonovim zakonom lahko izpeljemo pospešek, ki je funkcija časa, kraja in hitrosti. Če poznamo začetne pogoje, lahko določimo \( \vec{r} \) kjerkoli v prihodnosti.

Potreba po kvantni mehaniki se je razvila zaradi Michelsonovega poskusa, ki je pokazal, da je hitrost svetlobe v vakuumu absolutna. Čez 1 mesec bo 100 let, odkar je Heisenberg izdal svoj članek, ki se smatra kot začetek kvantne mehanike. Pred letom 1925 so bila sledeča odkritja, ki so kazala na nekaj več od klasične mehanike

- Planck, Einstein leta 1905 razložita enačbo \( E = \hbar \omega \)
- 1923 de Broglie opazi, da je hitrost elektrona obratno sorazmerna njegovi valovni dolžini

  \[ p = \frac{2 \pi \hbar}{\lambda} = m v
  \]
  - imamo valovanje pri masnih delcih \( \cos \left( k x - \omega t \right) \) in \( p = \hbar k \)
- energija elektrona je \( E = \frac{p ^2}{2m} \)
- spektri plinov so črtasti
- zanimala jih je stabilnost in sestava atoma - ta vprašanja je omogočala nova tehnologija

  Planetni model (pozitivno jedro - sonce, elektroni - planeti) pogojno razloži spekter vodikovega atom, vendar posplošitev ni bila mogoča. Ta razlaga tudi ne more razložiti spektra vodikovega atoma v električnem polju.

Decembra 1925 Heisenberg objavi svoj članek o kvantni mehaniki. V začetku leta 1926 je Schrödinger objavil svoj članek, kjer uvede Schrödingerjevo enačbo. Želel je izpeljati relativistično invariantno enačbo, česar ni uspel (Dirac, 3 leta kasneje, glej FJOD), hkrati pa je želel, da veljajo prve tri alineje.

Osnovna Schrödingerjeva enačba v eni dimenziji brez potenciala zapišemo kot

\[ \mathrm{i} \hbar \frac{\partial \Psi}{\partial t} = - \frac{\hbar ^2}{2m} \frac{\partial ^2 }{\partial x ^2} \Psi
\]

Rešitev enačbe je valovanje \( \Psi = A e^{\mathrm{i} \left( kx - \omega t \right)} \). Ko rešitev vstavimo vanj, dobimo

\begin{align*}
  \mathrm{i} \hbar \left( - \mathrm{i} \right) \omega &= - \frac{\hbar ^2}{2m} i ^2 k ^2 \\
\hbar \omega = \frac{\hbar ^2 k ^2}{2m} &= \frac{p ^2}{2m}
\end{align*}

Opazimo v zadnji vrstici vse tri alineje.

Valovna enačba ne reši problema kvantne mehanike (vstavi \( \Psi \) vanjo). Difuzijska enačba

\[ \frac{\partial T}{\partial t} = D \frac{\partial ^2 }{\partial x ^2} T
\]

je rešena s \( T (x, t) = \cos \left( kx - \omega t \right) \). Schrödingerjeva enačba je difuzijska enačba s kompleksno rešitvijo.

Schrödingerjevi enačbi dodamo tudi potencial

\begin{equation}
\label{eq:1}
\mathrm{i} \hbar \frac{\partial \Psi}{\partial t}  = - \frac{\hbar ^2}{2m} \frac{\partial ^2 }{\partial x^2} \Psi + V \Psi
\end{equation}

Newtonove enačbe so bile sprejete, saj je lahko prepričljivo izpeljal elipse planetov. Schrödinger se je na podoben način lotil Keplerjevega problema s potencialom \( V \left( \vec{r}, t \right) \propto \frac{1}{r} \). Z nekaj mučenja je izpeljal spekter vodika \( E_n \propto \frac{1}{n ^2} \), s še malo več mučenja je rešil tudi problem spektra vodikovega atoma v električnem polju \( E_n \left( \vec{E}, \vec{B} \right) \).

** Valovanje

Prišli smo do tega, da ja, je valovanje, vendar nas zanima, kaj valuje. Bornova interpretacija valovne funkcije definira verjetnost, da delec detektiramo na zaprtem intervalu \( [a, b] \) preko enačbe

\begin{equation}
\label{eq:4}
 P_{ab} = \int\limits_a^b \left| \Psi(x, t) \right| ^2 \, \mathrm{d} x
\end{equation}

kjer je \( \rho (x, t) = \left| \Psi(x, t) \right| ^2\) verjetnostna gostota. Velja enakost

\[ \frac{\mathrm{d} P}{\mathrm{d} x} = \rho
\]

Pri detekciji ne dobimo nobene druge informacije kot to ali je elektron bil na intervalu ali ne. Ob neskončnem številu ponovitev dobimo našo verjetnost

\[ \lim_{n \to \infty}  \frac{N_{zaznan}}{N} = P_{ab }
\]

Mi bomo obravnavali minimalistično Kobenhavensko interpretacijo kvantne mehanike.

** Lastnosti valovne funkcije

Pišemo lastnosti valovne funkcija v eni dimenziji. Velja, da je valovna funkcija normirana

\[ \int\limits_{-\infty}^{\infty} \left| \Psi \right| ^2 \, \mathrm{d} x = 1
\]

Enačba, ki dokazuje, da nimamo izvorov, je

\begin{equation}
\label{eq:2}
 \frac{\partial \rho}{\partial t} + \nabla \cdot \vec{\jmath} = q
\end{equation}


Verjetnostno gostoto nadomestimo z definicijo in upoštevamo odvod produkta. \( \Psi^{\ast} \) je kompleksna konjugiranka valovne funkcije, ki jo dobimo s konjugiranjem Schrödingerjeve enačbe in izražavo odvoda po času.

\begin{align}\label{ali:ss}
\frac{\partial \rho}{\partial t} &= \frac{\partial \Psi^{\ast} \Psi}{\partial t} \\
&= \frac{\partial \Psi^{\ast}}{\partial t} \Psi + \frac{\partial \Psi}{\partial t} \Psi^{\ast} \\
&=- \frac{\hbar ^2}{2m} \frac{1}{-\mathrm{i} \hbar} \frac{\partial ^2 }{\partial x ^2} \Psi^{\ast} \Psi + \frac{V^{\ast}}{- \mathrm{i} \hbar} \Psi^{\ast} \Psi + C. C.
\end{align}

kjer je c.c kompleksna konjugirana vrednost.

Odvod po kraju lahko razpišemo

\[ \frac{\partial ^2 \Psi^{\ast} }{\partial x ^2} \Psi = \frac{\partial }{\partial x}  \left( \frac{\partial \Psi^{\ast}}{\partial x} \Psi \right) - \frac{\partial \Psi^{\ast}}{\partial x}  \frac{\partial \Psi}{\partial x}
\]

Enačba \ref{ali:ss} postane

\begin{equation}
\label{eq:3}
 \frac{\partial \rho}{\partial t} = - \frac{\partial }{\partial x} \left( \frac{\hbar}{2 \mathrm{i} m }\left( \Psi^{\ast} \frac{\partial \Psi}{\partial x}  - \Psi \frac{\partial \Psi^{\ast}}{\partial x}  \right) \right) - \frac{2}{\hbar} \mathrm{Im} \left( V \left| \Psi \right| ^2 \right)
\end{equation}

Enačbo \ref{eq:2} zapišemo v eni dimenziji kot

\[ \frac{\partial \rho}{\partial t}  + \frac{\partial }{\partial x} \vec{\jmath} = q = 0
\]

Verjetnostni tok v treh dimenzijah zapišemo kot

\[ \vec{\jmath} = - \frac{\mathrm{i} \hbar}{2m} \left( \Psi^{\ast} \nabla \Psi - \Psi \nabla \Psi^{\ast} \right) = \vec{\jmath} \left( \vec{r}, t \right)
\]

Opazimo, da se verjetnostni tok pokrajša s prvim členom v enačbi \ref{eq:3} in nam tako ostane

\[ q = - \frac{2}{\hbar} \mathrm{Im} V \left| \Psi \right| ^2
\]

Za realen potencial je imaginaren del enak \( 0 \), kar pomeni, da nimamo izvorov ali ponorov, saj \( q = 0 \).

Preverimo še normiranost. Enačbo \ref{eq:4} odvajamo po času

\[ \frac{\mathrm{d} P_{ab }}{\mathrm{d} t} = - \int\limits_a^b \frac{\partial }{\partial x} j_x \, \mathrm{d} x = j_x (a) - j_x(b)
\]

Za \( a \to - \infty \) in \( b \to \infty \) bo razlika \( 0 \). Za naše valovne funkcije velja, da so del Scwarzovega prostora, torej

\[ \lim_{x \to \infty} x^n \left| \Psi \right|  = 0
\]

#+begin_my_example
Primera taka funkcije sta \( e^{- \lambda x} \) ter \( e ^{- \mu x ^2} \).
#+end_my_example
*** Zveznost

Valovna funkcija \( \Psi \) je zvezna funkcija. Odvod \( \frac{\partial \Psi}{\partial x} \) je zvezna funkcija, če je \( V \) zvezna funkcija. Drugi odvod \( \frac{\partial ^2 }{\partial x ^2} \Psi  \) je zvezna, če je \( V \) zvezna.

Pravokotna potencialna jama ima v jami kosinusno valovanje, izven jame pa potencialno pada, imamo prevoj v točki nezveznosti.

** Pričakovane vrednosti

Pričakovane vrednosti položaja izračunamo preko

\[ \left\langle x \right\rangle  = \int\limits_{- \infty}^{\infty} x \rho (x, t) \, \mathrm{d} x
\]

Predpostavimo, da imamo dve različni funkciji. Zanima nas, kako se spreminja težišče v odvisnosti od časa:

\begin{align*}
\frac{\mathrm{d} \left\langle x \right\rangle}{\mathrm{d} t} &= \int\limits_{- \infty}^{\infty} x \frac{\partial \rho}{\partial t} \, \mathrm{d} x \\
&= - \int\limits_{- \infty}^{\infty} x \frac{\partial j}{\partial x}  \, \mathrm{d} x && \text{per partes} \\
&=  \cancel{\left. x j \right|_{- \infty}^{\infty}} + \int\limits_{- \infty}^{\infty} j \, \mathrm{d} x \\
&= \int\limits_{- \infty}^{\infty} j \, \mathrm{d} x \\
&= - \frac{\mathrm{i} \hbar}{2m} \left( \int\limits_{-\infty}^{\infty} \Psi^{\ast} \frac{\partial \Psi}{\partial x}  \, \mathrm{d} x - \int\limits_{- \infty}^{\infty} \Psi \frac{\partial \Psi^{\ast}}{\partial x} \, \mathrm{d} x \right) && \text{per partes} \\
&= \frac{1}{m} \int\limits_{- \infty}^{\infty} \Psi^{\ast} \left( - \mathrm{i} \hbar \frac{\partial }{\partial x}  \right) \Psi \\
&= \frac{1}{m} \int\limits_{- \infty}^{\infty} \Psi^{\ast} \hat{p} \Psi \, \mathrm{d} x
\end{align*}

Dobimo novo zvezo in sicer pričakovano gibalno količine

\[ m \frac{\mathrm{d} \left\langle x \right\rangle}{\mathrm{d} t} = \left\langle \hat{p} \right\rangle
\]

kjer je \( \hat{p} = - \mathrm{i} \hbar \frac{\partial }{\partial x}  \) ali v treh dimenzijah \( \hat{\vec{p}} = - \mathrm{i} \hbar \nabla \).

S kvadriranjem operatorja gibalne količine dobimo nov operator kinetične energije:

\[ T = p ^2 = \vec{p} \vec{p} = - \hbar ^2 \nabla ^2
\]

Definiramo, nam že poznan, Hamiltonianov operator

\begin{equation}
\label{eq:5}
 \hat{H} = \frac{p ^2}{2m} + V = - \frac{\hbar ^2 \nabla ^2}{2m} + V
\end{equation}

** Stacionarna stanja

Za funkcijo, kjer ločimo spremenljivke

\[ \Psi \left( \vec{r}, t \right) = \psi (\vec{r}) f (t),
\]

iščemo taka stanja, da bo veljalo

\[ \hat{H} \Psi_n =  E_n \Psi_n
\]

Z upoštevanjem enačbe \ref{eq:5} razpišemo

\begin{align*}
  \left( - \frac{\hbar ^2}{2m} \nabla ^2 + V \right) \Psi_n &= E_n \Psi_n \\
\hat{H} \Psi = \mathrm{i} \hbar \frac{\partial \Psi}{\partial t} \\
&= E_n \Psi
\end{align*}

iz česar sledi enakost za časovni del

\[ f = \exp \left\{ - \mathrm{i} \frac{E_n}{\hbar} t \right\}
\]

V kvantni mehaniki pišemo časovni eksponent negativno predznačen kot \( e^{- \mathrm{i} \omega t} \), kjer je \( \omega = \frac{E}{\hbar} \).
** Komutator

Naj bosta \( \hat{A} \) in \( \hat{B} \) operatorja. Definiramo operacijo

\[ \left[ \hat{A}, \hat{B} \right] = \hat{A} \hat{B} - \hat{B} \hat{A}
\]

Glej Poissonove oklepaje iz klasične mehanike, kjer smo povedali

\[ \left[ q_i, p_i  \right]= \delta_{ij}
\]

#+begin_my_example
Naj bo operator \( \hat{A} = x \) in \( \hat{B} = \hat{p} = - \mathrm{i} \hbar \frac{\partial }{\partial  x} \). Po definiciji

\[ \left[ x, p \right] = xp - px = - \mathrm{i} \hbar \frac{\partial }{\partial x}  + \mathrm{i} \hbar \frac{\partial }{\partial x}  x
\]

\( x \) ne smeš odvajati v drugem členu. Potrebno je videti, kako ta komutator vpliva na splošno funkcijo \( \Psi \). Torej

\begin{align*}
 \left[ x, p \right]\Psi (x) &= - \mathrm{i} \hbar x \frac{\partial \Psi}{\partial x}  + \mathrm{i} \hbar \frac{\partial }{\partial x} \left( x \Psi \right) \\
&= - \mathrm{i} \hbar x \frac{\partial \Psi}{\partial x}  + \mathrm{i} \hbar \Psi + \mathrm{i} \hbar x \frac{\partial \Psi}{\partial x}  \\
&= \mathrm{i} \hbar \Psi
\end{align*}

kar velja za vsako funkcijo \( \Psi \).

Torej velja

\[ \left[ x_i, p_j \right] = \mathrm{i} \hbar \delta_{ij}
\]
#+end_my_example

Lastnosti komutatorjev so

- \[ \left[ \alpha A, B \right] = \alpha \left[ A, B \right]
  \]
- \[   \left[ AB, C \right] = A \left[ B, C \right] + \left[ A, C \right] B
  \]

  #+begin_proof
Dokazujemo drugo alinejo. Razpišemo desno stran

\begin{align*}
  A \left[ B, C \right] + \left[ A, C \right] B &= A \left( BC - CB \right) + \left( AC - CA \right) B \\
&= ABC - ACB + ACB - CAB \\
&= \left[ AB, C \right]
\end{align*}
  #+end_proof
** Lastnosti operatorjev

Imamo operator \( A = \frac{\partial }{\partial x}  \mathrm{i} \), s katerim operiramo na funkciji \( \phi \) in \( \psi \). Opazujemo matrični element, ki ga bomo še definirali kasneje

\[ \int\limits_{-\infty}^{\infty} \phi^{\ast} A \psi \, \mathrm{d} x = \int\limits_{- \infty}^{\infty} \phi^{\ast} \frac{\partial }{\partial x} \psi \, \mathrm{d} x
\]

Preko integriranja per partes in upoštevanja, da so naše funkcije v razredu Schwartzevih funkcij, pridobimo enakost

\[ \int\limits_{- \infty}^{\infty} \phi^{\ast} A \psi \, \mathrm{d} x =\left. \phi^{\ast} \psi \right_{-\infty}^{\infty} - \int\limits_{-\infty}^{\infty} \frac{\partial \phi^{\ast}}{\partial x} \psi \, \mathrm{d} x = - \int\limits_{-\infty}^{\infty} \left( A \phi^{\ast} \right) \psi \, \mathrm{d} x
\]

Lahko zapišemo člen v zadnjem integralu kot \( \left( A \phi^{\ast} \right) = \left( A \phi \right)^{\ast} \). Operator \( A \) je v tem primeru antisimetričen.

Če je operator \( A \) enak gibalni količini, potem preko enakega postopka pridemo do rezultata

\begin{align*}
  \int\limits_{-\infty}^{\infty} \phi^{\ast} \left( - \mathrm{i} \hbar \frac{\partial }{\partial x} \psi \right) \, \mathrm{d}x &= \mathrm{i} \hbar \int\limits_{-\infty}^{\infty} \frac{\partial \phi ^{\ast}}{\partial x} \psi \, \mathrm{d} x \\
&= \int\limits_{-\infty}^{\infty} \left( - \mathrm{i} \hbar \frac{\partial }{\partial x}  \phi \right)^{\ast} \psi \, \mathrm{d} x
\end{align*}

Operatorju, kjer velja

\[ \int\limits_{-\infty}^{\infty} \phi^{\ast} \hat{p}\psi \, \mathrm{d} x = \int\limits_{-\infty}^{\infty} \left( \hat{p} \phi \right)^{\ast} \psi \, \mathrm{d} x  ,
\]

pravimo, da je simetričen ali hermitski.

Poglejmo si še primer, ko je \( A = H = \frac{p ^2 }{2m} + V \). Problematičen del Hamiltoniana je \( p ^2 \).

\begin{align*}
  \int\limits_{-\infty}^{\infty} \phi^{\ast} \frac{\partial ^2 }{\partial x ^2} \psi &= - \int\limits_{-\infty}^{\infty} \frac{\partial \phi^{\ast}}{\partial x} \frac{\partial \psi}{\partial x}  \, \mathrm{d} x \\
&=  \int\limits_{-\infty}^{\infty}  \frac{\partial ^2 }{\partial x ^2} \phi^{\ast} \psi \, \mathrm{d} x
\end{align*}

Per partes smo naredili dvakrat - najprej na \( \frac{\partial }{\partial x}  \left( \frac{\partial \psi}{\partial x}  \right) \), kar nam pridela prvi negativen predznak. Z drugim per partes se negativna predznaka izničita.

\( H \) je hermitski, če je potencial realen ali dugače zapisano \( V = V^{\ast} \).

\[ \int\limits_{-\infty}^{\infty} \phi^{\ast} H \psi \, \mathrm{d} x = \int\limits_{- \infty}^{\infty} \left( H \phi \right)^{\ast} \psi \, \mathrm{d} x
\]
** Ehrenfestov teorem

Postopamo podobno kot pri izpeljavi operatorja gibalne količine. Imamo operator \( \hat{A} \), ki je lahko \( x, \hat{p} \) ali \( H \). Pričakovana vrednost je

\[ \left\langle \hat{A} \right\rangle = \int\limits_{-\infty}^{\infty} \Psi^{\ast} \hat{A} \Psi \, \mathrm{d} x
\]

Časovna odvisnost pričakovane vrednosti operatorja je

\begin{equation}
\label{eq:6}
 \frac{\mathrm{d} }{\mathrm{d} t} \left\langle \hat{A} \right\rangle  = \int\limits_{- \infty}^{\infty} \left( \frac{\partial \Psi^{\ast}}{\partial t} A \Psi + \Psi^{\ast} \frac{\partial A}{\partial t} \Psi + \Psi^{\ast} A \frac{\partial \Psi}{\partial x}   \right) \, \mathrm{d} x
\end{equation}

Veljata naslednji zvezi

\[ \frac{\partial \Psi}{\partial t}  = \frac{1}{\mathrm{i} \hbar} H \Psi \quad \text{in} \quad \frac{\partial \Psi^{\ast}}{\partial t} = - \frac{1}{\mathrm{i} \hbar} \left( H \Psi \right)^{\ast}
\]

Nadalje sledi iz enačbe \ref{eq:6}, da

\begin{align*}
  \frac{\mathrm{d} }{\mathrm{d} t} \left\langle A \right\rangle &= \int\limits_{- \infty}^{\infty} \left( - \frac{1}{\mathrm{i} \hbar} \left[ H \Psi \right]^{\ast} A \Psi + \Psi^{\ast} \frac{\partial A}{\partial t} \Psi + \Psi^{\ast} A \left[ \frac{1}{\mathrm{i} \hbar} H \Psi \right] \right) \, \mathrm{d} x \\
&=  \left\langle \frac{\partial \hat{A}}{\partial t}  \right\rangle + \frac{1}{\mathrm{i} \hbar} \int\limits_{- \infty}^{\infty} \left[ \Psi^{\ast} H \Psi - \left( H \Psi \right)^{\ast} A \Psi \right] \, \mathrm{d} x \\
&= \left\langle \frac{\partial \hat{A}}{\partial t}  \right\rangle + \frac{1}{\mathrm{i} \hbar} \left\langle \left[ \hat{A}, \hat{H} \right] \right\rangle
\end{align*}

Enačbi

\[ \frac{\mathrm{d} }{\mathrm{d} t} \left\langle \hat{A} \right\rangle =  \left\langle \frac{\partial \hat{A}}{\partial t}  \right\rangle + \frac{1}{\mathrm{i} \hbar} \left\langle \left[ \hat{A}, \hat{H} \right] \right\rangle
\]

pravimo Ehrenfestov teorem.


#+begin_my_example
Za \(  A = x \) s Hamiltonianom velja preko teorema

\[ \frac{\mathrm{d} }{\mathrm{d} t} \left\langle x \right\rangle  = \frac{1}{\mathrm{i} \hbar} \left\langle \left[ x, H \right] \right\rangle = \frac{1}{\mathrm{i} \hbar} \mathrm{i} \hbar \frac{\left\langle p \right\rangle}{m} = \frac{\left\langle p \right\rangle}{m}
\]

saj velja

\begin{align*}
  \left[ x, H \right] &= \left[ x, \frac{p ^2}{2m} + V(\vec{r}, t) \right] \\
&= \frac{1}{2m} \left[ x, p ^2 \right] \\
&= \frac{1}{2m} \left( \left[ x, p \right] p + p \left[ x, p \right] \right) \\
&= \frac{1}{2m} \left( \mathrm{i} \hbar p + p \mathrm{i} \hbar \right)
\end{align*}

Velja \( \left[ x, V \right] = 0 \).
#+end_my_example

#+begin_my_example
Za operator vzamemo gibalno količino \( A = p \). Lahko vzamemo totalni odvod, ker funkcija \( \vec{r} \) ni funkcija časa. Po definiciji Ehrenfestovega teorema

\[ m \frac{\mathrm{d} ^2 }{\mathrm{d} t ^2} \left\langle x \right\rangle  = \frac{\mathrm{d} \left\langle p \right\rangle}{\mathrm{d} t}
\]

kjer smo upoštevali rezultat prejšnjega primera. Nadaljujemo

\[ \frac{\mathrm{d} }{\mathrm{d} t} \left\langle p \right\rangle  = \frac{1}{\mathrm{i} \hbar} \left\langle \left[ p, H \right] \right\rangle = \frac{1}{\mathrm{i} \hbar} \left\langle \left[ p, \frac{p ^2}{2m} + V \right] \right\rangle
\]

Komutacija \( p \) in \( p ^2 \) nam da ničelni rezultat. Torej

\[\frac{\mathrm{d} }{\mathrm{d} t} \left\langle p \right\rangle &= \frac{1}{\mathrm{i} \hbar} \left\langle \left[ p, V \right] \right\rangle
\]

Komutacija \( p \) in \( V \) pa nam poda rezultat

\begin{align*}
  \left[ p, V(x, t) \right] \Psi &= \left( p V - V p \right) \Psi \\
&= - \mathrm{i} \hbar \frac{\partial }{\partial x} V \Psi + \mathrm{i} \hbar V \frac{\partial }{\partial x} \Psi \\
&= - \mathrm{i} \hbar \left( \frac{\partial V}{\partial x} V \right) \Psi - \mathrm{i} \hbar V \frac{\partial \Psi}{\partial x}  + \mathrm{i} \hbar V \frac{\partial \Psi}{\partial x } \\
&= \left( - \mathrm{i} \hbar \frac{\partial V}{\partial x}  \right) \Psi
\end{align*}

Torej

\[ \frac{\mathrm{d} }{\mathrm{d} t} \left\langle p \right\rangle  = m \frac{\mathrm{d} ^2 \left\langle x \right\rangle }{\mathrm{d} t ^2} = \left\langle  - \frac{\partial V}{\partial x}  \right\rangle = \left\langle F(x, t) \right\rangle
\]

To nas spominja na 2. Newtonov zakon. Klasično bi ga zapisali

\[ m \frac{\mathrm{d} ^2 }{\mathrm{d} t ^2} = F (x, t)
\]

Ekvivalenten kvantnomehanski zapis bi bil

\[ m \frac{\mathrm{d} ^2 \left\langle x \right\rangle }{\mathrm{d} t ^2} = F \left( \left\langle x \right\rangle , t \right)
\]

vendar mi imamo pa \( \left\langle F (x, t) \right\rangle \), kar je po definiciji

\[ \int\limits_{-\infty}^{\infty} \Psi^{\ast} F (x, t)  \Psi \, \mathrm{d} x = F \left( \left\langle x \right\rangle , t\right) \int\limits_{- \infty}^{\infty} \left| \Psi \right| ^2 \, \mathrm{d} x = F \left( \left\langle x \right\rangle , t\right)
\]

Verjetnostna gostota \( \rho(x, t) \) ima obliko \( \delta \)-funkcije in ko gre širina stolpca \( \sigma \) proti 0 okoli pričakovane vrednosti \( \left\langle x \right\rangle \) bo zgornji integral veljal, saj je \( F(x, t) \) neodvisna od \( x \). Temu prehodu, ko gre širina proti \( 0 \), pravimo klasična limita.

/Think through this, razlaga integrala je bolj švoh/.
#+end_my_example

#+begin_my_example
Vzemimo za operator \( \hat{A} = \hat{\vec{r}} \times \hat{\vec{p}} = \hat{\vec{L}} \). Za vajo dokažemo doma

\[ \frac{\mathrm{d} \left\langle \hat{\vec{L}} \right\rangle}{\mathrm{d} t} = \left\langle \hat{\vec{M}} \right\rangle  = \left\langle \vec{r} \times \left( - \nabla V \right) \right\rangle
\]

kjer je \( \hat{\vec{M}} = \vec{r} \times \vec{F} \).
#+end_my_example
** Nedoločenost

[vstavi graf]

Širina stolpca je enaka

\[ \delta x ^2 = \sigma_x ^2 = \left\langle x ^2 \right\rangle  - \left\langle x \right\rangle ^2 \ge 0
\]

Naredimo to za splošen operator

\[ \delta ^2 \hat{A} ^2 = \left\langle \hat{A} ^2 \right\rangle - \left\langle \hat{A} \right\rangle ^2
\]

Na vajah dokažemo, da za poljubna operatorja \( \hat{A} \) in \( \hat{B} \) velja

\[ \left| \Delta A \Delta B \right| \ge \frac{1}{2} \left\langle  \left[ \hat{A}, \hat{B} \right] \right\rangle
\]

preko Schwartzove neenakosti.

\[ \left| \int\limits_{}^{} \phi^{\ast} \psi \, \mathrm{d} x \right| \le \int\limits_{}^{} \left| \phi^ \right|^2 \, \mathrm{d} x \int\limits_{}^{} \left| \psi \right| ^2 \, \mathrm{d} x
\]

Za \( A = x \) in \( B = p \) je enako

\[ \delta x \delta p \ge \frac{1}{2} \hbar
\]
* Formalizem kvantne mehanike

Uporabljali bomo Diracov formalizem, ki ga je izdal v svoji knjigi leta 1930. Drugi pomembnejši za naš formalizem pa je von Neumann s knjigo leta 1932.

1. Nahajamo se v vektorskem prostor, ki je Hilbertov \( L ^2 \). Naj bo funkcija \( \Psi(\vec{r}, t) \in L ^2 \). Obstaja baza \( \left\{ \phi_n \right\} \) za \( n \in \mathbb{N} \). Če bi obstajala baza \( \left\{ \phi_k \right\} \), kjer \( k \in \mathbb{R} \) je to Banachov prostor, kjer je matematika drastično značilna.

2. Pri vektorjih imamo tudi avtomatsko skalarni produkt. Za dva vektorja \( \psi, \phi \in L ^2 \). Skalarni produkt zapišemo na več možnih načinov:

   \[ \left( \phi, \psi \right) = \left( \phi \middle| \psi \right) = \left\langle \phi, \psi \right\rangle  = \left\langle \phi \middle| \psi \right\rangle = \int\limits_{}^{} \phi^{\ast} \psi \, \mathrm{d} x
   \]

   Mi bomo uporabljali Diracov zapis skalarnega produkta, ki \( \left\langle \phi \middle| \psi \right\rangle \). Za skalarni produkt velja

   - \( \left\langle \phi \middle| \psi \right\rangle  = \left\langle \psi \middle| \phi \right\rangle ^{\ast} \)
   - \( \left\langle \psi \middle| \psi \right\rangle \ge 0 \) in če \( \left\langle \psi \midlle|\psi \right\rangle = 0\), ko \( \psi = 0 \)
   - \( \left| \left\langle \phi \middle| \psi \right\rangle \right| ^2 \ge \left\langle \phi \middle| \phi \right\rangle \left\langle \psi \middle| \psi \right\rangle\)

3. Definiram /ket/. Za funkcijo ali stanje \( \Psi(x, t) \in L ^2 \) , definiramo stanje ali vektor kot \( \left| \psi \right\rangle \)

4. Linearni operatorji je definiran s tem, da vsoto preslika v vsoto

   \[ \hat{A} \left( \lambda \left| \phi \right\rangle  + \mu \left| \psi \right\rangle\right) = \lambda \hat{A} \left| \phi \right\rangle + \mu \hat{A} \left| \psi \right\rangle
   \]

   Operator je antilinearen, če ga kompleksno konjugira:

   \[ \hat{A} \lambda \left| \psi \right\rangle  = \lambda^{\ast} \hat{A} \left| \psi \right\rangle
   \]

5. Rieszov izrek: Naj bo \( \hat{f} \) linearni funkcional. Obstaja neka funkcija, da delovanje funkcionala \( \hat{f} \) predstavimo kot skalarni produkt

   \[ \hat{f} \left| \psi \right\rangle = \left| f \middle| \psi \right\rangle = \int\limits_{}^{} f^{\ast} (x) \psi(x) \, \mathrm{d} x = z \in \mathbb{C}
   \]

   kjer je \( z \in \mathcal{C} \) število.

   Uvedemo bra \( \left\langle \psi \right| \). Funkcional zapišemo kot \( \left\langle \phi \right|  = \hat{f}\) ali drugače

   \[ \hat{f} \left| \psi \right\rangle  = z = \left\langle \phi\middle| \psi \right\rangle
   \]

   Tukaj velja, da če imamo bra, ki deluje na vektor, je to skalarni produkt

   \[ \left\langle \phi \right| \left| \psi \right\rangle = \left| \phi \middle| \psi \right\rangle
   \]

6. Razvoj stanja po dani bazi \( \left\{ \phi_n (x) \right\} \). Velja

   \[ \int\limits_{}^{} \phi^{\ast}_m \phi_n \, \mathrm{d} x = \delta_{mn }
   \]

   Integral je ortonormiran, vendar je lahko proble degeneriran.

   Funkcijo \( \Psi (x) \) razvijemo po bazi

   \[ \Psi (x) = \sum\limits_n^{} c_n \phi_n (x)
   \]

   Razvoj pomnožimo s \( \phi_m^{\ast} \) in upoštevamo zgornjo enakost

   \[ \int\limits_{}^{} \phi_m ^{\ast} (x) \Psi(x) \, \mathrm{d} x = c_m
   \]

   To pomeni, da lahko naš razvoj po bazi zapišemo namesto s \( c_n \) kot

   \[ \Psi (x) = \sum\limits_n^{} \int\limits_{}^{} \phi^{\ast}_n (x') \Psi(x') \, \mathrm{d} x' \phi_n (x)
   \]

   Ker varčujemo z biti, bomo pisali bazo \( \left\{ \left| \phi_n \right\rangle \right\} \) tudi kot \( \left\{ \left| n \right\rangle \right\} \). Razvoj po bazi zapišemo kot

   \[ \left| \psi \right\rangle  = \sum\limits_n^{} c_n \left| n \right\rangle
   \]

   Na vektor delujemo s funkcionalom \( \left| m \right\rangle \) in zapišemo

   \[ \left\langle m \middle| \psi \right\rangle  = \sum\limits_n^{} c_n \left\langle m \middle| n \right\rangle = c_m
   \]

   Poleg tega

   \[ \left| \psi \right\rangle  = \sum\limits_n^{} \left\langle n \middle| \\Psi \right\rangle \left| n \right\rangle = \sum\limits_n^{} \left| n \right\rangle \left\langle n \middle| \Psi \left\rangle = \left( \sum\limits_n^{} \left| n \right\rangle \left\langle n \right|\right) \left| \Psi \right\rangle = I \left| \Psi \right\rangle
   \]

   saj velja

   \[ I = \sum\limits_n^{} \left| n \right\rangle  \left| n \right\rangle \iff I = \sum\limits_n^{} \int\limits_{}^{} \phi_n ^{\ast} (x') \Psi(x') \, \mathrm{d} x' \phi_n (x)
   \]

7. Zapis operatorja v dani bazi \( \left\{ n \right\} \). Imamo poljuben operator \( \hat{A} \) in enakost \( I = \sum\limits_n^{} \left| n \right\rangle \left\langle n \right|\).

   Operator, ki deluje na vektor, zapišemo kot

   \begin{align*}
     A \left| \psi \right\rangle &= I A I \left| \psi \right\rangle \\
        &= \sum\limits_{m, n}^{} \left| m \right\rangle \left\langle m \right| A \left| n \right\rangle \left| n \middle| \psi \right\rangle \\
        &= \sum\limits_{m, n}^{} \left| m \right\rangle A_{mn} \left\langle n \middle| \psi \right\rangle \\
        &= \sum\limits_{m, n}^{} \left| m \right\rangle A_{mn} c_n
   \end{align*}

   Zapišemo \( A \left| \psi \right\rangle  = \left| \psi_1 \right\rangle\). Razvoj posameznih funkcij po bazi zapišemo kot

   \[ \left| \psi \right\rangle  = \sum\limits_n^{} c_n \left| n \right\rangle
   \]

   ter

   \[ \left| \psi_1 \right\rangle  = \sum\limits_n^{} d_n \left| n \right\rangle
   \]

   Torej bomo zapisali kot

   \[ A \left| \psi \right\rangle  = \sum\limits_m^{} \left( \sum\limits_n^{} A_{mn} c_n \right) \left| m \right\rangle = \left| \psi_1 \right\rangle
   \]

   Vsota \( \sum\limits_n^{} A_{mn} c_n \) predstavlja člene \( \sum\limits_m^{} d_m \). Vse skupaj lahko zapišemo v matrični obliki

   \[ \begin{pmatrix} d_{1} \\ d_{2} \\ \vdots \\ d_n \\ \vdots \end{pmatrix} = \begin{pmatrix}
                                                                               A_{11} & A_{12} & &  \\
                                                                                & \ddots & & \\
                                                                                &  & A_{nn} & \\
                                                                                &&&& \ddots
                                                                               \end{pmatrix} \begin{pmatrix} c_{1} \\ c_{2} \\ \vdots \\ c_{n} \\  \vdots \end{pmatrix}
   \]

   #+begin_my_example
        Operator gibalne količine \( A = - \mathrm{i} \hbar \frac{\partial }{\partial x}  = \hat{p} \). Baza je

        \[ \phi_n (x) = c_n \sin k_n x
        \]

        Matrični element neskončne potencialne jame bo

        \[ A_{mn} = \int\limits_{-a}^a \phi_m^{\ast} (x) \hat{p} \phi_n (x) \, \mathrm{d} x = \left\langle m \middle| A \middle| n \right\rangle
        \]

        Zapišemo razvoj po bazi

        \[ \psi(x) = \sum\limits_n^{} \alpha_n \phi_n (x)
        \]
   #+end_my_example

8. Operator je hermitski ali simetričen, če velja

   \[ \left| \phi \middle| A \middle| \psi \right\rangle  = \int\limits_{}^{} \phi^{\ast} A \psi \, \mathrm{d} x = \left| A \phi \middle| \psi \right\rangle
   \]

   za vsak vektor \( \phi, \psi \). Možen je tudi zapis \( \left\langle \psi \middle| A \middle| \psi \right\rangle  = \left\langle \psi \middle| A \psi \right\rangle\)

   Ima nekaj lepih lastnosti:
   - pričakovana vrednost

    \begin{align*}
      \left\langle \psi \middle| A \middle| \psi \right\rangle &= \left\langle A \psi \middle| \psi \right\rangle \\
       &= \left\langle \psi \middle| A \psi \right\rangle^{\ast} \\
       &= \left\langle \psi \middle| A \middle| \psi \right\rangle^{\ast}
    \end{align*}

    je realna, saj je konjugirana vrednost enaka nekonjugirani.

   - Naj bo \( a \) lastna vrednost. Potem zapišemo

     \[ A \left| a \right\rangle  = a \left| a \right\rangle
     \]

     kjer je \( \left| a \right\rangle \) lastni vektor. Nadalje to pomnožimo s funkcionalom \( \left\langle a \right| \) in dobimo

     \[ \left\langle a \middle| A \middle| a \right\rangle  = a \left\langle a \middle| a \right\rangle  \in \mathbb{R}
     \]

     Iz tega sledi, da je lastna vrednost \( a \in \mathbb{R} \) realna.

   - Imamo dve različni lastni vrednosti \( a, b \) in različna lastna vektorja \( \left| a \right\rangle \) ter \( \left| b \right\rangle \). Velja

     \[ A \left| a \right\rangle  = a \left| a \right\rangle \quad A \left| b \right\rangle = b \left| b \right\rangle
     \]

     Prvo enakost pomnožimo z lastnim vektorjem \( \left\langle b \right| \), dobimo

     \begin{align*}
       \left\langle b \middle| A \middle| a \right\rangle &= a \left\langle b \middle| a \right\rangle \\
        &= \left\langle Ab \middle| a \right\rangle \\
        &= b \left\langle b \middle| a \right\rangle \\
        &= (a - b) \left\langle b \middle| a \right\rangle = 0
     \end{align*}

     Imamo dve situaciji: če je \( a \ne b \), potem je skalarni produkt \( \left\langle b \middle| a \right\rangle  = 0\). Če pa \( a = b \), potem sta \( \left\{ \left| a \right\rangle, \left| b \right\rangle\right\} \) bazi in sledi \( \left| a_1 \right\rangle, \left| b_1 \right\rangle \)
