#+title: 1. predavanje iz Kvantne mehanike
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Uvod

Pri klasični mehaniki nas zanima trajektorija delca \( \vec{r}(t) \). Z Newtonovim zakonom lahko izpeljemo pospešek, ki je funkcija časa, kraja in hitrosti. Če poznamo začetne pogoje, lahko določimo \( \vec{r} \) kjerkoli v prihodnosti.

Potreba po kvantni mehaniki se je razvila zaradi Michelsonovega poskusa, ki je pokazal, da je hitrost svetlobe v vakuumu absolutna. Čez 1 mesec bo 100 let, odkar je Heisenberg izdal svoj članek, ki se smatra kot začetek kvantne mehanike. Pred letom 1925 so bila sledeča odkritja, ki so kazala na nekaj več od klasične mehanike

- Planck, Einstein leta 1905 razložita enačbo \( E = \hbar \omega \)
- 1923 de Broglie opazi, da je hitrost elektrona obratno sorazmerna njegovi valovni dolžini

  \[ p = \frac{2 \pi \hbar}{\lambda} = m v
  \]
  - imamo valovanje pri masnih delcih \( \cos \left( k x - \omega t \right) \) in \( p = \hbar k \)
- energija elektrona je \( E = \frac{p ^2}{2m} \)
- spektri plinov so črtasti
- zanimala jih je stabilnost in sestava atoma - ta vprašanja je omogočala nova tehnologija

  Planetni model (pozitivno jedro - sonce, elektroni - planeti) pogojno razloži spekter vodikovega atom, vendar posplošitev ni bila mogoča. Ta razlaga tudi ne more razložiti spektra vodikovega atoma v električnem polju.

Decembra 1925 Heisenberg objavi svoj članek o kvantni mehaniki. V začetku leta 1926 je Schrödinger objavil svoj članek, kjer uvede Schrödingerjevo enačbo. Želel je izpeljati relativistično invariantno enačbo, česar ni uspel (Dirac, 3 leta kasneje, glej FJOD), hkrati pa je želel, da veljajo prve tri alineje.

Osnovna Schrödingerjeva enačba v eni dimenziji brez potenciala zapišemo kot

\[ \mathrm{i} \hbar \frac{\partial \Psi}{\partial t} = - \frac{\hbar ^2}{2m} \frac{\partial ^2 }{\partial x ^2} \Psi
\]

Rešitev enačbe je valovanje \( \Psi = A e^{\mathrm{i} \left( kx - \omega t \right)} \). Ko rešitev vstavimo vanj, dobimo

\begin{align*}
  \mathrm{i} \hbar \left( - \mathrm{i} \right) \omega &= - \frac{\hbar ^2}{2m} i ^2 k ^2 \\
\hbar \omega = \frac{\hbar ^2 k ^2}{2m} &= \frac{p ^2}{2m}
\end{align*}

Opazimo v zadnji vrstici vse tri alineje.

Valovna enačba ne reši problema kvantne mehanike (vstavi \( \Psi \) vanjo). Difuzijska enačba

\[ \frac{\partial T}{\partial t} = D \frac{\partial ^2 }{\partial x ^2} T
\]

je rešena s \( T (x, t) = \cos \left( kx - \omega t \right) \). Schrödingerjeva enačba je difuzijska enačba s kompleksno enačbo.

Schrödingerjevi enačbi dodamo tudi potencial

\begin{equation}
\label{eq:1}
\mathrm{i} \hbar \frac{\partial \Psi}{\partial t}  = - \frac{\hbar ^2}{2m} \frac{\partial ^2 }{\partial x^2} \Psi + V \Psi
\end{equation}

Newtonove enačbe so bile sprejete, saj je lahko prepričljivo izpeljal elipse planetov. Schrödinger se je na podoben način lotil Keplerjevega problema s potencialom \( V \left( \vec{r}, t \right) \propto \frac{1}{r} \). Z nekaj mučenja je izpeljal spekter vodika \( E_n \propto \frac{1}{n ^2} \), s še malo več mučenja je rešil tudi problem spektra vodikovega atoma v električnem polju \( E_n \left( \vec{E}, \vec{B} \right) \).

** Valovanje

Prišli smo do tega, da ja, je valovanje, vendar nas zanima, kaj valuje. Bornova interpretacija valovne funkcije definira verjetnost, da delec detektiramo na zaprtem intervalu \( [a, b] \) preko enačbe

\begin{equation}
\label{eq:4}
 P_{ab} = \int\limits_a^b \left| \Psi(x, t) \right| ^2 \, \mathrm{d} x
\end{equation}

kjer je \( \rho (x, t) = \left| \Psi(x, t) \right| ^2\) verjetnostna gostota. Velja enakost

\[ \frac{\mathrm{d} P}{\mathrm{d} x} = \rho
\]

Pri detekciji ne dobimo nobene druge informacije kot to ali je elektron bil na intervalu ali ne. Ob neskončnem številu ponovitev dobimo našo verjetnost

\[ \lim_{n \to \infty}  \frac{N_{zaznan}}{N} = P_{ab }
\]

Mi bomo obravnavali minimalistično Kobenhavensko interpretacijo kvantne mehanike.

** Lastnosti valovne funkcije

Pišemo lastnosti valovne funkcija v eni dimenziji. Velja, da je valovna funkcija normirana

\[ \int\limits_{-\infty}^{\infty} \left| \Psi \right| ^2 \, \mathrm{d} x = 1
\]

Enačba, ki dokazuje, da nimamo izvorov, je

\begin{equation}
\label{eq:2}
 \frac{\partial \rho}{\partial t} + \nabla \cdot \vec{\jmath} = q
\end{equation}


Verjetnostno gostoto nadomestimo z definicijo in upoštevamo odvod produkta. \( \Psi^{\ast} \) je kompleksna konjugiranka valovne funkcije, ki jo dobimo s konjugiranjem Schrödingerjeve enačbe in izražavo odvoda po času.

\begin{align}\label{ali:ss}
\frac{\partial \rho}{\partial t} &= \frac{\partial \Psi^{\ast} \Psi}{\partial t} \\
&= \frac{\partial \Psi^{\ast}}{\partial t} \Psi + \frac{\partial \Psi}{\partial t} \Psi^{\ast} \\
&=- \frac{\hbar ^2}{2m} \frac{1}{-\mathrm{i} \hbar} \frac{\partial ^2 }{\partial x ^2} \Psi^{\ast} \Psi + \frac{V^{\ast}}{- \mathrm{i} \hbar} \Psi^{\ast} \Psi + C. C.
\end{align}

Odvod po kraju lahko razpišemo

\[ \frac{\partial ^2 \Psi^{\ast} }{\partial x ^2} \Psi = \frac{\partial }{\partial x}  \left( \frac{\partial \Psi^{\ast}}{\partial x} \Psi \right) - \frac{\partial \Psi^{\ast}}{\partial x}  \frac{\partial \Psi}{\partial x}
\]

Enačba \ref{ali:ss} postane

\begin{equation}
\label{eq:3}
 \frac{\partial \rho}{\partial t} = - \frac{\partial }{\partial x} \left( \frac{\hbar}{2 \mathrm{i} m }\left( \Psi^{\ast} \frac{\partial \Psi}{\partial x}  - \Psi \frac{\partial \Psi^{\ast}}{\partial x}  \right) \right) - \frac{2}{\hbar} \mathrm{Im} \left( V \left| \Psi \right| ^2 \right)
\end{equation}

Enačbo \ref{eq:2} zapišemo v eni dimenziji kot

\[ \frac{\partial \rho}{\partial t}  + \frac{\partial }{\partial x} \vec{\jmath} = q = 0
\]

Verjetnostni tok v treh dimenzijah zapišemo kot

\[ \vec{\jmath} = - \frac{\mathrm{i} \hbar}{2m} \left( \Psi^{\ast} \nabla \Psi - \Psi \nabla \Psi^{\ast} \right) = \vec{\jmath} \left( \vec{r}, t \right)
\]

Opazimo, da se verjetnostni tok pokrajša s prvim členom v enačbi \ref{eq:3} in nam tako ostane

\[ q = - \frac{2}{\hbar} \mathrm{Im} V \left| \Psi \right| ^2
\]

Za realen potencial je imaginaren del enak \( 0 \), kar pomeni, da nimamo izvorov ali ponorov, saj \( q = 0 \).

Preverimo še normiranost. Enačbo \ref{eq:4} odvajamo po času

\[ \frac{\mathrm{d} P_{ab }}{\mathrm{d} t} = - \int\limits_a^b \frac{\partial }{\partial x} j_x \, \mathrm{d} x = j_x (a) - j_x(b)
\]

Za \( a \to - \infty \) in \( b \to \infty \) bo razlika \( 0 \). Za naše valovne funkcije velja, da so del Scwarzovega prostora, torej

\[ \lim_{x \to \infty} x^n \left| \Psi \right|  = 0
\]

#+begin_my_example
Primera taka funkcije sta \( e^{- \lambda x} \) ter \( e ^{- \mu x ^2} \).
#+end_my_example
*** Zveznost

Valovna funkcija \( \Psi \) je zvezna funkcija. Odvod \( \frac{\partial \Psi}{\partial x} \) je zvezna funkcija, če je \( V \) zvezna funkcija. Drugi odvod \( \frac{\partial ^2 }{\partial x ^2} \Psi  \) je zvezna, če je \( V \) zvezna.

Pravokotna potencialna jama ima v jami kosinusno valovanje, izven jame pa potencialno pada, imamo prevoj v točki nezveznosti.

** Pričakovane vrednosti

Pričakovane vrednosti položaja izračunamo preko

\[ \left\langle x \right\rangle  = \int\limits_{- \infty}^{\infty} x \rho (x, t) \, \mathrm{d} x
\]

Predpostavimo, da imamo dve različni funkciji. Zanima nas, kako se spreminja težišče v odvisnosti od časa:

\begin{align*}
\frac{\mathrm{d} \left\langle x \right\rangle}{\mathrm{d} t} &= \int\limits_{- \infty}^{\infty} x \frac{\partial \rho}{\partial t} \, \mathrm{d} x \\
&= - \int\limits_{- \infty}^{\infty} x \frac{\partial j}{\partial x}  \, \mathrm{d} x && \text{per partes} \\
&=  \cancel{\left. x j \right|_{- \infty}^{\infty}} + \int\limits_{- \infty}^{\infty} j \, \mathrm{d} x \\
&= \int\limits_{- \infty}^{\infty} j \, \mathrm{d} x \\
&= - \frac{\mathrm{i} \hbar}{2m} \left( \int\limits_{-\infty}^{\infty} \Psi^{\ast} \frac{\partial \Psi}{\partial x}  \, \mathrm{d} x - \int\limits_{- \infty}^{\infty} \Psi \frac{\partial \Psi^{\ast}}{\partial x} \, \mathrm{d} x \right) && \text{per partes} \\
&= \frac{1}{m} \int\limits_{- \infty}^{\infty} \Psi^{\ast} \left( - \mathrm{i} \hbar \frac{\partial }{\partial x}  \right) \Psi \\
&= \frac{1}{m} \int\limits_{- \infty}^{\infty} \Psi^{\ast} \hat{p} \Psi \, \mathrm{d} x
\end{align*}

Dobimo novo zvezo in sicer pričakovano gibalno količine

\[ m \frac{\mathrm{d} \left\langle x \right\rangle}{\mathrm{d} t} = \left\langle \hat{p} \right\rangle
\]

kjer je \( \hat{p} = - \mathrm{i} \hbar \frac{\partial }{\partial x}  \) ali v treh dimenzijah \( \hat{\vec{p}} = - \mathrm{i} \hbar \nabla \).
