#+title: 3. predavanje iz Kvantne mehanike
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Formalizem kvantne mehanike

1. Hermitsko adjungiran operator

   Če velja za poljubna operatorja \( A, B \) in za vsaka vektorja \( \phi, \psi \)

   \[ \left\langle \phi \middle| A \middle| \Psi \right\rangle = \left\langle B \phi \middle| \Psi \right\rangle
   \],

   potem je \( B = A ^{\dagger} \) hermitsko adjungiran operator.

   Lastnosti operatorja so:
   - za \( z \in \mathbb{C} \) je \( A = z B \) velja

     \[ A^{\dagger} = z^{\ast} B ^{\dagger}
     \]

     Dokaz: \( z \) daš na levo (cinično).

   - za \( A = \left| m \right\rangle \left\langle n \right|\) velja

     \[ A ^{\dagger} = \left| n \right\rangle \left\langle m \right|
     \]

     Dokaz:

     \begin{align*}
        \left\langle \phi \middle| A \middle| \Psi \right\rangle  &=  \left\langle \phi \middle| m \right\rangle \left\langle n \middle| \Psi \right\rangle \\
        &= \left( \left\langle \Psi \middle| n \right\rangle \left\langle m \middle| \phi \right\rangle\right) ^{\ast} \\
        &= \left( \left\langle \Psi \middle| A \phi \right\rangle \right) ^{\ast} \\
        &= \left\langle A^{\dagger} \phi \middle| \Psi \right\rangle
     \end{align*}

   - velja

     \[ \left( \mu A + B \right)^{\dagger} = \mu^{\ast} A^{\dagger} + \lambda^{\ast} B^{\dagger}
     \]

   - velja

     \[ \left( AB \right) ^{\dagger} = B^{\dagger} A^{\dagger}
     \]

     Dokaz:

     \begin{align*}
       \left\langle \phi \middle| AB \middle| \Psi \right\rangle &= \left\langle A^{\dagger} \phi \middle| B \middle| \Psi \right\rangle \\
        &= \left\langle B^{\dagger} A^{\dagger} \phi \middle| \Psi \right\rangle
     \end{align*}

   - Kako najti hermitsko adjungiran operator \( A \)?

     \( A \) zapišemo v bazi

     \[ A = I A I = \sum\limits_{m, n}^{} \left| m \right\rangle A_{mn} \left\langle n \right|
     \]

     Hermitsko adjungiramo bazo in dobimo

     \[ A ^{\dagger} = \sum\limits_{m, n}^{} \left| n \right\rangle A_{mn}^{\ast} \left\langle n \right|
     \]

     Za ta operator velja \( \left( A^{\dagger} \right)^{\dagger} = A \)

     Za lepši zapis zamenjamo \( n \) z \( m \) in obratno. Tako se poenostavi(?) v

     \[ A^{\dagger} = \sum\limits_{m, n}^{} \left| m \right\rangle A_{nm}^{\ast} \left\langle n \right|
     \]

     kjer je \( A_{mn} \) postal \( A_{nm}^{\ast} \).

2. Sebi adjungirani operatorji so operatorji, če velja za operator \( A \)

   \[ A = A^{\dagger} \quad \mathrm{in} \quad \mathcal{D} \left( A \right) = \mathcal{D} \left( A^{\dagger} \right)
   \]

   Za \( \phi \) in \( \Psi \) \( \left\langle \phi \middle| A \middle| \Psi \right\rangle \) je enak robni pogoj, če je operator sebi adjungiran. Spektralni teorem

   \[ A \left| n \right\rangle  = a_n \left| n \right\rangle
   \]

   kjer je \( \left\{ \left| n \right\rangle \right\} \) baza v \( L ^2 \). To je izredno pomembno, saj če iščemo bazo, so tukaj lastne funkcije kar baza.

3. Unitarni operator je operator, kjer velja

   \[ U^{-1} = U^{\dagger}
   \]

   Velja \( U^{-1} U = U U^{-1} = I \) in posledično tudi \( U^{\dagger} U = U U^{\dagger} = I \).

   - Imamo vektorja \( \left| \phi \right\rangle \) in \( \left| \psi \right\rangle \). Zapišemo nov vektor

      \[ \left| \tilde{\phi} \right\rangle = U \left| \phi \right\rangle
      \]

      Zaradi definicije unitarnega operatorja velja

      \[ \left| \phi \right\rangle = U^{\dagger} \left| \tilde{\phi} \right\rangle
      \]

      Potem zapišemo

      \[ \left\langle \phi \middle| \Psi \right\rangle = \left\langle U ^{\dagger} \tilde{\phi} \middle| U^{\dagger} \tilde{\Psi} \right\rangle = \left\langle \tilde{\phi} \middle| U U^{\dagger} \middle| \tilde{\Psi} \right\rangle = \left\langle \tilde{\phi} \middle| \tilde{\Psi} \right\rangle
      \]

   - bla

     \begin{align*}
       \left\langle \phi \middle| \Psi \right\rangle &= \left\langle U^{\dagger} \tilde{\phi} \middle| A \middle| U^{\dagger} \tilde{\Psi} \right\rangle \\
        &= \left\langle \tilde{\phi} \middle| U A U ^{\dagger} \middle| \tilde{\Psi} \right\rangle \\
        &= \left\langle \tilde{\phi} \middle| \tilde{A} \middle| \tilde{\Psi} \right\rangle
     \end{align*}

     kjer je \( \tilde{A} = UA U^{\dagger} \).

   - Naj velja \( A \left| a \right\rangle  = a \left| a \right\rangle\). Potem velja, da so \( a \) tudi lastne vrednosti operatorja \( \tilde{A} \)

     \begin{align*}
       UAU^{\dagger}U \left| a \right\rangle &= a U \left| a \right\rangle \\
       \tilde{A} \left| \tilde{a} \right\rangle &= a \left| \tilde{a} \right\rangle
     \end{align*}

   - Če je \( K = K^{\dagger} \) (hermitski), potem je operator \( U \) definiran kot

     \[ U = e ^{\mathrm{i} K}
     \]

     unitaren operator.

     /Brez dokaza/.

   - Vsak enoparametrični unitarni operator ima naslednjo obliko

     \[ U(s) = e^{\mathrm{i} s K}
     \]

     kjer je \( K = K^{\dagger} \). Operatorju \( K \) rečemo generator.

4. Časovni razvoj stanja z unitarnim operatorjem

   Operator lahko razvijemo v vrsto. Za \( x \in \mathbb{C} \) lahko zapišemo

   \[ f(x) = \sum\limits_n^{} c_n x^n
   \]

   Definiramo operator \( \hat{A} \) in velja

   \[ f \left( \hat{A} \right) = \sum\limits_n^{} c_n \hat{A}^n
   \]

   Kot primer vzamemo funkcijo \( f(x) = e^x \) in operator \( \hat{A} = \frac{\partial }{\partial x}  \).  Potem je

   \[ e^{\frac{\partial }{\partial x} } = 1 + \frac{\partial }{\partial x}  + \frac{1}{2!} \frac{\partial ^2 }{\partial x ^2} + \ldots + \frac{1}{n!} \frac{\partial ^n }{\partial x ^n}
   \]

   \begin{align*}
     f \left( \hat{A} \right) \left| a_n \right\rangle &= \sum\limits_m^{} c_m \hat{A}^m \left| a_n \right\rangle \\
         \hat{A} \left| a_n \right\rangle &= a_n \left| a_n \right\rangle \\
        &= \sum\limits_m^{} c_m \left( a_n \right)^m \left| a_n \right\rangle = f \left( a_n \right) \left| a_n \right\rangle
   \end{align*}

   *Actual stuff* nimamo \( \Psi(t) \), vendar imamo začetni pogoj \( \Psi(0) \).

   Preko

   \[ H \left| \phi_n \right\rangle  = E_n \left| \phi_n \right\rangle
   \]

   potem

   \[ \left| \Psi(t) \right\rangle = \sum\limits_n^{} \left\langle \phi_n \middle| \Psi(0) \right\rangle \exp \left\{ - \mathrm{i \frac{E_n t}{\hbar}} \right\} \left| \phi_n \right\rangle
   \]

   kjer je npr. \( \phi_n (x) = C_n \sin k_n x \)

   Kakor smo zapisali višje v tej točki, lahko nadomestimo \( E_n \) z operatorjem

   \[ \left| \Psi(t) \right\rangle = \sum\limits_n^{} \left\langle \phi_n \middle| \Psi(0) \right\rangle \exp \left\{ - \mathrm{i \frac{H t}{\hbar}} \right\} \left| \phi_n \right\rangle = \exp \left\{ - \mathrm{i} \frac{H t}{\hbar} \right\} \sum\limits_n^{} \left\langle \phi_n \middle| \Psi(0) \right\rangle \left| \phi_n \right\rangle
   \]

   Ker velja komutacija pri skalarnem produktu, lahko vsoto pretvorimo v

   \[ \left| \Psi(t) \right\rangle = \exp \left\{ - \mathrm{i} \frac{Ht}{\hbar} \right\} \sum\limits_n^{} \left| \phi_n \right\rangle \left\langle \phi_n \right| \left| \Psi(0) \right\rangle
   \]

   Nadalje \( \left| \phi_n \right\rangle \left\langle \phi_n \right| = I \) in dobimo zapis

   \[ \left| \Psi(t) \right\rangle  = \exp \left\{ - \mathrm{i} \frac{Ht}{\hbar} \right\} \left| \Psi(0) \right\rangle
   \]

   Dobimo časovni razvoj

   \[ U(t) = \exp \left\{ - \mathrm{i} \frac{Ht}{\hbar} \right\}
   \]

5. Reprezentacija \( p \) in \( x \) (ang. /x- or p-representation/)

   Spomnimo se Fourierovega integrala

   \begin{equation}
   \label{eq:1}
    f(x) = \int\limits_{-\infty}^{\infty} \tilde{f} \left( k \right) e^{\mathrm{i} k x} \, \mathrm{d} k
   \end{equation}

   Za dovolj pohlevne funkcije predpostavimo obstoj inverza

   \[ \tilde{f}(k) = \frac{1}{2\pi} \int\limits_{-\infty}^{\infty} f(x') e^{- \mathrm{i} k x'} \, \mathrm{d} x'
   \]

   V enačbo \ref{eq:1} vstavimo definicijo inverz in zamenjamo vrstni red integriranja

   \begin{equation}
   \label{eq:2}
   f(x) = \int\limits_{-\infty}^{\infty} \left( \frac{1}{2\pi} \int\limits_{- \infty}^{\infty} e^{- \mathrm{i} k \left( x' - x \right)} \, \mathrm{d} k \right) f(x') \, \mathrm{d} x'
   \end{equation}

   Po stopinjah Diraca, uvedemo objekt

   \[ \frac{1}{2\pi} \int\limits_{-\infty}^{\infty} e^{- \mathrm{i}k \left( x' - x \right) } \, \mathrm{d} k = \delta (x ' - x)
   \]

   kot Diracovo delta funkcijo.

   Enačbo \ref{eq:2} z novo definicijo zapišemo

   \[ f(x) = \int\limits_{-\infty}^{\infty} \delta \left( x' - x \right) f(x') \, \mathrm{d} x'
   \]

   Vzemimo kot primer prost delec s potencialom \( V(x) = 0 \). Zanimata nas energija \( H = \frac{p ^2}{2m} \) in lastna funkcija energije

   \[ p \left| \phi_{p_0} \right\rangle = p_0 \left| \phi_{p_0} \right\rangle, \quad p_0 \in \mathbb{R}
   \]

   kjer je \( p \) operator in \( p_0 \) lastna vrednost. Upoštevamo definicijo operatorja gibalne količine

   \[ - \mathrm{i} \hbar \frac{\partial }{\partial x}  \phi_{p_0} (x) = p_0 \phi_{p_0} (x)
   \]

   katere rešitev je

   \[ \phi_{p_0} = C e^{\mathrm{i} \frac{p_0}{\hbar} x}
   \]

   in velja \( \left| \phi_{p_0} \right| ^2 = \left| C \right| ^2\). Funkcija torej ni normirana in se, I guess, ne da integrirati. Težavo lahko rešimo s Fourierovo transformacijo. Definiramo \( C = \frac{1}{\sqrt{2 \pi \hbar}} \). Faktor \( 2\pi \) smo uporabili zaradi definicije delta funkcije, medtem ko je valovni vektor definiran \( k = \frac{p}{\hbar} \). Hkrati pa za delta funkcijo velja \( \delta(ax) = \frac{1}{\left| a \right|} \delta(x) \). Rešitev se preobrazi v

   \begin{equation}
   \label{eq:3}
   \phi_{p_0} (x) = \frac{1}{\sqrt{2\pi\hbar}} e^{\mathrm{i} \frac{p_0 x}{\hbar}}
   \end{equation}

   Velja

   \begin{equation}
   \label{eq:4}
    \int\limits_{}^{}\phi_{p_0} ^{\ast} (x) \phi_p (x) \, \mathrm{d} x = \delta \left( p_0 - p \right)
   \end{equation}

   Delujemo z operatorjem \( \hat{p} \) na \( \Psi(x) \), ki ga zapišemo s Fourierovim integralom:

   \[ \hat{p} \Psi(x) = - \mathrm{i} \hbar \frac{\partial }{\partial x}  \Psi(x) = \int\limits_{}^{} \tilde{\Psi} (p) \left( - \mathrm{i} \hbar \frac{\partial }{\partial x}  \phi_p (x) \right) \, \mathrm{d} p
   \]

   *Note*:  Fourierovo transformacijo bomo pisali oblike

   \[ \Psi(x) = \frac{1}{\sqrt{2\pi\hbar}} \int\limits_{-\infty}^{\infty} \tilde{\Psi} (p) e^{\mathrm{i} \frac{p x}{\hbar}} \, \mathrm{d} p,  \quad \text{in}\quad \tilde{\Psi}(p) = \frac{1}{\sqrt{2\pi\hbar}} \int\limits_{-\infty}^{\infty} \Psi(x) e^{- \mathrm{i} \frac{px}{\hbar}} \, \mathrm{d} x
   \]

   Poudarek na ulomke pred integrali. Zaradi definicije \ref{eq:3} zapišemo

   \begin{align*}
     \Psi(x) &= 1 \int\limits_{-\infty}^{\infty} \tilde{\Psi}(p) \phi_p (x) \, \mathrm{d} p \\
        \tilde{\Psi} (p) &= 1 \int\limits_{-\infty}^{\infty} \Psi(x) \phi_p^{\ast} (x) \, \mathrm{d} p
   \end{align*}

   Koeficient v razvoju dobimo z integriranjem produkta funkcije in operatorja.

   Nadaljujemo naprej s \( \hat{p} \Psi(x) \). Odvod \( - \mathrm{i} \hbar \frac{\partial }{\partial x} \phi_p (x) \) nam bo zaradi definicije podal integral

   \[ \hat{p} \Psi(x) = \int\limits_{}^{} p \p \tilde{\Psi} (p) \phi_p (x) \, \mathrm{d} p
   \]

   Iz tega sledi

   \[ \hat{p}^n \Psi(x) = \int\limits_{}^{}p^n \tilde{\Psi}(p) \phi_p (x) \, \mathrm{d} p
   \]

   Poglejmo si še primer, ko množimo valovno funkcijo \( \Psi(x) \) z \( x \). Dobimo

   \begin{align*}
        x \Psi(x) &= \int\limits_{}^{} \vec{\Psi}(p) x \phi_p (x) \, \mathrm{d} p \\
        &= \int\limits_{}^{} \tilde{\Psi}(p) \left( - \mathrm{i} \hbar \frac{\partial }{\partial p} \phi_p (x) \right) \, \mathrm{d} p \\
        &= \int\limits_{}^{} \left( \mathrm{i} \hbar \frac{\partial }{\partial p}  \tilde{\Psi}(p) \right) \phi_p (x) \, \mathrm{d} p
   \end{align*}

   Tako dobimo relacijo

   \[ x \Psi(x) \iff \mathrm{i} \hbar \frac{\partial }{\partial p}  \tilde{\Psi}(p)
   \]

   Prav tako velja

   \[ x^n \Psi(x) \iff \left( \mathrm{i} \hbar \frac{\partial }{\partial p}  \right)^n \tilde{\Psi}(p)
   \]

   Ta formalizem nam omogoči obravnavo in normiranost funkcij, ki niso iz \( L ^2 \).

6. Verjetnostna amplituda \( \left\langle x \middle| \Psi \right\rangle \) in \( \left\langle p \middle| \Psi \right\rangle \)

   Naj bo funkcijo \( \Psi(x, t) \in L ^2  \)

   Enačbo

   \[ \left| \Psi \right\rangle = \int\limits_{}^{} \tilde{\Psi} (p) \left| p \right\rangle \, \mathrm{d} p
   \]

   kjer je \( \left| p \right\rangle \) oz. \( \frac{1}{\sqrt{2\pi\hbar}} e^{\mathrm{i} \frac{px}{\hbar}} \), pomnožimo s \( \left\langle p_1 \right| \), zapišemo

   \[ \left\langle p_1 \middle| \Psi \right\rangle  = \int\limits_{}^{} \tilde{\Psi}(p) \left\langle p_1 \middle| p_0 \right\rangle \, \mathrm{d} p = \tilde{\Psi} (p_1)
   \]

   kjer smo uporabili \ref{eq:4} in velja \( \left\langle p_0 \middle| p \right\rangle  = \delta \left( p_0 - p \right)\)

   #+begin_note
   Sledeče spada pod točko 13, ampak oh, well.

   Povedali smo, kaj je

   \[ \hat{p} \phi_{p_0} (x) = p_0 \phi_{p_0} (x)
   \]

   Zanima pa nas, kaj je v tem primeru operator \( \hat{x} \).


   \[ \hat{x} \Psi_0 (x) = x_0 \Psi_0 (x) = x \Psi(x)
   \]

   Funkcijo \( \Psi_0 \) razvijemo po Fourieru in jo lahko zapišemo kot

   \[ \hat{x} \Psi_0 (x) = x \int\limits_{}^{} \tilde{\Psi}_0 (p) \phi_p (x) \, \mathrm{d} p
   \]

   Hkrati pa vemo od prej, da mora biti množenje z \( x \) enak odvodu po \( p \), torej

   \[ x \int\limits_{}^{} \tilde{\Psi}_0 (p) \phi_p (x) \, \mathrm{d} p = \int\limits_{}^{} \left( \mathrm{i} \hbar \frac{\partial }{\partial p}  \tilde{\Psi}_0 (p) \right) \phi_p (x) \, \mathrm{d} p = x_0 \int\limits_{}^{} \tilde{\Psi}_0 (p) \phi_p (x) \, \mathrm{d} p
   \]

   Sedaj smo vzpostavili identiteto

   \[ \mathrm{i} \hbar \frac{\partial }{\partial p}  \tilde{\Psi}_0 (p) = x_0 \tilde{\Psi}_0 (p)
   \]

   ki nam poda

   \[ \frac{1}{\sqrt{2 \pi \hbar}} e^{-\mathrm{i} \frac{p x_0}{ \hbar} } = \phi^{\ast}_p (x_0)
   \]

   Tako sledi, da lahko zapišemo

   \[ \Psi_0 (x) = \int\limits_{}^{} \phi^{\ast}_p (x_0) \phi_p (x) \, \mathrm{d} p = \delta (x_0 - x) = \left| x_0 \right\rangle
   \]

   To je lastni
   #+end_note

   Poljuben vektor razvijemo po lastnih stanjih gibalne količine

   \[ \left| \Psi \right\rangle  = \int\limits_{}^{} \tilde{\Psi}(p) \left| p \right\rangle \, \mathrm{d} p
   \]

   Pomnožimo ga z lastno funkcijo \( x \) \( \left\langle x_0 \right| \)

   \[ \left\langle x_0 \middle| \Psi \right\rangle = \int\limits_{}^{} \tilde{\Psi}(p) \left\langle x_0 \middle| p \right\rangle \, \mathrm{d} p
   \]

   Iz prej izpeljanih stvari vidimo, da je

   \begin{align*}
     \left\langle x_0 \middle| p \right\rangle &= \int\limits_{}^{} \delta (x_0 - x) \frac{1}{\sqrt{2 \pi \hbar}} e^{\mathrm{i} \frac{px}{\hbar}} \, \mathrm{d} x \\
        &= \frac{1}{\sqrt{2\pi \hbar}} e^{\mathrm{i} \frac{px_0}{\hbar}}
   \end{align*}

   Identiteto upoštevamo v integralu, dobimo

   \[ \left\langle x_0 \middle| \Psi \right\rangle  = \int\limits_{}^{} \tilde{\Psi} (p) \frac{1}{\sqrt{2 \pi \hbar}} e^{\mathrm{i} \frac{p x_0}{\hbar}} \, \mathrm{d} p = \Psi(x_0)
   \]

   Torej to velja

   \begin{align*}
     \left\langle x \middle| \Psi \right\rangle &= \Psi(x) \\
        \left\langle p \middle| \Psi \right\rangle &= \tilde{\Psi}(p)
   \end{align*}

   Z upoštevanjem komutacije skalarnega produkta lahko preko zgornje zveze torej zapišemo

   \begin{align*}
        \left| \Psi \right\rangle &= \int\limits_{}^{} \Psi(x) \left| x \right\rangle \, \mathrm{d} x \\
        &= \int\limits_{}^{} \left\langle x \middle| \Psi \right\rangle \left| x \right\rangle \, \mathrm{d} x \\
        &= \left( \int\limits_{}^{} \left| x \right\rangle \left\langle x \right|\right) \, \mathrm{d} x \left| \Psi \right\rangle \\
        &= \left( \int\limits_{}^{} \left| p \right\rangle \left\langle p \right|\right) \, \mathrm{d} p \left| \Psi \right\rangle
   \end{align*}

   saj je skalarni produkt v oklepajih enak identiteti.
