#+title: 1. vaje iz Matematične fizike 2
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Teorija: PDE 1. reda

Rešujemo PDE 1. reda oblike

\[ a(x, y, u) \frac{\partial u}{\partial x}  + b (x, y, u) \frac{\partial u}{\partial y}  &= \phi (x, y, u)
\]

Enačbo rešujemo preko karakteristike (grafično jih predstavimo s črtami) z uvedbo novih spremenljivk \( x(s) \) in \( y(s) \). Parcialno odvajanje

\[ \frac{\partial u}{\partial s} = \frac{\partial u}{\partial x}  \frac{\mathrm{d} x}{\mathrm{d} s} + \frac{\partial u}{\partial y} \frac{\mathrm{d} y}{\mathrm{d} s}
\]

Izberemo, da velja

\begin{align*}
  \frac{\mathrm{d} x}{\mathrm{d} s} &= a(x, y, u) \\
\frac{\mathrm{d} y}{\mathrm{d} s} &= b(x, y, u)
\end{align*}

kar nam da še tretjo ODE

\[ \frac{\partial u}{\partial s}  = \phi(x, y, u)
\]
* 1. naloga

#+begin_my_example
Rešujemo Burgersevo enačbo

\[ \frac{\partial \rho}{\partial t}  + \rho \frac{\partial \rho}{\partial x}  = 0
\]

z začetnimi pogoji

\[ \rho (x, t = 0) = \begin{cases}
                       a ^2 - x ^2; & \left| x \right| \le a \\
                       0; & \left| x \right| > a
                     \end{cases}
\]
#+end_my_example

Kakor v teoriji, dobimo 3 ODE

\begin{align*}
  \frac{\mathrm{d} t}{\mathrm{d} s} &= 1 \\
\frac{\mathrm{d} x}{\mathrm{d} s} &= \rho \\
\frac{\mathrm{d} \rho}{\mathrm{d} s} &= 0
\end{align*}

Iz zadnje enačbe sledi, da je \( \rho(s) = \mathrm{konst} \). Iz prve enačbe po integraciji sledi

\begin{equation}
\label{eq:1}
 t(s) = s + C
\end{equation}

in ob predpostavki \( t(0) = 0 \) sledi, da je \( C = 0 \). Po integraciji druge enačbe dobimo

\begin{equation}
\label{eq:2}
 x(s) = \int\limits_{}^{} \rho(x, t) \, \mathrm{d} s = \rho(x, t) s + D
\end{equation}

kjer smo upoštevali, da je \( \rho(x, t) = \mathrm{konst} \). Zaradi enačbe \ref{eq:1} lahko zapišemo \ref{eq:2} kot

\[ x(s) = \rho(x, t) t + x_0
\]

kjer smo označili \( x(0)= x_0 = D \).

Naša enačba karakteristike bo

\[ x (t) = \rho(x_0, 0) t + x_0
\]

[glej skico karakteristik v [[https://matevzprincic.splet.arnes.si/files/2023/11/mafija2_latex_vaje.pdf][Prinčičevih zapiskih, stran 3]]]

Sedaj iščemo karakteristiko, ki reši našo enačbo, z upoštevanjem IC:

\begin{align*}
  x &= \rho(x_0, 0) t + x_0 \\
&= \left( a ^2 - x_0 ^2 \right)t + x_0 \\
&= a ^2 t - x_0 ^2 + x_0
\end{align*}

iz česar sledi

\[ x_0 = \frac{1 \pm \sqrt{1 - 4t \left( x - a ^2 t \right)}}{2t}
\]

Predznak bomo izbrali tako, da bomo pogledali predznak v določeni točki, ki jo poznamo. Poznamo \( x_0 = 0 \) pri \( x = 0 \) in \( t = 0 \) (glej skico karakteristik).

\[ x_0 = \lim_{t \to 0} \frac{1 \pm \sqrt{1 - 4 t (0 - a ^2 t)}}{2t} = \begin{cases}
                                                                        \infty; & + \\
                                                                        0; & -
                                                                       \end{cases}
\]

kjer smo pri limiti za negativen predznak uporabili L'Hopitalovo pravilo.

To nam poda rešitev

\[ \rho(x, t) = \rho \left( x_0(x, t), t = 0 \right) = a ^2 - \left( \frac{1 - \sqrt{1 - 4t \left( x - a ^2 t \right)}}{2t} \right) ^2
\]

(I guess, da smo to enakost dobili iz IC, ob upoštevanju vrednosti \( x_0 \))
* 2. naloga (reši doma)

#+begin_my_example
Rešujemo PDE 1. reda oblike

\[ (x - y) \frac{\partial u}{\partial x}  + \frac{\partial u}{\partial y}  = x
\]

z začetnimi pogoji \( u(x, y = 0) = f(x) \).
#+end_my_example

Rešitev, ki jo dobimo je,

\[ u(x, y) = f(1 + (x - y - 1) e^{-y}) + y + \frac{1}{2} y ^2 + (x - y - 1) \left( 1 - e^{-y} \right)
\]
* Enačba strune

Enačba strune je podana z enačbama

\begin{align*}
  \mu \frac{\partial ^2 x }{\partial t ^2} &= \frac{\partial }{\partial s}  \left( F(s) \frac{\partial x}{\partial s}  \right) + f_x   \\
  \mu \frac{\partial ^2 y}{\partial t ^2} &= \frac{\partial }{\partial s}  \left( F(s) \frac{\partial y}{\partial s}  \right) + f_y   \\
\end{align*}

kjer je \( \mu= \frac{\mathrm{d} m}{\mathrm{d} s} \) in \( f_{\alpha} = \frac{\mathrm{d} F_{sum, \alpha}}{\mathrm{d} s} \). Neraztegljivost podamo s pogojem

\[ \mathrm{d} s ^2 = \mathrm{d} ^2 x + \mathrm{d} ^2 y
\]
* 3. naloga: Viseči most

#+begin_my_example
Izračunaj obliko visečega mostu z maso \( M \) in dolžino vrvice \( L \), ki med dvema palicama z višinama \( y_1 \) in \( y_2 \) pokrije razdaljo \( l \).
#+end_my_example

Velja \( \frac{\partial y}{\partial t} = \frac{\partial x}{\partial t}  = 0 \). Najprej si pogledamo v \( x \) smeri, kjer velja

\[ \frac{\partial }{\partial s}  \left( F(s) \frac{\partial x}{\partial s}  \right) = - f_x = 0
\]

oziroma po integraciji

\[ F(s) \frac{\partial x}{\partial s}  = \mathrm{konst} = F_0
\]

V \( y \) smeri pa imamo

\[ \frac{\partial }{\partial s} \left( F(s) \frac{\partial y}{\partial s}  \right) = - f_y
\]

Zunanjo silo zapišemo kot

\[ \mathrm{d} F_{zun}  = \frac{Mg}{l} \mathrm{d} x
\]
 in jo prepišemo v

 \[ f_y = - \frac{Mg}{l} \frac{\mathrm{d} x}{\mathrm{d} s}
 \]

 Torej rešujemo

 \begin{align*}
   \frac{\partial }{\partial s} \left( F(s) \frac{\partial y}{\partial s}  \right) &= \frac{M g}{l} \frac{\mathrm{d} x}{\mathrm{d} s} \\
\frac{\partial s}{\partial x} \left( \frac{F_0}{\frac{\partial x}{\partial s}} \cdot \frac{\partial y}{\partial s}  \right) &= \frac{Mg}{l} \frac{\mathrm{d} x}{\mathrm{d} s}\\
\frac{\partial }{\partial s}  \left( F_0 \frac{\partial y}{\partial x}   \right) &= \frac{Mg}{l} \frac{\mathrm{d} x}{\mathrm{d} s}
 \end{align*}

 Kjer smo upoštevali definicijo \( F_0 \) in da se (nematematično) diferenciali v ulomkih (ds) pokrajšajo. Zaradi verižnega pravila velja

 \[ F_0 \frac{\partial x}{\partial s} \frac{\partial ^2 y}{\partial ^2 x} = \frac{Mg}{l} \frac{\partial x}{\partial s}
 \]

 saj

 \[ \frac{\partial }{\partial s}  \left( \frac{\partial y}{\partial x}  \right) = \frac{\partial }{\partial x}  \left( \frac{\partial y}{\partial x}  \right) \frac{\partial x}{\partial s}  = \frac{\partial ^2 y }{\partial x ^2} \frac{\partial x}{\partial s}
 \]

 Nadalje

 \begin{align*}
   \frac{\partial ^2 y }{\partial x ^2} &= \frac{Mg}{l F_0} \\
\frac{\partial y}{\partial x}  = \frac{Mg}{l F_0} + C_1
 \end{align*}

 in na koncu

 \[ y(x) = \frac{Mg}{l F_0} \frac{x ^2}{2} + C_1 x + C_2
 \]

 Ob upoštevanju začetnih pogojev:

 - \( y(0) = y_1 \)

   \[ y(0) = \frac{Mg}{lF_0} \cdot + C_1 \cdot 0 + C_2
   \]

 - \( y(l) = y_2 \)

   \[ y_2 = \frac{Mg l}{2F_0} + C_1 l + y_1
   \]

   in tako

   \[ C_1 = \frac{1}{l} \left( y_2 - y_1 - \frac{Mgl}{2 F_0} \right)
   \]

 - \[ L = \int\limits_{}^{} \, \mathrm{d} s = \int\limits_{}^{} \sqrt{ \mathrm{d} x ^2 + \mathrm{d} ^2 y} = \int\limits_{}^{} \sqrt{1 + \left( \frac{\mathrm{d} y}{\mathrm{d} x} \right) ^2 } \, \mathrm{d} x
   \]


** Struna s težo

V primeru, da vrv ni brezmasna, je zunanja sila enaka

\[ f_y = - \mu g
\]

in nadalje

\[ \frac{\partial }{\partial s}  \left( F_0 \frac{\partial y}{\partial x}  \right) = \mu g
\]

Ko razpišemo, pa dobimo

\[ F_0 \frac{\mathrm{d} y}{\mathrm{d} x} = \mu g s + C
\]

in po reševanju integrala dobimo

\[ y = \mathrm{cosh}  \left( \frac{a}{x} \right), \quad a = \frac{F_0}{\mu g}
\]

Glej Wikipedia - catenary.
* 4. naloga: Viseča struna

#+begin_my_example
Imamo visečo struno z majhnimi odmiki v \( y \) smeri. To pomeni, da

\[ \mathrm{d} ^2 = \mathrm{d} x ^2 + \mathrm{d} y ^2 \approx \mathrm{d} x ^2
\]

oziroma \( x = s \).
#+end_my_example

V smeri \( x \) velja

\[ \frac{\partial x}{\partial t}  = 0
\]

iz česar sledi

\[ \partial_s F (s) = - f_x = \frac{\mathrm{d} F_{zun, x}}{\mathrm{d} x} =  - \mu g
\]

saj

\[ F_{zun, x} = \mu g
\]

oziroma diferencialno zapisano

\[ \mathrm{d} F_{zun, x} = \mu g \mathrm{d} x
\]

Torej je zunanja sila enaka

\[ F(x) = - \mu g x + F_0
\]

Določimo

\[ mg = F(0) = F_0
\]

in tako zapišemo zunanjo silo kot

\begin{equation}
\label{eq:3}
 F(x) = \mu g \left( l - x \right)
\end{equation}

V \( y \) smeri pa nimamo zunanjih sil in je \( f_y = 0 \). Z upoštevanjem \ref{eq:3} preobrazimo našo enačbo strune

\[ \mu \frac{\partial ^2 y}{\partial t ^2} = \frac{\partial }{\partial x} \left( F(x) \frac{\partial y}{\partial x}  \right) + f_y
\]

v

\[ \frac{\partial ^2 y }{\partial t ^2} = g \left[ \left( l - x \right) \frac{\partial y ^2}{\partial x ^2} - \frac{\partial y}{\partial x}  \right]
\]
