#+title: 6. vaje iz Matematične fizike 2
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Naloga 17 (Prinčič 4.5)

#+begin_problem
Iščemo stacionarno porazdelitev temperature v polneskončni cevi. Voda teče v \( z \)-smeri s hitrostjo \( \vec{v}_0 \). Podano imam temperaturo plašča \( \left. T \right|_{u = r_0} = T_0 \) ter temperaturo osnovne plošče \( \left. T \right|_{z = 0} = T_1 (r) \).
#+end_problem

Rešujemo difuzijsko enačbo

\[ \frac{\mathrm{d} T}{\mathrm{d} t} = D \nabla ^2 T,
\]

vendar se zaradi premikajoče se snovi temperatura premika s snovjo. To težavo nam reši substancialni odvod

\[ \frac{\mathrm{D} }{\mathrm{D} t} = \frac{\partial }{\partial t}  + \left( \vec{v} \cdot \nabla \right) T.
\]

Sledeče je bilo izpeljano pri mafiji in bo izpeljano pri Mehaniki kontinuumov. Hitrost v smeri \( z \) zapišemo kot \( \vec{v} = v \hat{e}_z \). Iščemo stacionarno rešitev, torej bo enačba, ki jo rešujemo oblike

\[ \left( v \hat{e}_z \cdot \nabla \right) T = v \frac{\partial T}{\partial z} = \left[ \frac{1}{r} \frac{\partial }{\partial r} \left( r \frac{\partial T}{\partial r}  \right)+ \frac{\partial ^2 T}{\partial z ^2}   \right]D,
\]

kjer smo upoštevali Laplaceovo operator v cilindričnih koordinatah. Enačbo rešujemo s pomočjo separacije spremenljivke. Zakaj to deluje na polneskončnem primeru, bomo povedali kasneje. S \( T(r, z) = R(r) Z(z) \) difuzijska enačba postane

\[ \frac{v}{D} \frac{Z '}{Z} - \frac{Z''}{Z} = \frac{R' + r R''}{r R} = - \lambda
\]

Reševanje \( z \) dela delamo z nastavkom \( Z = e^{kz} \), saj imamo LDE s konstantnimi koeficienti. Dobimo kvadratno enačbo

\[ k ^2 - \frac{v}{D} k - \lambda = 0,
\]

katere rešitve so

\[ k_{1, 2} = \frac{\frac{v}{D} \pm \sqrt{\frac{v ^2}{D ^2} + 4 \lambda}}{2}.
\]

Splošna rešitev je tako

\begin{equation}
\label{eq:2}
 Z(z) = A e^{k_1 z} + B e^{k_2 z}.
\end{equation}

Za radialni del rešujemo enačbo

\[ r R'' + R' + \lambda r R = 0,
\]

ki jo pomnožimo z \( r \) ter uvedemo spremenljivko \( \tilde{r} = \sqrt{\lambda} r \), da dobimo Besselovo diferencialno enačbo

\[ \tilde{r} ^2 \frac{\mathrm{d} ^2 R}{\mathrm{d} \tilde{r} ^2} + \tilde{r} \frac{\mathrm{d} R}{\mathrm{d} \tilde{r}} + \tilde{r} ^2 R = 0
\]

Za \( n = 0 \) so so tako splošne rešitve

\begin{equation}
\label{eq:1}
 R(r) =  AJ_0 \left( \sqrt{\lambda} r \right) + B Y_0 \left( \sqrt{\lambda} r \right)
\end{equation}

Iz robnega pogoja \( \left. T \right|_{r = r_0} = T_0 \) z uvedbo nastavka \( T(r, z) = R(r) Z(z) + T_0 \) dobimo homogen robni pogoj \( R(r_0) = 0 \). Ker \( Y_0 \) divergirajo v izhodišču, naše rešitev pa ne, bo \( B = 0 \).

Homogen robni pogoj pa nam poda zvezo za ničle

\[ A J_0 \left( \sqrt{\lambda} r_0 \right) = 0 \implies \ \sqrt{\lambda_{1}} r_0 = \xi_n^{(0)}, \ n = 1, 2, \ldots
\]

Pri enačbi \ref{eq:2} zavržemo prvi člen, saj člen divergira v neskončnosti, medtem ko naša temperatura pa ne.

Naš ne-še-čisto-točen nastavek je

\[ T(r, z) = \sum\limits_{n = 1}^{\infty} B_n \exp \left\{ \frac{v}{D} - \sqrt{\frac{v ^2}{D ^2}  + 4 \lambda} z \right\} J_0 \left( \frac{\xi_n^{(0)}}{r_0} r \right) + T_0
\]

Upoštevamo še drugi robni pogoj \( \left. T \right|_{z = 0} = T_1 (r) \), da dobimo enačbo

\begin{equation}
\label{eq:3}
 T(r, z = 0) = \sum\limits_{n = 1}^{\infty} B_0 J_0 \left( \frac{\xi_n^{(0)}}{r_0} r \right) + T_0 = T_1 (r)
\end{equation}

Besselove funkcije \( J_0 \left( \xi_n ^{(0)} \frac{r}{r_0} \right) \) tvorijo KOS (kompletni ortogonalni sistem) v \( L_w ^2 \left( [0, r_0] \right) \). V cilindričnih koordinatah imamo tako utež \( w = r \mathrm{d} r \) in skalarni produkt je definiran kot

\[ \left\langle f, g \right\rangle  = \int\limits_0^{ r_0} r f(r) g(r) \, \mathrm{d} r
\]

Prav tako velja identiteta

\[ \left\lVert J_0 \left( \xi_n ^{(0)} \frac{r}{r_0} \right) \right\rVert ^2 = \frac{r_0 ^2}{2} J_1 ^2 \left( \xi^{(0)}_n \right)
\]

Enačbo \ref{eq:3} rešimo z integriranjem v mejah od \( [0, r_0] \)

\[ \int\limits_0^{r_0} \left( T_1 (r) - T_0 \right) r J_0 \left( \xi_n ^{(0)} \frac{r}{r_0} \right) \, \mathrm{d} r = \left( \frac{2}{r_0 ^2 J_1 ^2 \left( \xi_m^{(0)} \right)} \right)^{-1} B_m,
\]

iz česar sledi

\[ B_m = \frac{2}{r_0 ^2 J_1 ^2 (\xi_m)} \int\limits_0^{r_0} \left( T_1 (r) - T_0 \right) r J_0 \left( \frac{\xi_m}{r_0} r \right) \, \mathrm{d} r
\]

Ker imamo stacionarno rešitev, lahko drug robni pogoj izrazimo z vrsto, namesto da postopamo po poteh homogenizacije.
* Teorija Greenove funkcije

Imamo nehomogeno difuzijsko enačbo

\[ \left( \frac{\partial }{\partial t}  - D \nabla ^2 \right) T \left( \vec{r}, t \right) = f \left( \vec{x}, t \right),
\]

z začetnim pogojem \( T \left( \vec{x}, t = 0 \right) \).

Za \( x \in \mathbb{R} ^n \) in \( t \in [0, \infty) \) bo nehomogena diferencialna enačba oblike

\[ \left( \frac{\partial }{\partial t} - D \nabla ^2 \right) G \left( \vec{x}, \vec{x} \, ', t, t' \right) = \delta^{(n)} \left( \vec{x} - \vec{x}\, ' \right) \delta (t - t').
\]

Nehomogenost v tem primeru je Greenova funkcija, ki je

\begin{equation}
\label{eq:4}
 G \left( \vec{x}, \vec{x}\, ', t , t' \right) = \frac{1}{\sqrt{4 \pi D (t - t')}^n} \exp \left\{ - \frac{\left( \vec{x} - \vec{x}\, ' \right) ^2}{4 D (t- t')} \right\} \Theta (t - t').
\end{equation}


Rešitev difuzijske enačbe je

\[ T \left( \vec{x}, t \right) = \int\limits_{\mathbb{R} ^n}^{} T \left( \vec{x}, 0 \right) G \left( \vec{x}, \vec{x} \, ', t , t' \right) \, \mathrm{d} ^n \vec{x} \, ' + \int\limits_{- \infty}^{\infty} \int\limits_{\mathbb{R} ^n}^{} f \left( \vec{x} \, ', t' \right) G \left( \vec{x} \, ', \vec{x}, t, t' \right) \, \mathrm{d} ^n \vec{x} \, ' \mathrm{d} t'
\]

Prva rešitev je homogena, druga pa partikularna.

* Naloga 18 (Prinčič, 4.4)

#+begin_problem
Segrevamo palico. Funkcija, ki opisuje gretje, je

\[ f \left( \vec{x}, t \right) = f \delta(x) \theta(t)
\]
#+end_problem

Rešujemo integral

\[ T \left( \vec{x}, t \right) = \int\limits_{- \infty}^{\infty} \int\limits_{- \infty}^{\infty} f \delta(x) \theta(t) G \left( x, x', t, t' \right) \, \mathrm{d} x' \mathrm{d} t' .
\]

Uporabimo definicijo Greenove funkcije \ref{eq:4} in se integral pretvori v

\[ T \left( \vec{x}, t \right) = \int\limits_{- \infty}^{\infty} \int\limits_{- \infty}^{\infty} f \delta(x') \theta(t') \frac{1}{\sqrt{4 \pi  D(t - t')}} \exp \left\{ - \frac{\left( x - x' \right) ^2}{4 D (t - t')} \right\} \theta(t - t') \, \mathrm{d} x ' \mathrm{d} t'
\]

Integriramo po \( x' \) in nam preostane zgolj

\[ T \left( \vec{x}, t \right) = \int\limits_{- \infty}^{\infty} f \theta(t') \frac{1}{\sqrt{4 \pi D(t - t')}} \exp \left\{ -\frac{x ^2}{4 D (t - t')} \right\} \theta(t - t') \, \mathrm{d} t'
\]

Prva \( \theta(t') \) in druga \( \theta (t' - t) \) nam spremenita meje iz \( (- \infty, \infty) \) v \( (0, t) \)

Integral nas spomni na /error function/

\[ \mathrm{erf} = \frac{2}{\sqrt{\pi}} \int\limits_0^x e^{- t ^2} \, \mathrm{d} t
\]

V integralu tako uvedemo novo spremenljivko

\[ u ^2 = \frac{x ^2}{4 D (t - t')} \implies \, u = \frac{\left| x \right|}{\sqrt{4 D(t - t')}},
\]

kjer smo dali absolutno vrednost zaradi simetrije rešitve. Diferencial nove spremenljivke je

\[ \mathrm{d} u = \frac{2 D \left| x \right|}{4 D (t - t')^{\frac{3}{2}}} \, \mathrm{d} t'
\]

Integral je tako

\[ \int\limits_0^t f \frac{1}{\sqrt{4 \pi D (t - t')}} \exp \left\{ - \frac{x ^2}{4 D (t - t')} \right\} \, \mathrm{d} t' = \frac{1}{\sqrt{\pi}} \int\limits_{\frac{\left| x \right|}{\sqrt{4 D t}}}^{\infty} f \frac{\left| x \right|}{2 D u ^2} e^{- u ^2} \, \mathrm{d} u
\]

Slednji integral rešimo s +samomorom+ per partesom, kjer \( \mathrm{d} u = \frac{1}{z ^2} \, \mathrm{d} z \) in \( v = \exp \left\{ - z ^2 \right\} \).

Rešitev integrala je

\[ \int\limits_a^{\infty} \frac{1}{z ^2} e^{- z ^2} \, \mathrm{d} z = \frac{e^{- a ^2}}{a} + \sqrt{\pi} \left( \mathrm{erf} (a) - 1 \right)
\]

Rešitev toplotne enačbe je tako

\[ T \left( \vec{x}, t \right) = \frac{1}{\sqrt{\pi}} f \frac{\left| x \right|}{2 D} \left( \frac{\exp \left\{ - \frac{x ^2}{4 D t} \right\} \sqrt{4 D t}}{\left| x \right|} + \sqrt{\pi} \left( \mathrm{erf} \left( \frac{\left| x \right|}{\sqrt{4 D t}} \right) - 1 \right) \right)
\]
* Naloga 19 (Prinčič 5.3)

#+begin_problem
Imamo opno s polmerom \( R \) v gravitacijskem polju. Površinska gostota mase znaša \( \mu \), površinska napetost pa \( \gamma \).
#+end_problem

Rešujemo enačbo

\[ \nabla ^2 u = - \frac{p}{\gamma}.
\]

Tlak zapišemo z površinsko gostoto mase kot

\[ p = - \frac{\mathrm{d} m }{\mathrm{d} S } g = - \mu g
\]

Enačba, ki jo rešujemo, ima tudi robni pogoj \( u \left( r = a, \phi \right) = 0 \). Dan robni pogoj je v cilindričnih koordinatah.

Diferencialna enačb v cilindričnih koordinatah je tako

\[ \frac{1}{r} \frac{\partial }{\partial r}  \left( r \frac{\partial }{\partial r}  u \right) = \frac{\mu g}{\gamma}
\]

Po integriranju dobimo

\[ r \frac{\partial }{\partial r} u = \frac{r ^2}{2} \frac{ \mu g}{ \gamma} + C_0.
\]

Po ponovnem integriranju dobimo pa

\begin{equation}
\label{eq:5}
 u = \int\limits_{}^{} \left( \frac{r}{2} \frac{\mu g}{\gamma} + \frac{C_0}{r} \right) \, \mathrm{d} r = \frac{r ^2}{4} \frac{\mu g}{\gamma} + C_0 \ln r + C_1
\end{equation}

Naravni logaritem divergira v izhodišču, zato \( C_0 = 0 \). Iz robnega pogoja \( u (r = a) = 0 \) pa dobimo

\[ C_1 = - \frac{a ^2}{4} \frac{\mu g}{\gamma}.
\]

Rešitev je tako

\[ u \left( r \right) = \frac{\mu g}{4 \gamma} \left( r ^2 - a ^2 \right)
\]

Na opno sedaj položimo kovanec s polmerom \( R_k \) in maso \( m_k \). Sedaj imamo nov robni pogoj na obsegu kovanca.

Zaradi gravitacije kovanec upogiba opna in posledično opna deluje na delec s silo nazaj. Enakost sil je \( m g = F \sin \alpha \), kjer je \( \alpha \) kot med horizontalo in naklonom opne. Sila \( F \) je enaka \( l \gamma \), kjer je \( l = 2 \pi R_k \) obseg kovanca. \( \sin \alpha \) pa lahko zaradi majhnosti in simetričnosti zapišemo preko zveze \( \sin \alpha = \left. \frac{\mathrm{d} u}{\mathrm{d} r} \right|_{r = R_k} \).

Združimo sedaj vse skupaj, da dobimo drugi robni pogoj

\[ m_k g = \left. 2 \pi R_k \gamma \frac{\partial u}{\partial r} \right|_{r = R_k} \implies \left. \frac{\partial u}{\partial r} \right|_{r = R_k} = \frac{m_k g}{2 \pi R_k \gamma}
\]

Splošna rešitev \ref{eq:5} je še zmeraj enaka, vendar tokrat \( C_0 \) ne bo ničeln. Po upoštevanju prvega robnega pogoja je konstanta \( C_1 \) enaka

\[ C_1 = - \frac{\mu g}{ 4\gamma } a ^2 - C_0 \ln a.
\]

Preobrazimo splošno rešitev

\[ u(r) = \frac{\mu g}{4 \gamma} \left( r ^2 - a ^2 \right) + C_0 \ln \frac{r}{a},
\]

ki jo vstavimo v drugi robni pogoj in izrazimo \( C_0 \).

\[ \frac{\mu g}{4 \gamma} \cdot 2 R_k + \frac{C_0}{R_k} = \frac{m_k g}{2 \pi R_k \gamma} \implies  C_0 = \frac{m_k g + \pi R_k ^2 \mu g}{2 \pi \gamma}.
\]

Rešitev opne s kovancem je

\[ u(r) = \frac{\mu g}{4 \gamma} \left( r ^2 - a ^2 \right) + \frac{g}{2 \pi \gamma} \left( m - \pi \mu R_k ^2  \right) \ln \frac{r}{a}.
\]
