#+title: 8. vaje iz Matematične fizike 2
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Hidrodinamika
** Naloga 22 (Prinčič 6.1) - nadaljevanje

Rešujemo Laplaceovo enačbo

\[ \nabla ^2 \Phi = 0,
\]

kjer je \( \Phi \) hitrostni potencial.

Določili smo tudi robna pogoja, ki sta nam podali enačbi

\begin{align}\label{eq:rp1}
  \Phi (r \to \infty, \phi) &= - v_0 r \cos \phi \\ \label{eq:rp2}
\left. \frac{\partial \Phi}{\partial r}  \right|_{r = R} &= 0
\end{align}

Splošna rešitev Laplaceove enačbe je

\[ \Phi (r, \phi) = \left( A_0 + B_0 \ln r \right) \left( a + b\phi \right) + \sum\limits_{n = 1}^{\infty} \left( A_n r^n + B_n r^{-n}  \right)\left( C_n \sin (n \phi) + D_m \cos (n \phi) \right)
\]

Zaradi periodičnosti problema velja \( b = 0 \). Problem nam ne divergira v izhodišču, torej bo \( B_0 = 0 \). Robni pogoj \ref{eq:rp1} je odvisen samo od kosinusa, torej bo \( C_n = 0 \). Iz istega robnega pogoja tudi sledi \( A_1 = - v_0 \) in \( A_{n \ne 1} = 0 \).

Ostane nam torej

\[ \Phi (r, \phi) = - v_0 r \cos \phi + \sum\limits_{n = 1}^{} B_n r^{-n} \cos (n \phi)
\]

Upoštevamo še drugi robni pogoj \ref{eq:rp2}

\[ \left. \frac{\partial \Phi}{\partial r}  \right|_{r = R} = \sum\limits_{n = 1}^{} (-B_n) n R^{- n - 1} \cos (n \phi) - v_0 \cos \phi = 0,
\]

iz česar sledi \( B_{n \ne 1} = 0 \).

Po reševanju enačbe

\[ - B_1 R^{-2} \cos \phi - v_0 \cos \phi = 0 \implies \ B_1 = - v_0 R ^2
\]

je hitrostni potencial enak

\[ \Phi (r, \phi) = - v_0 R ^2 r^{-1} \cos \phi - v_0 r \cos  \phi.
\]

Hitrost pa je po definiciji gradienta v sferičnih koordinatah enak

\[ \vec{v} (r, \phi) = - \nabla \Phi(r, \phi) = \frac{\partial \Phi}{\partial r}  \hat{e}_r - \frac{1}{r} \frac{\partial \Phi}{\partial \phi}  \hat{e}_{\phi} = v_0 \cos \phi \left( 1 - \frac{R ^2}{r ^2} \right) \hat{e}_r - v_0 \sin \left( 1 + \frac{R ^2}{r ^2} \right)\hat{e}_{\phi}
\]
** Teorija

V primeru, da je hitrost oblike

\[ \vec{v} = \frac{\Gamma}{2 \pi} \frac{\hat{e}_{\phi}}{r},
\]

sta rotor in divergenca hitrosti enaka \( 0 \), vendar ne moremo uporabiti hitrostnega potenciala, kar dokažemo s protislovjem.

Če zapišemo hitrost s hitrostnim potencialom \( v_p = - \nabla \phi \), potem velja

\[ \oint\limits_{}^{} \vec{v}_p \cdot \mathrm{d} \vec{r} = - \oint\limits_{}^{} \nabla \phi \cdot \mathrm{d} \vec{r} = 0.
\]

Hkrat pa tudi velja iz definicija naše hitrosti, da

\[ \oint\limits_{r = R}^{} \frac{\Gamma}{2 \pi} \frac{\hat{e}_{\phi}}{r} \cdot \mathrm{d} r = \Gamma,
\]

s čimer imamo protislovje in \( \vec{v}_p \ne - \nabla \Phi \).
** Sferičen primer

Imamo sfero v laminaren toku, kjer je hitrost vzporedna s komponento \( z \). Robni pogoj je \( \vec{v} (r \to \infty) = v_0 \hat{e}_z \).

Splošna rešitev potenciala je

\begin{align*}
  \Phi (r, \theta, \phi) = & \sum\limits_{l = 0}^{\infty} \sum\limits_{m = 0}^l \left( A_{lm} r^l + B_{lm} r^{- (l + 1)} \right) \\
& \cdot \left( C_{lm} P_l^m (\cos \theta) + D_{lm}  Q_l ^m (\cos \theta) \right) \\
&\cdot \left( E_{lm} \cos(m \phi) + F_{lm} \sin (m \phi) \right)
\end{align*}

Iz tega nato sledi rešitev

\[ \vec{v} \left( r, \theta, \phi \right) = v_0 \cos \theta \left( 1 - \frac{R ^3}{r ^3} \right) \hat{e}_r - v_0 \sin \theta \left( 1 - \frac{R ^3}{2 r ^3} \right) \hat{e}_{\theta}
\]
** Naloga 23 (Prinčič, 6. 2)
#+begin_problem
Opazujemo Poiseuilloev zakona za viskozno in nestisljivo tekočino v tanki kvadratni cevi s stranico \( a \). Cev je dolga \( L \) in razlika tlakov med začetkom in koncem je \( \Delta p \). Zanima nas porazdelitev hitrosti, povprečno hitrost in pretok skozi cev.
#+end_problem

Fizikalni razmisleki, ki jih moramo narediti, da bo naš problem postal rešljiv. Zaradi dolžine cevi predpostavimo, da je hitrost neodvisna od dolžine cevi oz. \( \vec{v} \ne \vec{v} (z) \). Iščemo najpreprostejšo rešitev brez vrtincev, kar pomeni, da velja \( v_x = v_y = 0 \).

Enačba

\[ \rho \left( \vec{v} \cdot \nabla \right) \vec{v} = - \nabla p + \eta \nabla ^2 \vec{v}
\]

se nam poenostavi. \( \nabla \cdot \vec{v} = 0 \), saj je tekočina nestisljiva. Pri \( z = 0 \) imamo tlak \( p_1 \) in pri \( z = \infty \) imamo tlak \( p_2 \). Razliko teh tlakov predstavimo kot

\[ - \nabla p = - \frac{\Delta p}{L} \hat{e}_z.
\]

Zadnja poenostavitev pa je, da sta zaradi neodvisnosti \( \vec{v} \ne \vec{v} (x, y) \)

\[ \nabla ^2 \vec{v} = \nabla ^2 v_z \hat{e}_z
\]

Preostane nam torej Poissonova enačba

\[ \nabla ^2 v_z = \frac{\Delta p}{ L \eta},
\]

z robnimi pogoji

\begin{align} \label{eq:23rp1}
  v_z (x = 0, y) &= v_z (x = a, y) = 0 \\ \label{eq:23rp2}
v_z(z, y = 0) &= v_z (x, y = a) = 0
\end{align}

Spomnimo, da bomo problem reševali tako, da bomo najprej rešili Poissonovo enačbo, nato pa bomo rešili problem s homogenimi robnimi pogoji tako, da jih razvijemo po lastnih funkcijah.

#+begin_note
Iz problema

\[ \nabla ^2 v_n (x, y) = - \lambda_n ^2 v_n (x, y),
\]

z nastavkom \( u = \sum\limits_{n = 0}^{\infty} c_n v_n \) dobimo PDE oblike

\[ - \sum\limits_{n = 0}^{\infty} \lambda_n ^2 v_n c_n = f,
\]

iz česar sledi

\[ c_n = - \frac{\left\langle f, v_n \right\rangle}{\lambda_n ^2 \left\langle v_n, v_n \right\rangle}
\]
#+end_note

Za \( u = XY \) rešimo enačbo

\[ \frac{\partial ^2 }{\partial x ^2} u_n + \frac{\partial ^2 }{\partial y ^2} u_n = - \lambda_n ^2 u_n.
\]

Enačbo lahko preobrazimo v

\[ \frac{X ''}{X} + \frac{Y''}{Y} = - \lambda_n ^2 = - \lambda_{x, n} ^2 - \lambda_{y, n} ^2
\]

Rešitev v \( x \) smeri je

\[ X = A_n \cos (\lambda_{x, n}  x) + B_n \sin (\lambda_{x, n}  x),
\]

in iz robnega pogoja \( X(0) = 0 \) dobimo \( A = 0 \) ter \( X(a) = 0 \) dobimo \( \lambda_{x, n} = \frac{n \pi}{a} \).

Podobno rešitev dobimo tudi v \( y \) smeri, da je

\[ Y = C \sin \left( \lambda_{y, n}  y \right), \ \lambda_{y, m} = \frac{m \pi}{a}
\]

Uporabimo nastavek

\[ v = \sum\limits_{n = 1}^{\infty} B_{n, m} \sin \left( \frac{n \pi}{a} x \right) \sin \left( \frac{m \pi}{a} y \right),
\]

ki ga vstavimo v Poissonovo enačbo

\[ \sum\limits_{m, n = 0}^{\infty} - \left(n ^2 + m ^2 \right) \frac{\pi ^2}{a ^2} B_{n, m} \sin \left( n \pi \frac{x}{a} \right) \sin \left( m \pi \frac{y}{a} \right) = \frac{\Delta p}{\eta L}
\]

Dobljeno pomnožimo s skalarnim produktom, kjer upoštevamo, da velja

\[ \int\limits_0^a   \sin \left( n \pi \frac{x }{a} \right) \sin \left( n' \pi \frac{x}{a} \right) \, \mathrm{d} x = \frac{a}{2} \delta_{n, n'}.
\]

Dobimo torej

\begin{align*}
 \sum\limits_{n = 1}^{\infty} - \frac{a ^2}{4} \frac{\pi ^2}{2} \left( n ^2 + m ^2 \right) \delta_{n, n'} \delta_{m, m'} B_{n, m} &= \frac{\Delta p}{ \eta L} \int\limits_0^a \sin \left( n \pi \frac{x}{a} \right)\, \mathrm{d} x \int\limits_0^a \sin \left( n \pi \frac{y}{a} \right) \, \mathrm{d} y  \\
&= \frac{a ^2}{\pi ^2 n' m'} \left( 1 - (- 1)^{n'} \right) \left( 1 - (-1) ^{m'} \right).
\end{align*}


Iz enačbe

\[ \frac{\pi ^2}{4} \left( n' ^2 + m' ^2 \right) B_{n', m'} = - \frac{a ^2 \Delta p \left( 1 - (-1) ^{n'} \right) \left( 1 - (-1) \right)^{m'}}{\pi ^2 \eta L n' m'}
\]

lahko izrazimo \( B_{n', m'} \), kar pomeni, da je nastavek

\[ v = - \sum\limits_{n = 1}^{\infty} \frac{4 a ^2 \Delta p \left( 1 - (-1)^n \right) \left( 1 - (-1)^m \right)}{\pi ^4 \eta L n m (n ^2 + m ^2)} \sin \left( n \pi \frac{x}{a} \right) \sin \left( n \pi \frac{ y}{a} \right)
\]

Na koncu dneva nas zanima pretok

\[ \Phi = \int\limits_0^a \int\limits_0^a \left| v_z \right|  \, \mathrm{d} x \, \mathrm{d} y = C \frac{\Delta p a ^4}{L},
\]

kjer je \( C \) povprečenje ali pa seštevek vsote v rešitvi.
* Lastne funkcije

Če poznamo lastne funkcije \( u_n \) in pripadajoče lastne vrednosti \( \lambda_n \) enačbe

\[ \nabla ^2 u_n = - \lambda_n u_n,
\]

potem znamo rešiti naslednje probleme:

- Laplaceove enačbe
  - splošne rešitve

    \[ u = \sum\limits_{n, \lambda_n  = 0}^{} A_n u_n
    \]

  - Poissonovo enačbo s homogenimi robnimi pogoji

  - Poissonov enačbo z nehomogenimi robnimi pogoji, ki ga rešimo z nastavkom \( u = v + h \), kjer \( h \) zadosti robnim pogojem. V tem primeru rešujemo

    \[ \nabla ^2 v = f- \nabla ^2 h
    \]

- valovno

  \[ \nabla ^2 u (\vec{r}, t) = \frac{1}{c ^2} \frac{\partial ^2 u}{\partial t ^2}
  \]

  in difuzijsko enačbo

  \[ \nabla ^2 u (\vec{r}, t) = D \frac{\partial u}{\partial t} = L_t u
  \]

  To rešimo s separacijo spremenljivke \( u(\vec{r}, t) = X(x) T(t) \), ki nam poda enačbo

  \[ \nabla ^2 u(\vec{r}, t) = - k ^2 u.
  \]

  Rešitve so v tem primeru

  \[ T(t) = \begin{cases}
            \exp \left\{ \pm \mathrm{i} \omega t \right\} &; \text{valovna} \\
            \exp \left\{ - k_n ^2 D t \right\} &; \text{difuzijska}
            \end{cases}
  \]

  Znamo rešiti te enačbe, ki imajo
  - homogene robne in začetne pogoje \( u(\vec{r}, 0) = f(\vec{r}) \), ki nam poda vmesno rešitev

    \[ u (\vec{r}, t) = \sum\limits_n^{} c_n u_n (\vec{r}) T_n (t).
    \]

    Koeficiente določimo preko skalarnega produkta

    \[ c_n = \frac{\left\langle f, u \right\rangle}{\left| u_n \right| ^2}
    \]

  - nehomogene enačbe in homogene robne pogoje oblike

    \[ \mathcal{L}_t u = \nabla ^2 u + g.
    \]

    Za reševanje uporabimo nastavek \( u(\vec{r}, t) = \sum\limits_n^{} c_n (t) u_n (\vec{r}) \), funkcijo \( g \) pa razvijemo po lastnih funkcijah \( g(\vec{r}, t) = \sum\limits_n^{} g_n (t) u_n (\vec{r}) \), iz česar iz PDE dobimo ODE

    \[ \mathcal{L}_t c_n = - k_n ^2 c_n + g_n
    \]

  - nehomogene robne pogoje, kjer uporabimo nastavek \( u = v + h \), kjer \( h \) zadosti robni pogojem. Posledično \( v \) zadosti robnim pogojem in naša PDE postane

    \[ \nabla ^2 u = \mathcal{L}_t u \implies \ \nabla ^2 v + \nabla ^2 h = \mathcal{L}_t v + \mathcal{L}_t h
    \]

    Na koncu dobimo

    \[ \mathcal{L}_t v = \nabla ^2 v + \nabla ^2 h - L_t h = \nabla ^2 v + g,
    \]

    kar je nehomogena enačba z robnimi pogoji.

- cilindrične koordinate

  ~ nehal sem pisati, ker je bila samo ponovitev vsega že povedanega ~
