#+title: 9. vaje iz Matematične fizike
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Lastne funkcije
** Helmholtzova enačba v cilindričnih koordinatah

Helmholtzova enačba je diferencialna enačba oblike

\[ \nabla ^2 u + \lambda u = 0,
\]

ki jo rešujemo s separacijo spremenljivk \( u(r, \phi, z) = R(r) \Phi(\phi) Z(z) \).

Separacija nam poda 3 diferencialne enačbe.

Prva diferencialna enačba

\begin{equation}
\label{eq:1}
 \Phi'' = - m ^2 \Phi,
\end{equation}

poda rešitvi za azimutalni kot \( \phi \) za \( m \ge 0 \), kjer je \( m \) celo število. Za \( m > 0 \) je splošna rešitev enačbe \ref{eq:1}

\[ \Phi_m = A \cos \left( m \phi \right) + B \sin \left( m \phi \right).
\]

Za \( m = 0 \) je rešitev enačbe

\[ \Phi_0 = A + B \phi
\]

Druga diferencialna enačba

\begin{equation}
\label{eq:2}
Z'' = \pm \beta ^2 Z
\end{equation}

ima dve rešitvi glede na predznak.

\[ Z(z) = \begin{cases}
          C \sin (\beta z) + D \cos (\beta z) &; + \beta \\
          C \mathrm{sh} \left( \beta z \right) + D \mathrm{ch} (\beta z) &; - \beta
          \end{cases}
\]

Tretja diferencialna enačba se glasi

\[ r ^2 R'' + r R' + \left[ \left( \lambda \pm \beta ^2 \right) r ^2 - m ^2 \right] R = 0.
\]

Oblika rešitve bo odvisna od vrednosti \( \lambda \pm \beta ^2 \).

- vrednost \( \lambda \pm \beta ^2 = 0 \) bo za \( m \ge 0 \) podala rešitev oblike

  \[ R_m = \begin{cases}
           A r^m + B r^{-m} &; m > 0 \\
           A + B \ln r &; m = 0
           \end{cases}
  \]

- vrednost \( \lambda \pm \beta ^2 = k ^2 \) bo podala Besslove funkcije kot rešitve

  \[ R_m = A J_m (kr) + B Y_m (kr).
  \]

  Alternativna rešitev so tudi Henklove funkcije, ki so definirane kot

  \[ H_m^{(1)} (kr) = J_m (kr) + \mathrm{i} Y_m (kr) \quad \text{ in } \quad H_m^{(2)} (kr) = J_m (kr) - \mathrm{i} Y_m (kr).
  \]

  Rešitev se potem glasi

  \[ R_m = A H_m^{(1)} (kr) + BH_m^{(2)} (kr)
  \]

- vrednost \( \lambda \pm \beta ^2 = - k ^2 \) poda modificirane Beslove funkcije kot rešitve

  \[ R_m = A I_m (kr) + B K_m (kr)
  \]

Modificirane Besslove funkcije imajo v kompleksnem prostoru tudi povezavo z Besslovimi funkcijami

\[ J_m (\mathrm{i} z) = \exp \left\{  \frac{1}{2} \mathrm{i} \pi m\right\}I_m(z) \quad \text{ in } \quad N_m (\mathrm{i} z) =\exp \left\{ \frac{1}{2} (m + 1) \pi \right\} I_m (z) - \frac{2}{\pi} \exp \left\{ \frac{1}{2} \mathrm{i} m \pi \right\} K_m(z)
\]

Pri iskanju lastnih funkcij v cilindričnih koordinatah ima skalarni produkt dodano integralsko utež \( r \)

\[ \left\langle f, g \right\rangle = \int\limits_{}^{} f \cdot g \, r \, \mathrm{d} r \, \mathrm{d} \phi \, \mathrm{d} z
\]

*** Asimptotski približki

Asimptotska približka za Besslove funkcije, kjer je \( x \gg 1 \), so

\[ J_m (x) \asymp \sqrt{\frac{2}{\pi x}} \cos \left( x - \frac{1}{2} m \pi - \frac{\pi}{4} \right) \quad \text{ in } \quad Y_m(x) \asymp \sqrt{\frac{2}{\pi x}} \sin \left( x - \frac{1}{2} m \pi - \frac{\pi}{4} \right).
\]

Za Henklove funkcije sta asimptotska približka

\[ H_m^{(1)}(x) \asymp e^{\mathrm{i} x} \quad \text{ in } H_m^{(2)} (x) \asymp e^{- \mathrm{i} x}.
\]

Za konec pa še asimptotski približki modificiranih Besslovih funkcij

\[ I_m (x) \asymp e^x \quad \text{ in } \quad K_m (x) \asymp e^{- x}
\]
** Naloga 24 (Prinčič, 7.1)
#+begin_problem
Kovanec z maso \( m \) in polmerom \( R_1 \) je simetrično položen na opno s polmerom \( a \) in površinsko napetostjo \( \gamma \).
#+end_problem

Rešujemo valovno enačbo za opno

\[ \frac{\partial ^2 u}{\partial t ^2} = c ^2 \nabla ^2 u, \ c ^2 = \frac{\gamma}{\mu},
\]

kjer je \( \mu \) površinska gostota. Hkrati imamo tudi robna pogoja.

Prvi robni pogoj je to, da je opna na robu vpeta

\begin{equation}
\label{eq:3}
u (r = a) = 0.
\end{equation}

Drugi robni pogoj pa povezuje opno s kovancem preko drugega Newtonovega zakona

\begin{equation}
\label{eq:4}
m \ddot{u} \left( r = R_1 \right) = \oint\limits_{r = R_1}^{} \left. \gamma \frac{\partial u}{\partial r} \right|_{r = R_1} \, \mathrm{d} l = 2 \pi R_1 \left. \gamma \frac{\partial u}{\partial r} \right|_{r = R_1}
\end{equation}

Slednji robni pogoj je oblike

\[ \alpha x(0) + \beta x' (0) = 0,
\]

kar nam pove, da imamo opravka s Sturm-Liouvilleovim problemom.

Reševanja enačbe poteka preko separacije spremenljivk \( u(r, t) = R(r) T(t) \), ki nam poda dve ODE.

\[ \frac{\ddot{T}}{T} = c ^2 \frac{\nabla ^2 R}{R} = - \omega ^2.
\]

Reševanje diferencialne enačbe v času ima splošno rešitev

\begin{equation}
\label{eq:5}
T (t) = A \sin (\omega t) + B \cos (\omega t).
\end{equation}

Ostane nam še radialna diferencialna enačba

\[ \nabla ^2 R = - \frac{\omega ^2}{c ^2} R,
\]

in uvedemo \( k ^2 = \frac{\omega ^2}{c ^2} \) za krajši zapis. Rešitve radialnega dela so v splošnem odvisne od števila \( m \), ki se pojavi kot rešitev enačbe \ref{eq:1}. Naš problem je simetričen, kar pomeni, da nimamo odvisnosti od azimutalnega kota \( \phi \) in posledično je \( m = 0 \). Rešitev radialnega dela je tako

\begin{equation}
\label{eq:6}
R(r) = C J_0 (kr) + D Y_0 (kr).
\end{equation}

V rešitvi \ref{eq:6} \( Y_0 \) sicer divergirajo v izhodišču \( r = 0 \), vendar je naše definicijsko območje obroč na intervalu \( r \in [R_1, a] \).

Ob upoštevanju prvega robnega pogoja \ref{eq:3} in rešitve \ref{eq:6} dobimo enakost

\[ u(r = a) = T(t) \left[ C J_0 (ka ) + D Y_0 (ka) \right] = 0 \implies \ D = - C \frac{J_0 (ka)}{Y_0 (ka)}.
\]

Vmesna rešitev je torej

\begin{equation}
\label{eq:7}
R(r) = C J_0 (kr) - C\frac{J_0 (ka)}{Y_0 (ka)} Y_0 (kr).
\end{equation}

Sedaj jo vstavimo v drugi robni pogoj \ref{eq:4} in dobimo enakost

\[ - m \omega ^2 T \left( C J_0 (k R_1) - C \frac{J_0 (ka)}{Y_0 (k a)} Y_0 (k R_1) \right) = 2 \pi R_1 \gamma T \left( C k J_0 ' (k R_1) - C k \frac{J_0 (ka)}{Y_0 (ka)} Y_0 ' (kR_1) \right)
\]

Izpostavimo in pokrajšamo lahko koeficiente ter časovni del nastavka. Na pomoč nam priskočita tudi identiteti

\[ 2 J_n' = J_{n - 1} - J_{n + 1} \quad \text{ in } \quad J_{-n} = \left( -1 \right)^n J_n.
\]

Slednja identiteta velja tudi za \( Y \) in posledično velja

\[ J_0 ' = - J_1 \quad \text{ in } \quad Y_0 ' = - Y_1.
\]

Ostane nam

\[ - m c ^2 k ^2 \left( J_0 (k R_1) - \frac{J_0 (ka)}{Y_0 (ka)} Y_0 (k R_1) \right) = 2 \pi R_1 \gamma \left( - J_1 (k R_1) + \frac{J_0 (ka)}{Y_0 (ka) } Y_1 (k R_1) \right),
\]

od koder lahko izrazimo

\[ k = -\frac{2 \pi R_1 \gamma}{m c ^2} \frac{\left( - J_1 (k R_1) + \frac{J_0 (ka)}{Y_0 (ka)} Y_1 (k R_1) \right)}{J_0 (k R_1) - \frac{J_0 (ka)}{Y_0 (ka)} Y_0 (k R_1)}
\]
** Naloga 25 (Prinčič, 7.2)
#+begin_problem
Na boben s polmerom \( R_0 \) udarimo v točko \( (r = a, \phi = 0) \) s sunkom \( p_0 \). Kakšna je oblika bobna v kasnejših časih?
#+end_problem

Rešujemo valovno enačbo

\[ \frac{\partial ^2 u}{\partial t ^2}  = c ^2 \nabla ^2 u.
\]

Rob opne je vpet v obroč, kar nam da prvi robni pogoj

\begin{equation}
\label{eq:10}
u \left( r = R_0, \phi, t \right) = 0.
\end{equation}

Pred udarcem je boben miroval, kar pomeni, da je začetni pogoj njegovo mirovanje

\begin{equation}
\label{eq:8}
u (r, \phi, t = 0) = 0.
\end{equation}

Po udarcu pa odvod bobna ne bo več ničeln zaradi gibalne količine, s katero smo delovali nanj

\begin{equation}
\label{eq:11}
 \left. \frac{\partial u}{\partial t}  \right|_{t = 0} = \frac{C}{r} \delta (r - a) \delta(\phi),
\end{equation}

kjer je \( C \) konstanta. Določimo jo iz enačbe za gibalno količino.

\begin{align*}
  p_0 &= \int\limits_{}^{} v \, \mathrm{d} m = \int\limits_{}^{} \left. \mu \dot{u}\right|_{t = 0} \, \mathrm{d} S\\
&= C \mu \int\limits_{}^{} \frac{1}{r} \delta (r - a) \delta (\phi) r \, \mathrm{d}r \, \mathrm{d} \phi = C \mu
\end{align*}

Konstanta je torej enaka \( C = \frac{p_0}{\mu} \).

Nalogo rešujemo podobno kot nalogo 24 s separacijo spremenljivke. Rešitev časovne diferencialne enačbe \ref{eq:5} je enaka

\[ T = A \sin (\omega t),
\]

zaradi začetnega pogoja \ref{eq:8}.

Radialna diferencialna enačba je

\[ \frac{\nabla ^2 R}{R} = - \frac{\omega ^2}{c ^2} = - k ^2.
\]

Pri rešitvi tokrat imamo kotno odvisnost in bo splošna rešitev

\begin{equation}
\label{eq:9}
R_m = \left[ A_m J_m (kr) + B_m Y_m (kr) \right] \left[ C_m \cos (m\phi) + D_m \sin (m \phi) \right]
\end{equation}

Koeficienta \( B_m  \) in \( D_m \) bosta ničelna. Prvi zaradi tega, ker nimamo divergence v izhodišču, drugi pa zaradi simetričnosti problema.

Upoštevamo robni pogoj \ref{eq:10}, da določimo vrednosti, ki jih zavzame \( k \). Dobimo enačbo

\[ A_m J_m (k R_0)  C_m \cos (m \phi) = 0 \implies k_{nm} R_0 = \xi_n^{(m)}.
\]

Vrednosti, ki jih zavzame \( k_{nm} \) so torej

\[ k_{nm} = \frac{\xi_n^{(m)}}{R_0},
\]

kjer je \( \xi_n^{(m)} \) \( n \)-ta ničla \( m \)-te Besslove funkcije \( J_m \).

Z rešitvijo

\[ u (r, \phi, t) = \sum\limits_{m = 0}^{\infty} \sum\limits_{n = 1}^{\infty} \sin \left( c k_{mn} t \right)  C_{mn} J_m \left( \xi_n^{(m)} \frac{r}{R_0} \right) \cos (m \phi),
\]

kjer smo upoštevali \( \omega_{mn} = c k_{mn} \).

Za konec naloge lahko preko začetnega pogoja \ref{eq:11} poiščemo še vrednosti koeficientov \( C_{mn} \). Rešitev, ki smo jo odvajali po času je enaka

\[ \left. \frac{\partial u}{\partial t}  \right|_{t = 0} = c \sum\limits_{m = 0}^{\infty} \sum\limits_{n = 1}^{\infty} C_{mn} k_{mn} J_m \left( \xi_n^{(m)} \frac{r}{R_0} \right) \cos (m \phi).
\]

Imamo torej enakost

\[ c \sum\limits_{m = 0}^{\infty} \sum\limits_{n = 1}^{\infty} C_{mn} k_{mn} J_m \left( \xi_n^{(m)} \frac{r}{R_0} \right) \cos (m \phi) = \delta \left( r- a \right) \delta(\phi) \frac{p_0}{\mu_0 r}.
\]

Za izluščitev koeficienta bomo uporabili sledeča skalarna produkta

\[ \int\limits_0^{2 \pi} \cos (l \phi) \cos (l' \pi) \, \mathrm{d} \phi = \pi \delta_{l l'} \quad \text{ in } \quad  \int\limits_0^{R_0} J_m \left( \xi_n^{(m)} \frac{r}{R_0} \right) J_{m'} \left( \xi_n^{(m')} \frac{r}{R_0} \right) \cdot r \cdot \, \mathrm{d}r = \frac{R_0 ^2}{2} J_{m + 1} \left( \xi_n^{(m)} \right) ^2 \delta_{m m'}.
\]

Pri skalarnem produktu Besslovih funkcij smo upoštevali še dodano utež \( r \). Zgornjo enakost torej pomnožimo z \( \int\limits_0^{R_0} \int\limits_0^{2 \pi} J_{m'} \left( \xi_{n'}^{(m')} \frac{r}{R_0} \right) \cos (m' \phi) \cdot r \, \mathrm{d} r \mathrm{d} \phi \) in dobimo

\begin{align*}
  c k_{m'n'} C_{m' n'} \int\limits_0^{R_0} \int\limits_0^{2 \pi} \left( J_{m'} \left( \xi_{n'}^{(m')} \frac{r}{R_0} \right) \right) ^2 \cos ^2 (m' \phi) r \, \mathrm{d} r \, \mathrm{d} \phi &= \int\limits_0^{R_0} \int\limits_0^{2\pi} \delta (r - a) \delta(\phi) \frac{p_0}{\mu_0 r} r J_{m'} \left( \xi_{n'}^{(m')} \frac{r}{R} \right) \cos (m' \phi) \, \mathrm{d} r \, \mathrm{d} \phi \\
c k_{m' n'} C_{m' n'} \frac{R ^2}{2} J_{m' + 1} \left( \xi_{n'}^{(m')} \right) ^2 \pi &= J_{m'} \left( \xi_{n'}^{(m')} \frac{a}{R} \right) \cos (m' \cdot 0) \frac{p_0}{\mu_0} \\
 &= J_{m'} \left( \xi_{n'}^{(m')} \frac{a}{R_0} \right) \frac{p_0}{\mu_0}
\end{align*}

Vrednosti koeficientov so torej

\[ C_{mn} = \frac{2p_0}{\mu_0 \pi c R_0} \frac{J_m \left( \xi_n^{(m)} \frac{a}{R_0} \right)}{J_{m + 1} \left( \xi_n^{(m)} \right) ^2}, \ m \ne 0
\]
** Naloga 26
#+begin_problem
Imamo valj s polmerom \( a \) in rešujemo difuzijsko enačbo

\begin{equation}
\label{eq:12}
 \frac{\partial u}{\partial t}  = D \nabla ^2 u - \frac{1}{\tau} u.
\end{equation}

z robnim pogojem \( u (r = a) = u_0 \).

Zanima nas rešitev, če je rešitev

a) stacionarna
   a) zunaj
   b) znotraj valja
b) časovno odvisna od notranjosti valja z začetnim robnim pogojem \( u (r, t = 0) = u_0 \).
#+end_problem
*** Točka a)

Iščemo stacionarno rešitev, kar pomeni, da se enačba poenostavi v

\begin{equation}
\label{eq:13}
 \nabla ^2 u = \frac{1}{\tau D} u, \ k = \frac{1}{\tau D}
\end{equation}


Rešitve so v tem primeru (zakaj?) modificirane Besslove funkcije

\[ u(r) = AI_0 (kr) + BK_0 (kr).
\]

Zaradi neodvisnosti od kota je vrednosti indeksa \( m = 0 \). Rešitev zunaj valja je

\[ u(r) = B K_0 (kr),
\]

in iz robnega pogoja \( u(a) = u_0 \), da je vrednost koeficienta \( B = \frac{u_0}{K_0 (ka)} \). Analagono, določimo koeficient znotraj valja

\[ u(r) = A I_0 (kr) \implies \ A = \frac{u_0}{I_0 (ka)}
\]

Funkciji se zaradi oblik zlepita na robu.
*** Točka b)

V primeru časovne odvisnosti znotraj valja imamo nehomogene robne pogoje. Takojšnja separacija ni v redu, saj moramo pogoje homogenizirati.

Možni način homogenizacije bi bila uporaba nastavka

\[ u (r, t) = R(r) T(t) + u_0,
\]

ki nam po vstavitvi v enačbo poda sledečo diferencialno enačbo

\[ R \dot{T} = D \nabla ^2 R T - \frac{1}{\tau} RT - \frac{1}{\tau} u_0.
\]

Enačba je boljša, vendar tečna za reševanje.

Namesto tega bomo uporabili sledeč nastavek

\[ u (r, t) = R(r) T(t) + u_0 \frac{I_0 (kr)}{I_0 (ka)}.
\]

Nastavek vstavimo v difuzijsko enačbo in dobimo

\[ R \dot{T} = D \nabla ^2 R T - \frac{1}{\tau} RT - \frac{1}{\tau} u_0 \frac{I_0 (kr)}{I_0 (ka )} + D \nabla ^2 I_0 (kr) \frac{u_0}{I_0 (ka)}.
\]

V zadnjih dveh členih prepoznamo enačbo \ref{eq:13}, kar pomeni, da se izničita. Separiramo spremenljivke in dobimo

\[ \frac{\nabla ^2 R}{R} = \frac{1}{D} \frac{\dot{T}}{T} + \frac{1}{D \tau} = - \kappa ^2
\]

Diferencialno enačbo v času lahko rešimo

\[ \dot{T} + \frac{1}{\tau} T = - D \kappa ^2 T \implies \dot{T} = -(\frac{1}{\tau} + D \kappa ^2) T ,
\]

katere rešitev je

\[ T = C \exp \left\{ - \left( D \kappa ^2 + \frac{1}{\tau} \right) t \right\}.
\]

Diferencialna enačba v radialnem delu se glasi

\[ \frac{\nabla ^2 R}{R } = - \kappa ^2.
\]

Splošna rešitev je oblike

\[ R(r) = E J_0 (\kappa r) + F Y_0 (\kappa r).
\]

Divergence ni v središču valja, torej bo \( F = 0 \).

Upoštevamo robni pogoj

\begin{align*}
  \left. u (r, t) \right|_{r = a} &= \left. \exp \left\{ - \left( D \kappa ^2 + \frac{1}{\tau} \right) t \right\} E J_0 (\kappar) \right|_{r = a} + u_0 \frac{I_0 (ra)}{I_0 (ra)} \\
&= u_0.
\end{align*}

Preostane nam torej

\[ E J_0 (\kappa a) = 0.
\]

Določimo ničle Besslovih funkcij

\[ ka = \xi_n^{(0)}, \ n = 1, 2, 3, \ldots.
\]

Rešitev difuzijske enačbe bo tako

\[ u (r, t) = \sum\limits_{n = 1}^{\infty} E_n \exp \left\{ - \left( D \kappa ^2 - \frac{1}{\tau} \right)t \right\} J_0 \left( \xi_n^{(0)} \frac{r}{a} \right) + u_0 \frac{I_0 (kr)}{I_0 (ar)}.
\]

Upoštevamo še začetni pogoj \( u(r, 0) = u_0 \).

\[ u (r, 0) = \sum\limits_{n = 1}^{\infty} E_n J_0 \left( \xi_n^{(0)} \frac{r}{a} \right) + u_0 \frac{I_0 (kr) }{I_0 (ka)} = 0.
\]

Preko skalarnega produkta in množenja obeh strani enačbe z \( \int\limits_0^R J_0 \left( \xi_n^{(0)} \frac{r}{a} \right) r \, \mathrm{d} r \) lahko izluščimo vrednosti koeficientov \( E_n \).

\begin{align*}
  \int\limits_0^R \sum\limits_{n = 1}^{\infty} E_n J_0 \left( \xi_n^{(0)} \frac{r}{a} \right) ^2 r \, \mathrm{d}r &= \int\limits_0^R u_0 \left( 1 - \frac{I_0 (kr)}{I_0 (ka)} \right) J_0 \left( \xi_{n'}^{(0)} \frac{r}{a} \right) r \, \mathrm{d}r \\
E_n &= \frac{2}{a} \frac{u_0 \int\limits_0^R \left( 1 - \frac{I_0 (kr)}{I_0 (ka )} \right) J_0 \left( \xi_n^{(0)} \frac{r}{a} \right) r \, \mathrm{d} r}{J_1 ^2 \left( \xi_n^{(0)} \frac{r}{a} \right)}.
\end{align*}
