#+title: 8. vaje iz Matematične fizike 2
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Naloga xx (Prinčič 7.3)

#+begin_problem
Zanima nas hitrostni profil dolge cevi s polmerom \( R \), skozi katero teče nestisljiva tekočina z viskoznostjo \( \eta \).

a) \( \nabla p = \frac{\Delta p}{L} \hat{e}_z \)
b) \( \nabla p = \frac{\Delta p}{L} e^{\mathrm{i} \omega t} \hat{e}_z \)
#+end_problem

Robni pogoj je \( \vec{v} (r = R) = 0 \). Hitrost ima komponento samo v \( z \) smeri, torej \( \vec{v} = v(r, t) \hat{e}_z \).

Navier-Stokesova enačba

\[ \rho \left( \frac{\partial \vec{v}}{\partial t}  + \left( \vec{v} \cdot \nabla \right) \vec{v} \right) = - \nabla p + \eta \nabla ^2 \vec{v},
\]

se nam ob upoštevanju lastnosti tekočin preobrazi v

\begin{equation}
\label{eq:1}
 \rho \frac{\partial \vec{v}}{\partial t} = - \left( \nabla p \right) \cdot \hat{e}_z + \eta \nabla ^2 v
\end{equation}

Za a) primer iščemo hitrost po dolgem času, torej \( \frac{\partial \vec{v}}{\partial t} = 0 \).

Za b) zaradi znane časovne odvisnosti gradienta tlaka uporabimo nastavek \( v(r, t) = R(r) e^{\mathrm{i} \omega t} \). Navier-Stokes \ref{eq:1} postane nehomogena diferencialna enačba 2. reda

\begin{equation}
\label{eq:2}
 \rho R \mathrm{i} \omega - \eta \nabla ^2 R= - \frac{\Delta p}{L} .
\end{equation}

Homogeni del diferencialne enačbe je Helmholtzova enačba

\[ \nabla ^2 R_H = \frac{\rho \mathrm{i} \omega}{\eta} R_H,
\]

kjer je \( -k ^2 = \frac{\rho \mathrm{i} \omega}{\eta} \). Rešitev Helmholtzove enačbe je

\[ R_H (r) = A J_0 (kr) + B Y_0 (kr).
\]

Rešitev nam ne divergira v izhodišču, torej je \( B = 0 \). Izrazimo sedaj \( k \)

\[ - k ^2 = \frac{\rho \mathrm{i} \omega}{\eta} \implies k = \pm \sqrt{\frac{\rho \omega}{\eta}} \sqrt{- \mathrm{i}}.
\]

Koren od \( - \mathrm{i} \) lahko zapišemo v polarnim zapisom kot

\[ \sqrt{- \mathrm{i}} = \sqrt{e^{- \mathrm{i} \frac{\pi}{2}}} = e^{- \mathrm{i} \frac{\pi}{4}} = \frac{1}{\sqrt{2}} (1- \mathrm{i}).
\]

Koeficient \( k \) je tako enak

\[ k = \pm \sqrt{\frac{\rho \omega}{2 \eta}} (1 - \mathrm{i}).
\]

Zaradi identitet kot sta

\[ J_0 (x) = J_0 (-x) \text{ in } J_n (-x) = (-1)^n J_n (x),
\]

ni važno ali izberemo pozitivno ali negativno vrednost \( k \). Zaradi ljubezni do sebe izberemo pozitiven \( k \).

Izračunajmo še partikularno rešitev \( R_P \). Nehomogeni del enačbe je neodvisen od \( r \), kar pomeni, da želimo enako odvisnost imeti tudi pri funkcijah od \( R_P \). Torej bo partikularna rešitev

\[ R_P = \mathrm{i} \frac{\Delta p}{ L \rho \omega}
\]

Splošna rešitev enačbe \ref{eq:2} je

\[ R(r) = A J_0 (kr) + \mathrm{i} \frac{\Delta p}{L \rho \omega} .
\]

Preko robnega pogoja \( v(r = R) = 0 \) določimo, da je \( A = - \frac{\mathrm{i} \Delta p }{L \rho \omega J_0 (kR)} \). Končna rešitev je

\[ v(r, t) = - \mathrm{i} \frac{\Delta p}{L \rho \omega} \left( \frac{J_0 (kr)}{J_0 (k R)} - 1 \right) e^{\mathrm{i} \omega t}
\]
** Limite

Opazujemo rešitve za majhne \( \omega \). Besslovo funkcijo lahko razvijemo v vrsto

\begin{equation}
\label{eq:3}
 J_0 (x) = 1 - \frac{x ^2}{4} + o \left( x ^4 \right).
\end{equation}

Lahko tudi pogledamo, kakšne morajo biti vrednosti za majhne \( \omega \). Zaradi korenske premosorazmernosti sledi

\[ \left| k r \right| \ll 1,
\]

iz česar sledi

\[ \sqrt{\frac{\omega \rho}{\eta}} R \ll 1 \implies \ \omega \ll \frac{\eta}{\rho R ^2}.
\]

Hitrost pa je ob upoštevanju razvojev enaka

\begin{align*}
  v(r, t) &= - \mathrm{i} \frac{\Delta p}{L \rho \omega} e^{\mathrm{i} \omega t} \left( \frac{1 - \frac{k ^2 r ^2}{4}}{1 - \frac{k ^2 R ^2}{4}} - 1 \right) \\
&= - \mathrm{i} \frac{\Delta p}{ L \rho \omega} e^{\mathrm{i} \omega t} \left[ \left( 1- \frac{k ^2 r ^2}{4} \right) \left( 1 + \frac{k ^2 R ^2}{4} \right) - 1 \right]
\end{align*}

Pri razvoju v vrsto \ref{eq:3} smo šli zgolj do 2. reda. Zmnožek v zgornji vrsti pa nam bo dal člen s \( k ^4 \), ki ga zanemarimo. Če bi ga želeli upoštevati, bi morali pri \ref{eq:3} upoštevati četrti red. Torej

\begin{align*}
  v(r, t) &= - \mathrm{i} \frac{\Delta p}{L \rho \omega} e^{\mathrm{i} \omega t} \left( 1 + \frac{k ^2}{4} \left[ R ^2 - r ^2 \right] - \cancel{\frac{k ^4 R ^2 r ^2}{16}} - 1 \right) \\
&= \frac{\Delta p}{4 \eta L} e^{\mathrm{i} \omega t} \left( r ^2 - R ^2 \right)
\end{align*}

Za velike \( \omega \) bo veljalo

\[ \omega \gg \frac{\eta}{\rho R ^2}.
\]

Upoštevamo asimptoto za velike \( \omega \)

\[ J_m (x) \approx \sqrt{\frac{2}{\pi x}} \cos \left( x - \frac{1}{2} m \pi - \frac{\pi}{4} \right) .
\]

Hitrost zapišemo torej

\[ v(r, t) = - \mathrm{i} \frac{\Delta p}{L \rho \omega} e^{\mathrm{i} \omega t} \left[ \sqrt{\frac{R}{r}} \frac{\cos \left( kr - \frac{\pi}{4} \right)}{\cos \left( k R - \frac{\pi}{4} \right)} - 1 \right] .
\]

Zaradi \( \omega \gg 1 \) velja tudi \( kr \sim k R \) in posledično bo \( \sqrt{\frac{R}{r}} \approx 1 \). Kosinus lahko zapišemo kot vsoto polarnih števil

\[ \cos \left( x + \mathrm{i} y \right) = \frac{1}{2} \left[ e^{\mathrm{i} (x + \mathrm{i} y)} + e^{- \mathrm{i} (x + \mathrm{i} y)} \right]  \underset{\left| y \right| \gg 1}{\approx} \frac{1}{2} \begin{cases}
                                                                                                                                                                                                     e^{\mathrm{i} x - y} &; y < 0 \\
                                                                                                                                                                                                     e^{\mathrm{i} x + y} &; y > 0
                                                                                                                                                                                                     \end{cases}
\]

Torej bo \( y = \mathrm{Im} k R = \sqrt{\frac{\omega \rho}{2 \eta} R} < 0 \)

Iz tega sledi rešitev v limiti, ki je ravno v nasprotni fazi od toka

\[ v(r, t) = - \mathrm{i} \frac{\Delta p}{L \rho \omega} e^{\mathrm{i} \omega t} \left( \frac{\exp \left\{ \mathrm{i} \left( \sqrt{\frac{\rho  \omega}{2 \eta}} r - \frac{\pi}{4}\right) + \sqrt{\frac{\rho \omega}{2 \eta} r} \right\}}{\exp \left\{ \mathrm{i} \left( \sqrt{\frac{\omega \rho}{\eta}} R - \frac{\pi}{4} \right) + \sqrt{\frac{\omega \rho}{2 \eta} R} \right\} - 1 \right)
\]
* Helmholtzova enačba v sferičnih koordinatah

Rešujemo Helmholtzovo enačbo oblike

\[ \nabla ^2 u + \lambda u = 0.
\]

Enačbo rešujemo s pomočjo separacijo spremenljivk

\[ u(r, \phi, \theta) = R(r) \Theta(\theta) \Phi(\phi) = R (r) Y(\theta, \phi),
\]

kjer \( \phi \in [0, 2\pi) \) in \( \theta \in [0, \pi] \) na celi sferi. Laplaceov operator zapišemo v sferičnih koordinatah

\[ \nabla ^2 u = \frac{1}{r ^2} \frac{\partial }{\partial r}  \left( r ^2 \frac{\partial u}{\partial r}  \right) - \frac{L ^2}{r ^2} u
\]

in je

\[ L ^2 = - \frac{1}{\sin \theta} \frac{\partial }{\partial \theta} \left( \sin \theta \frac{\partial }{\partial \theta}  \right) - \frac{1}{\sin ^2 \theta} \frac{\partial ^2 }{\partial \phi ^2}.
\]

Za sferične harmonike velja

\[ L ^2 Y = l (l + 1) Y
\]

Enačbe azimutalnega dela je

\[ \Phi''= - m ^2 \Phi,
\]

katere rešitve so

\[ \Phi_m = \begin{cases}
           A \cos (m \phi) + B \sin (m \phi) &; m > 0  \\
           A + B \phi &; m = 0.
            \end{cases}
\]

Na celi sferi \( m \) zasedajo vrednosti \( 0, 1, \ldots, \).

Za \( \theta \) uvedemo spremenljivko \( t = \cos \theta \) in rešujemo diferencialno enačbo

\[ \frac{\mathrm{d} }{\mathrm{d} t} \left[ \left( 1 - t ^2 \right) \frac{\mathrm{d} }{\mathrm{d} t} \right] \Theta + \left[ l (l + 1) - \frac{m ^2}{1 - t ^2} \right] \Theta =0
\]

in rešitev je

\[ \Theta_{l, m} (\theta) = A P_l^m (\cos \theta) + B Q_l^m (\cos \theta),
\]

kjer \( l \) zaseda vrednosti \( 0, 1, 2, \ldots \) in \( m = 0, 1, \ldots, l \) na celi sferi. Vsi \( \theta \) divergirajo v \( \cos \theta = \pm 1 \).

Enačba radialnega dela je

\[ \frac{1}{r ^2} \frac{\mathrm{d} }{\mathrm{d} r} \left( r ^2 \frac{\mathrm{d} R}{\mathrm{d} r} \right) + \lambda R - \frac{l(l + 1)}{r ^2} R = 0
\]

Imamo tri možne rešitve

1) \( \lambda = 0 \), potem je rešitev

   \[ R_l (r) = A r^l + B r^{- (l + 1)}
   \]

2) \( \lambda = k ^2 \) so rešitve

   \[ R_l (r) = A j_l (kr) + B y_l (kr), \ j_l (x) = \sqrt{\frac{\pi}{2 x}} J_{l + \frac{1}{2}} (x)
   \]

   in velja

   \[ j_0 (x) = \frac{\sin x}{x}, \ y_0 (x) = - \frac{\cos x}{x}
   \]

3) \( \lambda = - k ^2 \) so rešitve

   \[ R_l (r) = A i_l (kr) + B k_l (kr)
   \]

   in velja

   \[ i_0 (x) = \frac{\mathrm{sinh} x}{x} , \ k_0 (x) = \frac{e^{- x}}{x}
   \]
** Naloga yy (Prinčič 7.4)

#+begin_problem
Opazujemo ohlajanje krogle s temperaturo \( T_1 \). Temperatura okolice je \( T_0 \).
#+end_problem

Rešujemo difuzijsko enačbo

\[ D \nabla ^2 T = \frac{\partial T}{\partial t},
\]

z robnim pogojem \( T(r = R, t) = T_0 \) in začetnim pogojem \( T(r, t = 0) = T_0 \).

Za reševanje uporabimo nastavek, ki nam homogenizira robni pogoj

\[ T = \tau (t) R(r) + T_0,
\]

ki nam da diferencialno enačbo

\[ \frac{\nabla ^2 R}{R} = \frac{1}{D} \frac{\dot{\tau}}{\tau} = - k ^2
\]

Rešitve časovnega dela je eksponento padanje

\[ \tau(t) = A e^{- k ^2 D t}.
\]

Enačba radialnega dela je

\[ \nabla ^2 R = - k ^2 R,
\]

katere rešitve so, kakor vidimo v delu s teorijo

\[ R(r) = B j_0 (kr) + C y_0 (kr).
\]

Rešitev nam v izhodišču ne divergira, torej bo \( C = 0 \), saj \( y_0 \) divergirajo. Rešitve radialnega dela ob upoštevanju definicije \( j_0 \) iz teorije je

\[ R(r) = B \frac{\sin (kr)}{kr}
\]

Upoštevajmo robni pogoj \( T(r = R, t) = T_0 \), da dobimo enačbo

\[ A e^{- k ^2 D t} \frac{\sin (k R)}{kR} + T_0 = T_0 \implies \ k = \frac{n \pi}{R}, \ n \in \mathbb{Z}^+
\]

Rešitev torej zapišemo kot vrsto

\[ T(r, t) = \sum\limits_{n = 1}^{\infty} \hat{A}_n \frac{\sin \left( \frac{n \pi}{R} r \right)}{\frac{n \pi}{R} r} e^{- \left( \frac{n \pi}{R} \right) ^2 D t} + T_0
\]

Za določitev koeficienta \( \hat{A} \) uporabimo še začetni pogoj \( T(r, t = 0) = T_1 \) in dobimo enačbo

\[ T_1 - T_0 = \sum\limits_{n = 1}^{\infty} \hat{A}_n j_0 (k_n r).
\]

Uporabimo skalarni produkt v sferičnih koordinatah

\[ \left( T_1 - T_0 \right) \int\limits_0^R j_0 (k_{n'}  \cdot r) r ^2 \, \mathrm{d} r = \hat{A}_m \int\limits_0^R \left( j_0 (k_{n'} r) \right) ^2 r ^2 \, \mathrm{d} r.
\]

Izrazimo koeficient \( \hat{A} \) in upoštevamo definicijo \( j_0 (x) \), da dobimo

\[ \hat{A}_n = \frac{(T_1 - T_0) \int\limits_0^R \frac{\sin (k_{n'} r)}{k_{n'} r} r ^2 \, \mathrm{d} r}{\int\limits_0^R \frac{\sin  ^2 (k_{n'}  r)}{k_{n'} ^2 r ^2} r ^2 \, \mathrm{d} r} = (T_1 - T_0) \frac{- \left( -1 \right)^n n \pi}{\frac{1}{2} n \pi} = 2 \left( -1 \right)^{n + 1} (T_1 - T_0)
\]

Celotna rešitev je tako

\[ T(r, t) = \sum\limits_{n = 1}^{\infty} 2 \left( - 1 \right)^{n + 1} (T_1 - T_0) \frac{\sin \left( \frac{n \pi}{R}r \right)}{\left( \frac{n \pi}{R}r \right)} \exp \left\{ - \left( \frac{n \pi}{R} \right) ^2 D t \right\} + T_0
\]

Za čas \( t = 0 \) je vrsta dobro definirana v srednjem (lokalni členi bodo konvergirali). Za \( t > 0  \) bodo členi eksponentno zadušeni in takrat vrsta absolutno konvergira.

Do take konvergence (v srednjem) pride takrat, ko imamo nezvezne začetne pogoje.
** Naloga zz (Prinčič 7.5)

#+begin_problem
Imamo tanko polsfero, ki se dotika ravnine s temperaturo \( T_0 \). Začetna temperatura polsfere je \( T_1 \).
#+end_problem

Rešujemo difuzijsko enačbo

\begin{equation}
\label{eq:4}
 D \nabla ^2 T = \frac{\partial T}{\partial t}
\end{equation}

z robnimi pogoji \( T \left( \theta = \frac{\pi}{2}, t \right)= T_0 \) in začetnim pogojem \( T \left( \theta, t = 0 \right)= T_1 \).

Problem bomo reševali s separacijo spremenljivk, ki nam hkrati uredi še težave z robnim pogojem

\[ T = T_0 + \Theta(\theta) \tau (t).
\]

Nastavek vstavimo v enačbo \ref{eq:4} in nam preostane enačba

\[ \frac{\nabla ^2 \Theta}{\Theta} = \frac{1}{D} \frac{\dot{\tau}}{\tau} = - \lambda
\]

Časovni del ima enačbo

\[ \frac{\dot{\tau}}{\tau} = - \lambda D,
\]

 z eksponentno rešitvijo

 \[ \tau(t) = A e^{- \lambda D t} .
 \]

 Kotni del ima enačbo

 \[ \nabla ^2 \Theta = - \lambda \Theta.
 \]

 Enačbo lahko napišemo z operatorjem vrtilne količine, kakor smo povedali v teoretičnem delu višje gor. Enačba je torej

 \begin{equation}
 \label{eq:5}
 -\frac{L ^2}{R ^2} \Theta = - \lambda \Theta.
 \end{equation}

 Ker nimamo kotne odvisnosti za \( \phi \), bodo rešitve samo navadni Legendrovi polinomi

 \[ \Theta(\theta) = A P_l (\theta) + B Q_l (\theta).
 \]

 Vemo pa tudi, da velja identiteta

 \[ L ^2 \Theta = l (l + 1),
 \]

 ki jo uporabimo v modificirani enačbi za kot \ref{eq:5}

 \[ \frac{- l (l + 1)}{R ^2} \Theta = -\lambda \Theta \implies \ \lambda = \frac{l (l + 1)}{R ^2}
 \]

 Zaradi divergence v \( \cos \theta = - 1 \) je koeficient \( A = 0 \) in nam preostane samo

 \[ \Theta (\theta) = B P_l (\cos \theta) .
 \]

 Nahajamo se na polsferi, kar pomeni, da ne poznamo, katere vrednosti \( l \)-jev pridejo v poštev. Te vrednosti bomo dobili iz robnih pogojev

 \[ T_0 = T_0 + \tau B P_l (0) \implies \ P_l (0) = 0 .
 \]

 Ničle tega Legendrovega polinoma so lihi \( l = 1, 3, 5, \ldots \).

Splošna rešitev je tako

\[ T = T_0 + \sum\limits_{l = 1,3,5, \ldots}^{\infty} C_l P_l (\cos \theta) \exp \left\{ - \frac{l(l + 1)}{R ^2} D t \right\}.
\]

Upoštevamo še začetni pogoj ter definicijo skalarnega produkta

\begin{align*}
  T_1 - T_0 &= \sum\limits_{l = 1}^{\infty} C_l P_l (\cos \theta) && \left/ \int\limits_0^1 P_l (\cos \theta) \, \mathrm{d} \cos \theta \\
(T_1 - T_0) \int\limits_0^1 P_l (\cos \theta) \, \mathrm{d} (\cos \theta) &= C_l \int\limits_0^1 P_l ^2 (\cos \theta) \, \mathrm{d} \cos \theta
\end{align*}

Vrednosti, ki jih \( l \) zaseda so lihe - torej so tudi Legendrovi polinomi v naši vrsti lihi.

Če vzamemo sodo funkcijo na sodem intervalu \( [-1, 1] \), integral lahko zapišemo kot dvakratni integral po intervalu \( [0, 1] \). Za lihe funkcije pa je potem integral po intervalu \( [0, 1] \) ravno polovica integrala po intervalu \( [-1, 1] \).

Poznamo identiteto

\[ \int\limits_{-1}^1 P_l ^2 (\cos \theta) \, \mathrm{d} (\cos \theta) = \frac{2}{(2l + 1)}
\]

Iz tega sledi, da je koeficient enak

\[ C_l = (2l + 1) (T_1 - T_0) \int\limits_0^1 P_l (\cos \theta) \, \mathrm{d} \cos \theta
\]
** Naloga ww :the_power_of_sturm_liouvile:

#+begin_problem
Imamo sfero s polmerom \( R \), ki ima v ekvatorialni ravnini grelec z močjo \( P \). Zunaj sfere je temperatura \( T_0 \). Iščemo stacionarno rešitev difuzijske enačbe.
#+end_problem

Iščemo stacionarno rešitev, torej velja \( \frac{\partial T}{\partial t} = 0 \). Od difuzijske enačbe nam torej ostane samo krajevni del in izvori

\[ \nabla ^2 T = - \frac{q}{\lambda}.
\]

Izvor je po definiciji \( q = \frac{\mathrm{d} P}{\mathrm{d} V} \). Naš grelec se nahaja v ekvatorialni ravnini sfere, kar pomeni, da se poslužimo \( \delta (z) \) funkcije.

Zapišemo torej

\[ q = \frac{\mathrm{d} P}{\mathrm{d} V} = C \delta(z) = C \delta \left( r \cos \theta \right).
\]

Konstantno \( C \) določimo tako, da pointegriramo po volumnu krogle, saj vemo, da je celotna moč po volumnu krogle samo naš grelec z močjo \( P \).

\begin{align*}
  P &= C \int\limits_V^{} \delta \left( r \cos \theta \right) \, \mathrm{d} V  \\
&= C \int\limits_0^R \int\limits_{-1}^1 \int\limits_0^{2 \pi} \delta \left( r \cos \theta \right) r ^2 \cos \theta \, \mathrm{d} r \, \mathrm{d} \cos \theta \, \mathrm{d} \phi \\
&= C \int\limits_0^R \int\limits_{-1}^1 r ^2 \frac{\delta \left( r \cos \theta \right)}{r} \, \mathrm{d} (\cos \theta) \, \mathrm{d} r \\
&= 2 \pi C \frac{R ^2}{2} \implies C = \frac{P}{\pi R ^2}
\end{align*}

Rešujemo Poissonovo enačbo

\[ \nabla ^2 T = - \frac{P}{\pi R ^2 \lambda} \delta \left( r \cos \theta \right)
\]

z nastavkom, ki nam tudi homogenizira naše robne pogoje.

\[ T = \sum\limits_{n = 1}^{\infty} \sum\limits_{l = 0}^{\infty} c_{n, l} j_l \left( \xi_n^{(l)} \frac{r}{R} \right) P_l \left( \cos \theta \right) + T_0
\]

(glej predavanja)

Nastavek vstavimo v difuzijsko enačbo

\[ \sum\limits_n^{} \sum\limits_l^{} c_{n, l} \nabla ^2 \left( j_l \left[ \xi_n^{(l)} \right] P_l (\cos \theta) \right)  = - \frac{P}{\pi R ^2 \lambda} \delta \left( r \cos \theta \right).
\]

Uporabimo eno fino zadevo Poissonove rešitve, da velja \( \nabla ^2 u  = - \lambda u \) - odvod nam poda lastne vrednosti. Nastavek tako postane

\[ \sum\limits_n^{} \sum\limits_l^{} c_{n, l} \left( \frac{\xi_n^{(l)}}{R} \right) ^2 j_l \left( \frac{\xi_n^{(l)}}{R} r \right) P_l (\cos \theta) = - \frac{P}{\pi R ^2 \lambda} \delta (r \cos \theta)
\]

S pomočjo skalarnega produkta lahko izračunamo

\begin{align*}
 -c_{n, l} \left( \frac{\xi_n^{(l)}}{R} \right) ^2 \int\limits_0^R \int\limits_{-1}^1 j_l ^2 \left( \xi_n^{(l)} \frac{r}{R} \right) P_l ^2 \left( \cos \theta \right) r ^2 \, \mathrm{d} r \, \mathrm{d} (\cos \theta) &= - \frac{P}{\pi R ^2 \lambda} \int\limits_0^R \int\limits_{-1}^1 \frac{\delta (r \cos \theta)}{r} r ^2 j_l \left( \xi_n^{(l)} \frac{r}{R} \right) P_l (\cos \theta) \, \mathrm{d} r \, \mathrm{d} (\cos \theta) \\
&= - \frac{P}{\pi R ^2 \lambda} P_l (0) \int\limits_0^{R} j_l \left( \xi_n^{(l)} \frac{r}{R} \right) \, \mathrm{d} r
\end{align*}

Iz tega lahko sedaj izrazimo koeficiente

\[ C_{n, l} = \frac{P (2l + 1)}{2 \pi \lambda \left( \xi_n^{(l)} \right) ^2} P_l (0) \frac{\int\limits_0^R r j_l \left( \xi_n ^{(l)} \frac{r}{R} \right) \, \mathrm{d} r }{\int\limits_0^R r ^2 j_l ^2 \left( \xi_n ^{(l)} \frac{r}{R} \right) \, \mathrm{d} r}
\]
*** Poseben primer

Za \( \delta \) funkcijo, ki se nahaja v volumnu, zmeraj velja

\[ \iiint\limits_{\mathbb{R} ^3}^{} f \left( \vec{r} \right) \partial_S \,\mathrm{d } ^3 \vec{r} = \iint\limits_S^{} f \left( \vec{r} \right) \,\mathrm{d} ^2 S.
\]

Specifično za naš primer

\begin{align*}
  \iiint\limits_{\mathbb{R} ^3}^{} f \left( \vec{r} \right) \delta_S r_s ^2 \, \mathrm{d} r_s \, \mathrm{d} \phi \,\mathrm{d } (\cos \theta) = \int\limits_0^R \int\limits_0^{2\pi} f \left( \vec{r} \right) r \, \mathrm{d} r \, \mathrm{d} \phi
\end{align*}

Tem integralom se reče \( \delta \) funkcije površine. Več je na voljo v Križaničevi knjigi Parcialne diferencialne enačbe.
** Naloga kk

#+begin_problem
Imamo sfero s polmerom \( R \) in toplotno prevodnostjo \( \lambda_k \). Sfero obdamo z lakom toplotne prevodnosti \( \lambda_l \) majhne debeline \( d \). Temperatura okolice je \( T_0 \). Temperatura sfere je ob času \( t = 0 \) enaka \( T_1 \).
#+end_problem

Rešujemo difuzijsko enačbo

\[ D \nabla ^2 T = \frac{\partial T}{\partial t}
\]

z začetnim pogojem \( T(t = 0) = T_1 \).

Toplotni tok skozi lak je zaradi majhne debeline enak

\[ j_l = \lambda_l \cdot\frac{ \Delta T}{d} = \lambda_l \frac{T_0 - T_{(r = R)}}{d}
\]

Tok, ki gre skozi stranico krogle, mora biti enak toku skozi lak, kar nam poda naš robni pogoj

\[ \left. \lambda_k \partial_r T \right|_{r = R} = \lambda_l \frac{T_0 - T(r = R)}{d}
\]

Robni pogoj še zmeraj precej enostavno homogeniziramo z nastavkom

\[ T(r, t) = R(r) \tau(t) + T_0.
\]

Nastavek vstavimo v difuzijsko enačbo in dobimo

\[ \frac{\nabla ^2 R}{R} = \frac{1}{D} \frac{\dot{\tau}}{\tau} = - k ^2
\]

Rešitev časovnega dela je eksponentno pojemanje

\[ \tau(t) = A \cdot e^{- D k ^2 t}.
\]

Radialni del je neodvisen od kotov, kar pomeni, da je \( m = l = 0 \). Po teoretičnem uvodu so rešitve torej samo

\[ R(r) = A j_0 (kr) + B y_0 (kr).
\]

Člen \( B = 0 \), saj divergira v izhodišču. V robne pogoje torej vstavimo \( R(r) = A j_0 (kr) \) in dobimo

\[ \lambda_k \tau A j_0 ' (kR) k = \lambda_l \left( - \frac{A j_0 (kR) \tau}{d} \right).
\]

Upoštevamo definicijo \( j_0 (x) = \frac{\sin x}{x} \), ki jo vstavimo v enačbo, kjer smo še pokrajšali časovne komponente.

\[ \lambda_k \left( \frac{\cos (kR)}{kR} - \frac{\sin (kR)}{(kR) ^2} \right)k = - \lambda_l \frac{\sin (kR)}{kR d}
\]

Enačbo delimo s \( \cos (kR) \) in uvedemo spremenljivko \( \xi = kR \)

\[ \lambda_k \left( \frac{1}{\xi} - \tan (\theta) \frac{1}{\xi ^2} \right) \frac{\xi}{R} = - \lambda_l \tan (\xi) \frac{1}{\xi d}
\]

Dobili smo transcendentno enačbo

\[ \tan (\xi) \left( \frac{\lambda_l}{ \lambda_k} \frac{R}{d} - 1 \right) = \xi.
\]

Uvedemo spremenljivko \( \alpha = \frac{\lambda_l }{\lambda_k} \frac{R}{d} \), ki ji pravimo /snovna konstanta/.

Rešitve enačbe

\begin{equation}
\label{eq:6}
 \tan (\xi) \left( \alpha - 1 \right) = \xi,
\end{equation}

so \( \xi_n \) za \( n = 1, 2, \ldots \) in rešitev je

\[ T(r, t) = \sum\limits_{n = 1}^{\infty} A j_0 \left( \xi_n \frac{r}{R} \right) \exp \left\{ - D \left( \xi \frac{r}{R} \right) ^2 t \right\} + T_0
\]

Upoštevamo še začetni pogoj \( T( t= 0 ) = T_1 \)

\[ T_1 - T_0 = \sum\limits_{n = 1}^{\infty} A j_0 \left( \xi_n \frac{r}{R} \right).
\]

\( \xi_n \) sicer niso ničle \( j_0 \), ampak nam Sturm-Liouvilleov izrek nam pove, da so rešitve enačbe \ref{eq:6} ortogonalne med seboj v danem skalarnem produktu. **Pomembno**: robni pogoji morajo biti tipa Sturm-Liouville.

\[ \int\limits_{}^{} (T_1 - T_0) j_0 \left( \xi_n \frac{r}{R} \right) r ^2 \, \mathrm{d} r = A_n \int\limits_{}^{} j_0 ^2 \left( \xi_n \frac{r}{R} \right) r ^2 \, \mathrm{d} r
\]
