#+title: 12. vaje iz Matematične fizike 2
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Greenove funkcije

Imamo diferencialni operator

\[ \mathcal{L} = \nabla ^2 + \lambda
\]

z Dirichletovimi robnimi pogoji na omejen območju \( \mathcal{D} \).

Po definiciji iščemo tako funkcijo, da velja

\[ \mathcal{L}_{\vec{r}} G \left( \vec{r}, \vec{r}_0 \right) = \delta \left( \vec{r}, \vec{r}_0 \right)
\]

in na robu velja

\[ \left.  G \left( \vec{r}, \vec{r}_0 \right)  \right|_{\vec{r} \in \partial \mathcal{D}} = 0.
\]

Uporabimo nastavek, kjer prvi člen predstavlja Greenovo funkcijo na neskončnem območju

\[ G \left( \vec{r}, \vec{r}_0 \right) = G_{\infty} \left( \vec{r}, \vec{r}_0 \right) + g \left( \vec{r}, \vec{r}_0 \right).
\]

Po aplikaciji diferencialnega operatorja dobimo

\[ \mathcal{L}_{\vec{r}} G \left( \vec{r}, \vec{r}_0 \right) = \delta \left( \vec{r}, \vec{r}_0 \right) + \mathcal{L}_{\vec{r}} g \left( \vec{r}, \vec{r}_0 \right) = \delta \left( \vec{r}, \vec{r}_0 \right),
\]

iz česar sledi pogoj za funkcijo \( g \)

\[ \mathcal{L} g \left( \vec{r}, \vec{r}_0 \right) = 0.
\]

Druga možnost za funkcijo pa je

\[ \left. g \left( \vec{r}, \vec{r}_0 \right) \right|_{\vec{r} \in \partial \mathcal{D}} = - \left. G_{\infty} \left( \vec{r}, \vec{r}_0 \right) \right|_{\vec{r} \in \partial \mathcal{D}}.
\]

Metode reševanja so

- zrcaljenje (+ inverzija)
- razvoj po lastnih funkcijah
- direktno (lepljenje)
- konformne preslikave v dveh dimenzijah.

Posplošena Greenova formula je

\[ \int\limits_{\mathcal{D}}^{} \left( u \nabla ^2 v - v \nabla ^2 u \right) \, \mathrm{d} V = \int\limits_{\partial \mathcal{D}}^{} \left( u \frac{\partial u}{\partial \vec{n}}  - v \frac{\partial u}{\partial \vec{n}} \right) \, \mathrm{d} S,
\]

kjer velja

\[  \int\limits_{\mathcal{D}}^{} \left( u \nabla ^2 v - v \nabla ^2 u \right) \, \mathrm{d} V = \int\limits_{\mathcal{D}}^{} \left( u \mathcal{L} v - v \mathcal{L} u \right) \, \mathrm{d} V.
\]

Normala \( \vec{n} \) je normala, ki na robu domene kaže navzven.

Če rešujemo problem oblike

\[ \mathcal{L} u \left( \vec{r} \right) = f \left( \vec{r} \right),
\]

vstavimo v enačbo \( v \left( \vec{r}, \vec{r}_0 \right) = G \left( \vec{r}, \vec{r}_0 \right) \). Potem dobimo iz posplošene Greenove formule

\begin{align*}
  \int\limits_{\mathcal{D}}^{} \left[ u \left( \vec{r} \right) \mathcal{L}_{\vec{r}}  G \left( \vec{r}, \vec{r}_0 \right) - G \left( \vec{r}, \vec{r}_0 \right) \mathcal{L}_{\vec{r}} u \left( \vec{r} \right) \right] \, \mathrm{d} V &= \int\limits_{\partial \mathcal{D}}^{} \left[  u \left( \vec{r} \right) \frac{\partial G \left( \vec{r}, \vec{r}_0 \right)}{\partial \vec{n}_{\vec{r}}} - G \left( \vec{r}, \vec{r}_0 \right) \frac{\partial u \left( \vec{r} \right)}{\partial \vec{n}_{\vec{r}}}   \right] \, \mathrm{d} S \\
\int\limits_{\mathcal{D}}^{} \left[ u \left( \vec{r} \right) \delta \left( \vec{r} - \vec{r}_0 \right) - G \left( \vec{r}, \vec{r}_0 \right) f \left( \vec{r} \right) \right] \, \mathrm{d} V &= \int\limits_{\partial \mathcal{D}}^{} \left[  u \left( \vec{r} \right) \frac{\partial G \left( \vec{r}, \vec{r}_0 \right)}{\partial \vec{n}_{\vec{r}}} \right] \, \mathrm{d} S.
\end{align*}

Opravimo zamenjavo \( \vec{r} \leftrightarrow \vec{r}_0 \) in \( G\left( \vec{r}, \vec{r}_0 \right)= G \left( \vec{r}_0 , \vec{r} \right) \) in dobimo enačbo

\begin{equation}
\label{eq:1}
 u \left( \vec{r} \right) = \int\limits_{\mathcal{D}}^{} G \left( \vec{r}, \vec{r}_0 \right) f \left( \vec{r}_0 \right) \, \mathrm{d} ^n \vec{r}_0 + \int\limits_{\partial \mathcal{D}}^{} \frac{\partial G \left( \vec{r}, \vec{r}_0 \right)}{\partial \vec{n}_{\vec{r}_0}} u \left( \vec{r}_0 \right) \, \mathrm{d} S_0
\end{equation}

** Neumannovi robni pogoji :iffy:

V primeru reševanja enačbe

\[ \nabla ^2 u = f.
\]

je postopek malo drugačen.

\begin{align*}
  \int\limits_{\mathcal{D}}^{} \nabla ^2 u \left( \vec{r} \right) \, \mathrm{d} V &= \int\limits_{\mathcal{D}}^{} \nabla \cdot \left( \nabla u \right) \, \mathrm{d} V \\
&= \oint\limits_{\partial \mathcal{D}}^{} \nabla u \, \mathrm{d} \vec{S} \\
&= \oint\limits_{\partial \mathcal{D}}^{} \frac{\partial u}{\partial \hat{n}} \, \mathrm{d} S \\
\end{align*}

Iz tega sledi, da je za Neumannove robne pogoje

\[ \oint\limits_{\partial \mathcal{D}}^{} \frac{\partial u}{\partial \hat{n}}  \, \mathrm{d} S = \int\limits_{\mathcal{D}}^{} f \left( \vec{r} \right) \, \mathrm{d} V
\]

V primeru, da je normalni odvod funkcije \( u \) ničeln, potem nam preostane enačba

\[ \int\limits_{\mathcal{D}}^{} f \left( \vec{r} \right) \, \mathrm{d} V = 0
\]

in Greenova funkcija v tem primeru je

\[ f \left( \vec{r} \right) = \delta \left( \vec{r} - \vec{r}_0 \right).
\]

** Naloga 34 (Prinčič, 5.2) - alternativno reševanje :w:

Ta problem smo že reševali.
#+begin_problem
Imamo polktrak širine \( a \), ki se nahaja v ravnini \( zy \). Poltrak ima napetost \( U_0 \). Rešujemo Laplaceovo enačbo

\[ \nabla ^2 U = 0,
\]

z robnimi pogoji

\[ U \left( x = 0, y, z \right) = \begin{cases}
                                    0 &; \left| y \right| > \frac{a}{2} \\
                                    U_0 &; \left| y \right| \le \frac{a}{2}
                                  \end{cases}
\]
#+end_problem

Kot smo povedali že pri prejšnjem reševanju te naloge, je problem v translacijsko invarianten v \( z \) smeri oz. \( U = U(x, y) \).

Naš problem je simetričen preko \( y \) osi, kar pomeni, da lahko rešujemo samo za \( x > 0 \). Potrebujemo Greenovo funkcijo \( G \left( \vec{r}, \vec{r}_0 \right) \) za polravnino.

Greenova funkcija za omejeno območje bo z nastavkom oblike

\[ G \left( \vec{r}, \vec{r}_0 \right) = G_{\infty} \left( \vec{r}, \vec{r}_0 \right) + g \left( \vec{r}, \vec{r}_0 \right).
\]

Za dan problem že poznamo, da je

\[ G_{\infty} \left( \vec{r}, \vec{r}_0 \right) = \frac{1}{2 \pi} \ln \left| \vec{r} - \vec{r}_0 \right| .
\]

Iz teoretičnega uvoda vemo

\[ \nabla_{\vec{r}} ^2 g \left( \vec{r}, \vec{r}_0 \right) = 0,
\]

iz česar sledi

\[ \left. g \left( \vec{r}, \vec{r}_0 \right) \right|_{x = 0} = \left. G_{\infty} \left( \vec{r}, \vec{r}_0 \right) \right|_{x = 0}.
\]

Nalogo bomo reševali preko zrcaljenja. Zamislimo si, da imamo točko \( \vec{r}_0 \) na polravnini \( x > 0 \) z nekim nabojem. Točko prezrcalimo čez \( x = 0 \) in ji damo obraten naboj. Na meji \( x = 0 \) bo pogoj, da je \( \left. G \left( \vec{r}, \vec{r}_0 \right) \right|_{\vec{r} \in \partial \mathcal{D}} = 0 \). Iz tega sledi, da bo

\[ g \left( \vec{r}, \vec{r}_0 \right) = - \frac{1}{2 \pi} \ln \left| \vec{r} - \vec{r}_0^{\ast} \right|.
\]

Koordinate točke \( \vec{r}_0^{\ast} \) so \( (- x_0, y_0) \), če so koordinate prve točke \( \vec{r}_0 = (x_0, y_0) \).

Ko smo znotraj naše domene \( x > 0 \), bo vedno veljalo

\[ \mathcal{L}_{\vec{r}} g \left( \vec{r}, \vec{r}_0 \right) = \delta \left( \vec{r} - \vec{r}_0 \right) = 0.
\]

Naša Greenova funkcija je tako oblike

\begin{align*}
  G \left( \vec{r}, \vec{r}_0 \right) &= \frac{1}{2 \pi} \ln \left| \vec{r} - \begin{bmatrix} x_{0} \\ y_{0} \end{bmatrix} \right| - \frac{1}{2 \pi} \ln \left| \vec{r} - \begin{bmatrix} -x_{0} \\ y_{0} \end{bmatrix} \right|\\
&= \frac{1}{4 \pi} \ln \left( \frac{(x- x_0) ^2 + (y - y_0) ^2}{(x + x_0) ^2 + (y - y_0) ^2} \right).
\end{align*}

Zaradi Dirichletovih pogojev \( \nabla ^2 u = f \left( \vec{r} \right) = 0 \) bo iz enačbe \ref{eq:1} veljalo

\[ \int\limits_{\mathcal{D}}^{} G \left( \vec{r}, \vec{r}_0 \right) f \left( \vec{r}_0 \right) \, \mathrm{d} ^2 \vec{r}_0  = 0.
\]

Ostane nam

\[ u \left( \vec{r} \right) = \int\limits_{\partial D}^{} \frac{\partial G \left( \vec{r}, \vec{r}_0 \right)}{\partial \vec{n}_{\vec{r}_0}} u \left( \vec{r}_0  \right) \, \mathrm{d} S_0.
\]

Normala \( \vec{n} \) kaže izven domene, v našem polravninskem problemu, je to \( \vec{n} = - \hat{e}_x \). Zapišemo

\[ \frac{\partial }{\partial \vec{n}_{\vec{r}_{0}}}  = - \frac{\partial }{\partial x_{0}}.
\]

Naša meja območja pa je \( \mathrm{d} S_0 = \mathrm{d} y_0 \).

Odvod Greenove funkcije po normali je enak

\[ \frac{\partial G}{\partial x_{0}} = \frac{1}{\pi} \frac{- x}{x ^2 + (y - y_0) ^2}.
\]

Računamo torej integral

\begin{align*}
  u \left( \vec{r} \right) &= \int\limits_{- \infty}^{\infty} \frac{x}{\pi} \frac{1}{x ^2 + (y - y_0) ^2} U \left( \vec{r}_0 \right) \, \mathrm{d} y \\
&= \int\limits_{- \frac{a}{2}}^{\frac{a}{2}} \frac{x}{\pi} \frac{1}{x + \left( y - y_0 \right) ^2} U_0 \, \mathrm{d} y
\end{align*}

Uvedemo spremenljivko \( z = \frac{y - y_0}{x} \) in dobimo

\[ u \left( \vec{r} \right) = \int\limits_{\frac{y + \frac{a}{2}}{x}}^{\frac{y - \frac{a}{2}}{x}} \frac{1}{\pi} \frac{1}{1 + z ^2} U_0   \, \mathrm{d} z = - \frac{U_0}{\pi} \left( \mathrm{arctg} \left( \frac{y - \frac{a}{2}}{x} \right) - \mathrm{arctg } \left( \frac{y + \frac{a}{2}}{x} \right) \right)
\]
** Akustika

Imamo hitrostno polje \( v \left( \vec{r}, t \right) \) z gostoto \( \rho \left( \vec{r}, t \right) = \rho_0 + \delta \rho \left( \vec{r}, t \right) \) in tlak \( p \left( \vec{r}, t \right) = p_0 + \delta p \left( \vec{r}, t \right) \).

Imamo več enačb

1. Euler (N - S za \( q = 0 \))

   \[ \rho \frac{\partial \vec{v}}{\partial t}  = - \nabla p
   \]

   in

   \[ \frac{\partial \vec{v}}{\partial t}  = \frac{\partial }{\partial x} + \cancel{\left( \vec{v} \cdot \nabla \right)} \vec{v}
   \]

2. Kontinuitetna enačba

   \[ \frac{\partial \rho}{\partial t}  = - \nabla \left( \rho \vec{v} \right)
   \]

3. Adiabatna stisljivost

   \[ \frac{\delta \rho}{\rho_0} = \chi_s \delta \rho
   \]

Iz predavanj vem

1. \( \vec{v} (t = 0) \) brezvrtinčno, potem je \( \vec{v} (t) \) brezvrtinčno in lahko zapišemo

   \[ \vec{v} = - \nabla \Phi.
   \]

   Eulerjeva enačba je potem

   \[ \rho_0 \frac{\partial \Phi}{\partial t}  = \delta p
   \]

2. Zapišemo lahko

   \[ \frac{\partial ^2 \delta p}{\partial t ^2}  = c ^2 \nabla ^2 \delta  p, \ c ^2 = \frac{1}{\chi_s} \rho_0
   \]

   Enako velja za \( \Phi \).

3. Robni pogoji ob trdi steni je

   \[ \vec{v} \cdot \hat{n} = 0,
   \]

   iz česar sledi

   \[ \frac{\partial \Phi}{\partial \vec{n}}  = 0 \implies \ \frac{\partial \delta p}{\partial \vec{n}} = 0
   \]

4. Povprečen energijski tok

   \[ \overline{\vec{\jmath}} = \frac{1}{2} \Re \left[ \delta p \vec{v}^{\ast} \right]
   \]
** Naloga 35 (Lloydovo zrcalo)
#+begin_problem
Imamo Lloydovo zrcalo, ki ima izvor na \( \vec{r} = a \hat{e}_z \). Rešujemo enačbo

\[ - \frac{1}{c ^2} \frac{\partial ^2 \delta p}{\partial t ^2} + \nabla ^2 \delta p = A \delta \left( \vec{r} - a \hat{e}_z \right) e^{- \mathrm{i} \omega t},
\]

z robnim pogojem \( \delta p (z = 0) = 0 \).
#+end_problem

Uporabili bomo nastavek

\[ \delta p \left( \vec{r}, t \right) = P \left( \vec{r} \right) e^{- \mathrm{i} \omega t},
\]

ki ga bomo vstavili v našo valovno enačbo.

\[ - \frac{1}{c ^2} (- \omega ^2) P \left( \vec{r} \right) e^{- \mathrm{i} \omega t} + \nabla_r ^2 P(\vec{r}) e^{- \mathrm{i} \omega t} = A \delta \left( \vec{r} - a \hat{e}_z \right) e^{- \mathrm{i} \omega t}.
\]

Uvedemo valovni vektor \( k ^2 = \frac{\omega ^2}{c ^2} \) in pokrajšamo časovna nihanja

\[ k ^2 P \left( \vec{r} \right) + \nabla_r ^2 P \left( \vec{r} \right) = A \delta \left( \vec{r} - a \hat{e}_z \right).
\]

Podana je funkcija za Greenovo funkcijo valovanja

\[ G_{\infty} \left( \vec{r}, \vec{r}_0 \right) = - \frac{1}{4 \pi} \frac{e^{\pm \mathrm{i} k \left| \vec{r} - \vec{r}_0 \right|} }{\left| \vec{r} - \vec{r}_0 \right|}.
\]

Izberemo pozitiven eksponent, saj je fizikalno to izvor nihanja.

Ponovno izberemo metodo zrcaljenja in tako kot pri prejšnjem primeru, se bodo na meji območja nasprotni valovi sešteli in izničili.

Naša Greenova funkcija je

\[ G \left( \vec{r}, \vec{r}_0 \right) = G_{\infty} \left( \vec{r}, \vec{r}_0 \right) - G_{\infty} \left( \vec{r}, \vec{r}_0^{\ast} \right) = - \frac{1}{4 \pi} \frac{e^{\mathrm{i} k \left| \vec{r} - \vec{r}_0 \right|}}{\left| \vec{r} - \vec{r}_0 \right|}  + \frac{1}{4 \pi} \frac{e^{\mathrm{i} k \left| \vec{r}- \vec{r}_0^{\ast} \right|}}{\left| \vec{r} - \vec{r}_0^{\ast} \right|}.
\]

Rešitev problema

\[ \mathcal{L} P \left( \vec{r} \right) = A \delta \left( \vec{r} - a \hat{e}_z \right)
\]

je

\[ P \left( \vec{r} \right) = \int\limits_{\mathcal{D}}^{} G \left( \vec{r}, \vec{r}_0 \right) A \delta \left( \vec{r} - a \hat{e}_z \right) \, \mathrm{d} ^3 \vec{r}_0.
\]

Vstavimo v integral izraz za Greenovo funkcijo in izračunamo integral, kjer velja, da je \( \vec{r}_0^{\ast} \) prezrcaljen in ima nasprotno predznačeno tretjo komponento.

\[ P \left( \vec{r} \right) = A \left( - \frac{1}{4 \pi} \frac{e^{\mathrm{i} k \left| \vec{r} - a \hat{e}_z \right|}}{\left| \vec{r} - a \hat{e}_z \right|} + \frac{1}{4 \pi} \frac{e^{\mathrm{i} k \left| \vec{r} + a \hat{e}_z \right|}}{ \left| \vec{r} + a \hat{e}_z \right|} \right).
\]

V primeru, da imamo Neumannove pogoje na meji, potem je drugi člen Greenove funkcije obratno predznačen

\[ G \left( \vec{r}, \vec{r}_0 \right) = G_{\infty} \left( \vec{r}, \vec{r}_0 \right) + G_{\infty} \left( \vec{r}, \vec{r}_0^{\ast} \right) .
\]

Za izračun toka \( \vec{\jmath} \) potrebujemo hitrosti, ki jo bomo dobili iz enačbe

\[ \rho \frac{\partial \vec{v}}{\partial t}  = - \nabla \delta p.
\]

Zaradi našega nastavka velja \( \frac{\partial \vec{v}}{\partial t}  = - \mathrm{i} \omega \vec{v} \) in dobimo enačbo

\[ \vec{v} = - \frac{\mathrm{i}}{\omega \rho} \nabla \delta p.
\]

Za majhne \( a \) oz. \( r \gg a \) je rezultat

\[ \vec{v} = - \frac{A}{4 \pi \rho c} \left[ \frac{e^{\mathrm{i} k r_-}}{r_-} - \frac{e^{\mathrm{i} k r_+}}{r_{+}} \right] \hat{e}_r e^{- \mathrm{i} \omega t},
\]

kjer sta

\[ r_{\pm} = r \pm a \cos \theta.
\]

Tok je potem

\[ \vec{\jmath} = \Re \left[ \delta p \vec{v}^{\ast} \right] \overset{r \gg a}{=} \frac{A ^2}{16 \pi \rho c} \frac{1}{c ^2} \left[ 1 - \cos \left( kr a \cos \theta \right) \right] \hat{e}_r,
\]

kjer smo upoštevali, da \( r_+ \sim r_- \sim r \). Pri \( \theta = \frac{\pi}{2} \) je \( \overline{\vec{\jmath}} = 0 \). V primeru Neumanna je v zgornjem oklepaju pozitiven predznak.
