#+title: Predavanja iz Fizikalnih merjenj, 13. teden v letu
#+subtitle: 2026/03/26
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Optimalna povratna zanka in poenostavitev Kalmanovega filtra
** Senzor prvega reda

V primeru opazovanja dinamik, katerih red je \( n > 1 \), lahko pride do sistematičnih napak.

Senzor opisuje enačba oblike

\[ \tau \dot{x} + x = z (t).
\]

Tipični vhodi \( z(t) \) so lahko

- \( z(t) = \delta(t) \)

- \( z(t) = H_0 (t) \)

- polinomi stopnje \( m = 1, 2, 3 \) \( z(t) = t^m \)

- \( z(t) = \cos (\omega t) \).

*** Tipičen vhod \( \delta(t) \)

Rešujemo enačbo

\[ \tau \dot{x} + x = \delta(t).
\]

Najprej rešimo homogen del enačbe, ki ima rešitev

\[ x = C e^{- \frac{t}{\tau}}.
\]

Parcialno rešitev bomo poiskali preko integracije po smiselnem intervalu \( \left[ - \epsilon, \epsilon \right] \) za \( \epsilon \to 0 \).

\begin{align*}
  \tau \int\limits_{-\epsilon}^{\epsilon} \frac{\mathrm{d} x}{\mathrm{d} t} \, \mathrm{d} t + \int\limits_{-\epsilon}^{\epsilon} x \, \mathrm{d} t &= \int\limits_{-\epsilon}^{\epsilon} \delta(t)\, \mathrm{d} t \\
\tau \left[ x(\epsilon) - x(- \epsilon) \right] &= 1,
\end{align*}

kjer smo upoštevali, da je integral \( \int_{-\epsilon}^{\epsilon} x \, \mathrm{d} t = 0 \).

Zahtevamo, da je \( x(- \epsilon) = \frac{\mathrm{d} ^n x(- \epsilon)}{\mathrm{d} t^n} = 0 \) (v besedah tehtnice s kazalcem: merilček mora biti na \( 0 \) in se ne sme vračati v prvotno lego, ampak že mora biti tam).

Dobimo torej določitev koeficienta

\[ x(0) = \frac{1}{\tau} = C.
\]

Dobimo torej

\[ x(t) = G(t) = \frac{1}{\tau} e^{- \frac{t}{\tau}}.
\]
*** Tipičen vhod \( \alpha t \)

Enačba senzorja je sedaj zelo podobna prejšnji

\[ \tau \dot{x} + x = \alpha t.
\]

Rešitev homogene enačbe je še zmeraj eksponentna

\[ x(t) = C e^{- \frac{t}{\tau}}.
\]

Za parcialno rešitev se bomo poslužili nastavka \( x_p (t) = At + B \). Nastavek vstavimo v enačbo in določimo vrednosti koeficientov

\[ A = \alpha \quad \text{ in } \quad B = - \alpha \tau.
\]

Parcialna rešitev je torej

\[ x(t) = \alpha t - \alpha \tau,
\]

in celotna rešitev je

\[ x(t) = Ce^{- \frac{t}{\tau}} + \alpha t - \alpha \tau.
\]

Ob upoštevanju robnih pogojev \( x(0) = 0 \) določimo še koeficient \( C = \alpha \tau \).

Rešitev je

\[ x(t) = \alpha t - \alpha \tau + \alpha \tau e^{- \frac{t}{\tau}}.
\]

Prvi člen je enak vhodni funkciji, drugemu členu pravimo /zamik/ (ang. /offset/), ob času \( t \to \infty \) pa gre zadnji člen proti nič.

Imamo torej sistematično napako v vrednosti zamika. Rezultati so zamaknjeni v relaciji z dejanskimi vrednostmi.
** Senzor drugega reda

Obravnavamo senzorje optimalne za spremljanje dinamike oblike

\[ \frac{\mathrm{d} ^2 x}{\mathrm{d} t ^2} = 0 + w.
\]

Zaradi pogojev Kalmanovega filtra moramo preiti na vektorsko reševanje \( \mathbf{x} = [x, \ v]^T \). Dinamika, ki jo spremljamo imajo obliko

\begin{align*}
  \dot{x} &= v \\
\dot{v} &= 0 + w
\end{align*}

Kalmanov filter oblike

\[ \dot{\mathbf{x}} = A \mathbf{x} + \Gamma \mathbf{w}
\]

za naš primer je potem

\[ \frac{\mathrm{d} }{\mathrm{d} t} \begin{bmatrix} x \\ v \end{bmatrix} = \begin{bmatrix}
                                                                           0 & 1 \\
                                                                           0 & 0
                                                                            \end{bmatrix} \begin{bmatrix} x \\ v \end{bmatrix} + \begin{bmatrix} 0 \\ 1 \end{bmatrix} w.
\]

Naš senzor zajema \( z = H\mathbf{x} + r \), kjer je okno \( H = \left| 1 \ 0 \right| \) - merimo torej samo spremenljivko \( x \) in ne njenega odvoda.

V merilnem sistemu \( M \) imamo oceno

\[ \hat{\mathbf{x}} = \begin{bmatrix} \hat{x} \\ \hat{v} \end{bmatrix}.
\]

Sledilna enačba po Kalmanu je

\[ \dot{\hat{\mathbf{x}}} = \begin{bmatrix}
                            0 & 1 \\
                            0 & 0
                             \end{bmatrix} \begin{bmatrix} \hat{x} \\ \hat{v} \end{bmatrix} + P H^T R^{-1} \left( z - H \hat{\mathbf{x}} \right).
\]

Variacija ocene je

\[ \dot{P} = AP + PA^T + \Gamma Q \Gamma ^T - P H^T R^{-1} HP.
\]

Rešimo sedaj ta matrični sistem. Prvi člen je

\begin{align*}
  AP &= \begin{bmatrix}
        0 & 1 \\
        0 & 0
         \end{bmatrix} \begin{bmatrix}
                       p_{11} & p_{12} \\
                       p_{21} & p_{22}
                        \end{bmatrix} \\
&= \begin{bmatrix}
   p_{12} & p_{22} \\
   0 & 0
    \end{bmatrix}.
\end{align*}

Njena transponirana različica je

\[ PA^T = \begin{bmatrix}
          p_{12} & 0 \\
          p_{22} & 0
           \end{bmatrix}.
\]

Nadaljni členi so še

\[ \Gamma Q \Gamma^T = \begin{bmatrix} 0 \\ 1 \end{bmatrix} [0 \ 1] Q = \begin{bmatrix}
                                                                        0 & 0 \\
                                                                        0 & Q
                                                                         \end{bmatrix}.
\]


Kovariančna matrika meritev je skalar, saj

\[ R = \left\langle r r^T \right\rangle.
\]

Zadnji člen v sledilni enačbi je torej

\begin{align*}
  PH^T R^{-1} HP &= \frac{1}{R} \begin{bmatrix}
                                p_{11} & p_{12} \\
                                p_{21} & p_{22}
                                 \end{bmatrix}
\begin{bmatrix} 1 \\ 0 \end{bmatrix} [1 \ 0]
\begin{bmatrix}
p_{11} & p_{12} \\
p_{21} & p_{22}
 \end{bmatrix} \\
&= \frac{1}{R} \begin{bmatrix}
               p_{11} ^2 & p_{11} p_{12}  \\
                p_{11} p_{12} & p_{22} ^2.
                \end{bmatrix}
\end{align*}

Sledilna enačba je, ko združimo vse izračunane člene

\[ \dot{P} = \begin{bmatrix}
             2p_{12} & p_{22} \\
             p_{22} & Q
              \end{bmatrix} - \frac{1}{R} \begin{bmatrix}
                                          p_{11}^{2} & p_{11}p_{12} \\
                                          p_{12}p_{11} & p_{12} ^2
                                           \end{bmatrix}  .
\]

Rešujemo torej sistem enačb

\begin{align*}
  \dot{p}_{11} &= 2 p_{12} - \frac{1}{R} p_{11} ^2 \\
\dot{p}_{12} &= p_{22}  - \frac{1}{R} p_{11} p_{12} \\
\dot{p}_{22} &= Q - \frac{1}{R} p_{12} ^2
\end{align*}

Iščemo stacionarno rešitev, saj rabimo konstantne koeficiente. Ojačevalni faktor bo \( K_{\infty} (\dot{P} = 0) \).

Iz zadnje enačbe dobimo enakost \( P_{12} = \sqrt{Q R} \).

V prvo enačbo vstavimo dobljeno vrednost

\[ p_{11} = \sqrt{2 R p_{12}} = \sqrt{2 R} \sqrt[4]{Q R}.
\]

Iz srednje enačbe pa dobimo

\[ p_{22} = \frac{1}{R} p_{11} p_{12} = 2 \sqrt[4]{QR}
\]

Ojačevalni faktor, katerega defincija je

\[ K_{\infty} = PH^T R^{-1} = \frac{1}{R} \begin{bmatrix}
                                          p_{11} & p_{12} \\
                                          p_{12} & p_{22}
                                           \end{bmatrix} \begin{bmatrix} 1 \\ 0 \end{bmatrix},
\]

bo potem imel vrednost

\[ K_{\infty} = \frac{1}{R} \begin{bmatrix} p_{11} \\ p_{12} \end{bmatrix} .
\]

V merilnem sistemu bodo potem ocene

\begin{align*}
  \dot{\hat{x}} &= \hat{v} + \frac{1}{R} p_{11} \left( z - \hat{x} \right) \\
\dot{\hat{v}} &= 0 + \frac{1}{R} p_{12} \left( z - \hat{x} \right).
\end{align*}

Prvo enačbo odvajamo po času in združimo

\[ \ddot{\hat{x}} = \frac{1}{R} p_{12} \left( z - \hat{x} \right) + \frac{1}{R} p_{11} (\dot{z} - \dot{\hat{x}}).
\]

Zgornjo enačbo lahko tudi zapišemo

\[ \ddot{\hat{x}} + \frac{p_{11}}{R} \dot{\hat{x}} + \frac{p_{12}}{R} \hat{x} = \frac{p_{11}}{R} \dot{z} + \frac{p_{12}}{R} z.
\]

Zapišemo s standardno notacijo

\begin{equation}
\label{eq:1}
 \ddot{\hat{x}} + 2 \xi \omega \dot{\hat{x}} + \omega ^2 \hat{x} = 2 \xi \omega \dot{z} + \omega ^2 z
\end{equation}

Vrednosti posamezni koeficientov so

\[\omega ^2 = \frac{p_{12}}{R} = \sqrt{\frac{QR}{R ^2}} = \sqrt{\frac{Q}{R}}
\]

ter

\[ 2 \xi \sqrt{\frac{p_{12}}{R}} = \frac{1}{R} \sqrt{2 R p_{12} \frac{1}{R}} \implies \xi = \frac{1}{2} \sqrt{2}.
\]

Enačbe \ref{eq:1} je enačba senzorja 2. reda.
*** Tipičen vhod \( \delta(t) \)

Podobno kot pri senzorjih prvega reda enačbo \ref{eq:1} integriramo po intervalu \( \left[ -\epsilon, \epsilon \right] \).

\[ \int\limits_{-\epsilon}^{\epsilon} \ddot{x} \, \mathrm{d} t + \int\limits_{- \epsilon}^{\epsilon} 2 \xi \omega \dot{x} \, \mathrm{d} t + \int\limits_{- \epsilon}^{\epsilon} \omega ^2 x \, \mathrm{d} t = \omega ^2 \int\limits_{- \epsilon}^{\epsilon} \delta(t) \, \mathrm{d} t.
\]

Zahtevamo začetne pogoje \( x(-t) = \dot{x}(-t) = 0 \).

Preostane nam

\[ \dot{x}(0) + 2 \xi \omega x(0) = \omega ^2.
\]

Začetni pogoji senzorja so

\[ x(0) = 0 \quad \text{ in } \quad \dot{x}(0) = \omega ^2.
\]

Homogen diferencialne enačbe

\[ \ddot{x} + 2 \xi \omega \dot{x} + \omega ^2 x = 0
\]

bomo rešili z nastavkom \( x = e^{\lambda x} \). Rešitvi za \( \lambda \) sta

\[ \lambda_{1, 2} = - \frac{2 \xi \omega \pm \sqrt{4 \xi ^2 \omega ^2 - \omega ^2}}{2}
\]

Prepišemo lahko ob upoštevanju \( \xi = \frac{1}{2} \) v

\begin{align*}
  \lambda_{1, 2} &= - \omega \left( \xi \mp \sqrt{\xi ^2 - 1} \right)\\
&= - \omega \left( \xi \mp \sqrt{1 - \xi ^2} \right) \\
&= - \omega \left( \frac{1}{\sqrt{2}} \mp \mathrm{i} \frac{1}{\sqrt{2}} \right)
\end{align*}

Karakteristični rešitvi zgornje enačbe sta torej

\[ \lambda_{1, 2} = - \frac{\omega}{\sqrt{2}} \left( 1 \mp \mathrm{i} \right).
\]

Njuna razlika je

\[ \lambda_1 - \lambda_2 = - \frac{2 \omega}{\sqrt{2} \mathrm{i}}.
\]

Imamo torej nastavek

\[ x = C_1 e^{\lambda_1 t} + C_2 e^{\lambda_2 t}.
\]

Ob upoštevanju začetnih pogojev \( x(0) = 0 \) dobimo \( C_1 = - C_2 \). Pred upoštevanjem drugega začetnega pogoja moramo odvajati nastavek

\[ \dot{x}(t) = C_1 \lambda_1 e^{\lambda_1 t} - C_1 \lambda_2 e^{\lambda_2 t}.
\]

Drugi začetni pogoj \( \dot{x}(0) = \omega ^2 \) dobimo vrednost konstante

\[ C_1 = \frac{\omega ^2}{\lambda_1 - \lambda_2} = \frac{\omega \sqrt{2}}{2 \mathrm{i}}.
\]

Rešitev je potem

\[ x (t) = \frac{\omega \sqrt{2}}{2 \mathrm{i}} \left( \exp \left\{  - \frac{\omega}{\sqrt{2}} (1 + \mathrm{i}) t\right\} - \exp \left\{ \frac{\omega}{\sqrt{2}} \left( 1 + \mathrm{i} \right) t \right\}  \right) = \omega \sqrt{2} \sin \left( \frac{\omega t}{\sqrt{2}} \right) \exp \left\{ - \frac{\omega t}{\sqrt{2}} \right\} = G(t).
\]
\]

Za splošen \( \xi \) pa je sta rešitvi kvadratne enačbe

\[ \lambda_{1, 2} = - \xi \omega \pm \mathrm{i} \omega \sqrt{1 - \xi ^2}.
\]

Njuna razlika je

\[ \lambda_1 - \lambda_2 = + \mathrm{i} \omega 2 \sqrt{1 - \xi ^2}.
\]

Enako enačbo dobimo za prvi začetni pogoj, za drugi začetni pogoj pa nam poda vrednost koeficienta

\[ C_1 = \frac{\omega ^2}{\lambda_1 - \lambda_2} = \frac{\omega}{\sqrt{1 - \xi ^2 } 2 \mathrm{i}}.
\]

Rešitev je potem

\[ x(t) = \frac{\omega}{\sqrt{1 - \xi ^2}} \left[ \frac{e^{\mathrm{i} \omega \sqrt{1 - \xi ^2} t} - e^{- \mathrm{i} \omega \sqrt{1 - \xi ^2} t}}{2 \mathrm{i}} \right] e^{- \xi \omega t} .
\]

Drugače lahko še zapišemo

\[ G(t) = x = \frac{\omega}{\sqrt{1 - \xi ^2}} \sin \left( \sqrt{1 - \xi ^2} \omega t \right) e^{- \xi \omega t},
\]

kar je Greenova funkcija senzorja 2. reda za poljuben \( \xi \).

Ločimo tri primere:

- \( \xi \to 0 \), kjer bo potem rešitev

  \[ x(t) = \omega \sin \left( \omega t \right).
  \]

  V tem primeru mamo nedušeno.

- v primeru \( \xi \to \frac{1}{\sqrt{2}} \) smo rešitev že zapisali in je optimalna rešitev senzorja 2. reda, ki eksponentno zaduši oscilatoren zapis

- v \( \xi \gg 1 \) imamo predušen senzor, kar pomeni, da lahko sinus razvijemo

  \begin{align*}
   x(t) &= \frac{\omega}{\sqrt{1 - \xi ^2 }} \sin \left( \sqrt{1 - \xi ^2 } \omega t \right) e^{- \omega t} \\
   &= \frac{\omega}{\xi ^2 - 1} \mathrm{sh} \left( \sqrt{\xi ^2 - 1 } \omega t \right)e^{- \xi \omega t}
  \end{align*}

  in nimamo več oscilatornega obnašanja.

*** Primer senzorja 2. reda

#+begin_my_example
Poglejmo si primer amortizerja oz. blažilnika.

Premikamo se na vrhu kolesa z amortizerjem. Naša vodoravna hitrost bo \( v \) in imamo maso \( m \).

Pri vožnji po kamenčkih se nam spreminja višina \( z(t) \). Zanima nas, kako se bo spreminjala naša višina \( x(t) \) v odvisnosti od odmika \( z(t) \).

V ravnovesju označimo \( x (t) = z(t) = 0 \).

Dinamika našega sistema bo odvisna od naše relativne lege in sile upora \( F_u = - \beta v \).

\[ m \ddot{x} = k \left( z - x \right) - \beta \left( \dot{x} - \dot{z} \right).
\]

Sila upora je ponovno odvisna od relativne lege. Dinamiko lahko prepišemo v

\[ \ddot{x} + \frac{\beta}{m} \dot{x} + \frac{k}{m} x = \frac{k}{m} z + \frac{\beta}{m} \dot{z}.
\]

Primerjamo enačbo \ref{eq:1} z zgornjo in lahko izluščimo vrednosti naših koeficientov. V primeru optimalnega senzorja bo še veljalo \( \xi = \frac{1}{\sqrt{2}} \).

Potem

\[ 2 \frac{1}{\sqrt{2}} \sqrt{\frac{k}{m}} = \frac{\beta}{m} \implies \beta = \sqrt{2 km} = \gamma \eta,
\]

kjer je \( \gamma \) koeficient upora in viskoznost \( \eta \).
#+end_my_example
** Laplaceova transformacija

Imamo meritve \( z(t) \) in ocene \( x(t) \), ki jih povezuje senzor prvega reda. Želeli bi tako integralsko transformacijo, ki diferencialno enačbo pretvori v algebraično.

Laplaceova transformacija \( \mathcal{L} \) je preslikava \( \mathcal{L}(x (t)) = x(s) \).

#+begin_definition
Laplaceova transformacija \( \mathcal{L}: f(t) \to F(s), \ s \in \mathbb{C} \) funkcije \( f(t) \) je

\[ \mathcal{L} \left( f(t) \right) = \int\limits_0^{\infty} f(t) e^{- st} \, \mathrm{d} t = F(s).
\]
#+end_definition

#+begin_theorem
Za funkcijo \( f(t) \) zahtevamo, da je njena vrednost in vsi odvodi ob času \( t = 0 \) ničelni.
Lastnosti Laplaceove transformacije so:

- \[ \mathcal{L}(1) = \int\limits_0^{\infty} e^{- s t} \, \mathrm{d} t = \left. \frac{1}{s} e^{-st} \right|_0^{\infty} = \frac{1}{s}.
  \]

- \[ \mathcal{L} \left( e^{at} \right) = \int\limits_0^{\infty} e^{(s - a) t} \, \mathrm{d} t = \frac{1}{s - a}.
  \]

- Produkt funkcije z eksponentno bodo
  \[ \mathcal{L} \left( f(t) e^{a t} \right) = \int\limits_0^{\infty} f(t) e^{(s - a) t} \, \mathrm{d} t = F(s - a).
  \]

- odvod funckije po parametru

  \[ \mathcal{L} \left( \frac{\mathrm{d} }{\mathrm{d} t} f(t) \right) = \int\limits_0^{\infty} \frac{\mathrm{d} }{\mathrm{d} t} f(t) e^{- st} \, \mathrm{d} t = s F(s)
  \]
  To se izračuna s pomočjo integriranja po delih za \( u = e^{- st} \) in \( \mathrm{d} v = \frac{\mathrm{d} }{\mathrm{d} t} f(t) \, \mathrm{d} t \).

- \[ \mathcal{L} \left( t \right) = \int\limits_0^{\infty} t e^{- st }\, \mathrm{d} t = \frac{1}{s ^2}.
  \]

  Do te identitete lahko pridemo tudi z uporabo prve alineje in lastnosti odvajanja.

- Podobno kot prejšnja alineja

  \[ \mathcal{L} \left( t^n \right) = n! \frac{1}{s ^{n + 1}}.
  \]

- z uporabo druge alineje za \( e^{\mathrm{i} \omega t} \) lahko dobimo vrednost za kosinus in sinus

  \[ \mathcal{L} \left( \cos (\omega t) + \mathrm{i} \sin (\omega t)  \right) = \mathcal{L} \left( e^{\mathrm{i} \omega t} \right) = \frac{s}{s ^2 + \omega ^2} + \mathrm{i} \frac{\omega}{s ^2 + \omega ^2}.
  \]

  Torej

  \[ \mathcal{L} \left( \cos \left( \omega t \right) \right) = \frac{s}{s ^2 + \omega ^2} \quad \text{ in } \quad \mathcal{L} \left( \sin \left( \omega t \right) \right) = \frac{\omega}{s ^2 + w ^2}.
  \]
#+end_theorem
** Prenosna funkcija senzorja

Splošna diferencialna enačba senzorja je oblike

\[\frac{\mathrm{d} ^{n}}{\mathrm{d} t^{n}} x + a_{n - 1} \frac{\mathrm{d} ^{n - 1}}{\mathrm{d} t^{n - 1}} x + \ldots + a_1 \frac{\mathrm{d} }{\mathrm{d} t} x+ a_0 x = \frac{\mathrm{d} ^{m}}{\mathrm{d} t^{m}} z + b_{m - 1} \frac{\mathrm{d} ^{m - 1}}{\mathrm{d} t^{m - 1}} z_1 + \ldots b_1 \frac{\mathrm{d} }{\mathrm{d} t} z + b_0 z.
\]

Enačbo lahko Laplaceovo transformiramo v

\[ \left( s^n + a_{n - 1} s^{n - 1} + \ldots + a_1 s + a_0 \right) x(s) = \left( s^m + b_{m - 1} s^{m - 1} +  \ldots + b_1 s + b_0 \right) z(s),
\]

kjer smo upoštevali \( \mathcal{L}(x(t)) = x(s) \) in \( \mathcal{L} (z(t)) = z(s) \). Njuno razmerje bo potem

\[ \frac{x(s)}{z(s)} = H(s) = \frac{s^m + b_{m - 1} s^{m - 1} +  \ldots + b_1 s + b_0 }{s^n + a_{n - 1} s^{n - 1} + \ldots + a_1 s + a_0}
\]

Kjer smo uvedli \( H(s) \) kot prenosno funkcijo senzorja. Zahtevamo \( n \ge m \) in \( n \ge 3 \).

#+begin_my_example
Za senzor prvega reda je prenosna funkcija

\begin{equation}
\label{eq:2}
 \frac{x(s)}{z(s)} = H(s) = \frac{1}{1 + \tau s}.
\end{equation}

Do nje pridemo preko Laplaceov transformacije enačbe senzorja 1. reda

\[ \tau \dot{x} + x = z(t),
\]

ki je

\[ \left( \tau s + 1 \right) x(s) = z(s).
\]
#+end_my_example

#+begin_my_example
Za senzor prvega reda je Laplaceova transformacije enačbe

\[ \left( s ^2 + 2 \xi \omega s + \omega ^2 \right) x(s) = \left( 2 \xi \omega s + \omega ^2 \right) z(s)
\]

in potem je prenosna funckija za senzor drugega reda

\[ H(s) = \frac{\omega ^2 + 2 \xi \omega s}{s ^2 + 2 \xi \omega s + \omega ^2}.
\]
#+end_my_example

#+begin_my_example
Vrnimo se nazaj k tipičnemu signalu \( \delta(t) \) za senzor prvega reda.

Laplaceova transformacije tipičnega signala je \( z(s) = 1 \). Upoštevamo enačbo \ref{eq:2} in dobimo

\[ x(s) = H(s) z(s) = 1 \left( \frac{1}{1 + \tau s} \right) = \frac{1}{\frac{1}{\tau} + s} \left( \frac{1}{\tau} \right).
\]

Prepoznamo v ulomku \( \mathcal{L} \left( e^{- \frac{t}{\tau}} \right) \) in je torej

\[ x(t) = \frac{1}{\tau} e^{- \frac{t}{\tau}}.
\]
#+end_my_example

#+begin_my_example
Tipičen signal Heavisideove funkcije je

\[ z(t) = H (t) z_0 .
\]

Njena Laplaceova transformiranka je

\[ z(s) = \frac{1}{s} z_0.
\]

Za senzor prvega reda je potem

\[ x(s) = \frac{1}{s} \cdot \frac{1}{1 + \tau s} z_0.
\]

Razcepimo na parcialna ulomka

\[ x(s) = z_0 \left[ \frac{1}{s} - \frac{\tau}{1 + \tau s} \right]
\]

in iz lastnosti Laplaceove transformacije prepoznamo inverzne transformacije

\[ x(t) = z_0 \left[ \mathcal{L} (1) - \mathcal{L} \left( e^{- \frac{t}{\tau}} \right) \right] = \left( 1 - e^{- \frac{t}{\tau}} \right) z_0
\]
#+end_my_example
