#+title: Predavanja iz Fizikalnih merjenj, 10. teden v letu
#+subtitle: 2026/03/05
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Merjenje skalarnih spremenljivk \( x(t) \)

V primeru, da ne poznamo dinamike, potem bo najboljša dinamike kar

\[ \hat{x}(t) = z(t).
\]

Varianca je potem kar

\[ \hat{\sigma}_x ^2 (t) = R.
\]

V primeru, če poznamo dinamiko med sistemi, potem rešujemo linearno diferencialno enačbo 1. reda

\[ \dot{x} (t) = A x + C(t).
\]

V diskretnem prostoru, kjer vzorčimo s časom \( T \), bo zgornja diferencialna enačba postala diferenčna enačba

\[ \dot{x} = \frac{x_{n + 1} - x_n}{T},
\]

kjer sta \( x_{n + 1} = x((n + 1)T) \) in \( x_n = x(n T) \). Potem lahko izrazimo \( x_{n + 1} \)

\[ x_{n + 1} = x_n + \left( A (nT) x_n + C(nT) \right) T = \left( 1 + A(nT) T \right) x_n + C(nT).
\]

Z uvedbo \( \phi_n = (1 + A(nT) T) \) in \( c_n = C(n T) T \) je krajši zapis

\[ x_{n + 1} = \phi_n x_n + c_n.
\]

Porazdeljenost se ohranja tudi znotraj diferenčne enačbe, saj sta množenje in seštevanje linearni operaciji.

Isto dinamiko privzamemo tudi za oceno \( \hat{x} \) v merilnem sistemu \( M \).

Recimo, da smo opravili \( n \) vzorčenj. Z znano dinamiko v času \( t = n T \) in optimalno oceno \( \hat{x}_n \) in \( \hat{\sigma}_n ^2 \), lahko napovemo oceno v času \( t = (n + 1) T \)

\[ \bar{x}_{n + 1} = \phi_n \hat{x}_n + c_n \quad \text{ in } \quad \bar{\sigma}_{n + 1} ^2 = \phi_{n ^2} \hat{\sigma}_n ^2.
\]

Dokažimo, da ta napoved ocene drži.

Varianco zapišemo po definiciji

\[ \hat{\sigma}_n ^2 = \left\langle \left( \hat{x}_n - x_n \right) ^2 \right\rangle.
\]

Napoved variance pa je

\[ \bar{\sigma}_{n + 1} ^2 = \left\langle \left( \bar{x}_{n + 1} - x_{n + 1}\right) ^2 \right\rangle.
\]

Upoštevamo napoved ocene in razpišemo

\[ \bar{\sigma}_{n + 1} ^2 = \left\langle \left[ \left( \phi_n \hat{x}_n + c_n \right) ^2 - \left( \phi_n x_n + c_n \right) ^2\right] \right\rangle = \left\langle \left[ \phi_n \left( \hat{x}_n - x_n \right) \right] ^2 \right\rangle.
\]

Zaključimo torej

\[ \bar{\sigma}_{n + 1} ^2 = \phi_n ^2 \left\langle \left( \hat{x}_n - x_n \right) ^2 \right\rangle = \phi_n ^2 \hat{\sigma}_n ^2.
\]

Za meritev \( z_{n + 1} \) z varianco \( \sigma ^2 \) lahko izostrimo oceno v času \( t = (n + 1) T \) z enačbami

\[ \hat{x}_{n + 1} = \bar{x}_{n + 1} + \frac{\sigma_{n + 1} ^2}{\sigma ^2} \left( z_{n + 1} - \bar{x}_{n + 1} \right) \quad \text{ in } \quad \hat{\sigma}_{n + 1} ^{-2} = \bar{\sigma}_{n + 1}^{-2} + \sigma^{-2}.
\]

Zgornjemu postopku pravimo ostrenje z meritvijo.

Uvedemo nove oznake: \( \hat{\sigma}_{n + 1} ^2 \) postane kovarianca izostrene ocene \( P_{n +1} \). \( \bar{\sigma}_{n + 1} ^2 \) postane kovarianca napovedi \( M_{n + 1} \), \( \frac{\hat{\sigma}_{n + 1} ^2}{\sigma ^2} \) postane ojačevalni faktor \( K_{n + 1} \) in \( \left( z_{n + 1} - \bar{x}_{n + 1} \right) \) je inovacija.

Z novimi oznakami imamo tako

\[ M_{n + 1} = \phi_n ^2 P_n \quad \text{ in } \quad P_{n + 1} = \frac{M_{n + 1} \sigma ^2}{M_{n + 1} + \sigma ^2}= M_{n + 1} - \frac{M_{n + 1} ^2}{M_{n + 1} + \sigma ^2}
\]
** Dinamični šum

Dinamiko spremenljivke \( x(t) \) v sistemu \( S \) ne poznamo eksaktno.

Spremenljivko spreminja nek neznan člen

\[ x_{n + 1} = \phi_n x_n + c_n + w(t),
\]

za katerega ne vemo ali je pozitiven ali negativen. Posledično lahko zaključimo, da je njena pričakovana vrednost \( \left\langle w \right\rangle = 0 \). Neznanemu členu pravimo naključeno šum.

Primer takega šuma so trki med delci: okolica deluje na delec v pozitivni ali negativni smeri.

Za naključen šum velja

\[ \left\langle w_n, w_{n'} \right\rangle = \delta_{n, n'} Q,
\]

kjer je \( Q \) velikost dinamičnega šuma, ki je nekorelirana (\( \delta \)).

Ponovna analogija s trki med delci: kam se delec odbije v naslednjem trenutku je neodvisno od trkov s prejšnjimi delci.

V diskretni obliki spremenljivko \( x \) zapišemo z dinamičnim šumom

\[ x_{n + 1} = \phi_n x_n + c_n + \Gamma_n w_n.
\]

V sistemu \( M \) pa bo odstopanje od spremenljivko v sistemu \( S \) ravno \( \Gamma_n w_n \), saj ne poznamo dinamike šuma. V sistemu \( M \) je ocena

\[ \bar{x}_{n + 1} = \phi \hat{x}_n + c_n.
\]

To odstopanje na ostrenje z meritvijo

\[ \hat{x}_{n + 1} = \bar{x} _{n + 1} + \frac{\hat{\sigma}_{n + 1} ^2}{\sigma ^2} \left( z_{n + 1} - \bar{x}_{n + 1} \right),
\]

ne bo imelo vpliva.

Poglejmo si, kakšen vpliv pa bo imela na kovarianco napovedi

\begin{align*}
  M_{n + 1} &= \left\langle \left[ \left( \bar{x}_{n + 1} - x_{n + 1} \right) \right]^2 \right\rangle \\
&= \left\langle\left[ \left( \phi_n \hat{x}_n  + c_n \right) - \left( \phi_n x_n + c_n + \Gamma_n w_n \right)\right] ^2  \right\rangle \\
&= \left\langle \left[ \phi_n \left( \hat{x}_n - x_n \right) - \Gamma_n w_n \right] ^2 \right\rangle.
\end{align*}

Kvadriramo oklepaje in ni korelacije med \( \hat{x}_n, x_n \) in \( w_n \), nam ostane samo

\begin{align*}
  M_{n + 1} &= \left\langle \phi_n ^2 \left( \hat{x}_n - x \right) ^2 + \left( \Gamma_n w_n \right) ^2 \right\rangle \\
&= \phi_n ^2 P_n + \Gamma_n ^2 \left\langle w_n ^2 \right\rangle.
\end{align*}

Kovarianca napovedi ima torej v vsakem trenutku prišteto dodaten konstanten člen

\[ M_{n + 1} = \phi_n ^2 P_n + Q_n.
\]

Pri prehodu v zvezno sliko je ocena spremenljivke v sistemu \( M \)

\[ \hat{x}_{n + 1} = \bar{x}_{n + 1} + K_{n + 1} \left( z_{n + 1} - \bar{x}_{n + 1} \right).
\]

Upoštevamo definicijo napovedi in

\[ \frac{\hat{x}_{n + 1} - x_n}{T} = \frac{\phi_n \hat{x}_n + c_n - \hat{x}_n + K_{n + 1} (z_{n + 1} - \bar{x}_{n + 1})}{T}.
\]

Dodatno lahko pretvorimo v

\[ \frac{\hat{x}_{n + 1} - \hat{x}_n}{T} = \frac{\left( \phi_n - 1 \right)}{T} \hat{x}_n + \frac{c_n}{T} + \frac{P_{n + 1}}{\sigma ^2 T} \left( z _{n + 1} - \bar{x}_{n + 1} \right).
\]

V limiti \( T \to 0 \) dobimo enačbo

\[ \dot{\hat{x}} = A(t) \hat{x}(t) + c(t) + \frac{P(t)}{R} \left( z(t) - \hat{x}(t) \right),
\]

kjer je \( \frac{\phi_n - 1}{T} = A(t) \) in \( \sigma ^2 T = R \). Upoštevali smo, da v limiti \( \hat{x}_n = \bar{x}_n = \hat{x}(t) \) in napoved kovariance \( M_{n + 1} \) je \( P(t) \) (prav tako je v limiti \( P_{n + 1} = P(t) \)).

Na podoben način želimo preiti v zvezno sliko tudi pri kovarianci izostrene ocene

\[ P_{n + 1} = M_{n + 1} - \frac{M_{n + 1} ^2}{M_{n + 1} + \sigma ^2} = \phi_n ^2 P_n + \Gamma_n Q_n - \frac{\left( \phi_n ^2 P_n + \Gamma_n  ^2 Q_n \right) ^2}{M_{n + 1} + \sigma ^2}.
\]

Za postopanje do odvoda zapišemo

\[ \frac{P_{n + 1} - P_n}{T}= \frac{\left( \phi_n ^2 - 1 \right)P_n}{T} + \frac{\Gamma_n ^2 Q_n}{T} - \frac{\phi_n ^2 P_n ^2 + 2 \phi_n ^2 P_n \Gamma_n ^2 Q_n + \Gamma_n ^4 Q_n ^2}{TM_{n + 1} + \sigma ^2 T} .
\]

V limiti \( T \to 0 \) gre \( \phi_n \to 1 \), hkrati pa upoštevamo identiteto od prej in lahko prvi člen zapišemo

\[ \frac{\left( \phi_n ^2 - 1 \right)P_n}{T} = \left( \phi_n - 1 \right)\frac{\left( \phi_n - 1 \right) }{T} P_n = 2 A P(t).
\]

Povejmo še nekaj limit. Po definicije nekorelacije velja \( \left\langle w_k w_{k'} \right\rangle = \delta_{k k'} Q_n \), iz česar sledijo limite

\begin{align*}
  \lim_{T \to 0} \left( Q_n T \right) &= Q(t)\\
\lim_{T \to 0} \left( \sigma ^2 T \right) &= R(t) \\
\lim_{T \to 0} \left( \frac{\Gamma_n}{T} \right) &= T(t)
\end{align*}

Drugi člen moramo pomnožiti s \( \frac{T}{T} \), da lahko zapišemo limito

\[ \frac{\Gamma_n ^2 Q T}{T ^2} = \Gamma ^2 Q.
\]

Pri zadnjem členu pa je v limiti

\[ \frac{\phi_n ^2 P_n ^2 + 2 \phi_n ^2 P_n \Gamma_n ^2 Q_n + \Gamma_n ^4 Q_n ^2}{TM_{n + 1} + \sigma ^2 T} =  \frac{1}{T M(t) + R} \left[ P ^2(t) + \frac{2 P \Gamma Q T}{T} + \Gamma ^2 (t) Q(t) T ^2 \right].
\]

Zadnje dva člena smo razširili s \( T \) in v limiti sta potem ničelna. Končna enačba je torej

\[ \dot{P} = 2 A P(t) + \Gamma ^2 Q - \frac{P ^2}{R}.
\]

Prvi člen nam pove dinamiko, drugi člen nam povečuje kovarianco zaradi dinamičnega šuma, tretji člen pa zmanjša kovarianco zaradi dotoka novih meritev.
* Vektorske spremenljivke

V sistemu \( S \) popišemo več spremenljivk \( \mathbf{r} = [x,y]^T = [x, v]^T \).

Včasih nam dinamika narekuje, da bi morali opazovati spremenljivk višjega reda, je Newtonov zakon \( \sum_{}^{} F = m a = m \ddot{x} \). Pri njem imamo 2. red spremenljivke \( x(t) \). Namesto tega prevedemo opazovanje na več spremenljivk \( \dot{x} = v \) in \( \dot{v} = \sum\limits_{}^{} \frac{F}{m} \) nižjega reda.

Potem bo opazovani sistem

\[ \frac{\mathrm{d} }{\mathrm{d} t} \begin{bmatrix} x \\ v \end{bmatrix} = \begin{bmatrix}
                                                                           0 & 1 \\
                                                                           0 & 0
                                                                            \end{bmatrix} \begin{bmatrix} x \\ v \end{bmatrix} + \mathbf{c}.
\]

Sedaj imamo sistem diferencialnih enačb.

Imamo torej spremenljivke

\[ \mathbf{x} = \begin{bmatrix} x_{1} \\ x_{2} \\ x_{3} \\ ldots \\ x_{n} \end{bmatrix}.
\]

Ocene v sistemu \( M \) s pripadajočimi disperzijami pa so

\[ \hat{\mathbf{x}} = \begin{bmatrix} \hat{x}_{1} \\ \hat{x}_{2} \\ \ldots \\ \hat{x}_{n} \end{bmatrix} \end{bmatrix}.
\]

Ker so disperzije lahko medseboj korelirane

\[ \left\langle \left( \hat{x}_i - x_i \right) ^2 \right\rangle = \hat{\sigma}_{x_i} ^2 \quad \text{ in } \quad \left\langle \left( \hat{x}_i - x_i \right) \left( \hat{x}_j - x_j \right) \right\rangle = \hat{\sigma}_{x_i, x_j}.
\]

Zapišemo jih v kovariančno matriko \( P \) za \( \dot{\mathbf{x}} \)

\[ P = \begin{bmatrix}
       \hat{\sigma}_{1} ^2 & & & & &  \\
        & \hat{\sigma}_2 ^2 & & & &  \\
        &  & \ddots & & & \\
        & & \hat{\sigma}_{ij} & \hat{\sigma}_{ii} ^2 & & \\
        & & & & \ddots & \\
        & & & & & \hat{\sigma}_n ^2
       \end{bmatrix},
\]

kjer so diagonalni komponenti variance, izvendiagonalne komponente pa korelacije.

#+name: Ostrenje
#+begin_problem

Imejmo sistem \( S \) s spremenljivkama \( \mathbf{x} = [x, v]^T \). Zajemamo meritve oblike \( z = x + r \), kjer je \( \left\langle r ^2 \right\rangle = \sigma_r ^2\). Ocene v merilnem sistemu \( M \) so

\[ \hat{\mathbf{x}} = \begin{bmatrix} \hat{x} \\ \hat{v} \end{bmatrix} = \begin{bmatrix} x + p_{x} \\ v + p_{v} \end{bmatrix}.
\]

Povprečje ocene je potem

\[ \left\langle \mathbf{x} \right\rangle = \begin{bmatrix} \left\langle x \right\rangle \\ \left\langle p \right\rangle \end{bmatrix} = \begin{bmatrix} x + m_x  \\ v + m_v \end{bmatrix}.
\]

[nadomesti langle with bar!]

Veljajo nekorelacije

\[ \left\langle r m_x \right\rangle = \left\langle r p_x \right\rangle = \left\langle r m_v \right\rangle = 0.
\]

Poskusimo ostriti z linearno superpozicijo

\begin{align*}
  \hat{x} &= x + p_x = a_{xx } \bar{x} + a_{xv} \bar{v} + b_x z \\
\hat{v} &= v + p_v = a_{vx } \bar{x} + a_{vv } \bar{v} + b_v z
\end{align*}

Zapišemo torej

\[ \hat{x} = a_{xx } (x + m_x) + a_{xv}  (v + m_v) + b_x (x + r).
\]

In ker je

\[ x + p_x = x (a _{xx } + b_x) + a_{xv} v + a_{xv} m_v + a_{xx } m_x + b_x r,
\]

in na levi strani nimamo nobenega člena z \( v \), zaključimo \( a_{xv} = 0 \). Hkrati pa dobimo tudi pogoj \( a_{xx } + b_x = 1 \). Potem je

\[ p_x = a_{xx } m_x + b_x r = a_{xx } m_x + (1 - a_{xx }) r.
\]

Pričakovane vrednosti so ničelne, zato bomo gledali variance

\begin{align*}
  \left\langle p_x ^2 \right\rangle = a_{xx } ^2 \left\langle m_x \right\rangle ^2 + (1 - a_{xx }) ^2 \left\langle r ^2 \right\rangle + a_{xx } (1 - a_{xx }) \left\langle w_x r \right\rangle \\
&= a_{xx } ^2 \sigma_x ^2 + (1 - a_{xx }) ^2 \sigma_r ^2.
\end{align*}

Upoštevali smo nekoreliranost. Optimalna ocena je potem pri

\[ \frac{\mathrm{d} }{\mathrm{d} a_{xx }} \left\langle p_x ^2 \right\rangle  = 0,
\]

kar je pri

\[ a_{xx } \frac{\sigma_r ^2}{\sigma_r ^2 + \sigma_x ^2}.
\]

Na podoben način pridemo tudi pri \( \hat{v} \)

\[ v + p_v = (a_{vx} + b_v) x + a_{vx} m_x + a_{vv} v + a_{vv} m_v + b_v.
\]

Zaključimo, da je \( a_{vv} = 1 \) ter \( a_{vx} + b_v = 0 \).

Torej

\[ p_v = a_{vx} m_x + m_r + b_v r = \left( a_{vx} (m_x - r) + m_r \right) ^2.
\]

Izračunamo kvadrat in varianco

\[ \left\langle p_v ^2 \right\rangle = a_{vx} ^2 \left[ \left\langle m_x ^2 \right\rangle + \left\langle r ^2 \right\rangle \right] + \left\langle m_v ^2 \right\rangle + 2 a_{vx} \left\langle m_x m_v \right\rangle.
\]

Po odvodu

\[ \frac{\mathrm{d} }{\mathrm{d} a_{vx}} \left\langle p_v ^2 \right\rangle = 0,
\]

dobimo

\[ a_{vx} = -\frac{\left\langle m_x m_v \right\rangle}{\sigma_x ^2 + \sigma_r ^2}.
\]

Ocena bo torej, ko nadomestimo vse izpeljane člene

\[ \hat{x} = \bar{x} + \frac{\sigma_x ^2}{\sigma_x ^2 + \sigma_r ^2} \left( z - \bar{x} \right)
\]

in

\[ \hat{v} = \bar{v} + \frac{\left\langle m_x m_v \right\rangle}{\sigma_x ^2 + \sigma_r ^2} \left( z - \bar{x} \right).
\]

Zaključimo, da z meritvijo lege in korelacije hkrati ostrimo tudi komponento hitrosti, čeprav je nismo direktno merili.

#+end_problem
