#+title: Predavanja iz Fizikalnih merjenj, 0. teden v letu
#+subtitle: 2026/02/26
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Optimalno filtriranje
** Merilni šum

Spomnimo: izmerek je definiran kot

\[ z = x + r,
\]

kjer je \( x \) prava vrednosti, \( r \) pa šum porazdeljen po normalni porazdelitvi \( N(0, \sigma) \).

Pričakovana vrednost šuma je

\[ \left\langle r \right\rangle = \int\limits_{- \infty}^{\infty} \frac{\mathrm{d} P}{\mathrm{d} r} \cdot r \, \mathrm{d} r = 0,
\]

saj je \( r \) liha funkcija na sodem intervalu.

To pomeni, da bo varianca - odstopanje od pričakovane vrednosti

\[ \left\langle \left( r - \left\langle r \right\rangle \right) ^2 \right\rangle = \left\langle r ^2 \right\rangle.
\]

Pričakovana vrednost kvadrata pa je

\begin{align*}
  \left\langle r ^2 \right\rangle &= \int\limits_{}^{} \frac{\mathrm{d} P}{\mathrm{d} r} \cdot r ^2 \, \mathrm{d} r \\
&= \int\limits_{}^{} \frac{1}{\sqrt{2 \pi}} \frac{1}{\sigma} r ^2 e^{- \frac{r ^2}{2 \sigma ^2}} \, \mathrm{d} r.
\end{align*}

Uvedemo novo spremenljivko \( \frac{r ^2}{2 \sigma ^2} = u ^2 \) in \( \mathrm{d} r = \sqrt{2 \sigma} \mathrm{d} u \) in vrednost integrala je

\[ \left\langle r ^2 \right\rangle = 2 \sigma ^2 \frac{1}{ \sqrt{\pi}} \int\limits_{}^{} u ^2 e^{- u ^2} \, \mathrm{d} u = \sigma ^2,
\]

saj je vrednost integrala \( \frac{\pi}{2} \).

V primeru uvedbe spremenljivke \( u = \frac{r}{\sigma} \), potem je \( u \) porazdeljen po \( N (0, 1) \), kar je standardizirana normalna porazdelitev.
** Povprečevanje

Imamo izmerke \( z_i \) za \( i = 1,2, \ldots, N \), ki so porazdeljeni po \( N(x, \sigma) \). Povprečje teh izmerkov je potem

\[ \bar{z} = \frac{1}{N} \sum\limits_{i = 1}^N z_i.
\]

Zanima nas, kakšna pa je porazdelitev povprečne vrednosti \( \frac{\mathrm{d} P}{\mathrm{d} \mathbf{z}} \).

Povprečna vrednost odstopanja za \( i \to \infty \) je ničeln

\[ \overline{\left( z_i - x \right)} = \bar{r} = 0.
\]

Iz tega razloga je tudi

\[ \overline{\left( \bar{z} - x\right)} = 0,
\]

saj je \( \bar{z} \) definirana z \( z_i \).

Izračunati moramo še

\begin{align*}
  \overline{\left( \bar{z} - z \right) ^2} &= \overline{\left( \frac{1}{N} \sum\limits_{i=1}^N z_i - x \right) ^2} \\
&= \frac{1}{N ^2} \overline{\left( \sum\limits_{i = 1}^N z_i - N x \right) ^2} \\
&= \frac{1}{N ^2} \overline{\left( \sum\limits_{i = 1}^N (z_i - x) \right) ^2} \\
&= \frac{1}{N ^2} \left( \overline{\sum\limits_{i = 1}^N \left( z_i - x \right) ^2} + \overline{\sum\limits_{i = 1}^N \sum\limits_{j = 1}^N \left( z_i - x \right) \left( z_j - x \right)} \right) \\
&= \frac{1}{N ^2} \left( \overline{\sum\limits_{i = 1}^N \left( z_i - x \right) ^2} + \overline{\sum\limits_{i = 1}^N \sum\limits_{j = 1}^N r_i r_j}  \right) \\
&= \frac{1}{N ^2} \sum\limits_{i = 1}^N \overline{\left( z_i - x \right) ^2} = \frac{\sigma}{N}
\end{align*}

Zaključimo torej, da je povprečna vrednost porazdeljena po ožji normalni porazdelitvi

\[ \frac{\mathrm{d} P}{\mathrm{d} \bar{z}} = N\left(x, \frac{\sigma}{\sqrt{\pi}}\right).
\]

To je tudi smisel ponavljanja in povprečevanja vrednosti.
** 2 oceni iste količine z različnima disperzijama

Imejmo dve oceni

\[ \bar{z}_1 = \frac{1}{n} \sum\limits_{i = 1}^n z_i, \ \sigma_1 ^2 = \frac{\sigma ^2}{n} \quad \text{ in } \quad \bar{z}_2 = \frac{1}{m} \sum\limits_{i = 1}^m z_i, \ \sigma_2 ^2 = \frac{\sigma ^2}{m}
\]

Oceni želimo združiti v oceno \( z_3 \) z disperzijo \( \sigma_3 \). Po definiciji bo povprečje te ocene

\[ \bar{z}_3 = \frac{1}{n + m} \sum\limits_{i = 1}^{n + m} z_i, \ \sigma_3 ^2 = \frac{\sigma}{n + m}.
\]

Razdelimo vsoto na dva dela

\[ \bar{z}_3 = \frac{n}{n + m} \left( \frac{1}{n} \sum\limits_{i = 1}^n z_i \right) + \frac{m}{n + m} \left( \frac{1}{m} \sum\limits_{i = 1}^m  z_i \right),
\]

kjer sta faktorja \( \frac{n}{n + m} \) in \( \frac{m}{ n + m}  \) uteži, ki ju lahko zapišemo tudi z disperzijo

\[ \frac{n}{n + m} = \frac{\sigma ^2 \sigma_3 ^2}{\sigma_1 ^2  \sigma ^2} = \frac{\sigma_3 ^2}{\sigma_1 ^2} \quad \text{ in } \quad \frac{m}{n + m} = \frac{\sigma_3 ^2}{\sigma_2 ^2}.
\]

Hkrati velja še

\[ \sigma_3 ^{-2} = \frac{n + m}{\sigma ^2} = \sigma_1 ^2 + \sigma_2 ^2,
\]

iz česar sledi

\[ \frac{1}{\sigma_3 ^2} = \frac{1}{\sigma_1 ^2} + \frac{1}{\sigma_2 ^2} \quad \text{ in } \quad \sigma_3 ^2 = \frac{\sigma_1 ^2 \sigma_2 ^2}{\sigma_1 ^2 + \sigma_2 ^2}.
\]

Združeno oceno torej zapišemo kot

\[ \bar{z}_3 = \frac{\sigma_3 ^2}{\sigma_1 ^2} \bar{z}_1 + \frac{\sigma_3 ^2}{\sigma_2 ^2} \bar{z}_2
\]

Sledi

\[ \bar{z}_3 = \frac{\sigma_2 ^2}{\sigma_1 ^2 + \sigma_2 ^2} \bar{z}_1 + \frac{\sigma_1 ^2}{\sigma_1 ^2 + \sigma_2 ^2} \bar{z}_2,
\]

kar lahko zapišemo tudi kot

\begin{equation}
\label{eq:1}
 \bar{z}_3 = \bar{z}_1 + \frac{\sigma_1 ^2}{\sigma_1 ^2 + \sigma_2 ^2} \left( \bar{z}_2 - \bar{z}_1 \right),
\end{equation}

kjer je \( \bar{z}_3 \) nova ocena, \( \bar{z}_1 \) stara ocena, faktor pred oklepajem utež in razlika v oklepaju je inovacija.

\( \sigma_1 \ll \sigma_2 \) nam pove, da ima bolj natančna ocena večjo utež. Enačba \ref{eq:1} je optimalno združena ocena.
** Kvadratna forma
[dopolni]
** Disperzija optimalno združene ocene

Imamo dva izmerki

\[ z_1 = x + r_1, \ \left\langle r_1 ^2 \right\rangle = \sigma_1 ^2 \quad \text{ in } \quad z_2 = x + r_2, \ \left\langle r_2 ^2 \right\rangle = \sigma_2 ^2.
\]

Združena ocena bo linearna kombinacija obeh

\[ z_3 = x + r_3 = \alpha z_1 + \beta z_2,
\]

iz česar sledi

\[ x + r_3 =  \left( \alpha + \beta \right) x + \alpha r_1 + \beta r_2.
\]

Dobimo pogoj \( \alpha + \beta = 1 \) in posledično velja \( \alpha r_1 + \beta r_2 = r_3 \).

Pričakovana vrednost \( r_3 \) je 0, saj sta pričakovani vrednosti posameznih komponent \( 0 \).

Pričakovana vrednost kvadrata pa je

\begin{align*}
  \left\langle r_3 ^2 \right\rangle &= \left\langle \left( \alpha r_1 + \left( 1 - \alpha \right) r_2 \right) ^2 \right\rangle \\
&= \left\langle \alpha ^2 r_1 ^2 + \left( 1 - \alpha \right) ^2 r_2 ^2  + 2 \alpha \left( 1 - \alpha \right)r_1 r_2\right\rangle
\end{align*}

Disperzija združene meritve je torej

\[ \sigma_3 ^2 = \alpha ^2 \left\langle r_1 ^2 \right\rangle + \left( 1 - \alpha \right) ^2 \left\langle r_2 ^2 \right\rangle + 2 \alpha \left( 1 - \alpha \right) \left\langle r_1 r_2 \right\rangle
\]

Šuma sta nekorelirana, zato je njuna pričakovana vrednost \( 0 \). Z odvajanjem po parametru \( \alpha \) lahko določimo optimalno vrednost disperzijo

\[ \frac{\mathrm{d} }{\mathrm{d} \alpha} \left( \sigma_3 ^2 \right) = 2 \alpha \sigma_1 ^2 + 2 \left( 1- \alpha \right) (-1) \sigma_2 ^2 = 0.
\]

Dobimo potrditev, da je to dejansko optimalno združena meritev, saj sta enaka rezultata kvadratni formi

\[ \alpha = \frac{\sigma_2 ^2}{\alpha_1 ^2 + \sigma_2 ^2} \quad \text{ in } \quad \beta = 1 - \alpha = \frac{\sigma_1 ^2}{\sigma_1 ^2 + \sigma_2 ^2}
\]
** Korelacija in kovarianca

Imamo 2 seta meritev \( \left\{ x_i \right\} \) in \( \left\{ y_i \right\} \) za \( i = 1, 2, \ldots, N \).

Obstaja povezava med šumom prve in druge meritve

\[ w_x = x_i - \bar{x} \quad \text{ in } \quad w_y = y_i - \bar{y},
\]

kjer je \( \bar{w}_x = \bar{w}_y =0 \) in \( \bar{w}_x ^2 = \sigma_x ^2 \) in \( \bar{w}_y ^2 = \sigma_2 \)

Definicija kovariance je

\[ \sigma_{xy} = \rho_{xy} \sigma_x \sigma_y = \overline{w_x w_y},
\]

kjer je \( \rho_{xy} \) korelacijski koeficient in zaseda vrednosti \( \left| \rho_{xy} \right| \le 1\).

Dokazujemo, da je

\[ \sigma_{xy} = \overline{xy} - \bar{x} \bar{y}.
\]

Upoštevamo defincije

\begin{align*}
  \sigma_{xy} &= \overline{xy} - \bar{x} \bar{y} \\
&= \frac{1}{N} \sum\limits_{}^{}\left( x_i - \bar{x} \right) \left( y_i - \bar{y} \right) \\
&= \frac{1}{N} \sum\limits_{}^{} \left( x_i y_i - x_i \bar{y} - \bar{x} y_i + \bar{x} \bar{y} \right) \\
&= \frac{1}{N} \left( \sum\limits_{}^{} x_i y_i - \bar{y} \sum\limits_{}^{} x_i - \bar{x} \sum\limits_{}^{} y_i + \bar{x} \bar{y} \sum\limits_{}^{} i \right) \\
&= \left( \frac{1}{N} \sum\limits_{}^{} x_i y_i - \bar{x} \bar{y} - \bar{x} \bar{y} + \bar{x} \bar{y} \frac{N}{N} \right) \\
&= \overline{xy} - \bar{x} \bar{y}
\end{align*}

Za nekolerirane ocene velja \( \rho = 0 \), z popolnoma (anti)korelirane \( x = (-)y \) velja \( \rho = (-) 1 \).
** Združevanje koreliranih meritev

Imejmo dva izmerka \( z_1, \sigma_1 \) in \( z_2, \sigma_2 \), ki imata korelacijski koeficient \( \rho \).

Posamezne izmerka sta definirana kot

\[ z_1 = x + w_1, \ \bar{w}_1 ^2 = \sigma_1 ^2 \quad \text{ in } \quad z_2 = x + w_2 , \ \bar{w}_2 ^2 = \sigma_2 ^2
\]

in velja \( \overline{w_1 w_2} \ne 0 \).

Po definiciji bo korelacija

\[ \sigma_{12} = \rho \sigma_1 \sigma_2 = \left\langle \left( z_1 - x \right) \left( z_2 - x \right) \right\rangle = \left\langle w_1 w_2 \right\rangle.
\]

Šuma nista neodvisna, torej ga lahko zapišemo kot linearnoa kombinacijo druge meritve in neodvisnega dela \( w_1 = \alpha w_2 + w \), kjer velja \( \left\langle w_2 w \right\rangle = 0\), kar je ekvivalentno

\[ (z_1 - x) = \alpha (z_2 - x) + w, \ \left\langle w (z_2 - x) \right\rangle  = 0.
\]

Linearno odvisnost upoštevamo v korelaciji

\begin{align*}
  \rho \sigma_1 \sigma_2 &= \left\langle \left( \alpha w_2 + w \right) \right\rangle \\
&= \alpha \sigma_1 ^2
\end{align*}

Iz tega sledi, da je koeficient linearne odvisnosti enak

\[ \alpha = \rho \frac{\sigma_1}{\sigma_2}.
\]

Zapišimo še varianco neodvisnega šuma

\begin{align*}
  \sigma_1 ^2 = \left\langle w_1 ^2 \right\rangle &= \left\langle \left( \alpha w_2 + w \right) ^2 \right\rangle \\
&= \left\langle \alpha ^2 w_2 ^2 + w ^2 + 2\alpha w_2 w  \right\rangle\\
&= \alpha ^2 \sigma_2 ^2 + \sigma_w ^2
\end{align*}

Varianco neodvisnega šuma ob upoštevanju vrednosti \( \alpha \) potem zapišemo

\[ \sigma_w ^2 = \sigma_1 ^2 \left( 1 - \rho ^2 \right)
\]

Optimalno združevanje ocen poteka preko kvadratov nekoreliranih šumov

\[ 2J(x) = \frac{w_2 ^2}{\sigma_2 ^2} + \frac{w ^2}{\sigma_w ^2} = \frac{w_2 ^2}{\sigma_2 ^2} + \frac{\left( w_1 - \alpha w_2 \right) ^2}{\sigma_w ^2}.
\]

Razdelimo na vsoto ulomkov in upoštevamo definicijo \( \alpha \) in dobimo

\[ 2 J(x) = \frac{w_2 ^2}{\sigma_2 ^2} + \frac{\rho ^2}{\sigma_2 ^2} \frac{w_2 ^2}{\left( 1 - \rho ^2 \right)} + \frac{w_1 ^2}{\sigma_1 ^2 \left( 1 - \rho ^2 \right)} - \frac{2 \rho w_1 w_2}{\sigma_1 \sigma_2 \left( 1 - \rho ^2 \right)}.
\]

V prvih dveh členih izpostavimo skupne lastnosti, ter upoštevamo definicijo šuma \( w = z - x \)

\[ 2J(x) = \left( 1 + \frac{\rho ^2}{1 - \rho ^2} \right) \frac{\left( z_2 - x \right) ^2}{\sigma_2 ^2} + \frac{\left( z_1 - x \right) ^2}{\sigma_1 ^2 \left( 1 - \rho ^2 \right) } - \frac{2 \rho \left( z_1 - x \right) \left( z_2 - x \right)}{\sigma_1 \sigma_2 \left( 1 - \rho ^2 \right)}
\]

Prvi oklepaj se razreši in iščemo optimum za funkcijo

\[ 2J(x) = \frac{\left( z_2 - x \right) ^2}{\left( 1 - \rho ^2 \right)\sigma_2 ^2} + \frac{\left( z_1 - x \right) ^2}{\left( 1 - \rho ^2 \right) \sigma_1 ^2} - \frac{2 \sigma \left( z_1 z_2 - x (z_1 + z_2) + x ^2 \right)}{\sigma_1 \sigma_2 \left( 1 - \rho ^2 \right)}
\]

Minimum te funkcije je

\[ \frac{\mathrm{d} }{\mathrm{d} x} (2J(x)) = \frac{z_2 - x}{\sigma_1 ^2} + \frac{z_1 - x}{\sigma_1 ^2} + \frac{\rho \left( - (z_1 + z_2) + 2x \right)}{\sigma_1 \sigma_2}.
\]

Izrazimo \( x \)

\[ x \left[ \frac{1}{\sigma_2 ^2} + \frac{1}{\sigma_1 ^2} - \frac{2 \rho}{\sigma_1 \sigma_2} \right] = \frac{z_2}{\sigma_2 ^2} + \frac{z_1}{\sigma_1} - \frac{\rho(z_1 + z_2)}{\sigma_1 \sigma_2},
\]

iz česar sledi, da je optimalno meritev pri

\[ x_{opt} = \left[  \frac{1}{\sigma_2 ^2} + \frac{1}{\sigma_1 ^2} - \frac{2 \rho}{\sigma_1 \sigma_2} \right] ^{-1}\left[ \frac{z_2}{\sigma_2 ^2} + \frac{z_1}{\sigma_1} - \frac{\rho(z_1 + z_2)}{\sigma_1 \sigma_2} \right].
\]

Pri \( \rho = 0 \) imamo potem

\[ x_{opt} = \left( \frac{1}{\sigma_1 ^2} = \frac{1}{\sigma_2 ^2} \right) ^{-1} \left[ \frac{z_1}{\sigma_1 ^2} + \frac{z_2}{\sigma_2 ^2} \right].
\]

Za \( \rho = 1 \) imamo potem

\[ x = z_3 = z_2 = z_1.
\]

Če je \( \rho \) poljuben, potem je \( \sigma_1 = \sigma_2 \), potem je

\[ x = \left( \frac{1 + 1 - 2 \rho}{\sigma ^2} \right)^{-1} \left( \frac{\left( z_1 + z_2 \right) - \rho (z_1 - z_2)}{\sigma ^2} \right) = \frac{z_1 + z_2}{2} .
\]
* On-line sledenje konstantnim količinam

Imamo sistem \( S \) s spremenljivkami \( x \) in merilni sistem \( M \), ki ju povezuje senzor z izmerki \( z_j \). Merilni sistem \( M \) ima ocene \( \hat{x} \). S časom \( T \) vzorčimo - merimo. Dobimo rezultate oblike

\[ z_j = x + r_j,
\]

kjer je \( x \) prava vrednosti in \( r_j \) normalni Gaussov šum.

Merilni šum je nekoreliran, kar matematično zapišemo

\[ \left\langle r_i r_j \right\rangle  = \delta_{ij} \sigma ^2.
\]

Idealizacija bi bila, da je tudi ob manjšanju \( T \to 0 \), šum še vedno nekoreliran.
