#+title: Priprava Ustni
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Elektrostatika
** 1. vprašanje
 #+begin_problem
Uvedi in razloži naslednje elektrostatske količine in koncepte: Coulombska sila, naboj, jakost polja, silnice, cirkulacija, pretok, potencial, ekvipotencialne ploskve in princip superpozicije.
 #+end_problem
*** Coulombov zakon

Mirujoče naelektreno telo z nabojem \( e_1 \) deluje na drugo mirujoče naelektreno telo z nabojem \( e_2 \) z električno silo

\begin{equation}
\label{eq:1}
 \vec{F} = \frac{e_1 e_2}{4 \pi \epsilon_0 r ^2} \frac{\vec{r}}{r}.
\end{equation}

Pri tem vektor \( \vec{r} \) kaže od naboja \( e_1 \) do naboja \( e_2 \). Konstanti \( \epsilon_0 = 8.85 \cdot 10^{-12} \frac{\mathrm{As}}{\mathrm{Vm}} \) pravimo influenčna konstanta vakuuma. Enačbi pravimo Coulombska sila.
*** Naboj

Naboj je ena izmed osnovnih količin, ki jo merimo v coulombih. Označimo jo s črko \( C \) in je ekvivalentna \( \mathrm{As} \).
*** Jakost električnega polja

Električno silo, ki deluje na daljavo, v Coulombovi sliki, nadomesti električno polje v Faradayjevi in Maxwellovi sliki. Torej je električno polje posrednik interakcije.

Električno silo naboja \( e_1 \) na nabit delec \( e_2 \) zapišemo preko enačbe

\[ \vec{F} = e_2 \vec{E}_1
\]

Iz enačbe \ref{eq:1} sledi, da je električno polje točkastega naboja enako

\[ E = \frac{e_0}{4 \pi \epsilon_0} \frac{\vec{r}}{r ^3}
\]
*** Silnice

Električne silnice so primer prostorske upodobitve vektorskega polja. Prostorskim krivuljam v naravni parametrizaciji \( \vec{r}(s) \), ki so v vsaki točki sorazmerna smeri elektrostatske sile, pravimo električne silnice.

\[ \odv{r}(s) = \frac{\mathrm{d} r}{\mathrm{d} s} = \frac{\vec{F}(\vec{r}(s))}{\left| \vec{F} (\vec{r} (s)) \right|}
\]

Podobno lahko zapišemo tudi s pomočjo električnega polja v vsaki točki prostora

\[ \odv{r}(s) = \frac{\vec{E} \left( \vec{r}(s) \right)}{\left| \vec{E} \left( \vec{r} (s) \right) \right|}
\]

Silnice so usmerjene proti naboju, če je negativen, drugače so pozitivne. Električne silnice imajo naslednje 4 lastnosti:

- silnice kažejo v smeri električnega polja \( \vec{E} \) in se ne sekajo
- površinska gostota silnic je sorazmerna velikosti električne polja \( \left| \vec{E} \right| \)
- silnice izvirajo v pozitivnih nabojih in izginjajo v negativnih nabojih
- silnice niso nikoli zaključene
*** Električna cirkulacija

Definiramo jo kot integral po zaključeni krivulji \( \mathcal{C} \)

\begin{equation}
\label{eq:2}
 \Gamma_E = \oint\limits_{\mathcal{C}}^{} \vec{E} \, \mathrm{d} \vec{r}
\end{equation}

Eksperimentalno je določeno, da je cirkulacija statičnega električnega polja enaka nič. Integral \ref{eq:2} lahko razpišemo s pomočjo Stokesovega izreka kot

\[ 0 = \oint\limits_{\mathcal{C}}^{} \vec{E} \, \mathrm{d} \vec{r} = \iint\limits_S^{} \nabla \times \vec{E} \,\mathrm{d } \vec{S}
\]

V tem primeru krivulja \( \mathcal{C} \) predstavlja rob \( \partial S \) območja \( S \). Iz lastnosti cirkulacije statičnega električnega polja sledi

\[ \nabla \times \vec{E} = 0
\]

kar po definiciji pomeni, da je brezvrtinčno.
*** Električni pretok

Električni pretok preko neke površine je definiran kot površinski integral jakosti električnega polja po neki dani površini:

\[ \Phi_E = \int\limits_S^{} \vec{E} \cdot \mathrm{d} \vec{S}
\]

\( \mathrm{d}\vec{S} \) je vektorski diferencialni element površine, ki ima smer lokalne zunanje normalena površino.
*** Električni potencial

Električni potencial definiramo tako, da vsaki točki prostora priredimo neko skalarno funkcijo \( \phi \left( \vec{r} \right) \), da velja zveza

\[ \vec{E} \left( \vec{r} \right) = - \nabla \phi \left( \vec{r} \right)
\]

kjer je \( \nabla \) diferencialni operator.

#+begin_my_example
Jakost električnega polja točkastega naboja je enaka

\[ \vec{E} = \frac{e}{4 \pi \epsilon_0} \frac{\vec{r}}{r ^3}
\]

Iz tega sledi, da je potencial enaka

\[ \phi = \frac{e}{4 \pi \epsilon_0} \frac{1}{r} + \phi_0.
\]
#+end_my_example

Potencial lahko določamo le do konstante natančno in je invarianten na transformacijo.
*** Ekvipotencialne ploskve
*** Princip superpozicije

Za prostor z več naboji \( e_i \) v točkah \( \vec{r}_i \), je električna sila na naboj \( e \), ki se nahaja v točki \( \vec{r} \) različni od \( \vec{r}_i \) enaka vsoti sil ostalih nabojev

\[ \vec{F} \left( \vec{r} \right) = \sum\limits_i^{}  \frac{e \cdot e_i}{4 \pi \epsilon_0} \frac{\left( \vec{r} - \vec{r}_i \right)}{\left| \vec{r} - \vec{r}_i \right| ^3}
\]

To je /princip superpozicije/.

Opomba, da je elektrostatika zgrajena na izključno parskih interakcijah. Jakost električnega polja in potencial tudi zadoščata principu superpozicije in ju zapišemo kot

\[ \vec{E} \left( \vec{r} \right) = \frac{1}{4 \pi \epsilon_0} \sum\limits_i^{} \frac{e_i \left( \vec{r} - \vec{r}_i \right)}{\left| \vec{r} - \vec{r}_i \right| ^3}, \quad \phi \left( \vec{r} \right) = \frac{1}{4\pi\epsilon_0} \sum\limits_i^{} \frac{e_i}{\left| \vec{r} - \vec{r}_i \right|}
\]
** 2. vprašanje
#+begin_problem
Uvedi gostoto naboja in za poljubno gostoto zapiši elektrostatsko silo, polje in električni potencial. Nato navedi primere gostote naboja, pri čemer tudi pokaži, kakšna je povezava med gostoto naboja in gostoto dipolnega momenta.
#+end_problem
*** Gostota naboja

Električni naboj, ki je porazdeljen, je enostavneje zapisati s pomočjo gostote naboja \( \rho \left( \vec{r} \right) \).

Gostoto električnega naboja v točki \( \vec{r} \) obkroženo s točkastimi naboji \( e_i \) v točkah \( \vec{r}_i \) zapišemo s pomočjo Diracove \( \delta \) funkcije.

\begin{equation}
\label{eq:3}
 \rho \left( \vec{r} \right) = \sum\limits_i^{} e_i \delta ^3 \left( \vec{r} - \vec{r}_i \right)
\end{equation}

Gostoto lahko zapišemo tudi v diferencialni obliki

\[ \rho \left( \vec{r} \right) = \frac{\mathrm{d} e}{\mathrm{d} V}
\]

Volumnski integral gostote električnega naboja \ref{eq:3} je enak celotnemu naboju

\[ e = \int\limits_{}^{} \rho \left( \vec{r} \right) \, \mathrm{d} V = \int\limits_{}^{} \sum\limits_i^{} \delta ^3 \left( \vec{r} - \vec{r}_i \right) \, \mathrm{d} V = \sum\limits_i^{} e_i
\]

Prav tako lahko zapišemo silo na naboj v polju drugih nabojev

\[ \vec{F} \left( \vec{r} \right) = \int\limits_{}^{} \rho \left( \vec{r} \right) \vec{E} \left( \vec{r} \right) \, \mathrm{d} ^3 \vec{r}
\]

Električno polje sistema točkastih nabojev

\[ \vec{E} \left( \vec{r} \right) = \frac{1}{4 \pi \epsilon_0} \int\limits_V^{} \frac{\rho \left( \vec{r} \, ' \right) \left( \vec{r} - \vec{r}\,' \right)}{\left| \vec{r} - \vec{r} \, ' \right| ^3} \, \mathrm{d} ^3 \vec{r} \, '
\]
Podobno je za potencial

\[ \phi \left( \vec{r} \right) = \frac{1}{4 \pi \epsilon_0} \int\limits_V^{} \frac{\rho \left( \vec{r} \, '\right)}{\left| \vec{r} - \vec{r} \, ' \right|} \, \mathrm{d} ^3 \vec{r} \, '
\]
*** Primeri
**** Točkast naboj

Za naboj \( e \) v točki \( \vec{r}_0 \) je gostota naboja

\[ \rho \left( \vec{r} \right) = e \delta \left( \vec{r} - \vec{r}_0 \right)
\]
**** Točkast dipol

Imamo dva nasprotno nabita točkasta naboja \( e \) in \( -e \) pri \( \vec{r}_1 = \vec{r}_0 - \delta \vec{r} \) in \( \vec{r}_2 = \vec{r}_0 + \delta \vec{r} \), ki sta narazen za \( d = \left|\vec{r}_1 - \vec{r}_2\right| \).

Gostoto naboja podamo kot

\[ \rho \left( \vec{r} \right) = e \delta ^3 \left( \vec{r} - \vec{r}_1 \right) - \delta ^3 \left( \vec{r} - \vec{r}_2 \right)
\]

Predpostavimo, da je razdalja med naboje zelo majhna \( \left| \delta \vec{r} \right| \ll \left| \vec{r}  \right|\).

Taylorjev razvoj z vektorji je enak:

\[ f \left( \vec{r} + \Delta \vec{r} \right) = f \left( \vec{r} \right) + \nabla f \left( \vec{r} \right) \cdot \Delta \vec{r} + \ldots
\]

Upoštevajoč definicije \( \vec{r}_1 \) in \( \vec{r}_2 \), lahko gostoto naboja razvijemo po Taylorju, da dobimo

\[ \rho \left( \vec{r} \right) = - e \left( \vec{r}_1 - \vec{r}_2 \right) \cdot \nabla \delta ^3 \left( \vec{r} - \vec{r}_0 \right) = - 2 e \delta \vec{r}\, \nabla \delta ^3 \left( \vec{r} - \vec{r}_0 \right)
\]

Vpeljemo vektor dipolnega momenta \( p = e \left( \vec{r}_1 - \vec{r}_2 \right) = -2 e \delta \vec{r} \).

Velja identiteta

\[ \nabla \cdot \left( \vec{p} \cdot \delta ^3 \left( \vec{r} - \vec{r}_0 \right) \right) = \left( \nabla \cdot p \right) \delta ^3 \left( \vec{r} - \vec{r}_0 \right) + \vec{p} \cdot \nu \left( \delta ^3 \vec{r} - \vec{r}_0 \right)
\]

Dipolni moment je konstanten, torej \( \nabla \cdot \vec{p} = 0 \). Preobrazimo našo gostoto v

\[ \rho \left( \vec{r} \right)= - \nabla \cdot \left[ \vec{p} \cdot \delta ^3 \left( \vec{r} - \vec{r}_0 \right) \right] = - \nabla \cdot \vec{P} \left( \vec{r} \right)
\]

kjer je \( \vec{P} = \vec{p} \cdot \delta ^3 \left( \vec{r} - \vec{r}_0 \right) \) polarizacija.
**** Površinsko porazdeljen naboj

Površinska gostota naboja \( \sigma \left( \vec{u} \right) \) vpeljemo kot

\[ \rho \left( \vec{r} \right) = \sigma \left( \vec{u} \right) \delta \left( z - z_0 \right)
\]

kjer je \( \vec{u} \) radij vektor v na površini podani z \( z = z_0 \).

Celoten naboj je površinski integral

\[ \int\limits_V^{} \rho \left( \vec{r} \right) \, \mathrm{d} ^3 \vec{r} = \int\limits_V^{} \sigma \left( \vec{u} \right) \delta \left( z - z_0 \right) \, \mathrm{d} z \, \mathrm{d} ^2 \vec{u} = \int\limits_S^{} \sigma \left( \vec{u} \right) \, \mathrm{d} ^2 \vec{u}
\]
**** Površinsko porazdeljen dipol

Podobno kot pri točkastem dipolu, imamo dve nasprotno nabiti površini, s površinskima gostotama naboja \( \sigma \left( \vec{u} \right) \) in \( - \sigma \left( \vec{u} \right) \). Površini se nahajata na ravnina \( z = z_1 = z_0 + \delta z \) ter \( z = z_2 = z_0 - \delta z \). Velja \( \delta z \ll z \).

Površinska gostota naboja je

\[ \rho \left( \vec{r} \right) = \sigma \left( \vec{u} \right) \delta (z - z_1) - \sigma (\vec{u}) \delta (z - z_2)

ki jo razvijemo po Taylorju

\[ \rho \left( \vec{r} \right) = - \sigma \left( \vec{u} \right) (z_1 - z_2) \frac{\partial }{\partial z}  \delta\left( z - z_0 \right)  = - p \left( \vec{u} \right) \frac{\partial }{\partial z} \delta \left( z - z_0 \right)
\]

kjer je \( p \left( \vec{u} \right) \) površinska gostota dipolnega momenta.
**** Volumsko porazdeljen naboj

Gostota je lahko porazdeljena po končnem volumnu. Za enakomerno porazdeljeno kroglo z radijem \( a \) je gostota naboja

\[ \rho \left( \vec{r} \right) = \begin{cases}
                                 \rho_0; & \left| \vec{r} \right| \leq a \\
                                 0; & \text{else}
                                 \end{cases} = \rho_0 H \left( a - r \right)
\]

kjer je \( H \) Heavisodeova funkcija.
**** Volumsko porazdeljen dipol

Vektor polarizacije \( \vec{P} \) zapišemo s porazdelitvijo

\[ P \left( \vec{r} \right) = \begin{cases}
                               P_0; & \left| \vec{r} \right| \leq a,\\
                               0; &\text{else}
                              \end{cases} = \vec{P}_0 H (a - r)
\]

Vzamemo nastavek enakomerno polarizirane krogle

\[ \rho \left( \vec{r} \right) = - \nabla \cdot \vec{P} \left( \vec{r} \right)
\]

in velja

\[ \frac{\mathrm{d} }{\mathrm{d} r} H (a - r) = - \delta (a - r)
\]

dobimo, da je gostota naboja enaka

\[ \rho \left( \vec{r} \right) = \vec{P}_0 \delta \left( a - r \right) \frac{\vec{r}}{r}
\]

Torej je naboj zgolj površinski.

** 3. vprašanje
#+begin_problem
Zapiši in razloži Gaussov izrek v integralni in diferencialni obliki. Pokaži njegovo uporabo na primeru geometrije/problema, ki ga sam izbereš.
#+end_problem
** 4. vprašanje
#+begin_problem
Zapiši Poissonovo in Laplaceovo enačbo in ju razloži. Izpelji splošno rešitev (Greenovo funkcijo) Poissonove enačbe v Fourierovem in direktnem prostoru. Z uporabo Greenove funkcije nato zapiši splošno obliko električnega potenciala in električnega polja. Kako se ta rešitev spremni v končnem volumnu?
#+end_problem
