#+title: 1. predavanje iz Matematične fizike 2
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Uvod

Zakaj, kje se pojavijo parcialne diferencialne enačbe? Gibanje enega delca opišemo z eno navadno difernencialno enačbo (ODE). Za opis gibanja dveh delcev imamo 2 sklopljeni ODE. Za opis gibanja neskončnega števila delcev imamo neskončno ODE. V kontinuumski limiti, ko iz diskretnih delcev preidemo na polje, dobimo PDE.

Za dobro definirano in enolično rešljivo PDE potrebujemo enačbo in začetne pogoje (ang. /boundary conditions/, označim BC).

Do PDE lahko pridemo tudi preko principa najmanjše akcije. Za 1 delec imamo Hamiltonian/Lagrangian, pri neskončnem številu delcev pa imamo integral po koordinatah. Pri Euler-Lagrangevih enačbah nimamo samo integrala po času, ampak tudi integral (lokalne) gostote. Tej lokalnosti pravimo fizikalno tudi kavzalnosti. E-L enačbe nam podajo PDE, ki so rešljive lokalno (?).
** Kakšne PDE rešujemo?

Tako kot ODE imajo tudi PDE rede, ki nakazuje stopnjo najvišjega odvoda. Najenostavnejša PDE je 1. reda.

#+name: Kontinuitetna enačba
#+begin_my_example
\begin{equation}
\label{eq:1}
 \frac{\partial \rho}{\partial t} + \mathrm{div} \left( \rho \vec{v} \right) = 0
\end{equation}

Kontinuitetna enačba, ki izraža nek ohranitveni zakon. Zanima nas, za katero količino je to diferencialna enačba - in zato potrebujemo zvezo med \( \rho \) in \( \vec{v} \).

Predpostavimo, da je ta zveza enaka \( \vec{\jmath} \sim \nabla \rho \), npr.

\begin{equation}
\label{eq:2}
 j = - \frac{\partial \rho}{\partial x}
\end{equation}

Z združitvijo enačb \ref{eq:1} in \ref{eq:2} dobimo PDE *2. reda*. Ciljali bomo na aproksimacijo, da so enačbe *linearne* (naravni zakoni, npr. Maxwellove enačbe, so eksaktno linearni). Prednost linearnosti je princip superpozicije.
#+end_my_example

Najpomembnejši primeri so:

- valovna enačba je hiperbolična

  \[ \nabla ^2 u = \frac{1}{c ^2} \frac{\partial ^2 }{\partial t ^2} u, \quad u \left( \vec{r}, t \right)
  \]

  kjer je \( c \) hitrost valovanja.

  Valovna enačba opisuje zvok, svetlobo, in ostala nihanja.

- difuzijska enačba je parabolična

  \[ \nabla ^2 u = \frac{1}{D} \frac{\partial u}{\partial t}
  \]

  kjer je \( D \) difuzijska enačba.

- Laplaceova enačba je eliptična

  \[ \nabla ^2 u = 0
  \]

  Opazimo, da ne vsebuje odvoda po času.
* PDE prvega reda (Kuščar, Kodre, poglavje 5.1, Haberman 12.2, Arfken 9.2)

#+begin_my_example
Kot primer bomo vzeli prometne zastoje. Operiramo v eni dimenziji, in kontinuitetna enačba je

\begin{equation}
\label{eq:3}
 \frac{\partial \rho}{\partial t} + \frac{\partial j}{\partial x}  = 0
\end{equation}

Na določenem, zaprtem intervalu, bo količina avtov, ki vstopajo na začetku intervala, enaka količino avtov, ki interval zapuščajo. Tok avtomobilov zapišemo s funkcijo

\begin{equation}
\label{eq:4}
 j = f(\rho) = \rho v(\rho)
\end{equation}

kjer je \( v \) hitrost avtomobilov.

Odvod enačbe \ref{eq:4} po \( x \) zapišemo s posrednim odvajanjem

\[ \frac{\partial j}{\partial x} = \frac{\partial j}{\partial \rho} \frac{\partial \rho}{\partial x} = c (\rho) \frac{\partial \rho}{\partial x}
\]

Količina \( c(\rho) \) je parameter, ki si ga izberemo. Upoštevajoč odvod \ref{eq:4} in \ref{eq:3} dobimo novo enačbo

\[ \frac{\partial \rho}{\partial t} + c \frac{\partial \rho}{\partial x}  = 0
\]

Parameter \( c \) je hitrost premikanja razredčin in zgoščin, kar je lahko različno od hitrosti premikanja mikroskopskih delcev (avtov).

Če je avtocesta prazna, bodo avtomobili vozili ob neki konstantni hitrosti \( v_0 \). Več je avtomobilov, počasneje bodo vozili, kar pomeni, da hitrost v odvisnosti od gostote zapišemo

\[ v (\rho) = v_0 \left( 1 - \frac{\rho}{\rho_{max}} \right)
\]

Če je cesta popolnoma polna, je hitrost \( 0 \). Naš približek je semi-dober.

Preko definicije \ref{eq:4} in definicije parametra \( c \), dobimo, da je hitrost motnje enaka

\[ c (\rho) = v_0 \left( 1 - \frac{2 \rho}{\rho_{max}} \right)
\]

Upoštevajoč dobljen \( c \) enačba ni več linearna.

Za začetek si bomo ogledali linearen problem, kjer je hitrost motnje \( c = v_0 = konst \). Rešujemo enačbo

\[ \frac{\partial \rho}{\partial t}  + v_0 \frac{\partial \rho}{\partial x} = 0
\]

Iščemo funkcijo \( \rho(x, t) \), ki velja za mirujoč opazovalni sistem. Recimo, da smo na vlaku, ki se premika kot \( x(t) \). Predpostavimo, da je gibanje linearno, torej

\begin{equation}
\label{eq:5}
x(t) = x_0 + vt
\end{equation}

Funkcija, ki jo sedaj iščemo, v premikajočem opazovalnem sistemu je \( \rho \left( x(t), t \right) \). Odvod po času je

\[ \frac{\mathrm{d} \rho }{\mathrm{d} t} = \frac{\partial \rho}{\partial t}  + \frac{\partial \rho}{\partial x} \cdot \dot{x}
\]

Zakaj totalni odvod?

Če je hitrost \( \dot{x} = v_0 \), se gostota ne spreminja

\[ \frac{\mathrm{d} \rho}{\mathrm{d} t} = 0
\]

Pri začetnem pogoju \( \rho_0 (x) = \rho(x, t = 0) \). Gostota bo tako enaka

\[ \rho(x, t) = \rho_0 (x_0) = \rho_0 (x - v_0 t)
\]

kjer smo \( x_0 \) izrazili iz enačbe \ref{eq:5} in zadnji enačaj predstavlja rešitev.
#+end_my_example

#+begin_note
Uporabljali bomo sledečo notacijo. Totalni odvod po času bomo označili s piko, torej

\[ \dot{x} = \frac{\mathrm{d} x}{\mathrm{d} t}
\]

Parcialni odvod po času bomo označili z indeksom \( t \), torej

\[ \frac{\partial u}{\partial t}  = \partial_t u = u_t
\]

kjer je \( u \) funkcija večih spremenljivk, ena od njih je čas.

Drugi odvod po kraju označimo z dvojnim \( x \), torej

\[ \frac{\partial ^2 }{\partial x ^2} = u_{xx }
\]
#+end_note

Definiramo diferencialno enačbo za karakteristiko

\[ \frac{\mathrm{d} x}{\mathrm{d} t} = v_0
\]

#+begin_my_example
Obravnavajmo zgornji primer, kjer je enačba nelinearna. Najlepšo linearnost bomo dosegli z \( c (\rho) = \rho \). Enačba, ki jo rešujemo je Burgerjeva enačba (ang. /Burger's equation/)

\[ \frac{\partial \rho}{\partial t}  + \rho \frac{\partial \rho}{\partial x}  = 0
\]
#+end_my_example
