#+title: 2. predavanje iz Matematične fizike 2
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Valovna enačba
** Izpeljava
*** Struna
**** Energija nihanja

Pri prejšnjem predavanju smo integral

\[ A = \int\limits_{}^{} \left( \frac{\mathrm{d} F_{y}}{\mathrm{d} x} \right) \, \mathrm{d} x \, \mathrm{d} u
\]

predelali v

\[ A = - \int\limits_{}^{} \frac{1}{2} F y_{xx } y \, \mathrm{d} x - \int\limits_{}^{} y f_y \, \mathrm{d} x
\]

Zapis se razlikuje samo v tem, da smo napisali negativno predznačen integral, saj je to naša sila na vrv. Prvi integral rešimo preko per partes, torej

\[ \int\limits_{}^{} \frac{1}{2} F y_{xx } y \, \mathrm{d} x = - \left. \frac{1}{2} F y_x y  \right|_a^b + \frac{1}{2} \int\limits_a^b y_x ^2 \, \mathrm{d} x
\]

Ob predpostavki, da zunanjih sil ni, dobimo željeni izraz za energijo, kjer je kvadrat odvoda. Prvi člen je robni člen in preko njega dajemo energijo v sistem. Če sta roba pripeta je ta člen ničeln, če pa z roko vzbujamo nihanje, vsaj na eni strani vrvi, produkt \( y_x \cdot y \) ni ničeln.

Skupna energija valovanja je tako

\[ E = \frac{\mu}{2} \int\limits_a^b \left[ y_t ^2 + c ^2 y_x ^2 \right] \, \mathrm{d} x
\]
** Valovna enačba v 1D (Goldbart 6.3)

Valovno enačbo v eni dimenziji

\begin{equation}
\label{eq:1}
 \frac{\partial ^2 u}{\partial t ^2} - c ^2 \frac{\partial ^2 u}{\partial x ^2} = 0
\end{equation}

razpišemo preko razlike kvadratov v

\[ \left( \frac{\partial }{\partial t} - c \frac{\partial }{\partial x}  \right) \left( \frac{\partial }{\partial t}  + c \frac{\partial }{\partial x}  \right) u = 0
\]

Oklepaj

\[ \left( \frac{\partial }{\partial t}  + c \frac{\partial  }{\partial x}  \right)u = 0
\]

je Burgerjeva enačba, katere rešitev smo zapisali prejšnji teden, da je oblike

\[ u (x, t) = g \left( x - ct \right)
\]

Spomnimo, da je rešitev samo oblika funkcije \( g \), ki se skozi čas seli v desno po koordinatnem sistemu. Analogno, samo z \( -c \) pa je rešitev enačbe

\[ \left( \frac{\partial }{\partial t} - c \frac{\partial }{\partial x}  \right)u = 0
\]

Splošna rešitev je tako linearna kombinacija poljubnih funkcij \( f \) in \( g \)

\[ u \left( x, t \right) = g \left( x - ct \right) + f \left( x + ct \right)
\]

Če opravimo zamenjavo koordinat iz \( x, t \) v \( p = x + ct \) in \( r = x - ct \), enačba \ref{eq:1} postane

\[ \frac{\partial ^2 u }{\partial p \partial r} = 0
\]

[vstavi graf \( \Sigma \) karakteristik]

Končen začetni pogoj \( \Gamma \) (glej graf) nam podaja informacije o odmik in hitrost strune (odvod). Lokalna rešitev je znotraj trapezioda in je omejena med \( [p_0, p_1] \) in \( [r_0, r_1] \). Rešitev je podana za tiste karakteristike, ki jih \( \Gamma \) seka.

Preko premic \( p \), ki jih začetni pogoj seka, določimo funkcijo \( f \), preko premic \( r \), ki jih seka \( \Gamma \), pa določimo funkcijo \( g \).

Obstajata tudi začetna pogoja, ki nam pokriva rešitev celotne realne osi. To sta, ko je \( t = \mathrm{konst} \) ali \( x = \mathrm{konst} \), saj sekata vse premice \( r \) in \( p \).

Začetni pogoj se propagira čez karakteristike.

#+begin_my_example
Želimo določiti \( f \) in \( g \) iz začetnih pogojev pri \( t = 0 \). Začetna pogoja sta

\begin{align*}
  u(x, t = 0) &= g (x) + f(x) \\
u_t \left( x, t = 0 \right) &= - c g'(x) + c f'(x)
\end{align*}

Z integrariranjem drugega začetnega pogoja v mejah \( [x - ct, x + ct] \) se rešimo odvodov:

\begin{align*}
  \frac{1}{2c}\int\limits_{x - ct}^{x + ct} u_t (x, t = 0) &= \frac{1}{2c} \left[ f(x + ct) - f(x - ct) - g(x + ct) + g(x - ct) \right]
\end{align*}

Po računanju zapišemo rešitev, ki je

\begin{equation}
\label{eq:2}
 u(x, t) = \frac{1}{2} \left[ u(x + ct, 0) - u(x - ct, 0) \right] + \frac{1}{2c} \int\limits_{x - ct}^{x + ct} u_t (y, 0) \, \mathrm{d} y =  \frac{1}{2} \left[ u(x + ct, 0) - u(x - ct, 0) \right] + \bar{v} t
\end{equation}

Zapisu \ref{eq:2} pravimo d'Alembertova rešitev (čeprav jo je Euler že prej izpeljal).

Če nas zanima rešitev \( t \) ob začetnih pogojih \( t = 0 \), bomo rešitev dobili tako, da pogledamo povprečje karakteristik \( u(x - ct) \) in \( u(x + ct) \) ob času \( t = 0 \), ki mu prištejemo povprečno hitrost na intervalu med točkama karakteristik ob času \( t = 0 \) pomnoženo s časom.

Točke \( u(x - ct), u(x + ct) \) in \( t \) tvorijo kavzalni stožec. Vse kar je znotraj stožca vpliva na rešitve, vse kar je izven, pa ne vpliva na rešitev.
#+end_my_example
