#+title: 2. predavanje iz Matematične fizike 2
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Valovna enačba
** Izpeljava
*** Struna
**** Energija nihanja

Pri prejšnjem predavanju smo integral

\[ A = \int\limits_{}^{} \left( \frac{\mathrm{d} F_{y}}{\mathrm{d} x} \right) \, \mathrm{d} x \, \mathrm{d} u
\]

predelali v

\[ A = - \int\limits_{}^{} \frac{1}{2} F y_{xx } y \, \mathrm{d} x - \int\limits_{}^{} y f_y \, \mathrm{d} x
\]

Zapis se razlikuje samo v tem, da smo napisali negativno predznačen integral, saj je to naša sila na vrv. Prvi integral rešimo preko per partes, torej

\[ \int\limits_{}^{} \frac{1}{2} F y_{xx } y \, \mathrm{d} x = - \left. \frac{1}{2} F y_x y  \right|_a^b + \frac{1}{2} \int\limits_a^b y_x ^2 \, \mathrm{d} x
\]

Ob predpostavki, da zunanjih sil ni, dobimo željeni izraz za energijo, kjer je kvadrat odvoda. Prvi člen je robni člen in preko njega dajemo energijo v sistem. Če sta roba pripeta je ta člen ničeln, če pa z roko vzbujamo nihanje, vsaj na eni strani vrvi, produkt \( y_x \cdot y \) ni ničeln.

Skupna energija valovanja je tako

\[ E = \frac{\mu}{2} \int\limits_a^b \left[ y_t ^2 + c ^2 y_x ^2 \right] \, \mathrm{d} x
\]
** Valovna enačba v 1D (Goldbart 6.3)

Valovno enačbo v eni dimenziji

\begin{equation}
\label{eq:1}
 \frac{\partial ^2 u}{\partial t ^2} - c ^2 \frac{\partial ^2 u}{\partial x ^2} = 0
\end{equation}

razpišemo preko razlike kvadratov v

\[ \left( \frac{\partial }{\partial t} - c \frac{\partial }{\partial x}  \right) \left( \frac{\partial }{\partial t}  + c \frac{\partial }{\partial x}  \right) u = 0
\]

Oklepaj

\[ \left( \frac{\partial }{\partial t}  + c \frac{\partial  }{\partial x}  \right)u = 0
\]

je Burgerjeva enačba, katere rešitev smo zapisali prejšnji teden, da je oblike

\[ u (x, t) = g \left( x - ct \right)
\]

Spomnimo, da je rešitev samo oblika funkcije \( g \), ki se skozi čas seli v desno po koordinatnem sistemu. Analogno, samo z \( -c \) pa je rešitev enačbe

\[ \left( \frac{\partial }{\partial t} - c \frac{\partial }{\partial x}  \right)u = 0
\]

Splošna rešitev je tako linearna kombinacija poljubnih funkcij \( f \) in \( g \)

\[ u \left( x, t \right) = g \left( x - ct \right) + f \left( x + ct \right)
\]

Če opravimo zamenjavo koordinat iz \( x, t \) v \( p = x + ct \) in \( r = x - ct \), enačba \ref{eq:1} postane

\[ \frac{\partial ^2 u }{\partial p \partial r} = 0
\]

[vstavi graf \( \Sigma \) karakteristik]

Končen začetni pogoj \( \Gamma \) (glej graf) nam podaja informacije o odmik in hitrost strune (odvod). Lokalna rešitev je znotraj trapezioda in je omejena med \( [p_0, p_1] \) in \( [r_0, r_1] \). Rešitev je podana za tiste karakteristike, ki jih \( \Gamma \) seka.

Preko premic \( p \), ki jih začetni pogoj seka, določimo funkcijo \( f \), preko premic \( r \), ki jih seka \( \Gamma \), pa določimo funkcijo \( g \).

Obstajata tudi začetna pogoja, ki nam pokriva rešitev celotne realne osi. To sta, ko je \( t = \mathrm{konst} \) ali \( x = \mathrm{konst} \), saj sekata vse premice \( r \) in \( p \).

Začetni pogoj se propagira čez karakteristike.

#+begin_my_example
Želimo določiti \( f \) in \( g \) iz začetnih pogojev pri \( t = 0 \). Začetna pogoja sta

\begin{align*}
  u(x, t = 0) &= g (x) + f(x) \\
u_t \left( x, t = 0 \right) &= - c g'(x) + c f'(x)
\end{align*}

Z integrariranjem drugega začetnega pogoja v mejah \( [x - ct, x + ct] \) se rešimo odvodov:

\begin{align*}
  \frac{1}{2c}\int\limits_{x - ct}^{x + ct} u_t (x, t = 0) &= \frac{1}{2c} \left[ f(x + ct) - f(x - ct) - g(x + ct) + g(x - ct) \right]
\end{align*}

Po računanju zapišemo rešitev, ki je

\begin{equation}
\label{eq:2}
 u(x, t) = \frac{1}{2} \left[ u(x + ct, 0) - u(x - ct, 0) \right] + \frac{1}{2c} \int\limits_{x - ct}^{x + ct} u_t (y, 0) \, \mathrm{d} y =  \frac{1}{2} \left[ u(x + ct, 0) - u(x - ct, 0) \right] + \bar{v} t
\end{equation}

Zapisu \ref{eq:2} pravimo d'Alembertova rešitev (čeprav jo je Euler že prej izpeljal).

Če nas zanima rešitev \( t \) ob začetnih pogojih \( t = 0 \), bomo rešitev dobili tako, da pogledamo povprečje karakteristik \( u(x - ct) \) in \( u(x + ct) \) ob času \( t = 0 \), ki mu prištejemo povprečno hitrost na intervalu med točkama karakteristik ob času \( t = 0 \) pomnoženo s časom.

Točke \( u(x - ct), u(x + ct) \) in \( t \) tvorijo kavzalni stožec. Vse kar je znotraj stožca vpliva na rešitve, vse kar je izven, pa ne vpliva na rešitev.
#+end_my_example

Funkcijo \( f \) (in \( g \)) lahko zapišemo preko Fourierovega razvoja

\[ f(x - ct) = \frac{1}{\sqrt{2 \pi}} \int\limits_{}^{} \, \mathrm{d} k \left[ a(k) e^{- \mathrm{i} \left( k x - \omega t \right)} + a^{\ast} (k) e^{\mathrm{i} (kx - \omega t)} \right]
\]

kjer je \( \omega = ck \).
**  Nehomogeno sredstvo
*** Diskretna sila

Obravnavamo valovno enačbo z dodano diskretno silo

\begin{equation}
\label{eq:3}
u_{tt } = c ^2 u_{ xx } + \frac{F_y}{\mu} \delta (x - x_0)
\end{equation}

Enačbo \ref{eq:3} integriramo v majhen intervalu \( [- \epsilon +x_0, \epsilon + x_0] \), ko \( \epsilon \to 0 \).

\begin{align*}
 \int\limits_{x_0 - \epsilon}^{x_0 + \epsilon} u_{tt } &= \int\limits_{x_0 - \epsilon}^{x_0 + \epsilon} c ^2 u_{xx } \, \mathrm{d} x + \int\limits_{x_0 - \epsilon}^{x_0 + \epsilon}\frac{F_y}{\mu} \delta(x - x_0) \, \mathrm{d} x \\
0 &= \left. c ^2 u_x \right|_{x_0^-} ^{x_0^+} + \frac{F_y}{\mu}\\
\left. F u_x \right|_{x_0^-}^{x_0^+} &= - F_y
\end{align*}

Označili smo levi \( x_0^- \) in desnji \( x_0^+ \) odvod.
*** Diskretna masa

Imamo maso \( m \) na koordinati \( x_0 \). Zapišemo Newtonov zakon za maso

\[ m u_{tt }(x_0) = \left. F u_{x} \right|_{x_0^-}^{x_0^+}
\]
*** Struna iz dveh delov

Imamo motnjo, ki se širi po vrvi od leve proti desni, ki ima različno debelino. Tanjši del se nahaja na levi strani in ima hitrost \( c_1 \), debelejši del pa na desni strani stika vrvi in hitrost \( c_2 \). Velja \( c_2 < c_1 \), saj je kvadrat hitrosti obratno sorazmeren z maso

\[ c ^2 = \frac{F}{\mu}
\]

Motnja ima v tanjšem delu nastavek

\begin{equation}
\label{eq:4}
 u_1 = u_i \left( x - c_1 t \right) + u_r (x + c_1 t)
\end{equation}

kjer indeks \( i \) označuje /initial/, in \( r \) označuje /reflected/ del vala.

Motnja v debelejšem delu je sestavljena samo iz dela, ki je bil prepuščen, torej

\begin{equation}
\label{eq:5}
 u_2 = u_t \left( x - c_2 t \right)
\end{equation}

Spomnim, da bodi pozoren na predznake ( \( u_r \) se širi v nasprotno smer od ostalih dveh nastavkov).

Predpostavimo, da je spoj na \( x = 0 \). Zahtevamo zveznost in zvezno odvedljivost v spoju, saj bi drugače bil v spoju neskončen pospešek. Matematično zapisano:

\begin{align*}
  u_1 (0, t) &= u_2 (0, t) \\
u_{1x } (0, t) &= u_{2x} (0, t)
\end{align*}

Nastavka \ref{eq:4} in \ref{eq:5} vstavimo v začetne pogoje in integriramo odvode v mejah \( (-\infty, t] \). Integriramo od \( -\infty \), saj bomo potem rekli, da je v tisti točki vrednost integrirancev enaka \( 0 \).

\begin{align*}
  u_1 (- c_1 t) + u_r (c_1 t) &= u_2 (- c_2 t) \\
u_1 ' (- c_1 \tilde{t}) + u_r '(c_1 \tilde{t}) &= u_t (- c_2 \tilde{t}) && \left/ \int\limits_{-\infty}^t \, \mathrm{d} \tilde{t}
\end{align*}

Opomnik, da indeks \( t \) označuje tranzitivnost in ne odvoda po času.

Po integriranju dobimo

\[ - \frac{1}{c_1} u_i (- c_1 t) + \frac{1}{c_1} u_r (c_1t) = - \frac{1}{c_2} u_t (-c_2 t)
\]

Skupaj s prvo enačbo iz začetnih pogojev, želimo izračunati \( u_r \) in \( u_t \) v odvisnosti od podanega \( u_i \).

\begin{align*}
  u_r (s) &= \frac{c_2 - c_1}{c_1 + c_2} u_i (- s) \\
u_t (s) &= \frac{2c_2}{c_2 + c_1} u_i (s \cdot \frac{c_1}{c_2})
\end{align*}

Koeficient \( \frac{c_2 - c_1}{c_1 + c_2} \) označimo z \( R \), koeficient \( \frac{2c_2}{c_2 + c_1} \) pa s \( T \).

[slika primera]

V primeru, če imamo polneskončno struno, gre \( c_2 \to 0 \), kar pomeni, da je \( R = -1 \) oziroma, val se popolnoma odbije, kar je ustreza pričakovanjem.

Prepuščeni val se skrči, saj je \( \frac{c_1}{c_2} > 1 \), kar pomeni, da ima prepuščeni val krajšo valovno dolžino. /ni mi popolnoma jasno, kako na to vpliva člen \( u_t \) v primerjavi z \( u_i \)/.

Energije so ohranjene in velja

\[ 1 = R ^2 + T ^2 \frac{c_1}{c_2}
\]
** Končna struna

Obravnavamo struno dolžine \( l \), ki je na obeh koncih vpeta. Vpetost strune predstavljajo homogene robne pogoje za poljuben čas \( t \)

\[ u(0, t) = u(l, t) = 0
\]

Homogeni robni pogoji so takšni pogoji, da če imamo dve različni rešitvi, ki zadoščata tej enačbi, bo njuna linearna kombinacija tudi rešila enačbo.

Imamo valovno enačbo

\[ u_{tt } = c ^2 u_{ xx }
\]

Reševanja se bomo ločili s separacijo spremenljivk, kjer uporabimo separacijski nastavek

\[ u(x, t) = X (x) T(t)
\]
