#+title: 4. predavanje iz Matematične fizike
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Zvok

Imamo sistem enačb, ki ga sestavljajo Navier-Stokesova enačba, kontinuitetna enačba in gostota funkcije

\begin{align*}
  \rho \left( \frac{\partial }{\partial t} \vec{v} + \left( \vec{v} \cdot \nabla \right) \vec{v} \right) &= - \nabla p +\eta \nabla ^2 \vec{v} + \vec{f}\\
\frac{\partial }{\partial t}  \rho + \mathrm{div} \left( \rho \vec{v} \right) &= 0 \\
\rho &= g (p)
\end{align*}

V zgornjih enačbah zanemarimo \( \left( v \cdot \nabla \right) v \), saj je \( \frac{v}{c} \ll 1 \), \( \eta \to 0 \), saj \( \frac{\eta}{\rho c} \ll \lambda \), kjer je \( \lambda \) valovna dolžina. Ulomek \( \frac{\eta}{\rho c} \) je v zraku povprečna prosta pot molekule. Zanemarimo tudi \( \vec{f} = 0 \).

Definiramo amplitudo tlaka \( \delta p = p - p_0 \ll p_0 \) ter \( \delta \rho \ll \rho_0 \).

S temi popravki sedaj ponovno zapišemo zgornjo množico enačb

\begin{align*}
  \rho_0 \vec{v}_t &= - \nabla \delta p \\
\delta \rho_t + \rho_0 \mathrm{div} \vec{v} &= 0 \\
\frac{\delta \rho_0}{\rho_0} &= \chi_s \delta p
\end{align*}

kjer je \( \chi_s = \frac{1}{p \cdot K} \) adiabatna stisljivost.

Želimo izraziti enačbo v odvisnosti od tlaka \( p \). Kontinuitetno enačbo odvajamo po času

\[ \delta \rho_{tt } + \rho_0 \mathrm{div} \vec{v}_t =0
\]

Nadomestimo \( \vec{v}_t \) z izrazom iz Navier-Stokesa, ter na koncu še namesto \( \delta \rho_{tt } \) upoštevamo gostoto

\[ \delta \rho_{tt } + \rho_0 \mathrm{div} \left( - \frac{1}{\rho_0} \nabla \delta p \right) = \rho_0 \chi_s \delta p_{tt } - \nabla ^2 \delta p = 0
\]

Dobili smo valovno enačbo

\[ \delta p_{tt} = c ^2 \nabla ^2 \delta p ,  \ c ^2 = \frac{1}{\rho \chi_s}
\]

Če je \( \mathrm{rot} \vec{v} = 0 \), potem je polje brezvrtinčno in lahko hitrost zapišemo kot

\begin{equation}
\label{eq:1}
\vec{v} = - \nabla \phi
\end{equation}

kjer je \( \phi \) hitrostni potencial. Navier-Stokesa (pokrajšanega) lahko zapišemo kot

\begin{equation}
\label{eq:2}
 \rho_0 \left( - \nabla \phi_t \right) = - \nabla \delta p  \implies \rho_o \phi_t = \delta p
\end{equation}

Odstranili smo odvode, saj sta člena enaka v odvodih, kar pomeni, da sta največ za konstanto narazen po integriranju in za to konstanto lahko rečemo, da je \( 0 \). Če nadaljujemo z valovno enačbo in nadomestimo izraz \( p \) z \ref{eq:2}, da dobimo

\[ \phi_{tt } = c ^2 \nabla ^2 \phi
\]

Poglejmo si še robni pogoje: pri trdni steni se delci ustavijo, torej bo \( \frac{\partial \phi}{\partial n} = 0 \), kjer je \( n \) normala v smeri stene. Ekvivalenten pogoj, vendar za tlak bi bil \( \frac{\partial \delta p}{\partial n}  = 0 \).
** Gostota energijskega toka

Gostoto energijske toka \( \vec{\jmath} \) zapišemo po definiciji

\[ \vec{\jmath} = \frac{\mathrm{d} E}{\mathrm{d} t \mathrm{d} S}
\]

Hkrati pa lahko zapišemo po izpeljavi, ki je ne bomo delali, kot

\[ \vec{\jmath} = \delta p \vec{v}
\]

Nakaz izpeljave: izhajamo ponovno iz kontinuitetne enačbe, vendar prej uvedemo še količino gostote energije \( w \).

\[ \frac{\partial w}{\partial t} + \mathrm{div} \vec{\jmath} = 0
\]

Gostota energije pa je definirana tudi preko kinetične energije in pa dela, ki ga zvok opravlja, ko valovanje potiska okoliški zrak

\[ w = \rho_0 \frac{v ^2}{2} + \frac{\left( \delta p \right) ^2}{2 \rho_0 c}
\]

Za harmonični zvok je

\[ \overline{\vec{\jmath}} = \frac{1}{2} \mathrm{Re} \left( \partial p \vec{v}^{\ast} \right)
\]

** Zvok v 3D (Goldbart 6.3.4)
Pri pojemanju amplitude (npr. eksplozija), ki pada s kvadratom razdalje, lahko zapišemo s pomočjo d'Alembertovega principa

\[ \phi \left( r, t \right) = \frac{f(r - ct)}{r} + \frac{g(r + ct)}{r}
\]

Funkcija \( g(r + ct) \) predstavlja implozijo, ki jo zanemarimo.

[ogled posnetka eksplozije, ki jo sedaj poskušamo razumeti]

Gledamo radialno hitrost \( v = v(r) \), ki jo po definiciji potenciala lahko zapišemo

\[ v = - \frac{\partial \phi}{\partial r} = - \frac{f' \left( r - ct \right)}{r} + \frac{f(r - ct)}{r ^2}
\]

Prvemu členu se v žargonu reče "far-field", saj ima vpliv šele na večje razdalje, drugemu členu pa "near-field" iz analognega razloga.
* Difuzijska enačba
** Izpeljava

Imamo površino, skozi katero izhaja energija navzven. Skozi čas sistem izgublja energije

\[ - \frac{\mathrm{d} E}{\mathrm{d} t} = \int\limits_{}^{} \vec{\jmath} \, \mathrm{d} \vec{S} = \int\limits_{}^{} \rho \, \mathrm{d} V - \int\limits_{}^{} \rho c_{\rho} \frac{\partial T}{\partial t} \, \mathrm{d} V
\]

kjer je \( \rho \) gostota energije izvorov. \( \rho \, \mathrm{d} V = \mathrm{d}m \), hkrati pa sistem izgublja temperaturo in je koeficient naklona negativen. Površinski integral z gostoto energijskega toka lahko prevedemo na volumnski integral preko identitete

\[ \int\limits_{}^{} \vec{\jmath} \, \mathrm{d} S = \int\limits_{}^{} \mathrm{div} \vec{\jmath} \, \mathrm{d} V
\]

Imamo tri volumnske integrale in z enačitvijo integrandov, dobimo

\[ \mathrm{div} \vec{\jmath} - q + \rho c_p \frac{\partial T}{\partial t}  = 0
\]

Preko fenomenološkega Fourierovega zakona

\[ \vec{\jmath} = - \lambda \nabla T
\]

dobimo

\[ - \lambda \nabla ^2 T - q + \rho c_p \frac{\partial T}{\partial t}  = 0
\]

in smo prišli do izraza difuzijske enačbe

\[ \frac{\partial T}{\partial t}  = D \nabla ^2 T + \frac{q}{\rho c_p} , \ D = \frac{\lambda}{\rho c_p}
\]

Difuzijska konstanta \( D \) ima enote \( \left[ \frac{m ^2}{s} \right] \). Preko dimenzijske analize lahko s pomočjo karakteristik telesa tudi dobimo difuzijsko konstanto \( D = \frac{1}{3} \bar{v} \bar{l} \).

V primeru, da smo v premikajočem sistemu postane odvod po času

\[ \frac{\partial T}{\partial t}  \to \frac{\partial T}{\partial t}  + \left( \vec{v} \cdot \nabla \right)T
\]
** Robni pogoji

Imamo več različnih robnihh pogojev. Pogoj je lahko, da je na robu temperatura \( T_{rob} = 0 \). Drug možni robni pogoj je \( \frac{\partial T}{\partial n} + \Lambda \left( T - T_0 \right) = 0 \) oziroma, če je izolirano, potem \( \frac{\partial T_{rob }}{\partial n}  = 0 \). Obstaja tudi Newtonov ali Robinov robni pogoj \( \frac{\partial T}{\partial n}  + \alpha T = 0 \) in pa tudi Štefanov (sevalni), nelinearen, robni pogoj \( \frac{\partial T}{\partial n} \sim T ^4 \)
** Neskončno sredstvo

Rešujemo difuzijsko enačbo v neskončnem sredstvu

\[ \frac{\partial T}{\partial t}  = D \frac{\partial ^2 T}{\partial x ^2}
\]

Enačba je tudi invariantna na zamenjavi \( t \to k ^2 t \) in \( x \to k x \). Če je enačba invariantna na tako zamenjavo, pravimo, da je /skalirno invariantna/. Z izbiro skalarja \( k = \frac{1}{\sqrt{t}} \) difuzijska enačba postane funkcija ene spremenljivke \( s = \frac{x}{\sqrt{t}} \)

\[ T(x, t) = T \left( k x, k ^2 t \right) = T \left( \frac{x}{\sqrt{t}}, 1 \right) = f \left( \frac{x}{\sqrt{t}} \right) = f(s)
\]

Odvoda nove spremenljivke sta

\[ \frac{\partial s}{\partial x}  = \frac{1}{\sqrt{t}}, \ \frac{\partial s}{\partial t}  = - \frac{1}{2} \frac{x}{\sqrt{t}} \frac{1}{t} = - \frac{1}{2} s \frac{1}{t}
\]

Verižno odvajanje nam poda enakost \( \frac{\partial }{\partial t} = \frac{\partial }{\partial s} \frac{\partial s}{\partial t}   \), ki jo uporabimo pri preobrazbi difuzijske enačbe

\[ f' \frac{\partial s}{\partial t}  = D \frac{\partial }{\partial x} \left( \frac{\partial f}{\partial s}  \frac{\partial s}{\partial x}  \right)
\]

in nadalje

\[ f' \left( - \frac{s}{2t} \right) = D \left( \frac{1}{\sqrt{t}} \right) ^2 f''
\]
