#+title: 5. predavanje iz Matematične fizike 2
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Difuzijska enačba
** Neskončno sredstvo (Goldbart 6.4.3 Duhamelov princip)

Rešujemo difuzijsko enačbo

\begin{equation}
\label{eq:1}
 \frac{\partial  T}{\partial t } = D \frac{\partial ^2 T}{\partial x ^2}.
\end{equation}

Z izbiro skalarja \( k = \frac{1}{\sqrt{t}} \) smo prevedli difuzijsko enačbo na funkcijo ene spremenljivke \( s = \frac{x}{\sqrt{t}} \). Prejšnjič smo ostali pri enačbi, kjer ločimo spremenljivke

\[ f' \left( - \frac{s}{2t} \right) = D \left( \frac{1}{\sqrt{t}} \right) ^2 f'' \implies \ \frac{f''}{f'} = - \frac{s}{2D}
\]

Po prvem integriranju je vmesni rezultat

\[ \ln \left( f' \right)  = - \frac{s ^2}{4D} + \tilde{C},
\]

in po drugem integriranju je enako

\[ f(s) = C \int\limits_0^s e^{- \frac{\bar{s} ^2}{4D}} \, \mathrm{d} \bar{s} + C'
\]

Dobili smo dva parametra za diferencialno enačbo 2. reda, kar je v redu.

Novo spremenljivko \( k \) smo lahko uvedli, saj je bila enačba skalarno invariantna. Nismo pa omenili in sedaj omenjamo, da mora biti začetni pogoj tudi skalarno invarianten.

Preko začetnega pogoja /step-function/-a

\[ T_1 (x, t = 0) = \begin{cases}
                    1 &; x > 0 \\
                    -1 &; x < 0
                    \end{cases}
\]

bomo določili \( C \) in \( C' \).

\begin{align*}
  T_1 (x, t) &= f\left(\frac{x}{\sqrt{t}}\right)\\
& = \frac{1}{\sqrt{\pi D}} \int\limits_0^{\frac{x}{\sqrt{t}}} e^{- \frac{s ^2}{4D}} \, \mathrm{d} s \\
&= \mathrm{erf} \left( \frac{x}{\sqrt{4 D t}} \right)
\end{align*}

Odvod in integral sta tudi linearni operaciji, torej bo tudi odvod \( T_1 \) rešil difuzijsko enačbo

\begin{equation}
\label{eq:3}
 T_2 (x, t) \equiv = \frac{1}{2} \frac{\partial }{\partial x} T_1 (x, t) = \frac{1}{\sqrt{4  \pi D t}} e^{- \frac{x ^2}{4D t}},
\end{equation}

Faktor \( \frac{1}{2} \) smo uvedli v definiciji funkcije \( T_2 \) zaradi estetskih razlogov. Izbrali smo si odvod ravno zato, ker je odvod /error function/-a Gaussova funkcija

:sparkles: It's all about vanity, people! :sparkles:

Rešitev enačbe \ref{eq:1} je tudi superpozicija \( T_2 \)

\begin{equation}
\label{eq:2}
 T(x, t) = \int\limits_{- \infty}^{ \infty} g(x_0) T_2 (x - x_0, t) \, \mathrm{d} x_0,
\end{equation}

kjer je \( g(x_0) \) utež. Enačba \ref{eq:2} je definicija konvolucije. Zanima nas limita, ko gre \( t \) proti \( 0 \). Pri mafiji 1 smo Diracovo \( \delta \) funkcijo zapisali na več načinov takšne funkcije, da je vsaka iteracija funkcija višja, ožja, njen integral pa je \( 1 \). Primera sta

\[ \delta(x) = \lim_{\epsilon \to 0} \begin{cases}
                                      \frac{\exp\{- \frac{x ^2}{4 \epsilon}\}}{\sqrt{4 \pi \epsilon}} &; \text{case } 1\\
                                      \frac{1}{\pi} \frac{\epsilon}{\epsilon ^2 + x ^2} &; \text{case } 2
                                     \end{cases}
\]

Za \( t \to 0 \) je posledično \ref{eq:2}

\[ T(x, t \to 0) = \int\limits_{}^{} g(x_0) \delta (x - x_0) \, \mathrm{d} x_0 = g(x)
\]

Decembra se bomo vrnili k tem tipom rešitev - Greenove funkcije, fundamentalna rešitev.

\[ G(x, x_0, t) = \frac{1}{\sqrt{4 \pi D t}} \exp \left\{ - \frac{(x -x_0)}{4Dt} \right\} \theta(t),
\]

and

\[ \left( \frac{\partial }{\partial t}  - D \frac{\partial ^2 }{\partial x ^2}  \right) G(x, x_0, t) = \delta(x - x_0) \delta(t)
\]

Fizikalna interpretacija je to, da če imamo špicov temperaturi, se bo toplota širila preko Gaussove funkcije, kjer je širina odvisna od \( \sqrt{t} \).

Enačba \ref{eq:3} krši /kavzalnost/. Če imamo temperaturo v \( \delta \) funkciji, bo v infinitezimalno kratkem času rešitev tudi Gaussova funkcija. Gaussova funkcija pa ima repe že takrat neničelne. Zaradi eksponenta bodo res majhni, vendar ne bodo ničelni. Če se nam rešitev čudno obnaša, je to mogoče problem.

** Polneskončno sredstvo

Imejmo poltrak na pozitivni osi, kjer je robni pogoj \( T(x = 0, t) = h (t) \) z začetnim pogojem \( T(x, 0) = 0 \), Zanima nas rešitev.

Če je \( h(t) = 1 \) (konstantna), potem je rešitev difuzijske enačbe

\[ T(x, t) = \left[ 1- T_1 (x, t) \right] \Theta(t) = w (x, t)
\]

Ideja, ki bi jo radi izvedli je, da z \( w(x, t) \) zapišemo rešitev za poljuben \( h(t) \). Temu se reče Duhamelov [du-a-mel] princip.

Za začetek zapišemo poljubno funkcijo \( h(t) \) kot superpozicijo majhnih prispevkov

\[ h(t) = h(0) + \int\limits_{}^{} \dot{h} (\tau) \Theta(t - \tau) \, \mathrm{d} \tau,
\]

kjer je \( \dot{h} (\tau) \mathrm{d} \tau \) skok(ec) v funkciji, stopničasta funkcija pa poskrbi za stopničastost. Konvolucija med \( w \) in \( \dot{h} \) nam preko per partesa poda splošno rešitev

\[ T(x, t) = \int\limits_0^t h(\tau) \frac{\partial }{\partial t}  w(x, t - \tau) \, \mathrm{d} \tau
\]

Glavna stvar, ki jo odneseš od difuzijske enačbe je

\[ x \sim \sqrt{t}
\]

(Posledično ima temperatura na 4m globine Zemlje nasprotno fazo od zunanjega zraka)
** Končna 2D domena

Imejmo kvadratno domena dolžine \( L \), kjer imajo spodnja, leva in desna stranica temperaturo \( T = 0 \). Zgornja stranica ima odvod ničeln \( \vec{\jmath} = 0 \). Začetni pogoj opišemo s

\[ T \left( \vec{r}, 0 \right) = f \left( \vec{r} \right)
\]

Še zmeraj rešujemo difuzijsko enačbo

\[ \frac{\partial T}{\partial t}  = \nabla ^2 T.
\]

Predpostavili smo \( D = 1 \). Za reševanje bomo uporabili separacijo spremenljivk in nastavek \( T(x, y, t) = \phi(x, y) u(t) = X(x) Y(y) u(t) \). Vstavimo nastavek v difuzijsko enačbo in dobimo

\[ \frac{\dot{u}}{u} = \frac{\nabla ^2 \phi}{\phi} = \frac{X''}{X} + \frac{Y''}{Y} = - \lambda
\]

Obravnavamo 3 primere: \( \lambda = 0, \pm \lambda \).
*** \( \lambda = 0 \)

V primeru, da je \( \lambda = 0 \), je rešitev časovnega dela

\[ \frac{\dot{u}}{u} = 0 \implies \ u(t) = \mathrm{konst}
\]

Rešujemo krajevi del in dobimo Laplaceovo enačbo

\[ \nabla ^2 \phi = 0
\]

Rešitev, ki zadosti robnim pogojem, je

\[ \phi(x, y) = 0.
\]

Taka rešitev je tudi v redu, zgolj in izključno, če \( f = 0 \). V splošnem rešitev ni v redu.
*** \( \lambda < 0 \)

Rešitev časovnega dela je v tem primeru

\[ u(t) = A \exp \left\{ \left| \lambda \right| t \right\}
\]

Iz enačbe

\[ \frac{X''}{X} + \frac{Y''}{Y} = - \lambda
\]

sledi, da mora biti vsaj eden od členov večji od 0, da je njuna vsota večja od \( 0 \). Predpostavimo \( \frac{X''}{X} > 0 \). Rešitev enega od krajevnih delov je

\[ X (x) = \alpha \mathrm{ch} (x) + \beta \mathrm{sh } (x)
\]

Ker je hiperbolični kosinus neničeln in ima hiperbolični sinus izključno eno ničlo, ne moremo zadostiti robnim pogojev, iz tega sledi, da ne moremo zadostiti robnim pogojev. Fizikalno gledano bi rešitev lahko že s časovnih delom zavrgli, saj eksponentno narašča. V splošnem rešitev ni v redu.
*** \( \lambda > 0 \)

Časovni del je

\[ u(t) = A e ^{- \lambda t}.
\]

V krajevnih delih imamo oscilirajoče funkcije \( \cos  \) in \( \sin  \). Zavržemo kosinus, saj v ni ničeln v točki \( (0, 0) \). Da zadostimo stranskima začetnima pogojema \( T = 0 \), je krajevni del v \( x \)-smeri enak

\[ X_n = \sqrt{\frac{2}{L}} \sin \left( \frac{n \pi x}{L} \right), \ n = 1, 2, \ldots
\]

Za \( y \)-os imamo na spodnji stranici enak začetni pogoj \( T = 0 \), vendar pri \( y = L \) pa imamo hrbet. Torej bo rešitev

\[ Y_m = \sqrt{\frac{2}{L}} \sin \left( \frac{\left( m + \frac{1}{2} \right) \pi y}{L} \right), \ m = 0, 1, 2, \ldots
\]

Sledi, da je

\[ \lambda_{n, m} = \left( \frac{\pi}{L} \right) ^2 \left[ n ^2 + \left( m + \frac{1}{2} \right) ^2 \right],
\]

čemur rečemo lastna vrednost. Funkciji

\[ \phi_{n, m} = X_n Y_m
\]

pravimo lastna funkcija.

Enačbi, ki združi dano lastno vrednost in lastno funkcijo,

\[ \nabla ^2 \phi_{n, m} = - \lambda_{n, m} \phi_{n, m}
\]

Helmholtzova ali amplitudna enačba.

Splošna rešitev je

\[ T(x, t) = \sum\limits_{n, m}^{} c_{n, m} \phi_{n, m} (x, y) e^{- \lambda_{n, m} t}
\]

Iz začetnega pogoja dobimo, da je

\[ c_{n, m} = \left\langle \phi_{n, m} \middle| f \right\rangle
\]

Funkcija doseže maksimum ob času \( 0 \) (zaradi eksponentnega padanja) ali ob robu (zaradi robnih pogojev).
