#+title: 6. predavanje iz Matematične fizike 2
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Laplaceova enačba

Laplaceova enačba je enačba oblike

\[ \nabla ^2 \phi =0
\]

Primeri poddomen fizike, kjer se Laplaceova enačba pojavlja so elektrostatika, stacionarna difuzijska enačba, minimalne površine (milnica), hidrodinamika - hitrostni potencial. Ne da se vsakega hitrostnega toka opisati s potencialom, vendar ko se da, pravimo, da je tok potencialen.

Površina, ki jo bo zasedla milnica bo minimalna zaradi minimizacije energije. V eni dimenziji je dolžina krivulje, ki jo opisuje poljubna funkcija \( z(x) \) izračunana preko

\[ \int\limits_0^l \sqrt{1 + z' ^2 } \, \mathrm{d} x.
\]

Dvodimenzionalen ekvivalent za površino je

\[ S = \int\limits_{}^{} \sqrt{1 + (\nabla z) ^2} \, \mathrm{d} x \mathrm{d} y.
\]

Minimiziramo površino z odvodom

\[ \mathrm{div} \left( \frac{\nabla z}{\sqrt{ 1 + \left( \nabla z \right) ^2}} \right) = 0
\]

in wham bam Laplaceova enačba.
** Matematični komentarji

Rešitev Laplaceove enačbe ima ničelno ukrivljenost. To pomeni, da sta ukrivljenosti različno predznačeni pri koordinatah - smo na sedlo. V nadaljevanju bomo srečali, da če imamo oscilirajočo funkcijo (npr. \( \sin  \)) v eni koordinati, bo v drugi koordinati eksponenta funkcija (npr. \( \mathrm{sh} \)).

Takim funkcijam, ki zadoščajo enačbi, pravimo harmonične funkcije. Imamo tudi izrek, da je vrednost v točki enaka povprečju v \( \epsilon \) okolici - to nam pove, da ni ekstremov znotraj območja. V dveh dimenzijah so analitične funkcije konformne preslikave (?). Realni in imaginarni del posebej rešitva Laplaceovo enačbo.

#+begin_my_example
Za \( z \in \mathbb{C} \) vzamemo kompleksen logaritem \( \ln z \). Realni del je \( \ln r \), imaginarni del pa je \( \phi = \arctan \frac{y}{x} \).
#+end_my_example

Laplaceova enačba je ekstrem variacijskega računa

\begin{equation}
\label{eq:1}
 S = \int\limits_{}^{} \left( \nabla \phi \right) ^2 \, \mathrm{d} V
\end{equation}

Numerično je včasih lažje računati \ref{eq:1} kakor Laplaceovo enačbo.

Za Neumannov robni pogoj velja, da je integral po smernih odvodih roba površine ničeln.

\[ \int\limits_{\partial \mathcal{D}}^{} \frac{\partial \phi}{\partial \vec{n}} \, \mathrm{d} S = 0.
\]

Upoštevamo definicijo smernega odvoda

\[ \frac{\partial \phi}{\partial \vec{n}} = \nabla \phi \cdot \vec{n},
\]

in funkcijo lahko preko Gaussovega izreka zapišemo kot

\[ \int\limits_{\partial \mathcal{D}}^{} \left( \nabla \phi \right) \cdot \mathrm{d} \vec{S} = \int\limits_{\mathcal{D}}^{} \nabla ^2 \phi \, \mathrm{d} V = 0.
\]

Nam to pove, da je pretok ničeln?
** Separacija spremenljivk v kartezičnih koordinatah
*** Kvadrat z Dirichletovimi robnimi pogoji

Imamo kvadrat s stranico \( L \). Na levi in desni stranici kvadrata imamo homogen robni pogoj \( \phi(x = 0, y) = \phi(x = L, y) = 0 \). Na zgornji in spodnji stranici kvadrata pa imamo nehomogene robne pogoje \( \phi(x, y = 0) = f(x) \) in \( \phi(x, y = L) = g(x) \).

Separacije spremenljivk ima obliko \( \phi(x, y) = X(x) Y(y) \), kar preobrazi Laplaceovo enačbo v

\[ \frac{X''}{X} + \frac{Y''}{Y} = 0
\]

Najprej bomo reševali v tisti koordinati, kjer imamo homogene robne pogoje. Zaradi homogenih robnih pogojev nas zanima oscilirajoča funkcija, saj imamo dve ničli na razdalji \( L \) med sabo. Torej je baza rešitev enačbe

\[ X'' + k X = 0,
\]

\( \left\{ \sin (kx), \cos (kx) \right\} \). Diskretne rešitve so ob upoštevanju robnih pogojev

\[ X_n (x) = \sqrt{ \frac{2}{L}} \sin \left( \frac{n \pi}{L} x \right).
\]

Rešimo še v koordinati \( y \). Kakor smo prej napisali, bodo sedaj tukaj eksponentne funkcije

\[ Y_n (y) = \alpha_n \mathrm{sh} \left( \frac{n \pi}{L} y \right) + \beta_n \mathrm{ch} \left( \frac{n \pi}{L} y \right).
\]

Skupna rešitev je tako

\begin{equation}
\label{eq:2}
 \phi = \sum\limits_n^{} \left( \alpha_n \mathrm{sh} \left( \frac{n \pi}{L} y \right) + \beta_n \mathrm{ch} \left( \frac{n \pi}{L} y \right) \right) X_n (x).
\end{equation}

Koeficienta \( \alpha_n \) in \( \beta_n \) določimo iz robnih pogojev

\[ y = 0: f(x) = \sum\limits_n^{} \beta_n \cdot 1 \cdot X_n (x), \quad y= L: \ g(x) = \sum\limits_n^{} \left( \alpha_n \mathrm{sh} (n \pi) + \beta_n \mathrm{ch} (n \pi) \right) X_n,
\]

which is ugly as fuck. Rešili bomo to grdoto nehomogenih robnih pogojev z uvedbo funkcijo

\begin{align*}
  u_n (y) &= \mathrm{sh} \left( \frac{n \pi}{L} y \right) \mathrm{ch} \left( \frac{n \pi}{L} 0 \right) - \mathrm{ch} \left( \frac{n \pi}{L} y \right) \mathrm{sh} \left( \frac{n \pi}{L} 0 \right) \\
v_n (y) &= \mathrm{sh} \left( \frac{n \pi}{L} y \right) \mathrm{ch} \left( \frac{n \pi}{L} L \right) - \mathrm{ch} \left( \frac{n \pi}{L}y \right) \mathrm{sh} \left( \frac{n \pi}{L} \cdot L \right)
\end{align*}

Taki funkciji sta kul, ker iz nehomogenih robnih pogojev ustvarita homogene robne pogoje. Namesto \( \mathrm{sh} \) in \( \mathrm{ch} \) v enačbi \ref{eq:2} nadomestimo s funkcijama \( u_n \) in \( v_n \).
*** Neumannov robni pogoj

Neumannov robni pogoj pomeni, da imamo v robnih pogojih predpisane odvode. Imamo kvadrat s stranico \( L \). Desna in leva stranica imata homogen Neumannov robnih pogoj \( \phi_x (x = 0, y) = \phi_x (x = L, 0) = 0 \). Na zgornji in spodnji stranici pa imamo nehomogen robni pogoj \( \phi_y (x, y = 0) = f(x) \) in \( \phi_y (x, y = L) = g(x) \).

Rešimo na podoben način kakor pri Dirichletovih robnih pogojih, vendar je tukaj razlika, da bosta \( u_n \) in \( v_n \) definirani tako, da bodo njuni odvodi ustvarili homogene robne pogoje.
** Separacija spremenljivk v polarnih koordinatah

Spomnimo bralca, da je Laplaceov operator v polarnih koordinatah enak

\[ \nabla ^2 \psi = \frac{\partial ^2 \psi}{\partial r ^2} + \frac{1}{r} \frac{\partial \psi}{\partial r} + \frac{1}{r ^2} \frac{\partial ^2 \psi}{\partial \phi ^2}
\]

Separacija spremenljivk bo oblike \( \psi(r, \phi) = R(r) \Phi(\phi) \). Enačba za \( \phi \) se glasi

\[ \Phi'' + m ^2 \Phi = 0,
\]

hkrati imamo pa periodičnost na \( 2 \pi \), ker tako delujejo krožnice. Rešitev te enačbe bomo zapisali z eksponentnim zapisom

\[ \Phi_m = e^{\mathrm{i} m \phi},  \ \phi \in [0, 2\pi), m \in \mathbb{Z}
\]

V primeru, da je \( m = 0 \), sta linearno neodvisni rešitvi \( \left\{ 1, \phi \right\} \) (konstanta in linearna funkcija).

Radialni del ima enačbo

\[ R'' + \frac{R'}{r} - \frac{m ^2}{r ^2}R = 0,
\]

katere rešitev je \( R (r) = r^{\pm \left| m \right|} \). V primeru, da je \( m = 0 \) sta bazi \( \left\{ 1, \ln r \right\} \)- to je zato, ker logaritem narašča počasneje kot katerakoli potenca.

Splošna rešitev, ki vsebuje vse napisano je

\[ \psi(r, \phi) = \left( A_0 + B_0 \ln r \right) \left( a_0 + b_0 \phi \right) + \sum\limits_{m \ne 0, m = -\infty}^{\infty} \left( A_m r^{\left| m \right|} + B_m r^{- \left| m \right|}  \right) e^{\mathrm{i} m \phi}
\]

Želimo rešiti enačbo z Dirichletovimi robnimi pogoji \( \psi(r = a, \phi) = f(\phi) \), kjer je \( a \) polmer kroga, na katerem rešujemo enačbo. Konstanti \( B_0 \) in \( B_m \) sta ničelna, hkrati pa je zaradi periodičnosti \( b_0 = 0 \). Upoštevamo še robni pogoj

\[ f(\phi) = A_0 + \sum\limits_m^{} A_m a^{\left| m \right|} e^{\mathrm{i} m \phi}.
\]

Preko Fourierove transformacije se priborimo do vrednosti koeficientov

\[ A_m = \frac{1}{2 \pi} \frac{1}{a ^{\left| m \right|}} \int\limits_0^{2\pi} e^{- \mathrm{i} m \phi '} f(\phi ') \, \mathrm{d} \phi '
\]

Ker veljajo matematični pogoji, lahko zamenjamo integral in vsoto, da je končna rešitev enaka

\[ \psi(r, f) = \frac{1}{2 \pi} \int\limits_0^{2\pi} \frac{\left( a ^2 - r ^2 \right) f(\phi')}{a ^2 - 2ar \cos (\phi - \phi') + r ^2} \, \mathrm{d} \phi'
\]
** Komentar
