#+title: 9. predavanje iz Matematične fizike 2
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Sturm-Liouvilleov problem
** Cilindrični koordinatni sistem - Laplace

Rešujemo Laplaceovo enačbo v cilindričnih koordinatah

\[ \nabla ^2 u =0.
\]

Problem bomo reševali s separacijo spremenljivk \( u(r, \phi, z) = R(r) \Phi(\phi) Z(z) \). Kot primer, na katerem rešujemo naš problem, je cilinder polmera \( a \) in širine \( a \) z Dirichletovimi robnimi pogoji na vseh ploskvah razen na zgornji, kjer imamo funkcijo \( f(r, \phi) \).

V smeri \( \phi \) bo zaradi periodičnosti problema baza rešitev \( \left\{ \cos (m\phi), \sin (m\phi) \right\} \). V koordinati \( r \) bomo imeli neko oscilirajočo rešitev, ki zadosti Dirichletovim robnih pogojom - baza rešitev bodo Besselove funkcija \( J_m \left( \xi_{m, n} \frac{r}{a} \right) \).

Do baze rešitve v \( z \) smeri pridemo preko naslednjega razmisleka: iščemo funkcijo(-e) \( h( \alpha z), \alpha \in \mathbb{C} \), ki bo zadostila Laplaceovi enačbi in se bo njen odvod odštel z odvodom radialnega dela v nič. Drugače povedano, razlika funkcij \( u_{zz} \sim \alpha ^2 h(z) J_m   \) in \( \nabla_r ^2 u \sim - \frac{\xi_{m, n} ^2}{a ^2} h(z) J_m \) bo ničelna.

Drugi odvod oscilirajoče funkcije je negativen, zato je \( \nabla_r ^2 u \) negativno predznačena.

Preproste funkcije, ki jih poznamo in za njih velja \( \frac{\mathrm{d} ^2 h}{\mathrm{d} z ^2} = h(z) \) so kotne in hiperbolične funkcije. Drugi odvod kotnih funkcij je drugačno predznačen, kakor njihova osnovna funkcija, kar pomeni, da so edino eksponentne funkcije take, ki zadostijo našim zahtevam.

Baza funkcijo v \( z \) smeri je torej \( \left\{ \mathrm{ch} \left( \frac{\xi_{m, n}}{a} z \right), \mathrm{sh} \left( \frac{\xi_{m, n}}{a} z \right) \right\} \). Robnemu pogoju \( u(r, \phi, a) = f(r, \phi) \) zadosti zgolj hiperbolični sinus.

Nastavek bo torej oblike

\[ u(r, \phi, z) = \sum\limits_{m = 0}^{\infty} \sum\limits_{n = 1}^{\infty} J_m \left( \xi_{m, n} \frac{r}{a} \right) \mathrm{sh} \left( \frac{\xi_{m, n}}{a} z \right) \left[ \alpha_{m, n} \cos (m \phi) + \beta_{m, n} \sin (m \phi) \right]
\]

V primeru, če bi imeli funkcijski robni pogoj na plašču, torej \( u(a, \phi, z) = f(\phi, z) \) in drugje \( u(r, \phi, 0) = u(r, \phi, h) = 0 \), potem preko analognega razmisleka pridemo do nastavka

\[ u(r, \phi, z) = \sum\limits_{m = 0}^{\infty} \sum\limits_{n = 1}^{\infty} \sin \left( \frac{\pi n z}{h} \right) I \left( \frac{n \pi}{h} r \right)  \left[ \alpha_{m, n} \cos (m \phi) + \beta_{m, n} \sin (m \phi) \right],
\]

kjer je \( I \) modificirana Besselova funkcija.
** Sferični koordinatni sistem - lastne vrednosti

Rešujemo Helmholtzovo enačbo

\[ \nabla ^2 u + \lambda u = 0,
\]

v sferičnih koordinatah. Laplaceov operator v sferičnih koordinatah zapišemo

\[ \nabla ^2 u = \frac{1}{r ^2 } \frac{\partial }{\partial r} \left( r ^2 u_r \right) - \frac{L ^2}{r ^2} u,
\]

kjer je \( L \) kotni del sferičnih koordinat

\[ L ^2 = - \frac{1}{\sin \theta} \frac{\partial }{\partial \theta}  \left( \sin \theta \frac{\partial }{\partial \theta}  \right) - \frac{1}{\sin ^2 \theta} \frac{\partial ^2 }{\partial \phi ^2}.
\]

Namenoma smo zapisali na tak način, saj kotni del v resnici predstavlja vrtilno količino \( \vec{L} = \vec{r} \times \vec{p} \), če je definicija gibalne količine enaka \( \vec{p} = - \mathrm{i} \nabla \).

*** Kotni del
Za kotni del velja enakost

\begin{equation}
\label{eq:1}
 L ^2 u = l(l + 1) u.
\end{equation}

Pri reševanju s separacijo spremenljivk \( u(r, \phi, \theta) = R(r) \Theta(\theta) \Phi(\phi) \) ponovno pogledamo vsako spremenljivko posebej.

V koordinati \( \phi \) imamo opravko z diferencialno enačbo

\[ \frac{\Phi''}{\Phi} = - m ^2,
\]

katere baza rešitev je \( \left\{ \sin(m \phi), \cos(m \phi) \right\} \). Tukaj se lahko tudi navežemo na tretjo komponento vrtilne količine \( L_z = - \mathrm{i} \frac{\partial }{\partial \phi}  \), za katero velja

\[ L_z ^2 \Phi_m = m ^2 \Phi_m
\]

V koordinati \( \theta \) uvedemo spremenljivko \( t = \cos \theta \). Enačba \ref{eq:1} tako postane

\[ \frac{\mathrm{d} }{\mathrm{d} t} \left[ \left( 1- t ^2 \right) \frac{\mathrm{d} \Theta}{\mathrm{d} t} \right] + \left[ l(l + 1) - \frac{m ^2}{1 - t ^2} \right] \Theta = 0
\]

Zaradi drugega reda diferencialne enačbe bomo imeli dve linearno odvisni rešitvi. Iz kvantne mehanike že poznamo eno od rešitev in sicer sferne harmonike

\[ \Theta \cdot \Phi = Y_{l, m} \left( t = \cos \theta, \phi \right).
\]

Iz kvantne mehanike vemo, da so dovoljene vrednosti celoštevilski ali polštevilski \( l \le n \) ter \( -l \le  m \le l\). Ta pogoj se pri naši enačbi skriva v sebiadjungiranosti kot posledica končnosti na polih (look into further).

Sferični harmoniki so sorazmerni s \( P_l^m (t) e^{\mathrm{i} m \phi} \), kjer so \( P_l^m \) Legendrovi polinomi. Sferični harmoniki so tudi ortonormirani

\[ \int\limits_{-1}^1 \int\limits_0^{2\pi} Y^{\ast}_{l, m} Y_{l', m'} \, \mathrm{d} t \mathrm{d} \phi = \delta_{ll'} \delta_{m m'}.
\]

Legendrovi polinomi imajo tudi pripadajoče generatrise ([[https://viri.cjvt.si/sopomenke/eng/headword/8196943][tvorilke]]). Nekatere so:

\[ \frac{1}{\sqrt{1 - 2xt + x ^2}} = \sum\limits_{l = 0}^{\infty} P_l (t) x^l.
\]

Za vektorja \( r_1 \) in \( r_2 \) z vmesnim kotom \( \gamma \) bo generatrisa tudi

\[ \frac{1}{\left| \vec{r}_1 - \vec{r}_2 \right|}  = \frac{1}{r_{>}} \sum\limits_{l = 0}^{\infty} \left( \frac{r_{<}}{r_{>}} \right)^l P_l (\cos \gamma).
\]

Vektorja \( \vec{r}_1 \) in \( \vec{r}_2 \) imata pripadajoči koordinati \( \theta_i , \phi_i \) za \( i = 1, 2 \).

\[ P_l (\cos \gamma) = \frac{4 \pi}{2l  1} \sum\limits_{m = - l}^l Y_{lm}^{\ast} \left( \theta_1, \phi_1 \right) Y_{lm}(\theta_2, \phi_2)
\]

Druga neodvisna rešitem je \( Q_l ^m (t, \phi) \), kjer je

\[ Q_0 = \frac{1}{2} \ln \left( \frac{1 + t}{1 - t} \right).
\]

Opazimo lahko, da ima \( Q_0 \) za celoštevilske \( l \) pole.

*** Radialni del

Za radialni del imamo diferencialno enačbo

\[ \frac{1}{r ^2} \left( r ^2 R' \right) ' - \frac{l (l + 1)}{r ^2} R + \lambda R = 0.
\]

Ob uvedbi nove spremenljivke \( R = \frac{Z(r)}{\sqrt{r}} \) dobimo Besslova diferencialno enačbo

\[ r ^2 Z '' + r Z' + \left[ \lambda r ^2 - \left( l + \frac{1}{2} \right) ^2 \right] Z = 0,
\]

ki pa ima polarni indeks. Rešitve so Besslove funkcije, ki pa jim zaradi našega koordinatnega sistema pravimo sferične Besslove funkcije

\begin{align*}
  j_l (r) &= \sqrt{\frac{\pi}{2 r}} J_{l + \frac{1}{2}} \left( r \right) \\
y_l (r) &= \sqrt{\frac{\pi}{2 r}} Y_{l + \frac{1}{2}} \left( r \right)
\end{align*}

\( j_l \) je sferičen ekvivalent Besslove funkcije, \( y_l \) pa sferičen ekvivalent Neumannove funkcije.

Z utežjo \( r ^2 \) so funkcije ortogonalne.

V primeru ničelne lastne vrednosti \( \lambda = 0 \) rešujemo Laplaceovo enačbo. Radialni del ima bazo \( \left\{ r^l, r^{- l ( + 1 )} \right\} \). Splošna rešitev Laplaceove enačbe je

\[ u (r, \theta, \phi) = \sum\limits_{l, m}^{} C_{l, m} \begin{bmatrix} r^{l} \\ r^{- (l + 1)} \end{bmatrix} Y_{l, m} (\theta, \phi) .
\]

To nas spominja na multipolni razvoj potenciala pri EMP.
