#+title: 12. predavanje iz Matematične fizike
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Greenove funkcije

Rešujemo problem

\[ \nabla ^2 u + k ^2 u = \delta \left( \vec{r} - \vec{r}_0 \right)
\]
** Trodimenzionalni problem

Za \( k = 0 \) je Greenova funkcija, ki reši problem

\[ G \left( \vec{r}, \vec{r}_0 \right) = \frac{1}{4 \pi} \frac{1}{\left| \vec{r} - \vec{r}_0 \right|},
\]

saj poznamo

\[ G \left( \vec{r}, \vec{r} _0 \right) = - \frac{1}{4 \pi} \frac{1}{r_s} \sum\limits_{k = 0}^{\infty} \left( \frac{r_l}{r_s} \right) ^l P_l \left( \cos \theta \right).
\]

Za \( k ^2 > 0 \) v izhodišču je Greenova funkcija

\[ G \left( \vec{r}, 0 \right) = \begin{cases}
                                  -\frac{1}{4 \pi r} e^{\pm\mathrm{i} k r}&; \text{potujoci} \\
                                   -\frac{\cos (kr)}{2 \pi r} &; \text{ stojeci}
                                 \end{cases}.
\]

Ne moremo zapisati \( k ^2 < 0 \), saj bi to pomenilo, da je \( k \in \mathrm{Im} \). Namesto tega bomo rekli, da rešujemo enačbo

\[ \left( \nabla ^2 - k ^2 \right) u = \delta,
\]

katere rešitve so

\[ G \left( \vec{r}, 0 \right) = - \frac{e^{\pm k r}}{4 \pi r}
\]
** Končno območje

Na končnem območju (krompirju) \( \mathcal{D} \) Greenova funkcija \( G \left( \vec{r}, \vec{r}_0 \right) \) ne zadosti robnim pogojem.

Rešujemo problem

\[ \mathcal{L} u = \delta \left( \vec{r}- \vec{r}_0 \right)
\]

in potrebujemo Greenovo funkcijo \( G \left( \vec{r}, \vec{r}_0 \right) \), ki je na robu \( 0 \) (torej zadosti Dirichletovemu problemu).

\[ G \left( \vec{r}, \vec{r}_0 \right) = G_{\infty} \left( \vec{r}, \vec{r}_0 \right) + g \left( \vec{r}, \vec{r}_0 \right),
\]

kjer velja \( \mathcal{L} g = 0 \) in robni pogoj za Dirichleta je \( g \left( \vec{r}_B, \vec{r}_0 \right) = - G_{\infty} \left( \vec{r}_B, \vec{r}_0 \right) \),

kjer je \( \vec{r}_B \) radij vektor, ki teče po \( \partial \mathcal{D} \).

Ko izračunamo \( G \), uporabimo Greenovo zvezo, da dobimo rešitev.

Operator je definiran kot

\[ \mathcal{L} u = \nabla ^2 u + q \left( \vec{r} \right) u.
\]

Greenova zveza je

\[ \int\limits_{\mathcal{D}}^{} \left( u \mathcal{L} v - v \mathcal{L} u \right) \, \mathrm{d} V = \int\limits_{\partial D}^{} \left( u \frac{\partial v}{\partial n} - v \frac{\partial u}{\partial n}   \right)\, \mathrm{d} S
\]

Dirichletov problem te vrste je

\[ \mathcal{L} u = f \left( \vec{r} \right), \, \vec{r} \in \mathcal{D}
\]

z robnim pogojem \( u \left( \vec{r}_B \right) = g \left( \vec{r}_B \right) \) za \( \vec{r}_B \in \partial \mathcal{D} \).

Za Greenovo funkcijo bo veljalo

\[ \mathcal{L}_{\vec{r}} G = \delta \left( \vec{r} - \vec{r}_0 \right),
\]

in \( G \left( \vec{r}_B, \vec{r}_0 \right) = 0 \). Uporabimo Greenovo zvezo

\begin{align*}
  \int\limits_{\mathcal{D}}^{} \left( u \mathcal{L} G - G \mathcal{L} u \right) \, \mathrm{d} V &= \int\limits_{\partial \mathcal{D}}^{} \left( u \frac{\partial G}{\partial n}  - G \frac{\partial y}{\partial n}  \right) \, \mathrm{d} S\\
\int\limits_{\mathcal{D}}^{} \left( u \delta - G f \right) &= \int\limits_{\partial \mathcal{D}}^{} g \frac{\partial G}{\partial n}  \, \mathrm{d} S
\end{align*}

Po postopku izrazimo funkcijo \( u \)

\[ u \left( \vec{r} \right) = \int\limits_{\mathcal{D}}^{} G \left( \vec{r}, \vec{r}_0 \right) f \left( \vec{r}_0 \right) \, \mathrm{d} V_0 + \int\limits_{\partial \mathcal{D}}^{} g \left( \vec{r}_B \right) \frac{\partial G \left( \vec{r} , \vec{r}_B \right)}{\partial \vec{r}_B} \cdot \mathrm{d} \vec{S}_B
\]

V primeru Neumannovega problema imamo

\[ \nabla ^2 u = f \left( \vec{r} \right)
\]

z robnim pogojem

\[ \frac{\partial u \left( \vec{r}_B \right)}{\partial n} = g \left( \vec{r}_B \right), \ \vec{r}_B \in \partial \mathcal{D}.
\]

Uvedemo vez, ki nam fizikalno sporoča, da je vsota izvirov v volumnu, enaka toku po robu

\[ \int\limits_{\partial \mathcal{D}}^{} g \left( \vec{r}_B \right) \, \mathrm{d} S_B = \int\limits_{\mathcal{D}}^{} f \left( \vec{r} \right) \, \mathrm{d} V
\]

Greenova funkcija je

\begin{equation}
\label{eq:1}
 \mathcal{L} G = \delta
\end{equation}

in

\begin{equation}
\label{eq:2}
 \frac{\partial G \left( \vec{r}_B, \vec{r}_0 \right)}{\partial \vec{r}_B} = 0.
\end{equation}

Pogoja Greenova funkcije sta prestroga, saj za \ref{eq:1} velja

\[ \int\limits_{\partial \mathcal{D}}^{} \frac{\partial G}{\partial n}  \, \mathrm{d} S = 1,
\]

medtem ko pridemo do neenakosti pri Greenovi zvezi \ref{eq:2}.

Zrahljali bomo pogoj \ref{eq:2} tako, da

\begin{align*}
  \nabla ^2 G_N &= \delta \left( \vec{r} - \vec{r}_0 \right) - \frac{1}{V} \\
\left. \frac{\partial G_{N}}{\partial n} \right|_{\partial \mathcal{D}} &= 0.
\end{align*}

Slednjemu se reče Neumann Greenova funkcija.

Greenova zveza nam poda

\[ u \left( \vec{r} \right) = \int\limits_{\mathcal{D}}^{} G_N \left( \vec{r}, \vec{r}_0 \right) f \left( \vec{r}_0 \right) \, \mathrm{d} V_0 - \int\limits_{\partial \mathcal{D}}^{} g \left( \vec{r}_B \right) G_N \left( \vec{r}, \vec{r}_B \right) \, \mathrm{d} S_B + \mathrm{konst}
\]
** Primer

Imejmo polneskončno domeno \( \mathcal{D} \). Rešujemo Laplaceovo enačbo

\[ \nabla ^2 u = f(x, y)
\]

z robnim problemom \( u(x = 0, y)= h(y) \).

Greenova funkcija je

\[ \nabla ^2 G = \delta,
\]

kjer je

\[ G = G_{\infty} + g, \, G_{\infty} = \frac{1}{2 \pi} \ln \left| \vec{r} - \vec{r}_0 \right|.
\]

Funkcija \( g(0, y) \) je

\[ g(0, y) = - \frac{1}{2 \pi} \ln \left| (0, y) - \vec{r}_0 \right|
\]

z

\[ \nabla ^2 g = 0.
\]

Zrcaljenje \( \vec{r} = (-x_0, y_0) \). Greenova funkcija je

\[ G = \frac{1}{2 \pi} \ln \frac{\left| \vec{r} - \vec{r}_0 \right|}{\left| \vec{r} - \vec{r}_0 \right|}
\]
** Primer b) (Haberman 11.3, Hassani)

Imamo diferencialni operator

\[ \mathcal{L} = \left( \frac{\partial }{\partial t} - D \nabla ^2 \right)
\]

Rešujemo enačbo

\[ \mathcal{L} u = f \left( \vec{r}, t \right)
\]

z začetnim pogojem \( u \left( \vec{r} , t= 0 \right) = h \left( \vec{r} \right) \) in Dirichletovim robnim pogojem \( u \left( \vec{r}_B, t \right) = g \left( \vec{r}_B, t \right) \). Greenova funkcija je

\[ \mathcal{L} G \left( \vec{r}, t \right) = \delta \left( \vec{r} - \vec{r}_0 \right) \delta(t).
\]

Posplošena Greenova zveza poda

\begin{align*}
  u \left( \vec{r}, t \right) = & \int\limits_{\mathcal{D}}^{} G \left( \vec{r}, \vec{r}_0, t \right) h \left( \vec{r}_0 \right) \, \mathrm{d} V_0 + \iint\limits_{\mathcal{D}}^{} G \left( \vec{r}, \vec{r}_0, t - \tau \right) f \left( \vec{r}_0, \tau \right) \,\mathrm{d } V_0 \\
&- D \int\limits_{\partial D}^{} \frac{\partial G}{\partial n}  \left( \vec{r}, \vec{r}_B, t  \tau \right) g \left( \vec{r}_B, \tau \right) \, \mathrm{d} S_B \, \mathrm{d} \tau
\end{align*}

Prvi integral poskrbi za začetne pogoje, drugi integral nehomogenosti in tretji robne pogoje.
** Primer: disk, Laplace

Imejmo disk s polmerom \( R \). Greenova funkcija naj bo

\[ G = G_{\infty} + g, \, G_{\infty} = \frac{\ln r}{2 \pi}.
\]

Rešujemo

\[ \nabla ^2 g = 0
\]

z robnimi pogoji

\[ \left. g \right|_{\partial \mathcal{D}} = - \left. G_{\infty} \right|_{\partial D} = - \frac{1}{4 \pi} \ln \left( R ^2 + r_0 ^2 - 2 R r_0 \cos \left( \phi - \phi_0 \right) \right)
\]

Splošna rešitev je

\[ g = c_0 + \sum\limits_{m = 1}^{\infty} \left[ c_m \cos (m \phi) + d_m \sin (m\phi) \right] r^m
\]

Velja

\[ \ln \left( 1 + x ^2 - 2x \cos \alpha \right) = - \sum\limits_{n = 1}^{\infty} \frac{2}{n} x^n \cos (n \alpha).
\]

Zapišemo

\[ \ln \left[ (1 - z) (1 - z ^n) \right] , \ z = \lambda e^{\mathrm{i} \alpha}.
\]

Iz tega velja

\[ g = - \frac{\ln R ^2}{4 \pi} - \frac{1}{4 \pi }\left[ \sum\limits_{n = 1}^{\infty} - \left( \frac{r_0}{R} \right) ^2 \frac{2}{n} \left\{ \cos (n \phi) \cos (n \phi_0) + \sin (n\phi) \sin (n \phi_0) \right\} \right]
\]

Odčitamo \( c_n \) in \( d_n \). Vrsta za \( g \) istega tipa kot \( \ln \left( \ldots \right) \) in jo nazaj seštejemo

\[ g = - \frac{1}{4 \pi} \ln \left[ R ^2 + \frac{\left( r_0 r \right) ^2}{R ^2} - 2 r r_0 \cos (\phi - \phi_0) \right].
\]

Imamo zrcaljenje

\[ G = G_{\infty} + g = \frac{1}{4 \pi}  \frac{\left| \vec{r} - \vec{r}_0 \right| ^2}{\left( \frac{r_0}{R} \right)^2 \left| \vec{r} - \vec{r}_0 \right|}
\]

Kvocient v imenovalcu poskrbi, da je Greenova funkcija na robu res \( 0 \). Slednja funkcija nam poda zrcaljenje čez mejo roba.
