#+title: 15. predavanje iz Matematične fizike
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Greenova funkcija
** Greenova funkcija in integralska enačba

Rešujemo  problem oblike

\begin{equation}
\label{eq:1}
 \mathcal{L} u(x) + \epsilon V(x) u(x) = 0,
\end{equation}

kjer je \( \mathcal{L} \) poljubni diferencialni operator in poznamo njegovo Greenovo funkcijo. Enačbo obravnavamo kot nehomogeno.

Rešitev te enačbe je sestavljena iz homogenega dela \( h(x) \), ki zadosti enačbi \( \mathcal{L} h(x) = 0 \) in podobno robnim pogojem. Drugi del pa je rešitev nehomogene enačbe, ki smo ga že srečali. Dobimo integralsko enačbo

\[ u(x) = h(x) + \epsilon \int\limits_{}^{} G(x, x_0 ) V(x_0) u(x_0) \, \mathrm{d} x_0.
\]

Drugo ime za to integralsko enačbo je Fredholmova enačba.

#+name: vezana stanja v enodimenzionalnem potencialu \( V(x) \)
#+begin_my_example
Imamo Schrödingerjevo enačbo

\[ -\frac{\hbar ^2}{2m} u'' + V(x) u = E u.
\]

Pretvorili jo bomo na obliko enačbe \ref{eq:1}

\[ \left( \frac{\mathrm{d} ^2 }{\mathrm{d} x ^2} - \kappa ^2 \right) u = \frac{2m V(x)}{\hbar ^2} u, \  \kappa ^2 = -\frac{2m E}{\hbar ^2}
\]

Diferencialni operator je torej \( \mathcal{L} = \left( \frac{\mathrm{d} ^2 }{\mathrm{d} x ^2} - \kappa ^2 \right) \).

Greenova funkcija za dan operator je

\[ G(x, x_0) = - \frac{- e^{- \kappa \left| x - x_0 \right|}}{2 \kappa}.
\]

Da je temu res tako, lahko bralec preveri doma.

Kako smo prišli do te Greenove funkcije. Nekaj z zlepljenjem eksponentnega padanja pri \( x = x_0 \) z odvodom različnim od 0.

Integralska enačba je

\begin{equation}
\label{eq:2}
 u(x) = - \frac{m}{\kappa \hbar ^2} \int\limits_{- \infty}^{\infty} e^{- \kappa \left| x - x_0 \right|} V(x_0) u(x_0) \, \mathrm{d} x_0.
\end{equation}

Zaradi prave izbire Greenove funkcije je homogena rešitev enaka \( 0 \). Splošen nastavek homogene rešitve bi bil

\[ h(x) = C_1 e^{- \kappa x} + D_1 e^{ \kappa x}.
\]

Zaradi regularnosti v \( x = \infty \) mora biti \( C_1 = 0 \) in ekvivalentno tudi \( D_1 \).
#+end_my_example

#+begin_comment
Komentar k rešitvi primera.

1) Rešitev \ref{eq:2} je lastna funkcija v eni dimenziji za HO, jamo, itd.

2) Za potencial \( V(x) = \delta(x - a) \) dobimo edino vezano stanje.
#+end_comment

#+name: Sipanje v treh dimenzijah
#+begin_my_example
Ravni val \( e^{\mathrm{i} \vec{k}_0 \vec{r}} \) pošljemo v smeri \( \vec{k}_0 \) na nek potencial.

Greenova funkcija v treh dimenzijah je oblike

\[ G = - \frac{1}{4 \pi r} e^{\mathrm{i} \vec{k} \cdot \vec{r}}.
\]

Integralska enačba pa je

\[ u \left( \vec{r} \right) = e^{\mathrm{i} \mathbf{k} \cdot \mathbf{r}} - \frac{2m}{\hbar ^2} \int\limits_{}^{} \frac{e^{\mathrm{i} \mathbf{k}_0 \left| \mathbf{r} - \mathbf{r}_0 \right|}}{4 \pi \left| \mathbf{r} - \mathbf{r}_0 \right|} V \left( \mathbf{r}_0 \right) u \left( \mathbf{r}_0 \right) \, \mathrm{d} V_0
\]
#+end_my_example
*** Perturbacijski razvoj

Naj bo za enačbo \ref{eq:1} vrednost \( \epsilon \) majhna.

Naj bo rešitev \( h(x) \) približno enako 1. V 0. tem redu lahko zapišemo

\[ u_0 (x) = h(x)
\]

Rešitev Fredholma ob 1. redu v \( \epsilon \) je

\[ u_1 (x) = h(x) + \epsilon \int\limits_{}^{} G(x, y_1) V(y_1) h(y_1) \, \mathrm{d} y_1.
\]

Rešitev v 2. redu bo vsebovala rešitev 1. reda in se bo glasila

\[ u_2 (x) = u_1 (x) + \epsilon ^2 \iint\limits_{}^{} G (x, y_1) G(y_1, y_2) V(y_1) V(y_2) h(y_2) \,\mathrm{d} y_1 \mathrm{d} y_2.
\]

Rešitve se nadaljujejo do poljubnega reda \( r \). Tej vrsti se reče Neumannova-Borrnova vrsta in ima končen konvergenčni radij.

Obstaja pa tudi boljša konvergentna resumacija, ki konvergira (Fredholmova vrsta).

Naj bo \( \mathcal{K} \) linearni operator, za katerega velja

\[ \mathcal{K} u = \int\limits_{}^{} G(x, x_0) V(x_0) u(x_0) \, \mathrm{d} x_0.
\]

Fredholmova enačba je

\[ u = h + \epsilon \mathcal{K} u.
\]

Izrazimo \( u \)

\[ u = \frac{h}{(1 - \epsilon \mathcal{K})},
\]

kar lahko izrazimo v vrsti, saj je \( \epsilon \) majhen.
* Variacijska formulacija

Rešujemo enačbo

\[ \mathcal{L} u (x) = f (x),
\]

kjer je \( \mathcal{L} \) sebi-adjungiran z ustreznimi robnimi pogoji. Želimo ga zapisati kot ekstrem nekega funkcionala, ki je oblike

\[ S = \frac{1}{2} \left\langle \mathcal{L} u \middle| u \right\rangle - \left\langle f \middle| u \right\rangle
\]

#+begin_proof
Opravimo funkcijsko variacijo \( \delta S \), za katero velja, da je enaka \( 0 \).

Upoštevamo našo nastavek, ki ga dokazujemo.

\[ \delta S = 0 = \frac{1}{2} \left\langle \mathcal{L} \delta u \middle|  u \right\rangle + \frac{1}{2} \left\langle \mathcal{L} u \middle| \delta u  \right\rangle - \left\langle f \middle| \delta u \right\rangle.
\]

Zaradi sebi-adjungiranosti lahko prvi člen zapišemo kot

\[ \left\langle \mathcal{L} \delta u \middle| u \right\rangle = \left\langle \delta u \middle| \mathcal{L}^{\ast} u \right\rangle = \left\langle \delta u \middle| \mathcal{L} u \right\rangle
\]

Ob predpostavki, da je \( u \) realno, potem velja

\[ \left\langle \delta u \middle| \mathcal{L} u \right\rangle  = \left\langle \mathcal{L} u \middle| \delta u \right\rangle.
\]

Sedaj izpeljano vstavimo v variacijo

\[ \delta S = 0 = \left( \frac{1}{2} \left\langle \mathcal{L} u \right| + \frac{1}{2} \left\langle \mathcal{L} u \right| - \left\langle f \right|\right) \left| \delta u \right\rangle = 0,
\]

saj velja iz formulacije problema

\[ \mathcal{L} u - f = 0
\]
#+end_proof

#+begin_my_example
Naj bo diferencialni operator \( \mathcal{L} = - \nabla ^2 \) in \( f = 0 \).

Funkcional je po definiciji

\[ S = - \frac{1}{2} \int\limits_{}^{} \nabla ^2 u u \, \mathrm{d} V
\]

Integral lahko prepišemo v

\[ \int\limits_{}^{} \nabla ^2 u u \, \mathrm{d} V = - \frac{1}{2} \int\limits_{}^{} \mathrm{div} \left( \nabla u u \right) \, \mathrm{d} V + \frac{1}{2} \int\limits_{}^{} \left( \nabla u \right) ^2 \, \mathrm{d} V
\]

Integral z divergenco lahko pretvorimo na ploskovni integral in oba sta ničelna

\[ - \frac{1}{2} \int\limits_{}^{} \mathrm{div} \left( \nabla u u \right) \, \mathrm{d} V = - \frac{1}{2} \int\limits_{}^{} \nabla u u \, \mathrm{d} S = 0.
\]

Sledi torej

\[ S = \frac{1}{2} \int\limits_{}^{} \left( \nabla u \right) ^2 \, \mathrm{d} V
\]

Ta problem smo srečali pri energiji polja v EMP, kjer je \( u = \phi \).
#+end_my_example

#+name: Poissonova enačba
#+begin_my_example
Naj bo diferencialni operator \( \mathcal{L} = -\nabla ^2 \) in \( f \ne 0 \).

Funkcional je

\[ S = \frac{1}{2} \int\limits_{}^{} \left( \nabla u \right) ^2 \, \mathrm{d} V - \int\limits_{}^{} f u \, \mathrm{d} V.
\]

Integral funkcije \( fu \) je potrebna energija naboja v potencialu u.
#+end_my_example

#+name: Helmholtzova enačba
#+begin_my_example
Naj bo diferencialni operator \( \mathcal{L} u = \left( \nabla ^2 + k ^2 \right)u \) in \( f = 0 \).

Problem rešujemo kot vezan problem

\[ S = \int\limits_{}^{} \left( \nabla u \right) ^2 \, \mathrm{d} V
\]

ob vezi

\[ \int\limits_{}^{} u ^2 \, \mathrm{d} V  = 1.
\]

Vrednost \( S \) v ekstremu pa je \( k ^2 = S (u_{ekstr}) \).

Zapišemo

\[ k ^2 = \frac{\int\limits_{}^{} \left( \nabla u \right) ^2 \, \mathrm{d} V}{\int\limits_{}^{} u ^2 \, \mathrm{d} V},
\]

ki smo ga izvrednotili v ekstremu. Minimalna vrednost \( k ^2 \) je minimiziran kvocient. V kvantni mehaniki se tej minimizaciji reče Rayleigh-Ritzova minimizacija.
#+end_my_example

#+name: Najnižja frekvenca okrogle opne
#+begin_my_example
Rešujemo enačbo

\[ \nabla ^2 u + k ^2 u = 0
\]

z robnim pogojem \( u (R) = 0 \).

Vemo, da je točna rešitev

\[ u \sim J_0 \left( \xi_0^1 \frac{r}{R} \right) \implies \, k ^2 = \left( \frac{\xi_0^1}{R} \right) = 5.78319
\]

Variacijski nastavek, ki ga uporabimoje

\[ u = A \left( 1 - \left( \frac{r}{R} \right) ^2 \right)
\]

Minimizirati moramo torej

\[ k ^2 = \frac{\int\limits_{}^{} 2 \pi r u'  ^2 \, \mathrm{d} r}{\int\limits_{}^{} 2 \pi r u ^2} = 6
\]

Napaka je za 3.7%.

Če upoštevamo še drugi člen variacijskega nastavka

\[ k ^2 = A \left( 1 - \left( \frac{r}{R} \right) ^2 \right) + B \left( 1 - \left( \frac{r}{R} \right) ^2 \right) ^2.
\]

Z minimizacijo dobimo

\[ k ^2_{min} = = \frac{20 (2 + 4B + 2B ^2)}{10 + 15B + 6B ^2} = 5.78413
\]

in napaka je \( 1.00016 \xi_0^{(1)} ^2 \). Z nadaljnimi členi ne pridobimo signifikantne natančnosti.

Za večjo natančnost brez potrebe računanja novih parametrov členov bomo uporabili Fredholmovo enačbo

\[ u (\mathbf{r}) = \left( - k ^2 \right) \int\limits_{}^{} G \left( \mathbf{r}, \mathbf{r}_0 \right) u (\mathbf{r}_0) \, \mathrm{d} S
\]
#+end_my_example
