#+title: 1. predavanje iz EMP
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Elektrostatika
** Coulumbova sila med naboji

Elektrostatika opisuje sile med /mirujočimi/ električnimi naboji. Ker so mirujoči, pomeni, da nimamo nobenih magnetnih sil. Točkasta nabita telesa med seboj delujejo z električno silo. Sila je privlačna, če sta različno predznačena in odbojna, če sta enako predznačena. Sila je sorazmerna z velikostjo obeh nabojev

\begin{equation}
\label{eq:1}
 \vec{F} = \frac{e_1 e_2}{4 \pi \epsilon_0 r ^2} \frac{\vec{r}}{r}
\end{equation}

Enačba \ref{eq:1} opisuje silo, ki jo čuti naboj \( e_2 \) zaradi \( e_1 \). Konstanti \( \epsilon_0 = 8.85 \cdot 10^{-12} \frac{\mathrm{As}}{\mathrm{Vm}} \) rečemo indukcijska/influenčna konstanta (ang. /vacuum conductivity/). Izvor Coulumbove sile so bile meritve.
** Velikost in enota eletričnega naboja

Naboj merimo v Coulumbih \( 1 \mathrm{C} = 1 \mathrm{As} \). Naboj je (praviloma) mnogokratnik osnovnega naboja \( e_0 = 1.6 \cdot 10^{-19} \mathrm{As} \). Najmanjši naboj v naravi je na kvarku in sicer \( \frac{1}{3} e_0 \).

| thing of magic          | naboj (e 0)                             |
| kvark                   | 1/3                                     |
| elektrona               | 1                                       |
| kondenzator             | \(1 \cdot 10^{-7} \mathrm{As }\)        |
| blisk                   | 1 - 100 C                               |
| avto akumulator         | \( 10 \mathrm{Ah} = 36000 \mathrm{C} \) |
| Zemlja (brez atmosfere) | 1 C                                     |
| elektrarna (1 leto)     | \( 3 \cdot 10^{11} \mathrm{C} \)        |
** Jakost električnega polja

V Faradeyjevi in Maxwellovi sliki je električno polje posrednik interakcije (elektrostatske sile). Z uvedbo posrednika se s trenutnim znanjem izognemo veliki količini enačb, kasneje se izkaže, da sta v relativizmu magnetno in električno polje sklopljena in je najbolj naravno govoriti o tem.

En (ali več) naboj električnega polja, ki pa potem deluje na drugi naboj. Električno silo zapišemo kot

\[ \vec{F} = e  \vec{E} \quad \text{ali} F_{21} = e_1 \vec{E}_2
\]

Sila \( \vec{F}_{21} \) je sila, ki deluje na prvi naboj, ki pa jo ustvarja električno polje drugega naboja. Posledica uvedbe električnega polja \(  \vec{E} \) preko sile je to, da je smer \( \vec{E} \) sile na pozitiven točkast naboj.

Električno polje točkastega naboja je enako

\[ E = \frac{e_0}{4 \pi \epsilon_0} \frac{\vec{r}}{r ^3}
\]

ki ga izpeljemo preko primerjave s Coulumbovim zakonom (I presume).

[skici el. polja + in - naboja]

\[ \begin{array}{|c|c|} \hline \text{kozmicno sevanje} & 10 \mu \frac{\mathrm{V}}{ \mathrm{m}} \\ \text{polje znotraj bakrene zice} & 0.5 \frac{m \mathrm{V}}{m} \\ \text{polje v Zemljini atmosferi} & 100 - 300 \frac{\mathrm{V}}{\mathrm{m}} \\ \text{prebojna jakost v atmosferi} & 1 - 3 \frac{M \mathrm{V}}{m} \\ \text{polje preko bioloske membrane} & 10 \frac{M \mathrm{V}}{m} \\ \text{polje v mocnem laserskem pulzu} & 100 \frac{\mathrm{T V}}{\mathrm{m}}\\ \hline \end{array}
\]


#+begin_my_example
Električno polje zaslona (LCD). Napetost približno \( 10 \mathrm{V} \). Debelina zaslonov je nekaj \( 10 \mu m \). Električno polje je tako

\[ E \sim \frac{U}{d} \sim 10^6 \frac{V}{m}
\]
#+end_my_example
** Električne silnice

[mreza nabojev 3 x 3]

Lastnosti silnic so:
- silnice kažejo v smeri \( \vec{E} \) in se ne sekajo
- silnice se začnejo v pozitivnem naboju in končajo v negativnem naboju
- silnice niso zaključene
- gostota silnic ustreza jakosti polja

Mreža, ki smo jo narisali, je Faradayjeva konstrukcija.
** Električna cirkulacija

Cirkulacija se uvede kot integral skalarnega produkta

\[ \Gamma_E = \oint\limits_{C}^{} \vec{E} \cdot \, \mathrm{d} \vec{r}
\]

po zaključeni zanki \( C \).

#+begin_my_example
Imamo homogeno električno polje \( \vec{E} \). V njem tvorimo poljubno pravokotno zanko \( C \) tako, da sta dve stranici \( b \) pravokotni, dve stranici \( a \) pa vzporedni električnemu polju. Zanima nas \( \Gamma_E \), ki bo vsota skalarnih produktov posameznih stranic pravokotnika. Skalarni produkt stranic pravokotnih na električno polje je po definiciji skalarnega produkta enako 0. Stranici, ki sta vzporedni, pa je integral enak \( E\cdot a \).

\[ \Gamma_E = E\cdot a + 0 - E \cdot a = 0 = 0
\]
#+end_my_example

#+begin_theorem
Za vsa statična električna polja velja \( \Gamma_E = 0 \).
#+end_theorem

Iz tega sledi z uporabo Stokesovega izreka

\[ 0 = oint\limits_C^{} \vec{E} \cdot \mathrm{d} \vec{r} = \iint\limits_{S}^{} \nabla \times \vec{E} \,\mathrm{d } \vec{S}
\]

kjer je \( C = \partial S \). Posledično sledi

\[ \nabla \times \vec{E} = 0
\]

Statično električno polje je vedno brezvrtinčno (lastnost 3 naših silnic).

#+begin_my_example
Imamo dve polji. Glej slike.

a) Polje opišemo z

   \[ \vec{E}_1 = E_0 \frac{\vec{r}}{r}
   \]

   Rotor polja \( \vec{E}_1 \) je enak \( 0 \). Divergenca polja \( \vec{E}_1 \) je različna od \( 0 \).
   /Kuščar, Kodre imata identitete na koncu knjige./

   Brezvrtinčno polje je izvorno.

b) Električno polje je

   \[ \vec{E}_2 = E_2 \hat{e}_{\phi} = E_0 \left( - \sin \phi, \cos \phi \right)
   \]

   Rotor polja \( \vec{E}_2 \) je različen od \( 0 \), divergenca pa enaka ničla.
#+end_my_example

** Električni pretok

Električni pretok je definiran kot integral električnega polja po površini

\[ \Phi_E = \int\limits_S^{} \vec{E} \cdot \mathrm{d} \vec{S}
\]

Površina je poljubna, vendar ni nujno sklenjena. Če je, dobimo Gaussov zakon.

/O njem bomo več povedali v prihodnosti. Tole sedaj je samo :sparkles: foreplay :sparkles:/.
** Električni potencial

Uvedemo ga kot

\[ \vec{E} \left( \vec{r} \right) = - \nabla \phi \left( \vec{r} \right)
\]

Negativen predznak je tam po dogovoru. Uvedemo električni potencial, zato da si olajšamo računanje, saj je skalarna količina.

#+begin_my_example
Električni potencial točkastega naboja je po definiciji enak

\[ \vec{E} = - \nabla \phi
\]

Električno polje je definirano iz sile.

\begin{equation}
\label{eq:2}
 \frac{e}{4 \pi \epsilon_0} \frac{\vec{r}}{r ^3} = - \nabla \left( \frac{e}{4 \pi \epsilon_0} \frac{1}{r} + \phi_0 \right)
\end{equation}

Za točkast naboj je potencial tako

\[ \phi \left( \vec{r} \right) = \frac{e}{4 \pi \epsilon_0} \frac{1}{r} + \phi_0
\]
#+end_my_example

Potencial v enačbi \ref{eq:2} lahko določimo do konstante natančno, kar dosežemo do \( \phi_0 \). Tej zadevi pravimo umeritev (ang. /gauge/).
Izbira umeritve nima vpliva na makroskopsko dinamiko našega potenciala. Potencial sam na ne pove veliko - napetost je razlika potencialov in se umeritvi odštejeta. Poleg tega je sila povezana z električnim poljem, konstanto pa prvi odvod izniči.

Za drugačna polja se lahko umerja tudi različne funkcije \( f \).
