#+title: 4. predavanje iz Elektromagnetnega polja
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Elektrostatika
** Sila kot funkcional električnega polja

Zanima nas sila, ki deluje na \( \rho \left( \vec{r} \right) \) v odvisnosti od celotnega \( E \left( \vec{r} \right) \). Sila na telo je volumnski integral

\[ \vec{F} = \int\limits_V^{} \rho \left( \vec{r} \right) \vec{E}_{Z} \left( \vec{r} \right) \, \mathrm{d} ^3 \vec{r}
\]

po volumnu telesa. \( \vec{E}_Z \) je zunanje električno polje. Preko Maxwellove enačbe nadomestimo \( \rho \left( \vec{r} \right) \) z

\[ \nabla \cdot \vec{E}_L = \frac{\rho}{\epsilon_0}
\]

kjer je \( \vec{E}_L \) notranje električno polje. Sila je tako

\[ \vec{F} \left( \vec{r} \right) = \epsilon_0 \int\limits_V^{} \left( \nabla \cdot \vec{E}_L \right) \vec{E}_{Z} \, \mathrm{d} ^3 \vec{r}
\]

Opomba, da je integral produkta gostote električnega polja in lastnega električnega polja enak 0 (ne moreš sam sebe dvigniti):

\[ \int\limits_V^{} \rho \left( \vec{r} \right) \vec{E}_L \, \mathrm{d} ^3 \vec{r} = 0
\]

Zapis sile lahko razširimo z \( \nabla \cdot \vec{E}_Z \). Ta člen je v našem integralu enak \( 0 \) (torej nismo nič spremenili, ko smo ga dodali), saj je integral po volumnu telesa, medtem ko so naboji zunanjega električnega polja neskončno oddaljeni.

\[ \vec{F} \left( \vec{r} \right) = \epsilon_0 \int\limits_V^{} \left( \nabla \cdot \vec{E}_L + \nabla \cdot \vec{E}_Z \right) \vec{E}_Z \, \mathrm{d} ^3 \vec{r} = \epsilon_0   \int\limits_V^{} \left( \nabla \cdot \vec{E} \left( \vec{r} \right) \right) \vec{E}_Z \, \mathrm{d} ^3 \vec{r}
\]

Vsota zunanjega in lastnega polja je pa ravno celotno električno polje - upoštevali smo linearnost divergence.

Naš volumnski integral bi radi zapisali v površinski integral, kar bomo naredili preko zveze s tenzorskim produktom

\[ \nabla \cdot \left( \vec{E} \otimes \vec{E} \right) = \vec{E} \cdot \left( \nabla \cdot \vec{E} \right) + \left( \vec{E} \cdot \nabla  \right) \vec{E}
\]

ter Gaussovega izreka(?)

\[ \int\limits_V^{} \nabla \cdot \vec{E} \, \mathrm{d} ^3 \vec{r} = \int\limits_{\partial V}^{} \vec{E} \, \mathrm{d} \vec{S}
\]

Tenzorski produkt za vektorja \( \vec{a} = (a_1, a_2, a_3) \) in \( \vec{b} = (b_1, b_2, b_3) \) je \( 3 \times 3 \) matrika, kjer je \( ij \)-ti element matrike

\[ \left( \vec{a} \otimes \vec{b} \right)_{ij} = a_i \cdot b_j
\]

Integral se tako pretvori v

\begin{equation}
\label{eq:1}
 \vec{F} = \epsilon_0 \int\limits_V^{} \left[ \nabla \cdot \left( \vec{E} \otimes \vec{E}\right) - \left( \vec{E} \cdot \nabla  \right) \vec{E} \right] \, \mathrm{d} ^3 \vec{r} = \epsilon_0 \int\limits_{\partial V}^{} \left( \vec{E} \otimes \vec{E}\right) \, \mathrm{d} \vec{S} - \epsilon_0 \int\limits_V^{} \left( \vec{E} \cdot \nabla \right) \vec{E} \, \mathrm{d} ^3 \vec{r}
\end{equation}


Upoštevamo identiteto

\[ \frac{1}{2} \nabla E ^2 = \left( \vec{E} \cdot \nabla \right) \vec{E} + \vec{E} \times \left( \nabla \times \vec{E} \right)
\]

Člen z vektorskim produktom je ničeln (zakaj?). Enačba \ref{eq:1} pa se pretvori v

\[ \vec{F} = \epsilon_0 \int\limits_{\partial V}^{} \left( \vec{E} \otimes  \vec{E}\right) \, \mathrm{d} \vec{S} - \frac{\epsilon_0}{2} \int\limits_V^{} \nabla E ^2 \, \mathrm{d} ^3 \vec{r} = \epsilon_0 \int\limits_{\partial V}^{} \left[ \left( \vec{E} \otimes \vec{E}\right)- \frac{1}{2} E ^2 \right] \, \mathrm{d} \vec{S}
\]

Torej bo sila

\begin{equation}
\label{eq:2}
 \vec{F} = \epsilon_0 \int\limits_{\partial V}^{} \left[ \left( \vec{E} \otimes  \vec{E}\right) - \frac{1}{2} E ^2 \cdot I \right] \vec{n} \, \mathrm{d} S
\end{equation}

kjer je \( \vec{E} \) celotno električno polje, \( I \) identiteta in \( \vec{n} \) normala delca. Silo \( \vec{F} \) smo prav tako določili brez eksplicitne uporabe gostote električnega polja \( \rho \left( \vec{r} \right) \).
** Napetostni tenzor električnega polja

Dobljen zapis silo v električnem polju \ref{eq:2} se lahko zapiše z uporabo napetostnega tenzorja električnega polja

\[ F_i = \oint\limits_V^{} T_{ik} n_k \, \mathrm{d} S, \quad T_{ik} = \epsilon_0 \left( E_i \cdot E_k - \frac{1}{2} E ^2 \delta_{ik} \right)
\]

kjer je \( T_{ik} \) napetostni tenzor električnega polja.

Velja tudi Gauss-Ostrogradski

\begin{equation}
\label{eq:3}
 F_i = \oint\limits_{\partial V}^{} T_{ik} \, \mathrm{d} S_k = \int\limits_V^{} \frac{\partial T_{ik}}{\partial x_{k}} \, \mathrm{d} ^3 \vec{r}
\end{equation}

Zapišemo identiteto

\[ a_{ik} b_k = \sum\limits_k^{} a_{ik} b_k.
\]

Iz \ref{eq:3} lahko prepoznamo oz. uvedemo volumsko gostoto sile

\[ f_i = \frac{\partial T_{ik}}{\partial x_{k}}
\]

Zapis gostote sile kot divergence napetostnega tenzorja je splošen in se lahko uporablja tudi za druga polja.
** Multipolni razvoj električnega potenciala

Imamo predmet, ki ima gostoto električnega polja \( \rho \left( \vec{r} \right) \). Ta predmet ustvarja potencial \( \phi \left( \vec{r} \right) \). Velja, kakor že mnogokrat povedano,

\begin{equation}
\label{eq:4}
 \phi \left( \vec{r} \right) = \int\limits_{}^{} \frac{\rho \left( \vec{r} \right)}{4 \pi \epsilon_0 \left| \vec{r} - \vec{r} \, ' \right|} \, \mathrm{d} ^3 \vec{r} \,'
\end{equation}

Zanima nas električno polje "daleč" stran od same gostote naboje in to po vodilnih prispevkih - multipolih. Vektor \( \vec{r} \) je vektor znotraj telesa. Zanima nas režim \( \left| \vec{r} \right| \gg \left| \vec{r} \, ' \right|\).

Ponovimo Taylorjev razvoj za vektorje

\[ f \left( \vec{r} + \vec{h} \right) = f \left( \vec{r} \right) + \vec{h} \cdot \nabla f \left( \vec{r} \right) + \frac{1}{2} \vec{h} H \left( f\left( \vec{r} \right) \right) \cdot \vec{h} + \ldots
\]

kjer je \( H \left( f \left( \vec{r} \right) \right) \) Hessejeva matrika. S pomočjo tega lahko razvijemo ulomek v potencialu kot

\[ \frac{1}{\left| \vec{r} - \vec{r} \, ' \right|} = \frac{1}{r} - \vec{r} \, ' \cdot \nabla \frac{1}{\left| \vec{r} \right|}  + \ldots = \frac{1}{\vec{r}} + \vec{r} \, ' \frac{\vec{r}}{r ^3}
\]

Torej bo potencial potem

\begin{align*}
  \phi \left( \vec{r} \right) &= \frac{1}{4 \pi \epsilon_0} \int\limits_{}^{} \frac{\rho \left( \vec{r} \, ' \right)}{r} \, \mathrm{d} ^3 \vec{r} \, ' + \frac{1}{4 \pi \epsilon_0} \int\limits_{}^{} \rho \left(\vec{r}\,'\right) \vec{r} \, \frac{\vec{r} \, '}{r ^3} \, \mathrm{d} ^3 \vec{r} \, ' \\
&= \frac{1}{4 \pi \epsilon_0} \int\limits_{}^{} \rho \left( \vec{r} \,' \right) \, \mathrm{d} ^3 \vec{r} \,' + \frac{\vec{r}}{4 \pi \epsilon_0 r ^3} \int\limits_{}^{}\vec{r}\,' \rho \left( \vec{r} \, ' \right) \, \mathrm{d} ^3 \vec{r} \, ' + \ldots
\end{align*}

Torej je potencial enak

\[ \phi \left( \vec{r} \right) = \frac{e}{4 \pi \epsilon_0 r} + \frac{\vec{r} \cdot \vec{p}}{4 \pi \epsilon_0 r ^3}
\]

\begin{align*}
  \int\limits_{}^{} \rho \left( \vec{r} \, ' \right) \, \mathrm{d} ^3 \vec{r} \, ' = e && \text{ električni monopol } \\
\int\limits_{}^{} \vec{r} \, ' \rho \left( \vec{r} \, ' \right) \, \mathrm{d} ^3 \vec{r} = \vec{p}  && \text{električni dipol}
\end{align*}

Zgornji integralom pravimo elementi multipolnega razvoja električnega potenciala. V splošnem velja v sferičnih koordinatah \( r, \phi, \theta \)

\[ \phi \left( \vec{r} \right) = \frac{1}{4 \pi \epsilon_0} \sum\limits_{l = 0}^{\infty} \sum\limits_{m = - l}^l \frac{4 \pi}{2l + 1} \frac{q_{lm}}{r^{l + 1} } Y_{lm} \left( \theta, \phi \right)
\]

kjer so \( Y_{lm} \left( \theta, \phi \right) \) sferični harmoniki (krogelne funkcije), \( q_{lm} \) multipolni koeficienti

\[ q_{lm} = \int\limits_{}^{} \rho(s) s^l Y_{lm} \left( \theta', \phi' \right) \, \mathrm{d} ^3 \vec{s}
\]

** Polje in potencial točkastega dipola

Kakor smo že izračunali, velja

\[ \phi \left( \vec{r} \right) = \frac{\vec{r} \cdot \vec{p}}{4 \pi \epsilon_0 r ^3}
\]

Električno polje pa je po definiciji

\[ \vec{E} \left( \vec{r} \right) = - \nabla \phi \left( \vec{r} \right) = - \nabla \left( \frac{\vec{r} \cdot \vec{p}}{4 \pi \epsilon_0 r ^3} \right) = - \frac{\vec{p}}{4 \pi \epsilon_0 r ^3} + \frac{3 \left( \vec{r} \cdot \vec{p} \right) \vec{r}}{4 \pi \epsilon_0 r ^5}
\]

[slika električnega dipola]
** Multipolni razvoj elektrostatske energije

Imamo predmet z gostoto električnega naboja \( \rho \left( \vec{r} \right) \) v zunanjem električnem polju \( \vec{E} \) oz. potencialu \( \phi \). Zanima nas elektrostatska energija multipolov v zunanjem električnem polju. Kakor je bilo izpeljano na prejšnji uri, je elektrostatska energija

\begin{equation}
\label{eq:5}
 W = \int\limits_V^{} \rho \left( \vec{r} \right) \phi \left( \vec{r} \right) \, \mathrm{d} ^3 \vec{r}
\end{equation}

kjer je \( V \) volumen telesa.

Predpostavimo, da je naboj zbran okrog točke \( \vec{r}_0 \) znotraj volumna. Potem je potencial

\[ \phi \left( \vec{r} \right) = \phi \left( \vec{r}_0 \right) + \left( \vec{r} - \vec{r}_0 \right) \nabla \phi \left( \vec{r}_0 \right)
\]

Razvoj potenciala vstavimo v enačbo \ref{eq:5} za elektrostatsko energijo in ker je \( \vec{r}_0 \) neodvisen od \( \vec{r} \), lahko konstante postavimo pred integral

\begin{align*}
  W &= \int\limits_V^{} \rho \left( \vec{r} \right) \left[ \phi \left( \vec{r}_0 \right) + \left( \vec{r} - \vec{r}_0 \right) \nabla \phi \left( \vec{r}_0 \right) \right] \, \mathrm{d} ^3 \vec{r} \\
&= e \phi \left( \vec{r}_0 \right) + \nabla \phi \left( \vec{r}_0 \right) \int\limits_V^{} \rho \left( \vec{r} \right) \left( \vec{r} - \vec{r}_0 \right) \, \mathrm{d} ^3 \vec{r}
\end{align*}

To pomeni, da je elektrostatska energije multipolnega razvoja enaka

\begin{equation}
\label{eq:6}
 W = e \phi - \vec{p} \cdot \vec{E}
\end{equation}

kjer je prvi člen energija monopola zunanjega pola, drugi člen pa energija dipola v zunanjem polju.

** Sila in navor na multipole v zunanjem polju

Za prej obravnavani predmet z gostoto električnega naboja \( \rho \left( \vec{r} \right) \) opisan z multipoli nas zanimata sila in navor.

Začnimo s silo, kjer uporabimo definicijo

\begin{equation}
\label{eq:7}
 \mathrm{d} W = - \vec{F} \cdot \mathrm{d} \vec{r}
\end{equation}

in je sila

\begin{equation}
\label{eq:8}
 F = - \nabla W
\end{equation}

Z drugimi besedami nas zanima, za koliko se spremeni energija, če predmet z \( \rho \left( \vec{r} \right) \) premaknemo za \( \mathrm{d} \vec{r} \). V enačbo \ref{eq:7} vstavimo prej dobljeno enačbo \ref{eq:6} in dobimo

\begin{align*}
  \mathrm{d} W &= \mathrm{d} \left( e \phi - \vec{p} \vec{E} \right) \\
&= e \nabla \phi \left( \vec{r}_0 \right) \, \mathrm{d} \vec{r} -  \mathrm{d} \left( \vec{p} \cdot \vec{E} \right)\\
&= e \nabla \phi \left( \vec{r}_0 \right) \, \mathrm{d} \vec{r} - \nabla \left( \vec{p} \cdot \vec{E}  \right) \, \mathrm{d} \vec{r}
\end{align*}

Pred nadaljevanjem moramo omeniti identiteto

\[ \nabla \left( \vec{p} \cdot \vec{E} \right) = p \times \left( \nabla \times \vec{E} \right) + \left( \vec{p}\cdot \nabla \right) \vec{E}
\]

Prvi člen z vektorskim produktom je ničeln.

Delo se nadalje preobrazi v

\begin{align*}
  \mathrm{d} W &= e \nabla \phi \left( \vec{r}_0 \right) \, \mathrm{d} \vec{r} - \left( \vec{p} \cdot \nabla \right) \vec{E} \, \mathrm{d} \vec{r}
\end{align*}

iz česar sledi sila

\[ \vec{F} = e \vec{E} + \left( \vec{p} \cdot \nabla \right) \vec{E}
\]

kjer je prvi člen sila na monopol, drugi člen pa sila na električni dipol. Drugi člen je tudi smerni odvod, definiran kot

\[ \left( \vec{p} \cdot \nabla \right) \vec{E} = \left( p_x \frac{\partial }{\partial x}  + p_y \frac{\partial }{\partial y}  + p_z \frac{\partial }{\partial z}  \right)\vec{E}
\]

___

Za navor nas ponovno zanima sprememba energije ob zasuku za \( \mathrm{d} \vec{\phi} \). Poleg recikliranja enačb \ref{eq:7} in \ref{eq:8} dodamo še enačbe  za navor

\[ \mathrm{d} W = - \vec{M} \cdot \mathrm{d} \vec{\phi} \implies \vec{M} = - \frac{\mathrm{d} W}{\mathrm{d} \phi}
\]

Ponovno upoštevamo še enačbo \ref{eq:6}

\[ \mathrm{d} W = \mathrm{d} \left( e \phi - \vec{p} \cdot \vec{E} \right) = - \mathrm{d} \vec{p} \cdot \vec{E}
\]

kjer je \( \mathrm{d} \vec{p} = \mathrm{d} \vec{\phi} \times \vec{p} \) in se naše delo dodatno preobrazi v

\[ \mathrm{d} W = - \left( \mathrm{d} \vec{\phi} \times \vec{p} \right) = - \mathrm{d} \vec{\phi} \cdot \left( \vec{p} \times \vec{E} \right)
\]

Navor je torej

\[ M = \vec{p} \times \vec{E}.
\]

To je navor električnega dipola, da se zavrti v zunanjem električnem polju.
* Magnetostatika
** Amperova sila med (ravnimi) električnimi vodniki

Imamo dva vzporedna vodnika, po katerih tečeta \( I_1 \) in \( I_2 \). Ker po njiju teče tok, bo vodnik s tokom \( I_1 \) na vodnik s tokom \( I_2 \) deloval s silo \( \vec{F} \). Drugi vodnik bo na drugega deloval z \( - \vec{F} \). Radij vektor v cilindričnih koordinatah vodnika s tokom \( I_1 \) je \( \rho_1 \), drugega vodnika pa \( \vec{\rho}_2 \). Sila na vodnik je

\begin{equation}
\label{eq:9}
 \vec{F} = \frac{\mu_0}{4 \pi} \frac{I_1 I_2 \cdot l}{\left| \vec{\rho}_2 - \vec{\rho}_1 \right|} \frac{\vec{\rho}_2 - \vec{\rho}_1}{\left| \vec{\rho}_2 - \vec{\rho}_1 \right|}
\end{equation}

kjer je \( l \) dolžina žice.

Sila je za istosmerna tokova privlačna, za različno smerna tokova pa odbojna. Sili \ref{eq:9} pravimo Amperova sila, ki je magnetni analog Coulombovi sili v elektrostatiki.
** Sila med poljubnima vodnikoma

Gledamo dva splošna vodnika. Vodnika smo opisali kot parametrični krivulji \( \vec{r}_1 (l_1) \) in \( \vec{r}_2 (l_2)  \). Za začetek bomo najprej obravnavali silo med koščkama \( \mathrm{d} \vec{l}_1 \) in \( \mathrm{d} \vec{l}_2 \). Malo smo pogoljufali z zapisom, saj \( \mathrm{d} \vec{l}_1 = \vec{r}_1 \left( l_1 + \mathrm{d} l_1 \right) - \vec{r}_1 \left( l_1\right) \) in analogno za drugo žico. Sila na prvo žico je enaka

\[ \mathrm{d} \vec{F} = \frac{\mu_0}{4 \pi} \frac{\left( I_1 \mathrm{d} \vec{l}_1 \right) \left( I_2 \mathrm{d} \vec{l}_2 \right)}{\left| \vec{r}_2 \left( l_2 \right) - \vec{r}_1 \left( l_1 \right) \right| ^2} \cdot \frac{\left( \vec{r}_2 \left( l_2 \right) - \vec{r}_1 \left( l_1 \right) \right)}{\left| \vec{r} _2 \left( l_2 \right) - \vec{r}_1 \left( l_1 \right) \right|}
\]

Smer \( \mathrm{d} \vec{l}_1 \) in \( \mathrm{d} \vec{l}_2 \) je določena s smerjo električnega toka

\[ \vec{F} = \frac{\mu_0 I_1 I_2}{4 \pi} \int\limits_{c_1}^{c_2} \frac{\mathrm{d} \vec{l}_1 \mathrm{d} \vec{l}_2 }{\left| \vec{r}_2 \left( l_2 \right) - \vec{r}_1 \left( l_1 \right) \right| ^2} \cdot \frac{\left( \vec{r}_2 (l_2) - \vec{r} (l_1) \right)}{\left| \vec{r}_2 \left( l_2 \right) - \vec{r} \left( l_1 \right) \right|}
\]

kar lahko prepišemo v

\[ \vec{F} = \frac{\mu_0 I_1 I_2}{4\pi} \int\limits_{c_1}^{} \int\limits_{c_2}^{} \frac{\mathrm{d} \vec{l}_1 \times \left( \mathrm{d} \vec{l}_2 \times \left( \vec{r}_{2} (l_2) - \vec{r} (l_1) \right) \right)}{\left| \vec{r}_2 (l_2) - \vec{r}(l_1) \right| ^3}
\]
