#+title: 9. predavanje iz Elektromagnetnega polja
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Kvazi-statično električno polje
** Induktivnost

Imamo \( i = 1, 2, \ldots, N \) tokovnih vodnikov - zank. Po vsaki teče električni tok \( I_i \). Računamo energijo magnetnega polja

- prvi način je po enačbi

  \[ W = \frac{1}{2} \int\limits_{}^{} \vec{\jmath} \cdot \vec{A} \, \mathrm{d} ^3 \vec{r}.
  \]

  Upoštevamo enakost \( \vec{\jmath} \, \mathrm{d} ^3 \vec{r} = I \cdot \mathrm{d} \vec{l} \), saj nimamo toka po volumnu, ampak diskretne toke po zankah. Enačba mora hkrati upoštevati tudi tokove vseh krožnih zank

  \[ W = \frac{1}{2} \sum\limits_i^{} I_i \oint\limits_{}^{} \vec{A} \cdot \mathrm{d} \vec{l}_i.
  \]

  Krivuljni integral lahko prevedemo na integral po ploskvi, s čimer dobimo magnetni pretok

  \[ W = \frac{1}{2} \sum\limits_i^{} I_i \int\limits_{}^{} \vec{B} \cdot \mathrm{d} \vec{S} = \frac{1}{2} \sum\limits_i^{} I_i \Phi_i
  \]

- pri drugem načinu se poslužimo Kirchoffove enačbe, ki nam vektorski potencial pretvori v

  \[ W = \frac{1}{2} \int\limits_{}^{} \vec{\jmath} (\vec{r}) \cdot \vec{A} \, \mathrm{d} ^3 \vec{r} = \frac{1}{2} \frac{\mu_0}{4 \pi} \iint\limits_{}^{} \frac{\vec{\jmath} (\vec{r}) \cdot \vec{\jmath} (\vec{r}\, ')}{\left| \vec{r} - \vec{r} \, ' \right|} \, \mathrm{d} ^3 \vec{r} \, \mathrm{d} ^3 \vec{r} \, '
  \]

  (Opomba, da sta \( \vec{\jmath} (\vec{r}) \) in \( \vec{\jmath} (\vec{r} \, ') \) isti gostoti toka po različnih koordinatah).

  Na enak način, ker nimamo toka po volumnu, ampak tok po krožnih zankah, lahko zapišemo

  \[ W = \frac{\mu_0}{8 \pi} \sum\limits_{i, k}^{} I_i I_k \oint\limits_i^{} \oint\limits_k^{} \frac{\mathrm{d} \vec{l}_i \cdot \mathrm{d} \vec{l}_k}{\left| \vec{r} \left( l_i \right) - r(l_k) \right|}
  \]

Enačimo rezultata prvega in drugega načina

\[ W_m = \frac{1}{2} \sum\limits_i^{} I_i \Phi_i = \frac{1}{2} \frac{\mu_0}{4 \pi} \sum\limits_{i, k}^{} I_i I_k \oint\limits_i^{} \oint\limits_k^{} \frac{\mathrm{d} \vec{l}_i \cdot \mathrm{d} \vec{l}_k}{\left| \vec{r} (l_i) - \vec{r}(l_k) \right|}
\]

Uvedemo (tenzor) induktivnosti kot

\[ L_{ik} = \frac{\mu_0}{4 \pi} \oint\limits_i^{} \oint\limits_k^{} \frac{\mathrm{d} \vec{l}_i \cdot \mathrm{d} \vec{l}_k}{\left| \vec{r} (l_i) - \vec{r}(l_k) \right|}.
\]

Opazimo, da je induktivnost neodvisna od \( i \) in \( k \) in lahko sta celo ista! V tem primeru imamo koeficient \( L_{ii} \), ki ji pravimo lastna induktivnost.

Velja

\[ \Phi_i = \sum\limits_k^{} L_{ik} I_i.
\]

Dodatno opazimo tudi to, da je induktivnost odvisna samo od geometrije.
** Kožni pojav

Ko *izmenični* tok teče skozi prevodnik (žico), se razporedi tako, da je gostota toka največja blizu sten prevodnika. Temu pojavu se reče kožni pojavi (ang. /skin effect/).

*** Osnovne enačbe kožnega pojava

Uporabili bomo Maxwellove enačbe ter Ohmov zakon za prevodnik.

Znotraj prevodnika je gostota naboja \( \rho = 0 \). Iz tega sledi, da je

\begin{equation}
\label{eq:1}
\nabla \cdot \vec{E} = 0.
\end{equation}

Druga enačba za električno polje pa je še

\begin{equation}
\label{eq:2}
 \nabla \times \vec{E} = - \frac{\partial \vec{B}}{\partial t}.
\end{equation}

Maxwellovi enačbi za magnetno polje pa sta

\begin{align}
  \nabla \cdot \vec{B} &= 0 \label{eq:B1} \\
\nabla \times \vec{B} &= \mu_0 \vec{\jmath} \cancel{\left( + \mu_0 \epsilon_0 \frac{\partial \vec{E}}{\partial t}  \right)} \label{eq:B2}
\end{align}

Prečrtan člen lahko zanemarimo za \( \omega < 10^{18} / s \). Gostoti magnetnega polja \( \vec{B} \) omejimo izvir (tok) z Ohmovim zakonom in enačba \ref{eq:B2} postane

\begin{equation}
\label{eq:3}
 \nabla \times \vec{B} = \mu_0 \sigma \vec{E}
\end{equation}

Na enačbi \ref{eq:2} in \ref{eq:3} delujemo z rotorjem

\[ \nabla \times \left( \nabla \times \vec{E} \right) = - \frac{\partial }{\partial t}  \nabla \times \vec{B} = - \mu_0 \sigma \frac{\partial \vec{E}}{\partial t}
\]

ter

\[ \nabla \times \left( \nabla \times \vec{B} \right) = \nabla \times \left( \mu_0 \sigma \vec{E} \right) = - \mu_0 \sigma \frac{\partial \vec{B}}{\partial t}
\]

Navidezno smo razklopili enačbi (saj sta leva in desna stran odvisni od iste količine). Pri računanju tako lahko uporabimo katerokoli izmed enačb, vendar se moramo zavedati, da sta količini \( \vec{E} \) in \( \vec{B} \) sklopljeni preko Maxwellovih enačb.

Uporabimo identiteto

\[ \nabla \times \left( \nabla \times \vec{A} \right) = \nabla \left( \nabla \cdot \vec{A} \right) - \nabla ^2 \vec{A},
\]

iz česar dobimo enačbi

\begin{align}
  \nabla ^2 \vec{E} &= \mu_0 \sigma \frac{\partial \vec{E}}{\partial t}  \\
\nabla ^2 &= \mu_0 \sigma \frac{\partial \vec{B}}{\partial t}
\end{align}

Dobljeni enačbi sta oblike, ki je značilna za difuzijske enačbe.

Rešitev iščemo s separacijo spremenljivk

\[ \vec{E} (\vec{r}, t) = \vec{E} (\vec{r}) e^{- \mathrm{i} \omega t} \quad \vec{B} (\vec{r}, t) = \vec{B}(\vec{r}) e^{- \mathrm{i} \omega t}
\]

Tak časovni faktor smo si izbrali, saj lahko poljubno časovno odvisnost zapišemo kot vsoto po ravnih valovih. Nastavka vstavimo v enačbi in dobimo

\[ \nabla ^2 \vec{E} = k ^2 \vec{E} \quad \nabla ^2 \vec{B} = k ^2 \vec{B},
\]

kjer je \( k ^2 = \frac{(1 - \mathrm{i})}{\sqrt{2}} \sqrt{\omega \mu_{0}} \sigma \).

V eni dimenziji ima rešitev oblike

\[ \vec{E} (z, t), \vec{B} (z, t) \sim e^{- k z} = \exp \left\{ - \sqrt{\frac{\omega \mu_0 z}{2}} z \right\} \exp \left\{ - \mathrm{i} \sqrt{\frac{\omega \mu_0 \sigma}{2} z}  \right\}.
\]

Rešitev je zmnožek oscilirajoče funkcije za čas in eksponentno padajoče funkcije za kraj. Količina \( \sqrt{\frac{\omega \mu_0 \sigma}{2}} \) je značilna dolžina. Obratni vrednosti bomo rekli udarna globina \( \frac{\sqrt{2}}{\sqrt{\omega \mu_0 \sigma}} \).

#+begin_my_example
Za baker pri frekvenci \( 50 \mathrm{Hz} \) z notranjo uporabnostjo \( \sigma_{Cu} = 5.8 \cdot 10^7 \frac{\mathrm{S}}{\mathrm{m}} \) je udorna globina približno \( 2 \mathrm{cm} \).

Za frekvenco \( 750 \mathrm{Hz} \) (gigaherzčni internet) je udorna globina \( 2 \mu \mathrm{m} \).
#+end_my_example

Kožni pojav se zgodi zaradi indukcije kot posledica izmeničnega toka.
*** Geometrija polj in rešitev

Obravnavamo cilindrični vodnik polmera \( r \). Gostota električnega toka kaže vzdolž vodnika, v smeri \( z \):

\[ \vec{\jmath} = j_0 \hat{e}_z
\]

Nahajamo se v cilindričnih koordinatah \( (r, \phi, z) \) s cilindrično bazo. Posledično so neničelne komponente samo

\[ E_z (r, t) = E_z (r) e^{- \mathrm{i} \omega t} \quad B_{\phi} (r, t) = B_{\phi} (r) e^{- \mathrm{i} \omega t}
\]

Ob upoštevanju Laplaceovega operatorja v cilindričnih koordinatah dobimo navidezno nesklopljeni enačbi

\begin{align*}
  \frac{1}{r} \frac{\partial }{\partial r} \left( r \frac{\partial B_{\phi}}{\partial r}  \right) - \frac{B_{\phi}}{r ^2} &= - \mathrm{i} \omega \mu_0 \sigma B_{\phi} \\
\frac{1}{r} \left( r \frac{\partial E_{r}}{\partial r}  \right) &= - \mathrm{i} \omega \mu_0 \sigma E_r
\end{align*}

Velja še vez med \( \vec{E} \) in \( \vec{B} \)

\[ \nabla \times \vec{E} = - \frac{\partial \vec{B}}{\partial t}  \implies \ - \mathrm{i} \omega B_{\phi} = - \frac{\partial E_r}{\partial r} .
\]

Rešitev enačb je

\[ E_z (r) = A J_0 (kr) \quad B_{\phi} = - \mathrm{i} A \frac{k}{\omega} J_1 (kr),
\]

kjer je \( k = \frac{1 - \mathrm{i}}{\sqrt{2}} \sqrt{\omega \mu_{0}} \sigma \). Imamo modificrane Besslove funkcije, ker je \( k \) kompleksno število.

Ustrezajoča gostota električnega toka

\[ \vec{\jmath} = \sigma \vec{E} \implies \ \vec{\jmath} = \hat{e}_z \sigma A J_0 (kr),
\]

kjer je \( A \) določen iz robnega pogoja.

Loči se šibek in močan kožni pojav glede na velikost frekvence.
