#+title: 11. predavanje iz Elektromagnetnega polja
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Elektromagnetno polje v snovi
** Magnetno polje v snovi
*** Konstitutivna relacija za magnetno polje v snovi

Magnetizacija je odvisna od zunanjega magnetnega polja

\[ \vec{M} = \vec{M} \left( \vec{H} \right) .
\]

Tej enačbi pravimo konstitutivna relacija, kjer je \( \vec{H} \) poljubna funkcija. Odvisnost smo zapisali s \( \vec{H} \), saj je magnetizacija povezana s snovjo. V izotropni homogeni snovi in za šibka polja velja

\begin{equation}
\label{eq:1}
 \vec{M} = \chi_M \vec{H} + o \left( H ^2 \right),
\end{equation}

kjer je \( \chi_M \) magnetna susceptibilnost.

Uvedemo tudi magnetno permeabilnosti \( \mu \), ki je definirana kot

\[ \chi_M = \mu- 1.
\]

Potem preko linearne konstitutivno relacije \ref{eq:1} velja

\[ \vec{H} = \frac{\vec{B}}{\mu_0} - \chi_M \vec{H} = \frac{\vec{B}}{\mu_0} - (\mu - 1) \vec{H},
\]

iz česar sledi

\[ \vec{B} = \mu \mu_0 \vec{H}, \quad   \vec{M} = \left( 1 - \frac{1}{\mu} \right) \frac{\vec{B}}{\mu_0}.
\]

Poudarjamo, da to velja samo za *linearno konstitutivno relacijo*.
*** Magnetizacija in gostota magnetnega dipolnega momenta

Zanima nas, kaj je vektorsko polje magnetizacije \( \vec{M} \)?

Obravnavamo Maxwellovo relacijo

\[ \nabla \times \vec{B} = \mu_0 \vec{\jmath} + \nabla \times \vec{M}.
\]

Preko te enačbe zapišemo enačbo za magnetni potencial \( \vec{A} \), ki jo rešimo in rešitev primerjamo z \( \vec{A} \) magnetnega dipola. Iz tega sledi, da je magnetizacija \( \vec{M} \) je (volumska) gostota magnetnega dipolnega momenta.
*** Klasifikacija snovi glede na odziv na magnetno polje

Glede na magnetne lastnosti ločimo tri skupine:

- /feromagnetiki/ imajo permanentno magnetizacijo, ki je neodvisna od zunanjega magnetnega polja. Praviloma je močno odvisna od temperature (Curiejeva temperatura)
- /diamagnetiki/ imajo magnetizacijo samo ob prisotnosti zunanjega magnetnega polja. Magnetizacija kaže v obratno smer kot zunanje polje. Iz tega sledi, da \( \chi_M < 0 \). Superprevodnik je idealni diamagnet. Drugače reda \( 10^{-5} \).
- /paramagnetiki/ imajo magnetizacijo samo ob prisotnosti zunanjega polja in kaže v smeri polja - efektivno ga ojačuje.

** Maxwellove enačbe v snovi

Kompleten sistem Maxwellovih enačbo je

\begin{align*}
  \nabla \cdot \vec{D} = \rho, & \qquad \nabla \cdot \vec{B} = 0 \\
\nabla \times \vec{E} = - \frac{\partial \vec{B}}{\partial t}, &\qquad \nabla \times \vec{H} = \vec{\jmath} + \frac{\partial \vec{D}}{\partial t} .
\end{align*}

Poleg Maxwellovih enačb za izračunljivost potrebujemo tudi 2 konstitutivni relaciji

\[
\begin{array}{|c|c|} \hline
\text{splosno} & \text{linearna konst. rel.} \\ \hline
\vec{P} = \vec{P} \left( \vec{D} \right) & \vec{D} = \epsilon \epsilon_0 \vec{E} \\ \hline
\vec{M} = \vec{M} \left( \vec{H} \right) & \vec{B} = \mu \mu_0 \vec{H} \\ \hline
\end{array}
\]

V anizotropni snovi \( \epsilon \) nadomestimo s tenzorjem \( \underline{\epsilon} \).

Gostota električnega polja je potem

\[ \vec{D} = \epsilon_0 \underline{\epsilon} \vec{E}.
\]

Analogno je permeabilnost \( \mu \) zamenjana za \( \underline{\mu} \), in gostota magnetnega polja je

\[ \vec{B} = \mu_0 \underline{\mu} \vec{H}.
\]

S tenzorji \( \vec{D} \) in \( \vec{B} \) nista nujno vzporedna njunima pripadajočima poljema \( \vec{E} \) in \( \vec{H} \).

V nelinearnih snoveh (npr. nelinearna optika)

\begin{align*}
  \vec{D} &= _ \vec{E} + _ \vec{E} \cdot \vec{E} + _ \vec{E} \vec{E} \vec{E} + \ldots
\end{align*}
