#+title: 12. predavanje iz Elektromagnetnega polja
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Elektromagnetno polje v snovi
** Robni pogoji za Maxwellove enačbe
*** Robni pogoji za \( \vec{D} \)

Imamo dve različni snovi z gostota električnega polja \( \vec{D}_1 \) in \( \vec{D}_2 \) za pripadajočo snov.

V diferencialni obliki velja

\[ \nabla \cdot \vec{D} = \sigma \iff \int\limits_V^{} \nabla \cdot \vec{D} \, \mathrm{d} ^3 \vec{r} = \int\limits_V^{} \sigma \, \mathrm{d } ^3 \vec{r}.
\]

Definiram podoben valjast volumen kakor pri robnem pogoju za \( \vec{B} \) s širino \( \mathrm{d} l \) in normalama \( \vec{n}_1 \) in \( \vec{n}_{2} \) v pripadajočih snoveh.

Preko Gaussovega izreka pretvorimo volumenski integral na integral po zaključeni ploskvi

\[ \int\limits_V^{} \nabla \cdot \vec{D} \, \mathrm{d} ^3 \vec{r} = \oint\limits_{\partial V}^{} \vec{D} \cdot \mathrm{d} \vec{S}.
\]

Razpišemo ploskovni integral

\[ \oint\limits_{\partial V}^{} \vec{D} \cdot \mathrm{d} \vec{S} = \int\limits_{(1)}^{} \vec{D}_1 \cdot \vec{n}_1 \, \mathrm{d} S + \int\limits_{(2)}^{} \vec{D}_2 \cdot \vec{n}_2 \, \mathrm{d} S + \int\limits_{\text{plasc}}^{} \vec{D}_{pl} \cdot \vec{D}_{plasc} \, \mathrm{d} S.
\]

V limiti \( \mathrm{d} l \to 0 \) gre zadnji integral proti \( 0 \) in preostane nam robni pogoj za \( \vec{D} \), ki povezuje gostoti električnega polja v dveh snoveh

\[ \vec{D}_1 \cdot \vec{n}_1 + \vec{D}_2 \cdot \vec{n}_2 = \sigma \implies D_{1n} - D_{2n} = \sigma.
\]
*** Robni pogoj za \( \vec{E} \)

Imamo dve različni snovi 1 in 2, ki se stikata in vsaka ima pripadajočo jakost električnega polja \( \vec{E}_1 \) in \( \vec{E}_2 \).

Velja diferencialna oblika Maxwellovega zakona

\[ \nabla \times \vec{E} = - \frac{\partial \vec{B}}{\partial t}.
\]

Zamislimo si zanko, ki je na meji med snovema. Njena širina naj bo \( \mathrm{d} h \) in njena višina je \( \mathrm{d} l \). Tangenta v snovi ena je \( \vec{t}_1 \), v drugi snovi pa \( \vec{t}_2 \).

Iz diferencialne oblike pretvorimo Maxwellov zakon v integral po preseku in nato še po robu preseka

\[ \int\limits_V^{} \nabla \times \vec{E} \, \mathrm{d} \vec{S} = \int\limits_{\partial S}^{} \vec{E} \cdot \mathrm{d} \vec{r} = - \int\limits_{V}^{} \frac{\partial \vec{B}}{\partial t} \, \mathrm{d} \vec{S}.
\]

Integral po robu preseka lahko razpišemo

\[ \int\limits_{\partial S}^{} \vec{E} \cdot \mathrm{d} \vec{r} = \vec{E}_1 \cdot \vec{t}_1 \cdot \mathrm{d} h + \vec{E}_2 \cdot \vec{t}_2 \cdot \mathrm{d} h + \vec{E}_{rob} \cdot \vec{t}_3 \cdot \mathrm{d} l + \vec{E}_{rob} \cdot \vec{t}_3 \cdot \mathrm{d} l.
\]

\( \vec{t}_3 \) in \( \vec{t}_4 \) sta tangentna vektorja na stranicah pravokotnika, ki sekata snovi. V limiti \( \mathrm{d} l \to  0 \) bosta člena s tema vektorjema šla proti \( 0 \) in dobimo robni pogoj

\[ \vec{E}_1 \cdot \vec{t}_1 + \vec{E}_2 \cdot \vec{t}_2 = 0 \implies \, E_{1t} - E_{2t} = 0
\]
*** Robni pogoj za \( \vec{H} \)

Zamislimo si isti pravokotnik kot v prejšnjem poglavju. Velja Maxwellova enačba

\[ \nabla \times \vec{H} = \vec{\jmath} + \frac{\partial \vec{D}}{\partial t}.
\]

Na podoben način preko Stokesovega izreka integral po preseku \( S \) po robu pravokotnik \( \partial S \).

\[ \int\limits_S^{} \nabla \times \vec{H} \, \mathrm{d} \vec{S} = \oint\limits_{\partial S}^{} \vec{H} \cdot \mathrm{d} \vec{r} = \int\limits_S^{} \vec{\jmath} \, \mathrm{d} \vec{S} + \int\limits_S^{} \frac{\partial \vec{D}}{\partial t}  \, \mathrm{d} \vec{S}
\]

Integral po robu pravokotnika je enak

\[ \int\limits_{\partial S}^{} \vec{H} \cdot \mathrm{d} \vec{r} = \vec{H}_1 \cdot \vec{t}_1 \cdot \mathrm{d} h + \vec{H}_2 \cdot \vec{t}_2 \cdot \mathrm{d} h + \cancel{\vec{H}_{rob} \cdot \vec{t}_3 \cdot \mathrm{d} l} + \cancel{\vec{H}_{rob} \cdot \vec{t}_4 \cdot \mathrm{d} l }.
\]

Po analognem razmisleku nam ostanejo samo členi, ki ne prečkajo mej snovi.

Desna stran pa ima malo posebnosti. Vektor normale preseka \( \mathrm{d} \vec{S} \) kaže na skici v ravnino ali izven nje, medtem ko \( \vec{\jmath} \) kaže vzporedno z mejo med snovema.

\[ \int\limits_S^{} \vec{\jmath} \mathrm{d} \vec{S} + \int\limits_S^{} \frac{\partial \vec{D}}{\partial t} \mathrm{d} \vec{S} = \vec{\jmath} \cdot \vec{t} \cdot \mathrm{d} h \mathrm{d} l + \frac{\partial \vec{D}}{\partial t}  \cdot \mathrm{d} h \cdot \mathrm{d} l.
\]

V limiti \( \mathrm{d} l \to 0 \) je drugi člen ničeln. Pri prvem členu pa definiramo površinsko gostoto toka \( K \) z enotami \( \left[ K \right]= \frac{A}{m} \)

\[ K = \vec{\jmath} \cdot \vec{t} \cdot \mathrm{d} l
\]

Dobimo robni pogoj

\[ \vec{H}_1 \vec{t}_1 + \vec{H}_2 \vec{t}_2 = K \implies \ H_{1t} - H_{2t} = K .
\]
* Frekvenčna odvisnost dielektrične funkcije

Dielektrična funkcija oziroma lomni količnik sta močno frekvenčno odvisna

\[ \epsilon = \epsilon(\omega) \iff \epsilon(\omega) = n ^2 (\omega),
\]

kjer je \( n \) lomni količnik. Slednji zapis je značilen za jezik optike.

Istočasno si zamislimo, da je \( \epsilon(\omega) \) kompleksna količina, kjer \( \mathrm{Re} \epsilon(\omega) \) določa odboj in lom, \( \mathrm{Im} \epsilon(\omega) \) pa predstavlja absorpcijo v snovi.
** Kramers-Kronigove relacije

Realen in imaginaren del dielektrične funkcija sta povezana - če poznaš enega, lahko izračunaš drugega.

Velja

\[ \mathrm{Re} \epsilon(\omega) = 1 + \frac{2}{ \pi } \mathcal{P} \int\limits_0^{\infty} \frac{\omega' \mathrm{Im} \epsilon(\omega') }{\omega ' ^2 - \omega ^2} \, \mathrm{d} \omega ' ,
\]

in

\[ \mathrm{Im} \epsilon(\omega) = - \frac{2 \omega}{\pi} \mathcal{P} \int\limits_{0}^{\infty} \frac{\mathrm{Re} \epsilon(\omega') - 1}{\omega' ^2 - \omega ^2} \, \mathrm{d} \omega'.
\]

Temu pravimo, Kramers-Kronigove relacije. Uvedli smo posebno oznako integrala

\[ \mathcal{P} \int\limits_{-\infty}^{\infty} \frac{g (\omega')}{\omega' - \omega} \, \mathrm{d} \omega' = \lim_{\epsilon \to 0} \left[ \int\limits_{-\infty}^{\omega - \epsilon} \frac{g(\omega')}{\omega' - \omega} \, \mathrm{d} \omega' + \int\limits_{\omega + \epsilon}^{\infty} \frac{g(\omega')}{\omega' - \omega} \, \mathrm{d} \omega' \right],
\]

s čimer smo izrezali pol, ki nastane pri \( \omega = \omega' \) in preprečili njegovo divergenco. Integralu pravimo integral glavne vrednosti.

Kramers-Kronigove relacije se izpelje z uporabo integrala glavne prednosti in Plemljeve enačbe.

Relacije so pomembne v spektroskopskih tehnikah kot so odboj, prepustnostin absorpcija svetlobe.
** Modeli \( \epsilon(\omega) \)
*** Gibalna enačba za vezan naboj

V dielektriku imamo vezan naboj, ki se ne more prosto gibati. Obravnavamo v klasičnem režimu. Vezan naboj je vezan preko harmonskega potenciala frekvence \( \omega_0 \), iz ravnovesnega položaja pa ga premika zunanje polje \( e \vec{E}(t) \). Da ne pride do resonance zaradi \( t \propto \omega \), saj se v realnem svetu to ne dogaja, je še dodaten člen, ki predstavlja disipacijo (dušenje nihanja) kot posledico viskoznosti ali sipanja v kristalih.

\[ m \frac{\mathrm{d} ^2 \vec{r}}{\mathrm{d} t ^2} = - m \gamma \frac{\mathrm{d} \vec{r}}{\mathrm{d} t} - m \omega_0 ^2 \vec{r} + e \vec{E} \left( \vec{r} \right)
\]

kjer \( \vec{r} \) predstavlja položaj vezanega naboja.

Uporabimo Fourierovo transformacijo

\[ \vec{r} \left( t \right) = \int\limits_{}^{} \vec{r} (\omega) \exp \left\{ - \mathrm{i} \omega t \right\} \, \mathrm{d} \omega
\]

in enačba postane

\[ - m \omega ^2 \vec{r} (\omega) = m \gamma \cdot \mathrm{i} \omega \vec{r} (\omega) - m \omega_0 ^2 \vec{r} (\omega) + e \vec{E}(\omega).
\]

Rešimo enačbo za \( \vec{r}(\omega) \)

\[ \vec{r} (\omega) = \frac{e}{m} \frac{\vec{E}(\omega)}{\omega_0 ^2 - \omega ^2 - \mathrm{i} \gamma \omega},
\]

in prepoznamo resonančnost.

Na koncu dneva nas zanima \( \epsilon \), do katerega pridemo preko električnega dipolnega momenta. Zgornja rešitev je rešitev enega delca, mi pa imamo \( N \) delcev v končnem volumnu \( V \), ki nam definirajo volumsko številsko gostot \( n \). Polarizacija bo

\[ \vec{P}(\omega) = n \cdot e \vec{r}(\omega) = \frac{n e ^2}{m} \cdot \frac{\vec{E}(\omega)}{\omega_0 ^2 - \omega ^2 + \mathrm{i} \gamma \omega}.
\]

Velja tudi

\[ \vec{P}(\omega) = \epsilon_0 \left( \epsilon(\omega) - 1 \right) \vec{E}(\omega),
\]

in iz enačenja dobimo splošno odvisnost

\[ \epsilon_0 \left( \epsilon(\omega) - 1 \right) = \frac{n e ^2}{m} \cdot \frac{1}{\omega_0 ^2 - \omega ^2 - \mathrm{i} \gamma \omega}
\]

V realnih snove imaš tipično lahko več virov harmonskih potencialov (več \( \omega_0 \)) in več virov disipacij \( \gamma \). Obstaja več režimo (približkov) kot so Debyjeva, Lorentzova in plazemska relaksacija.
*** Debyjeva relaksacija

Ta relaksacija je relavantna pri nizkih frekvencah, kjer zanemarimo \( \omega ^2 \). Enačba tako izgleda

\[ \vec{P}(\omega) = \frac{n e ^2}{m} \cdot \frac{\vec{E}(\omega)}{\omega_0 ^2 - \mathrm{i} \gamma \omega} .
\]

Pomembna je pri relaksacija dipolnega momenta v molekulah, kjer so frekvence reda velikosti \( \omega \sim 10^7 - 10^9 \mathrm{Hz} \).
*** Lorentzova relaksacija

To je polna odvisnost in uporabi vse člene

\[ \vec{P}(\omega) = \frac{n e ^2}{\omega} \frac{\vec{E}(\omega)}{\omega_0 ^2 - \omega ^2 - \mathrm{i} \gamma \omega}.
\]

Označimo \( \epsilon(0) = \epsilon(\omega = 0) \).

Sledi, da je odvisnost

\[ \epsilon(\omega) - 1 = \frac{(\epsilon(0) - 1)\omega_0 ^2}{\omega_0 ^2 - \omega ^2 - \mathrm{i} \gamma \omega}.
\]

[vstavi skico grafa]

Pomembna je pri nihanju molekul, ko so frekvence reda \( \omega \sim 10^{12} - 10^{16} \mathrm{Hz} \). Za nas so še posebej pomembne, saj je vidna svetloba pri \( 10^{15} \mathrm{Hz} \).
*** Plazemska relaksacija

Pri visokih frekvenca zanmaeriš vse člene razen električnega gibanja.

\[ \vec{P}(\omega) = - \frac{e ^2 n}{m} \frac{\vec{E}(\omega)}{\omega ^2},
\]

iz česar sledi

\[ \epsilon(\omega) = 1 - \frac{\omega_p ^2}{\omega ^2},
\]

kjer je \( \omega_p \) plazemska frekvenca. Definirana je kot

\[ \omega_p ^2 = \frac{e ^2 n}{m \epsilon_0}.
\]

Pomembna je pri frekvenca reda velikosti \( \omega > 10^{16} \). Pri tej frekvenci se elektroni v snovi obnašajo kot prosti delci.

#+name: dielektrična funkcija vode
#+begin_my_example
Uporabi se Debyjev model pri nizkih frekvenca in Lorentzov pri višjih

\[ \epsilon (\mathrm{i} \omega) = 1 + \sum\limits_{i = 1}^1 \frac{d_i}{1 + \omega \tau_i} + \sum\limits_{i = 1}^{11} \frac{f_i}{\omega_i ^2 + g_i \omega +  \omega ^2},
\]

kjer so \( d_i, \tau_i, f_i, \omega_i \) in \( g_i \) fenomenološke konstante.
#+end_my_example

* Elektromagnetno valovanje
** Valovna enačba v vakuumu

Predpostavimo, da v prostoru ni izvorov \( \vec{\jmath} = 0 \) in \( \rho = 0 \). Zapišimo torej Maxwellove enačbe

\begin{align*}
  \nabla \cdot \vec{E} = 0 &\quad \nabla \cdot \vec{B} = 0 \\
\nabla \times \vec{E} = - \frac{\partial \vec{B}}{\partial t}  &\quad \nabla \times \vec{B} =  \mu_0\epsilon_0 \frac{\partial \vec{E}}{\partial t}
\end{align*}

Rotoriziramo rotor električnega polja

\begin{align*}
  \nabla \times \vec{E} &= - \frac{\partial \vec{B}}{\partial t} && \left/ \nabla \times \right. \\
\nabla \times \left( \nabla \times \vec{E} \right) &= - \frac{\partial }{\partial t} \nabla \times \vec{B}\\
\nabla \left( \nabla \cdot \vec{E} \right) - \nabla ^2 \vec{E} &= - \frac{\partial }{\partial t} \nabla \times \vec{B}
\end{align*}

Upoštevamo, da velja \( \nabla \cdot \vec{E} = 0 \) in dobimo

\[ \nabla ^2 \vec{E} - \epsilon_0 \mu_0 \frac{\partial ^2 \vec{E}}{\partial t ^2}  = 0.
\]

Analogno dobimo tudi

\[ \nabla ^2 \vec{B} - \epsilon_0 \mu_0 \frac{\partial ^2 \vec{B}}{\partial t ^2} = 0.
\]

Dobljeno sta valovni enačbi, in definiramo hitrost valovanja

\[ c ^2 = \frac{1}{\epsilon_0 \mu_0}.
\]

Iščemo rešitve valovne enačbe v obliki ravnih valov ob predpostavki ene frekvence in neskončnega praznega prostora.

\begin{align*}
  \vec{E} \left( \vec{r}, t \right) &= \vec{E} \left( \vec{r} \right) e^{- \mathrm{i} \omega t} = E_0 e^{\mathrm{i} \left( \vec{k} \vec{r} - \omega t \right)} \\
\vec{B} \left( \vec{r}, t \right) &= B \left( \vec{r} \right) e^{-\mathrm{i} \omega t} = \vec{B}_0 e^{\mathrm{i} \left( \vec{k} \vec{r} - \omega t \right)}
\end{align*}

V praznem prostoru sta \( \vec{E}(\vec{r}) \) in \( \vec{B}(\vec{r}) \) konstanti.

Najti želimo še zvezo med \( \omega \) in \( \vec{k} \), ki jo dobimo s tem, da rešitve vstavimo v valovno enačbo

\[ \left( - \mathrm{i} k  \right)^2 - \frac{1}{ c ^2} \left( - \mathrm{i} \omega \right) ^2 = 0   \implies \omega = kc
\]
