#+title: 14. predavanje iz Elektromagnetnega polja
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Naslov

Na prejšnjem predavanju smo dobili transformirane količine v sistemu, ki se premika s svetlobno hitrostjo. Transformirane komponente električnega polja so

\begin{align*}
  E_x &= E_{x'} ' \\
E_y &= \gamma \left( E_{y'}' + v B_{z'} ' \right) \\
E_z &= \gamma \left( E_{z'}' - v B_{y'} ' \right),
\end{align*}

kjer je sistem s črtico premikajoči se sistem. Transformirane komponente magnetnega polja pa so

\begin{align*}
  B_x &= B_{x'}' \\
B_y &= \gamma \left( B_{y'}' - \frac{v}{c ^2} E_{z'}' \right) \\
B_z &= \gamma \left( B_{z'}' + \frac{v}{c ^2} E_{y'}' \right) \\
\end{align*}

Sledeče ima dve posledici.

Prva posledica je, da je skalarni produkt invarianten - koti med poljema \( \mathbf{E} \) in \( \mathbf{B} \) se ohranjajo.

\begin{align*}
  \mathbf{E} \cdot \mathbf{B} &= E_x B_x + E_y B_y + E_z B_z \\
 \mathbf{E}' \cdot \mathbf{B} '&= E_{x'}' B_{x'}' + \gamma ^2 \left( 1 - \frac{v ^2}{c ^2} \right) E_{y'}' + B_{y'}' + \gamma \left( 1 - \frac{v ^2}{c ^2} \right) E_{z'}' B_{z'}' .
\end{align*}

Druga posledica je to, da ima v praznem prostoru rešitev Maxwellove enačbe enako obliko - obliko ravnega vala - veliko polj pa sta odvisni od sistema.

\[ E ^2 - c ^2 B ^2 = E' ^2 + c ^2 B ' ^2.
\]

Poteka pretakanje iz enega polja v drugo in ni več ločeno na magnetno in električno polje.
** Prostor Minkovskega

Ideja je, da se teorijo relativnosti formulira s štirivektorji, ki pri posebni teoriji relativnosti (PTR) sledijo metriki Minkovskega. Pri splošni teoriji relativnosti pa je metrika odvisna od porazdelitve mase.

Štirivektor dogodka je

\[ x_{\mu} = (x, y, z, ct).
\]

Indeks \( \mu \) spodaj zavzema vrednosti \( 1 - 4 \) in označuje kovariantni vektor.

Štirivektor dogodka z indeksom zgoraj

\[ x^{\mu} = (x, y, z, - ct),
\]

označuje kontravariantni vektor.

Lorentzova transformacija ohranja skalarni produkt

\[ x_{\mu} x^{\mu} = x' _{\mu}  x'^{\mu}.
\]

Zanima nas, kako bi elektromagnetno polje zapisali s četverci.
** Štirivektor gostote toka
*** Gostota naboja in Lorentzova transformacija

Naboj mora biti invarianten na Lorentzovo transformacijo, saj bi drugače s prehajanjem med sistem pridobivali ali izgubljali naboj.

Torej velja

\[ e = \int\limits_V^{} \rho \, \mathrm{d} ^3 \mathbf{r} = \int\limits_{V'}^{} \rho' \mathrm{d} ^3 \mathbf{r}'.
\]

Gostota naboja \( \rho \) se nahaja v sistemu \( S \), medtem ko je \( \rho' \) v sistemu \( S' \). Ob upoštevanju, da velja

\[ \mathrm{d} ^3 \mathbf{r} = \mathrm{d} x \mathrm{d} y \mathrm{d} z = \mathrm{d} ^3 \mathbf{r} ' = \mathrm{d} x' \mathrm{d} y' \mathrm{d} z' = \gamma \mathrm{d} x \mathrm{d} y \mathrm{d} z,
\]

enakost postane

\[ e = \int\limits_V^{} \rho  \mathrm{d} x \mathrm{d} y \mathrm{d} z = \int\limits_{V'}^{} \rho' \gamma  \mathrm{d} x \mathrm{d} y \mathrm{d} z.
\]

Sledi

\[ \rho' = \frac{\rho}{\gamma}.
\]

Zaključimo lahko, da je \( \frac{\rho}{\gamma} \) invariantna količina na Lorentzovo transformacijo.
*** Štirivektor gostote toka

V treh dimenzijah je bila gostota toka zapisana kot

\[ \mathbf{j} = \rho \mathbf{v}.
\]

Uvede se ga kot

\[ j_{\mu} = \frac{\rho}{\gamma} u_{\mu} = \frac{\rho}{\gamma} (\gamma_v, \gamma_c).
\]

Sledi, da sta kovariantni in kontravariantni vektor enaka

\[ j_{\mu} = \left( \mathbf{j}, \rho c \right) \quad \text{ in } \quad j^{\mu} = \left( \mathbf{j}, - c \rho \right).
\]

Gostoto toka smo uvedli kot pravi štirivektor, iz česar sledi, da zanj velja Lorentzova transformaija

\begin{align*}
  j_x ' &= \gamma \left( j_x - \beta c \rho \right) \\
j_y ' &= j_y \\
j_z ' &= j_z\\
c \rho' &= \gamma \left( c \rho - \beta j_x \right)
\end{align*}

Invarianca ima obliko

\[ j_{\mu} j^{\mu} = \mathbf{j} \cdot \mathbf{j} - c ^2 \rho ^2.
\]

Če na invarianco delujemo z \( \frac{\partial }{\partial x^{\mu}}  \), iz česar sledijo stvari kot so npr. kontinuitetna enačba

\[ \nabla \cdot \mathbf{j} - \frac{\partial \rho}{\partial t} = 0.
\]

Razcep štirivektorja toka je relativen, odvisen, od gostote naboja in gotota toka je odvisn od sistema.
** Štirivektor elektromagnetnega potenciala

Spomnimo se Riemann-Lorentzovbih enačb za magnetni vektorski potencial \( \mathbf{A} \) in \( \phi \).

\[ \nabla ^2 \phi - \frac{1}{c ^2} \frac{\partial ^2 \phi}{\partial t ^2} = - \frac{\rho}{\epsilon_0} \quad \text{ in } \quad \nabla ^2 \mathbf{A} - \frac{1}{c ^2} \frac{\partial ^2 \mathbf{A}}{\partial t ^2} = - \mu_0 \mathbf{j}.
\]

Uvedemo D'Alembertov operator \( \square ^2 = \partial_{\mu} \partial^{\mu} = \left( \nabla, - \frac{\partial }{\partial (ct)} \right) \left( \nabla,  \frac{\partial }{\partial (tc)}  \right) \). Drugače zapišemo

\[ \square ^2 \phi = - \frac{\rho}{\epsilon_0} \quad \text{ in } \quad \square ^2 \mathbf{A} = - \mu_0 \mathbf{j}
\]

Električna gostota naboja in gostota toka tvorita četverca in pričakujemo, da tudi \( \mathbf{A} \) in \( \phi \) tvorita četverec. Štirivektor elektromagnetnega potenciala je

\[ A_{\mu} = \left( \mathbf{A}, \frac{\phi}{c} \right) \quad \text{ in } \quad A^{\mu} = \left( \mathbf{A}, - \frac{\phi}{c} \right).
\]

Torej lahko Riemann-Lorentzove enačbe zapišemo v manifestno Lorentzovi invariantni obliki kot

\[ \square ^2 A_{\mu} = - \mu_0 j_{\mu} \quad \text{ oziroma } \quad \square A^{\mu} = - \mu_0 j^{\mu}.
\]

Ker uvedemo \( \mathbf{A} \) kot pravi štirivektor, zanj ponovno velja Lorentzova transformacija.

\begin{align*}
  A_x ' &= \gamma \left( A_x - \beta \frac{\phi}{c} \right) \\
A_y' &= A_y \\
A_z ' &= A_z \\
\frac{\phi '}{c} &= \gamma \left( \frac{\phi}{c} - \beta A_x \right)
\end{align*}

Invariantna je enaka

\[ A_{\mu} A^{\mu} = A ^2 - \frac{\phi ^2}{c ^2}
\]

Razcep \( A_{\mu} \) na \( \mathbf{A} \) in \( \phi \) je ponovno odvisen od sistema. Z drugimi besedami je relativen.
*** Schwartzschildova invarianta v relativistični dinamiki

Želimo zapisati Lagrangeev člen za nabite delce v zunanjem polju v relativistični obliki. In sicer

\[ - \int\limits_{}^{} \left( \rho \phi + \mathbf{j} \cdot \mathbf{A} \right) \, \mathrm{d} ^3 \mathbf{r} \, \mathrm{d} t = \int\limits_{}^{} A_{\mu} j^{\mu} \, \mathrm{d} ^4 x_{\mu} = \int\limits_{}^{}A^{\mu} j_{\mu} \, \mathrm{d} ^4 x^{\mu}.
\]

kjer sta \( \phi \) in \( \mathbf{A} \) zunanja potenciala.
** Kovariantni tenzor elektromagnetnega polja

Zanima nas, kakšen je kovarianten ( = manifestno invarianten na Lorentzovo transformacijo) zapis osnovnih polj \( \mathbf{E} \) in \( \mathbf{B} \), saj so bile transformacije nestandardne.

Pri izpeljavi nam bosta prav prišli identiteti

\[ \mathbf{B} = \nabla \times \mathbf{A} \quad \text{ in } \mathbf{E} = - \nabla \phi - \frac{\partial \mathbf{A}}{\partial t}
\]

ter, da se zavedamo

\[ A_{\mu} = \left( \mathbf{A}, \frac{\phi}{c} \right) \quad \text{ in } \quad \frac{\partial }{\partial x^{\mu}} = \left( \nabla, \frac{\partial }{\partial (ct)}  \right)
\]

\begin{align*}
  E_x &= - c \frac{\partial \frac{\phi}{c} }{\partial x}  + c \frac{\partial A_{x}}{\partial (-ct} \\
&= -c \frac{\partial A_{4}}{\partial x^{1}} + c \frac{\partial A_{1}}{\partial x^{4}}
\end{align*}

Poglejmo še za \( B_x \), ki je po definiciji

\[ B_x = \frac{\partial A_{z}}{\partial y}  - \frac{\partial A_{y}}{\partial z}.
\]

V jeziku četvercev je \( A_z = A_3, y = x^2, A_y = A_2 \) in \( z = x^3 \).

Sledi torej

\[ B_x = \frac{\partial A_{3}}{\partial x^{2}} - \frac{\partial A_{2}}{\partial x^{3}}.
\]

Obe komponenti se izvažata kot "nekakšen štiri dimenzionalni rotor".

V treh dimenzijah je

\[ \left( \nabla \times \mathbf{c} \right)_i = \epsilon_{ijk} \frac{\partial c_{j}}{\partial x_{k}}.
\]

Na osnovi tega razmisleka uvedemo tenzor elektromagnetnega polja

\[ F_{\mu \nu} = \frac{\partial A_{\nu}}{\partial x^{\mu}} - \frac{\partial A_{\mu}}{\partial x^{\nu}} = \partial_{\mu} A_{\nu} - \partial_{\nu} A_{\mu},
\]

ki je antisimetričen.

Zapisali smo že \( B_x = F_{23} \) in \( F_{14} = \frac{- E_x}{c} \)

Obravnavamo ga po komponentah

\[ F_{\mu \nu} = \begin{bmatrix}
                 0 & B_z & - B_y & - \frac{E_x}{c} \\
                 -B_z & 0 & B_x & - \frac{E_y}{c} \\
                 B_y & -B_x & 0 & -\frac{E_z}{c} \\
                 \frac{E_x}{c} & \frac{E_y}{c} & \frac{E_z}{c} & 0
                 \end{bmatrix}.
\]

Tenzor je antisimetričen in torej velja \( F_{\mu \nu} = - F_{\nu \mu} \). Komponente tenzorja so komponente \( \mathbf{E} \) in \( \mathbf{B} \). Tako smo polji združili v eno količino. V štirih dimenzijah postane eno polje.
