#+title: Priprava na ustni izpit iz Kvantne mehanike
#+startup: nolatexpreview
#+startup: entitiespretty nil
#+startup: show2levels
#+latex_header: \usepackage{amsmath} \usepackage{unicode-math} \usepackage{cancel} \usepackage{graphicx}
#+latex_header: \renewcommand{\theta}{\vartheta} \renewcommand{\phi}{\varphi} \renewcommand{\epsilon}{\varepsilon}
#+latex_header: \newcommand{\odv}[1]{\dot{\vec{#1}}} \newcommand{\oddv}[1]{\ddot{\vec{#1}}}
#+latex_header: \newcommand{\rot}{\mathrm{rot}}\newcommand{\dive}{\mathrm{div}} \newcommand{\iu}{\mathrm{i}}
#+latex_header: \newcommand\mapsfrom{\mathrel{\reflectbox{\ensuremath{\mapsto}}}}
* Prvi set vprašanj
** Schrödingerjeva enačba

Osnovna Schrödingerjeva enačba v eni dimenziji je

\[ \mathrm{i} \hbar \frac{\partial \Psi (x, t)}{\partial t} = - \frac{\hbar ^2}{2m} \frac{\partial ^2 }{\partial x ^2} \Psi(x, t) + V(x, t) \Psi(x, t)
\]

V treh dimenzijah pa je enačba enaka

\[ \mathrm{i} \hbar \frac{\partial \Psi}{\partial t} \left( \vec{r}, t \right) = - \frac{\hbar ^2}{2m} \nabla ^2 \Psi (\vec{r}, t) + V \left( \vec{r}, t \right) \Psi \left( \vec{r}, t \right)
\]

Schrödingerjeva enačba je najenostavnejša enačba, ki zadošča naslednjim kvantno-mehanskim lastnostim:

- delec je neke vrste valovanje z valovno dolžino \( \lambda = \frac{2\pi}{k} \) in s frekvenco \( \nu = \frac{\omega}{2\pi} \)
- energije delca je sorazmerna s frekvenco valovanje \( E = \hbar \omega \), kjer je \( h = 2\pi \hbar \) Planckova konstanta
- gibalna količina naj bo podana z valovnim vektorjem \( p = \hbar k \)
- energija prostega delca z maso \( m \) ima obliko \( E = \frac{p ^2}{2m} \) in disperzijsko relacijo \( \omega \propto k ^2 \)

Zadnja točka je tudi razlog, zakaj valovna enačba ni primerna - poda nam linearno disperzijsko relacijo. Disperzijska relacija nam podaja zvezo med frekvenco in valovnim vektorjem.

Schrödingerjeva enačba je podobna difuzijski enačbi

\[ \frac{\partial T}{\partial t}  = D \frac{\partial ^2 T}{\partial x ^2}
\]

vendar jo rešimo s kompleksnim nastavkom \( e^{\mathrm{i} (k x - \omega t)} \), kar nam poda kvadratno disperzijsko relacijo \( \omega = - \mathrm{i} D k ^2 \). Željena energijska zveza \( E = \frac{p ^2}{2m} \) velja zgolj za \( D = \frac{\mathrm{i} \hbar}{2m} \in \mathbb{C} \).

Realna rešitev difuzijske enačbe ne oscilira in zato ni rešitev.

Pokažimo, da valovna funkcija oscilira ter da lahko valovno funkcijo izrazimo z dvema realnima funkcijama. Zapišemo jo kot

\[ \Psi = \alpha + \mathrm{i}\beta, \ \alpha, \beta \in \mathbb{R}
\]

Ko vstavimo to v Schrödingerjevo enačbo, dobimo sklopljeni enačbi

\begin{align*}
  -\hbar \dot{\beta} &= - \frac{\hbar ^2}{2m} \alpha '' + V \alpha \\
  -\hbar \dot{\alpha} &= - \frac{\hbar ^2}{2m} \beta '' + V \beta
\end{align*}

Sklopljenost dveh enačb vodi do osciliranje, vidimo pa tudi, da dve realni funkciji rešita Schrödingerjevo enačbo.
** Valovna funkcija

#+begin_problem
Kaj je valovna funkcija in kaj je njena vloga v kvantni mehaniki? Kako je valovna funkcija povezana z verjetnostjo zaznave delca v določenem prostoru?
#+end_problem

Valovna funkcija \( \Psi \left( \vec{r}, t \right) \) je osnovna količina, s katero opišemo delce v kvantni mehaniki. Z valovno funkcijo definiramo gostoto verjetnosti

\[ \rho \left( \vec{r}, t \right) = \left| \Psi \left( \vec{r}, t \right) \right| ^2
\]

Gostota verjetnosti nam pove, s kakšno verjetnostjo \( \mathrm{d} P = \rho \mathrm{d} ^3 \vec{r} \) bomo v okolici koordinate \( \vec{r} \) ob času \( t \) v delu prostora \( \mathrm{d} ^3 \vec{r} \) zaznali delec.

Delec bomo v vsem prostoru \( V \) zagotovo detektirali \( P = 1 \), zato je valovna funkcija ob vsakem času \( t \) normirana

\[ \int\limits_V^{} \left| \Psi \left( \vec{r}, t \right) \right| ^2 \, \mathrm{d} ^3 \vec{r} = 1.
\]

* Drugi set vprašanj - stacionarna stanja in časovni razvoj

# To vključujem najprej, saj se vprašanje o lastnostih valovne funkcije dotikajo snovi tega vprašanja.

#+begin_problem
Kaj so stacionarna stanja? Poveži s fizikalno interpretacijo!
#+end_problem

Valovna enačba ima določene rešitve stoječega valovanja. To so rešitve, kjer se valovanje na koncu medija odbije in potuje nazaj, pri čemer se vpadni in odbiti val srečata in seštejeta. Tako valovanje ne potuje, ampak valovi potujejo navzgor in navzdol. Schrödingerjeva enačba ima tudi kvantnomehansko rešitev, ki je ekvivalent stoječega valovanja. To so rešitve, kjer lahko valovno funkcijo zapišemo kot produkt krajevnega (amplitudnega) in časovnega dela

\[ \Psi \left( \vec{r}, t \right) =  \psi \left( \vec{r} \right) f(t).
\]

Takim rešitvam pravimo stacionarna stanja valovne funkcije.

Predpostavimo, da je potencialna energija neodvisna od časa. Upoštevajoč definicijo stacionarnega stanje je Schrödingerjeva enačba

\[ \mathrm{i} \hbar \frac{\partial f(t)}{\partial t}  \psi \left( \vec{r} \right) = - \frac{\hbar ^2}{2m} \nabla ^2 \psi \left( \vec{r} \right) f(t) + V \left( \vec{r} \right) \psi \left( \vec{r} \right) f(t)  \implies \quad \mathrm{i} \hbar \frac{1}{f(t)} \frac{\partial  f(t)}{\partial t } = - \frac{\hbar ^2}{2m} \frac{\nabla ^2 \psi \left( \vec{r} \right)}{\left( \vec{r} \right)} + V \left( \vec{r} \right) = E
\]

Uspešno smo ločili spremenljivke in to velja za vsak položaj in vsak čas. Posledično je rešitev lahko samo konstantna \( E \). Iz tega tako sledi stacionarna Schrödingerjeva enačba

\[ - \frac{\hbar ^2}{2m} \nabla ^2 \psi \left( \vec{r} \right) + V \left( \vec{r} \right) \psi \left( \vec{r} \right) = E \psi \left( \vec{r} \right),
\]

kjer je \( \psi \) lastna funkcija in \( E \) lastna energija.
* Tretji set vprašanj

#+begin_problem
Izpelji kontinuitetno enačba za verjetnost. Ali je valovna funkcija vedno normirana? Kaj so lastnosti valovne funkcije?
#+end_problem
** Kontinuitetna enačba

Želimo dokazati, da je valovna funkcija normirana tudi ob drugih časih, če je že ob danem. Gostoto verjetnosti odvajamo po času z odvodom produkta

\[ \frac{\partial \rho \left( \vec{r}, t \right)}{\partial t} = \frac{\left| \Psi \left( \vec{r}, t \right) \right| ^2}{\partial t} = \frac{\partial \Psi \left( \vec{r}, t \right)}{\partial t} \Psi^{\ast} \left( \vec{r}, t \right) + \frac{\partial \Psi^{\ast} \left( \vec{r}, t \right)}{\partial t} \Psi \left( \vec{r}, t \right)
\]

Upoštevali smo definicije absolutne vrednosti kompleksne vrednosti \( \left| z \right| ^2 = z \cdot z^{\ast}, \ z \in \mathbb{C} \).

Nadomestimo vrednosti \( \Psi \) z nastavkom Schrödingerjeve enačbe, da dobimo izraz

\begin{align*}
  \frac{\partial \rho \left( \vec{r}, t \right) }{\partial t} = & \left( - \frac{\hbar \mathrm{i}}{2m} \nabla ^2 \Psi^{\ast} \left( \vec{r}, t \right)+ \frac{\mathrm{i}}{\hbar} V^{\ast} \left( \vec{r}, t \right) \Psi^{\ast} \left( \vec{r}, t \right) \right) \Psi \left( \vec{r}, t \right) \\
&+ \left( \frac{\hbar \mathrm{i}}{2m} \nabla ^2 \Psi \left( \vec{r}, t \right) - \frac{\mathrm{i}}{\hbar} V \left( \vec{r}, t \right) \Psi \left( \vec{r}, t \right) \right) \Psi^{\ast} \left( \vec{r}, t \right)
\end{align*}

Uporabimo identiteto

\[ \Psi \nabla ^2 \Psi^{\ast} = \nabla \cdot \left( \Psi \nabla \Psi^{\ast} \right) - \nabla \Psi \cdot \nabla \Psi^{\ast}
\]

da prepišemo zgornji dobljeni rezultat v obliko kontinuitetne enačbe za gostoto verjetnosti \( \rho \left( \vec{r}, t \right) \)

\[ \frac{\partial }{\partial t} \rho \left( \vec{r}, t \right) + \nabla \cdot \vec{\jmath} \left( \vec{r}, t \right) = q \left( \vec{r}, t \right)
\]

kjer je

\[ \vec{\jmath} \left( \vec{r}, t \right) = \frac{\hbar}{2 \mathrm{i} m} \left[ \Psi^{\ast} \nabla \Psi \left( \vec{r}, t \right) - \Psi \left( \vec{r}, t \right) \nabla \Psi ^{\ast} \left( \vec{r}, t \right) \right],
\]

*gostota verjetnostnega toka*.  \( q \left( \vec{r}, t \right) = \frac{2}{\hbar} \mathrm{Im} \left( V \left( \vec{r}, t \right) \right) \rho \left( \vec{r}, t \right) \) je gostota izvorov verjetnosti. Kontinuitetna enačba je konstantna, če je

\[ \int\limits_{}^{} q \left( \vec{r}, t \right) \, \mathrm{d} \vec{r} = 0 \quad \forall \rho \left( \vec{r}, t \right)
\]

To velja za realne potencialne energije \( V \left( \vec{r}, t \right) \).
** Lastnosti valovne funkcije

